change_var_basetype;f0;a;float
change_var_basetype;f0;b;float
change_var_basetype;f0;c;float
change_var_basetype;f0;d;float
change_var_basetype;f0;e;float
change_var_basetype;f0;f;float
change_var_basetype;f0;g;float
change_var_basetype;f0;h;float
change_var_basetype;f0;i;float
change_var_basetype;f0;j;float
change_var_basetype;f0;k;float
change_var_type;f1;a;AD_real
change_var_type;f1;b;AD_real
change_var_type;f1;c;AD_real
change_var_type;f1;d;AD_real
change_var_type;f1;e;AD_real
change_var_type;f1;f;AD_real
change_var_type;f1;g;AD_real
change_var_type;f1;h;AD_real
change_var_type;f1;i;AD_real
change_var_type;f1;j;AD_real
change_var_type;f1;k;AD_real
change_every_basetype;f2:args,body,ret;double=>float
change_every_basetype;$global;double=>float
change_var_basetype;$global;gc;float
change_every_basetype;$global;A=>B
change_every_basetype;$global;B=>A
