# Generated automatically from Makefile.in by configure.
# Main libs Makefile
# $Id: Makefile,v 1.1 2005/10/11 17:18:11 vuduc2 Exp $

# keep the order, some libs have to be build before others
# PDU not yet working => MAKEOPT -i
include ../config/mkcommon.inc

MAKEOPT	= -i
SUB_DIRS = $(LIBTARGETS)

include ../config/mksubdirs.inc
