// This is the file that represents the array dsl compiler.
// It should be almost completely generic to any specific 
// abstraction (but for inclusion of the header file representing 
// the family of DSL target abstractions).

#define DIM 2

// The single point where this target abstractions is referenced (header files).
// #include "array.h"
#include "Multigrid.H"

// ROSE header file (since this compiler is implementd as a source-to-source translator).
#include "rose.h"

// DSL header file to include DSL infrastructure.
#include "dsl.h"

// The code generated by the evaluation of the target DSL abstraction 
// (seperate code generation pass implemented using ROSE).
#include "generated_dsl_attributes_header.C"
#include "generated_dsl_attributes.C"

// Main program (independent of the target DSL abstraction).
int main( int argc, char * argv[] )
   {
  // If we want this translator to take specific options (beyond those defined 
  // by ROSE) then insert command line processing for new options here.
    std::vector <std::string> argvList (argv, argv + argc);

  // To better support the stencil specification that might benifit from constant 
  // folding, I have turned this ON is hte frontend.  By default it is OFF so that
  // we can preserve source code as much as possible (original expression trees).
  // The Stencil DSL can be made to work in eithr setting, but this make sure that
  // dimension dependent processing of the stencil coeficients will be evaluated 
  // to constants.  I will turn this off (and thus use a less blunt axe) when the new
  // constant expression evaluation in ROSE is fixed to support more general types
  // than integer expresion (should be done by JP later today).
  // bool frontendConstantFolding = true;
     bool frontendConstantFolding = false;

  // Generate the ROSE AST.
     SgProject* project = frontend(argvList,frontendConstantFolding);
     ROSE_ASSERT(project != NULL);

  // Call the DSL specific compiler support
     int status = DSL_Support::dslProcessing(project);

  // Return the associated compiler error code.
     return status;
   }
