// This is temporary test to look at how arrays and handled in some detail.
// so that I can match the behavior with the AST generated by Fortran (the 
// Open Fortran Parser).

int A[10];

void foo()
   {
     A[7] = 42;
   }

// Example of ODR violation if initialized differently in different files.
struct X { const int a = 0; };

X x1;
