INTEGER :: a
INTEGER(KIND=4) :: b
REAL :: c
REAL(KIND=4) :: d
DOUBLE PRECISION :: e
DOUBLE PRECISION :: f
COMPLEX :: g
COMPLEX(KIND=4) :: h
DOUBLE COMPLEX :: i
DOUBLE COMPLEX :: j
CHARACTER :: k
CHARACTER(1) :: l
LOGICAL :: m
LOGICAL(KIND=1) :: n
INTEGER :: foo
END PROGRAM
