%{
#include <stdio.h>
#include "crsh.hpp"
#include "crsh-parse.hpp"

extern "C" int yywrap(void) { return 1; }
%}

%%
"create"                       return DBCREATE;
"connect"                      return DBCONNECT;
"close"                        return DBCLOSE;
"exit"                         return EXIT;
"export"                       return EXPORT;
"MONITOR"                      return MONITOR;
"run"                          return RUN;
"::"                           return QUAL;
!                              return SHELL;

\"(\\.|[^"\\])*\"              {
                                 yylval.m_str = strdup(yytext);
                                 return QUOTSTR;
                               }

"sqlite3://"[".""/"a-zA-Z0-9]+ {
                                 yylval.m_str = strdup(yytext);
                                 return SQLLITE;
                               }
"{"                            return LBLK;
"}"                            return RBLK;
"@"                            return NOTE;
"$"                            return VAR;
"="                            return EQUAL;
[0-9]+                         {
                                 yylval.m_num = atoi(yytext);
                                 return NUM;
                               }
[a-zA-Z0-9\\\.\-\+\=\*/]+      {
                                 yylval.m_str = strdup(yytext);
                                 return STRING;
                               }

\n                             /* return NL; */
[ \t]+                         /* ignore whitespace */;
"#".*                          /* ignore line comment */;
%%
