%{
#include <stdio.h>
#include "crsh-parse.hpp"

extern "C" int yywrap(void) { return 1; }
%}

%%
"connect"                      return CONNECT;
"export"                       return EXPORT;
"suite"                        return TESTSUITE;
"test"                         return TESTCASE;
"exit"                         return EXIT;
"::"                           return QUAL;
"sqlite3://"[".""/"a-zA-Z0-9]+ {
                                 yylval.m_str = strdup(yytext);
                                 return SQLLITE;
                               }
"{"                            return LBLK;
"}"                            return RBLK;
"="                            return EQU;
[0-9]+                         {
                                 yylval.m_num = atoi(yytext);
                                 return NUM;
                               }
[a-zA-Z0-9"\""/"".""-"]+       {
                                 yylval.m_str = strdup(yytext);
                                 return STRING;
                               }

\n                             /* ignore end of line */;
[ \t]+                         /* ignore whitespace */;
"#".*                          /* ignore line comment */;
%%
