! user defined operator not supported
MODULE TEST
       INTERFACE OPERATOR (+)
       END INTERFACE
       INTERFACE OPERATOR (-)
       END INTERFACE
       INTERFACE OPERATOR (*)
       END INTERFACE
       INTERFACE OPERATOR (/)
       END INTERFACE
       INTERFACE OPERATOR (.SIN.)
       END INTERFACE
       INTERFACE ASSIGNMENT(=)
       END INTERFACE
END MODULE TEST
