/*
  Author: Pei-Hung Lin
  Contact: phlin@cs.umn.edu

  Date Created       : July 5th, 2012
 
 This is a source to source compiler for Fortran

  Fortran to C translator 
  * input  : Fortran 77 source code
  * output : C source code

*/  

#include "rose.h"
#include "f2c/f2cStatement.h"

using namespace std;
using namespace Fortran_to_C;

int main( int argc, char * argv[] )
{
// Build the AST used by ROSE
  SgProject* project = frontend(argc,argv);
  AstTests::runAllTests(project);   

  generateAstGraph(project,8000,"_orig");
/*
  1. The following funcitons search for the Fortran-specific
     AST nodes and transform them into C nodes. 
  2. The new C nodes are created first.  Attributes and details
     are then copied from original Fortran nodes.  After the 
     copy, original Fortran nodes are deleted. 
  3. Having the node list generated by NodeQuery is earsier to 
     handle AST node deletion. 
  
  TODO:  We might be able enhance the following part by using
         AST traversal. 
*/
  translateFileName(project);
  translateProgramHeaderStatement(project);
  translateProcedureHeaderStatement(project);
  translateFortranDoLoop(project);
      
/*
  1. There should be no Fortran-specific AST nodes in the whole
     AST graph after the translation. 
  
  TODO: make sure translator generating clean AST 
*/
  
  //generateDOT(*project);
  generateAstGraph(project,8000);
  return backend(project);
}

