#!/bin/bash

if [[ ("$#" < 5) || ("$1" = "--help") ]]; then 
  echo "Usage: <problem no.> <version> <CodeThorn src dir> <CodeThorn build dir> <temp make check log dir> [<number-of-threads>] [<keep-err-states(yes|[no])>]";
  exit;
fi
#optional parameter: number of threads
if [[ ("$#" < 6) || ("$6" = 1) ]]; then 
  NUMTHREADS=1;
  NUMS=""
else
  NUMTHREADS=$6;
  NUMS="s";
fi
#optional parameter: --keep-error-states
if [[ ("$#" < 7) || ("$7" = no) ]]; then 
  KEEP_ERR_STATES=""
elif  [[ ("$7" = yes) ]]; then 
  KEEP_ERR_STATES="--keep-error-states=yes"
else
  echo "ERROR: Value of parameter \"keep-err-states\" not recognized."
  exit 1
fi

#list of supported RERS problems
P1="Problem1"
P2="Problem2"
P3="Problem3"
P4="Problem28"
P5="Problem1T_size5_14" #training phase '14, alphabet size 5

#set problem specific codethorn options
case $1 in
1) INPUT_VALUES="\"{1,2,3,4,5,6}\"" LTLS="properties1.txt" LTL_ALPHABET="";;
2) INPUT_VALUES="\"{1,3,4,5,6}\"" LTLS="properties2.txt" LTL_ALPHABET="--ltl-in-alphabet=\"{1,2,3,4,5,6}\"" ;;
3) INPUT_VALUES="\"{1,2,3,4,5,6}\"" LTLS="properties3.txt" LTL_ALPHABET="";;
4) INPUT_VALUES="\"{1,2,3,4,5,6}\"" LTLS="properties28.txt" LTL_ALPHABET="";;
5) INPUT_VALUES="\"{1,2,3,4,5}\"" LTLS="constraints-RERS14-5.txt" LTL_ALPHABET="--ltl-out-alphabet=\"{19,20,21,22,23,24,25,26}\"";;
esac

SRCDIR=$3
BUILDDIR=$4 
MC_LOG_DIR=$5
MC="_make_check"
PROBLEMDIR=$MC_LOG_DIR #the modified code versions can be found in the temporary make check log directory (default)
PROBLEM_MC="_make_check" #suffix for the temporarily generated problem files during make check

case $2 in
1) VERSION="" ; PROBLEMDIR=$SRCDIR/tests/rers ; PROBLEM_MC="" ;; # take the original problem for the unmodified version
2) VERSION="_mod";;
3) VERSION="_inline";;
4) VERSION="_opt";;
esac

#PROBLEM= eval \${P${1}}${VERSION}  #problem name appended by version (e.g."Problem28_mod")

eval echo "Generating RERS LTL results for \${P${1}}${VERSION} with $NUMTHREADS thread$NUMS."
echo ".________________________."
echo "| start running CodeThorn|"
echo "*~~~~~~~~~~~~~~~~~~~~~~~~*"
eval $BUILDDIR/codethorn ${PROBLEMDIR}/\${P${1}}${VERSION}${PROBLEM_MC}.c --edg:no_warnings --threads=${NUMTHREADS} --input-values=${INPUT_VALUES} ${LTL_ALPHABET} --rersmode=yes --check-ltl="$SRCDIR/tests/rers/${LTLS}" --csv-spot-ltl="${MC_LOG_DIR}/\${P${1}}${VERSION}_ltl_results${MC}.csv" --with-counterexamples=no ${KEEP_ERR_STATES}
echo ".___________________________."
echo "| finished running CodeThorn|"
echo "*~~~~~~~~~~~~~~~~~~~~~~~~~~~*"
eval echo "\${P${1}}${VERSION} LTL results written to file: ${MC_LOG_DIR}/\${P${1}}${VERSION}_ltl_results${MC}.csv."
