#!/bin/bash

OPTIONS="--normalize-fcalls --ignore-unknown-functions --report-only-file-name"

# test 1-9: normalization: YES
# test 10:  normalization: NO

TESTDIR=$1
echo "------------------------------------------------"
echo "running DEADCODE TESTS"
echo "------------------------------------------------"

BENCH_PASS=0
BENCH_FAIL=0

testNumbers1=`echo {001..007}`
testNumbers2=`echo {009..013}`
testNumbers="$testNumbers1 $testNumbers2"
echo "Scheduled tests: $testNumbers"
echo "Skipping DC008."
for testNumber in $testNumbers; do
    benchmarkprefix=$TESTDIR/DC${testNumber};
    for benchmark in ${benchmarkprefix}_*.C; do
        rm -f tmptest.csv
        rm -f tmptest_col1.csv
        rm -f test${p}_col1.csv
        benchmarkname=$(basename $benchmark)
        echo -n "Testing $benchmarkname : "
        ./analyterix --csv-deadcode-unreachable=$benchmarkname.csv ${OPTIONS} $benchmark > /dev/null
        diff $benchmarkname.csv $TESTDIR/$benchmarkname.csv
        #cut -d, -f1 $benchmarkname.csv | sort > $benchmarkname.line.csv
        #cut -d, -f1 $TESTDIR/$benchmarkname.csv |sort > ${benchmarkname}_ref.line.csv
        #diff $benchmarkname.line.csv ${benchmarkname}_ref.line.csv
        if [ ! $? -eq 0 ]
        then
	    echo "FAIL"
            exit 1
        else
	    echo "PASS"
        fi
    done
done
rm -rf DC*.csv
