#!/bin/bash

TESTDIR=$1
    echo "------------------------------------------------"
    echo "running DEADCODE TESTS"
    echo "------------------------------------------------"

    for p in 1 2 3 4 5 6 7 8 9; do
	./analyterix --csv-deadcode-unreachable=tmptest.csv $TESTDIR/deadcode/test$p.C
	echo -n "DEADCODE test${p}.C : "
	diff tmptest.csv $TESTDIR/deadcode/test$p.csv
	if [ ! $? -eq 0 ]
	then
	    echo "FAIL"
	else
	    echo "PASS"
	fi
	echo "-------------------------------------------------"
    done
#    rm -f tmptest.csv
