#!/bin/bash

OPTIONS=--normalization --inlining

TESTDIR=$1
    echo "------------------------------------------------"
    echo "running DEADCODE TESTS"
    echo "------------------------------------------------"

    # C++ tests
    for p in 1 2 3 4 5 6 7 8 9; do
	./analyterix --csv-deadcode-unreachable=tmptest.csv $OPTIONS $TESTDIR/deadcode/test$p.C
	echo -n "DEADCODE test${p}.C : "
	diff tmptest.csv $TESTDIR/deadcode/test$p.csv
	if [ ! $? -eq 0 ]
	then
	    echo "FAIL"
            exit 1
	else
	    echo "PASS"
	fi
	echo "-------------------------------------------------"
    done

    # C tests
    for p in 10; do
	./analyterix --csv-deadcode-unreachable=tmptest.csv $OPTIONS $TESTDIR/deadcode/test$p.c
	echo -n "DEADCODE test${p}.c : "
	diff tmptest.csv $TESTDIR/deadcode/test$p.csv
	if [ ! $? -eq 0 ]
	then
	    echo "FAIL"
            exit 1
	else
	    echo "PASS"
	fi
	echo "-------------------------------------------------"
    done

    # C tests
    for p in 11; do
	./analyterix --csv-deadcode-unreachable=tmptest.csv --ignore-unknown-functions $OPTIONS $TESTDIR/deadcode/test$p.C
	echo -n "DEADCODE test${p}.C : "
        echo "Skipping check."
	echo "-------------------------------------------------"
    done

#    rm -f tmptest.csv
