#!/bin/bash

TEST_DIR=$1

./codethorn $TEST_DIR/DOM089_np_join.C --vis --tg1-estate-memory-subgraphs=1 --abstraction-mode=1 --byte-mode=1 --pointer-sets=1 --exploration-mode=topologic-sort --solver=16
