#!/bin/bash

if [[ ("$#" < 5) || ("$1" = "--help") ]]; then 
  echo "Usage: <problem no.><LTL-property-id><CodeThorn src dir> <CodeThorn build dir> <temp make check log dir> [<with/without error states>]";
  exit;
fi
#optional parameter: number of threads
if [[ ("$#" < 6) || ("$5" = "no") ]]; then 
  ERROR_STATES="no"
  ES_SUFFIX="out"
else
  ERROR_STATES="yes"
  ES_SUFFIX=""
fi

#set problem specific codethorn options
case $1 in
Problem140[1-3]) INPUT_VALUES="{1,2,3,4,5}" LTL_ALPHABET="--ltl-in-alphabet={1,2,3,4,5} --ltl-out-alphabet={18,19,20,21,22,23,24,25,26}" LTLS="constraints-RERS14-5.txt";;
esac

PROPERTY=$2
SRCDIR=$3
BUILDDIR=$4
MC_LOG_DIR=$5
MC="_make_check"
PROBLEMDIR=$SRCDIR/tests/rers/
PROBLEM_MC="_make_check" #suffix for the temporarily generated problem files during make check

MAX_ITER=100

#PROBLEM= eval \${P${1}}${VERSION}  #problem name appended by version (e.g."Problem28_mod")

echo "Generating CEGPRA LTL results (RERS'14) for ${1} (with${ES_SUFFIX} error states)."
echo ".__________________________________."
echo "| start running CodeThorn (CEGPRA) |"
echo "*~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~*"

$BUILDDIR/codethorn ${PROBLEMDIR}/${1}_opt.c --edg:no_warnings --input-values=${INPUT_VALUES} ${LTL_ALPHABET} --rersmode=yes --check-ltl="$SRCDIR/tests/rers/${LTLS}" --exploration-mode=loop-aware --cegpra-ltl=${PROPERTY} --cegpra-max-iterations=${MAX_ITER} --csv-spot-ltl="${MC_LOG_DIR}/${1}_ltl_results${MC}.csv" --with-counterexamples=${ERROR_STATES}

echo "._____________________________________."
echo "| finished running CodeThorn (CEGPRA) |"
echo "*~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~*"
echo "CEGPRA LTL results (${1}, ltl#${PROPERTY}) written to file: ${MC_LOG_DIR}/${1}_ltl_results${MC}.csv."
