#!/bin/bash 

echo "This script runs all benchmarks as separate processes."

all_benchmarks=`ls *orig_tile_1_1_1* | sed 's/_orig_tile_1_1_1\.c//g' | grep -v fdtd-apml | grep -v doitgen | tr "\n" " "`

for benchmark in $all_benchmarks; do
  ./verify_polybench --check $benchmark &
  #echo "./verify_polybench --check $benchmark"
done

echo "All processes have been started. "
ps -A | grep verify_polybench
