replace_varbasetype;f0;a;float
replace_varbasetype;f0;b;float
replace_varbasetype;f0;c;float
replace_varbasetype;f0;d;float
replace_varbasetype;f0;e;float
replace_varbasetype;f0;f;float
replace_varbasetype;f0;g;float
replace_varbasetype;f0;h;float
replace_varbasetype;f0;i;float
replace_varbasetype;f0;j;float
replace_varbasetype;f0;k;float
replace_vartype;f1;a;AD_real
replace_vartype;f1;b;AD_real
replace_vartype;f1;c;AD_real
replace_vartype;f1;d;AD_real
replace_vartype;f1;e;AD_real
replace_vartype;f1;f;AD_real
replace_vartype;f1;g;AD_real
replace_vartype;f1;h;AD_real
replace_vartype;f1;i;AD_real
replace_vartype;f1;j;AD_real
replace_vartype;f1;k;AD_real
replace_basetype;f2:args,body,ret;double=>float
replace_basetype;$global;double=>float
replace_varbasetype;$global;gc;float
replace_basetype;$global;A=>B
replace_basetype;$global;B=>A
