#!/bin/sh

# This script adds a unique variable name to each *.docs file so that
# it can be processed as a C/C++ file and any internal comments will 
# be saved and attached to the IR node represented by the unique variable 
# in the AST.

SRC="$1"
# ABS_SRC="`cd $1 && pwd`"

rm -rf sage_doxygen_documentation.h
for docfile in ${SRC}/*; do
     echo >> ${docfile}
     echo "int SAGE_Doxygen_Dummy_${RANDOM}${RANDOM}${RANDOM};" >> ${docfile}
     echo "#include \"${PWD}/$docfile\"" >> sage_doxygen_documentation.h
done

