/*!
 *  \file tests/acc_compiler_data.c
 *
 * This file provides default version of the code that should be generated by the compiler for the runtime.
 *
 */

#include "OpenACC/internal/compiler.h"
#include "OpenACC/internal/region.h"
#include "OpenACC/internal/kernel.h"
#include "OpenACC/internal/loop.h"

#ifndef ACC_RUNTIME_ABS_DIR
# error "Need OpenACC runtime directory."
#endif

#ifndef ACC_KERNELS_ABS_DIR
# error "Need generated kernels directory."
#endif

#ifndef ACC_RUNTIME_OPENCL_FILE
# define ACC_RUNTIME_OPENCL_FILE "lib/opencl/libopenacc.cl"
#endif

struct acc_kernel_version_t_ kernel_0x00_default = {
  0, 0, 0, NULL, ""
};

struct acc_loop_t_ kernel_0x00_v1_loops[1] = {
  {
    (struct acc_loop_tile_t_){ e_tiling_static_iteration, 0 , 1 }, ///!< Filing Tile 0
    (struct acc_loop_tile_t_){ e_tiling_dynamic         , 0 , 0 }, ///!<   Gang Tile
    (struct acc_loop_tile_t_){ e_tiling_static_iteration, 0 , 1 }, ///!< Filing Tile 1
    (struct acc_loop_tile_t_){ e_tiling_dynamic         , 0 , 0 }, ///!< Worker Tile
    (struct acc_loop_tile_t_){ e_tiling_dynamic         , 1 , 0 }, ///!< Filing Tile 2
    (struct acc_loop_tile_t_){ e_tiling_static_iteration, 1 , 1 }, ///!< Vector Tile
    (struct acc_loop_tile_t_){ e_tiling_static_iteration, 1 , 1 }  ///!< Filing Tile 3
  }
};

struct acc_kernel_version_t_ kernel_0x00_v1 = {
  0, 0, 1, kernel_0x00_v1_loops, "_gang_worker_tile_2"
};

acc_kernel_version_t kernel_0x00_versions[2] = { &kernel_0x00_default , &kernel_0x00_v1 };

const size_t kernel_0x00_scalar_sizes[1] = { sizeof(float) };

struct acc_kernel_desc_t_ kernel_0x00_desc = {
  0,
  "kernel_102",
  1, kernel_0x00_scalar_sizes,
  1,
  1,
  2, kernel_0x00_versions
};

acc_kernel_desc_t region_0x00_kernels[1] = { &kernel_0x00_desc };

struct acc_region_desc_t_ region_0x00_desc = {
  0,
  "102-kernels.cl",
  0, NULL,
  1, region_0x00_kernels
};

acc_region_desc_t regions[1] = { &region_0x00_desc };

acc_compiler_data_t compiler_data = {
  (const char * ) ACC_RUNTIME_ABS_DIR, /* Absolute directory for OpenACC runtime (needed to compile OpenCL C codes) */
  (const char * ) ACC_RUNTIME_OPENCL_FILE,  /* Name of the OpenCL C runtime file */
  (const char * ) ACC_KERNELS_ABS_DIR, /* Absolute directory where the OpenCL C kernels have been stored. */
  1, regions
};

