! user defined operator not supported
MODULE test2007_236_TEST
   INTERFACE OPERATOR (+)
   END INTERFACE
   INTERFACE OPERATOR (-)
   END INTERFACE
   INTERFACE OPERATOR (*)
   END INTERFACE
   INTERFACE OPERATOR (/)
   END INTERFACE
   INTERFACE OPERATOR (.SIN.)
   END INTERFACE
   INTERFACE ASSIGNMENT(=)
   END INTERFACE
END MODULE test2007_236_TEST
