! This is an error since the function is assigned an implicit type
! and the declaration of the return type using the older syntax does
! not reset the type of the function.

! Note that specification of return type in cuntion declaration 
! is allowed in gfrotran generally, but not when -std=f95 is used
! in the syntax checking used within filtering input codes in ROSE
! for syntax errors.  Since this option is not used on the code 
! generated by ROSE, the unparsed code is allowed to unparse as
!    integer function foo2()

function foo2()
    integer x,foo2
    foo2 = 1
end function
