include $(top_srcdir)/config/Makefile.for.ROSE.includes.and.libs

SUBDIRS = partialRedundancyElimination finiteDifferencing \
          functionCallNormalization constantFolding implicitCodeGeneration \
          astInlining astOutlining loopProcessing ompLowering extractFunctionArgumentsNormalization singleStatementToBlockNormalization

EXTRA_DIST = CMakeLists.txt
