#!/bin/bash
set -e
arg0="${0##*/}"
date=$(date '+%Y%m%d')

# Full name of this script because we're going to change directories later
case "$0" in
    /*)
	SELF="$0"
	;;
    *)
	SELF="$(pwd)/$0"
	;;
esac

# Directory where portability tools are (or will be) installed.
: ${MATRIX_ROOT:-"$HOME/var/rose-portability-testing"}

# Prefix to be added to docker host mount points.
: ${MATRIX_HOST_ROOT:-$(pwd)/}

# Minimum amount of free disk space in GiB. At the end of each test, this script deletes as many cached software
# dependencies as necessary to reach this amount of free space.
MIN_FREE_SPACE=40

# If non-empty, prepare to run tests but do not run any tests.
SETUP=

# If non-empty, remove source repositories and build directories when possible. This reduces total disk usage
# but requires more time to download and build.
SMALL_FOOTPRINT=

# Non empty if we're on an AWS EC2 instance.
AWS_EC2_INSTANCE=

# Whether to update system software. Empty, auto, or other.
UPDATE_SYSTEM_SOFTWARE=auto

# Override default slave name.
SLAVE_NAME=

help() {
    ######--------------------------------------------------------------------------------
    echo "Purpose: to run portability tests as directed by the server"
    echo
    echo "Usage: $arg0 [SWITCHES] [setup]"
    echo
    echo "Switches"
    echo "    --root=DIRECTORY"
    echo "        This is the directory in which this script does all its work, which"
    echo "        includes creating and removing files and subdirectories. The default is"
    echo "        $MATRIX_ROOT"
    echo
    echo "    --aggressive-cleanup"
    echo "        Remove reproducible things when possible so we don't use as much disk"
    echo "        space. The tradeoff is we use more CPU time."
    echo
    echo "    --slave=NAME"
    echo "        Use the specified string as the slave name instead of \"user@host\"."
    echo
    echo "    --update-system-software"
    echo "    --no-update-system-software"
    echo "        If --update-system-software is specified, the system's software is"
    echo "        updated even if this requires a password to be entered interactively."
    echo "        If --no-update-system-software is specified, then nothing is updated."
    echo "        The default if neither switch is specified is that the system software"
    echo "        is updated if \"sudo\" can be run without a password, as is typically"
    echo "        the case in Docker containers and cloud instances."
    echo
    echo "  Sharing downloads"
    echo "    You can prevent the slave from re-downloading all the RMC/Spock packages it"
    echo "    needs by linking the slave's download area to your user RMC/Spock download"
    echo "    area.  Do this by creating a symbolic link \"spock/var/downloads\" under the"
    echo "    portability testing root directory (see --root) that points to your user"
    echo "    download area, usually ~/.spock/var/downloads."
    ######--------------------------------------------------------------------------------
}

die() {
    rose-matrix-slave-health run-error "$*" || true
    echo "$arg0:" "$@" >&2
    exit 1
}

while [ "$#" -gt 0 ]; do
    case "$1" in
	--help|-h)
	    help
	    exit 0
	    ;;
	--root=*)
	    MATRIX_ROOT="${1#--root=}"
	    shift
	    ;;
	--aggressive-cleanup)
	    SMALL_FOOTPRINT=yes
	    shift
	    ;;
	--slave=*)
	    SLAVE_NAME="${1#--slave=}"
	    shift
	    ;;
	--update-system-software)
	    UPDATE_SYSTEM_SOFTWARE=yes
	    shift
	    ;;
	--no-update-system-software)
	    UPDATE_SYSTEM_SOFTWARE=
	    shift
	    ;;
	-*)
	    die "error: unrecognized switch: $1"
	    ;;
	setup)
	    SETUP=yes
	    UPDATE_SYSTEM_SOFTWARE=yes
	    shift
	    break
	    ;;
	*)
	    die "error: incorrect usage; see --help"
	    ;;
    esac
done

[ "$#" -eq 0 ] || die "error: incorrect usage; see --help"

# Only update system software when we're in "setup" mode. Here's why: if this script is run by
# rose-matrix-slave-babysitter, then the first time it runs the user will probably notice that
# it's asking for a password for sudo (if it needs one). Then if this script crashes after a few
# hours and the babysitter re-runs it, a password might be required but there's no user around
# anymore to supply it and everything hangs.
if [ -n "$UPDATE_SYSTEM_SOFTWARE" -a "$SETUP" = "" ]; then
    echo "$arg0: warning: forcing --no-update-system-software for non-\"setup\" runs"
    echo "$arg0: info: if you want system softare to be updated, add the \"setup\" argument."
    UPDATE_SYSTEM_SOFTWARE=
fi

#------------------------------------------------------------------------------------------------------------------------
# Try to report our health to the database. It's okay if this fails.
matrix-report-health() {
    local health="$1"
    rose-matrix-slave-health --slave="$SLAVE_NAME" "$health" || true
}

#------------------------------------------------------------------------------------------------------------------------
# Make sure the system is up-to-date, that all system dependencies are installed, that users and user groups are set.
# This will run according to the UPDATE_SYSTEM_SOFTWARE setting.
matrix-update-system-software() {
    echo
    echo
    echo "================================================================================"
    echo "Updating system software"
    echo "================================================================================"
    echo
    matrix-report-health run-system >/dev/null 2>&1; # we don't care about errors at this early point

    if [ "$UPDATE_SYSTEM_SOFTWARE" = "" ]; then
	echo "disabled from command-line"
	return 0
    elif [ "$UPDATE_SYSTEM_SOFTWARE" = "auto" ]; then
	if ! sudo -n true; then
	    echo "update skipped because a password would be required"
	    return 0
	fi
    fi
    
    # Ubuntu insists on updating system software willy nilly, which is confusing to matrix testing since it needs a
    # stable system. Therefore, turn it off.
    if [ -n "$SETUP" ] && [ -f /etc/apt/apt.conf.d/10periodic ]; then
	echo "disabling automatic software updates -- we want a stable test environment"
	(set -x; sudo sed -i~ 's/Update-Package-Lists "1"/Update-Package-Lists "0"/' /etc/apt/apt.conf.d/10periodic)
    fi

    # Install basic system software. If this is the setup script, we might be fighting with Ubuntu's automatic updates,
    # so just keep trying until we succeed.
    while true; do
	sleep 5

	(
	    set -x
	    sudo apt-get -y update || continue
	    sudo apt-get -y install git wget build-essential g++ gfortran libtool automake flex bison \
		 graphviz-dev cmake libpqxx-dev ghostscript perl-doc groff libgcrypt20-dev \
		 libfcgi-dev libfuse3-dev gcc-multilib g++-multilib gfortran-multilib \
		 fuse3 bsdmainutils libxapian-dev p7zip-full rsync time libreadline-dev \
		 locales language-pack-en-base jq screen figlet libpcre3-dev || continue
	)

	# Install Docker
	if ! docker --version >/dev/null 2>&1; then
	    (
		set -x
		sudo apt-get -y install apt-transport-https ca-certificates curl software-properties-common || continue
		curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add - || continue
		sudo add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/ubuntu bionic stable" || continue
		sudo apt-get -y update || continue
		sudo apt-get -y install docker-ce || continue
		sudo usermod -aG docker $(whoami)
	    )
	fi

	break
    done
}

#------------------------------------------------------------------------------------------------------------------------
# Test whether docker works
matrix-test-docker() {
    echo
    echo
    echo "================================================================================"
    echo "Testing whether docker works"
    echo "================================================================================"
    echo

    if ! docker run --rm hello-world; then
	echo
	echo "$arg0: if the error says \"permission denied while trying to connect to the"
	echo "    Docker daemon socket\", then you probably need to add $(whoami) to"
	echo "    the \"docker\" group and re-login."
	echo
	echo "    Try \"sudo usermod -a -G docker $(whoami)\""
	echo
	exit 1
    fi
}

#------------------------------------------------------------------------------------------------------------------------
# Get the initial manual configuration. This is optional, but it gives us a place to start. It's main purpose is to tell
# us which version of the portability testing tools we should compile, because we need them in order to figure out what
# tests we should be running and to report results back to the server. If the manual (or default) configuration doesn't
# match what the database is advertising, then we may end up having to compile two versions of the tools before we can
# start running tests (the guessed version, and the correct version).
matrix-get-initial-configuration() {
    echo
    echo
    echo "================================================================================"
    echo "Obtaining initial configuration information"
    echo "================================================================================"

    # The various attempts are listed here from worst to best quality of answers, so each step can override
    # the previous steps, or provide settings that the previous steps didn't provide.

    echo
    echo "Trying AWS EC2 User Data"
    if wget -O matrix-config.tmp --tries=1 http://169.254.169.254/latest/user-data; then
	AWS_EC2_INSTANCE=yes
	cat -n matrix-config.tmp
	source matrix-config.tmp

	# Don't save these over the top of previously known settings that we want to look at next...
	rm matrix-config.tmp
    fi

    echo
    echo "Trying to reuse settings from the previous run"
    if [ -r matrix-config ]; then
	cat -n matrix-config
	source matrix-config
    fi

    echo
    echo "Trying ROSE_MATRIX_SLAVE_DATABASE"
    if [ -n "$ROSE_MATRIX_SLAVE_DATABASE" ]; then
	# This is sometimes set in user environments so that users don't need to have ROSE_MATRIX_DATABASE always set to
	# a read-write role.
	ROSE_MATRIX_DATABASE="$ROSE_MATRIX_SLAVE_DATABASE"
	echo "using ROSE_MATRIX_DATABASE=$ROSE_MATRIX_DATABASE"
    else
	echo "environment variable not set"
    fi

    export ROSE_MATRIX_DATABASE
    if [ -n "$ROSE_MATRIX_DATABASE" ]; then
	echo
	echo "Trying the database"
	if rose-matrix-slave-config -Fshell >matrix-config.tmp; then
	    cat -n matrix-config.tmp
	    source matrix-config.tmp
	    mv matrix-config.tmp matrix-config
	fi
    fi

    # Default location for downloading the portability testing tools that are part of ROSE.
    if [ "$MATRIX_REPOSITORY" = "" ]; then
	MATRIX_REPOSITORY='https://github.com/rose-compiler/rose'
    fi
    if [ "$MATRIX_COMMITTISH" = "" ]; then
	MATRIX_COMMITTISH='weekly'
    fi
    
    # Export the URL to be used by the various tools
    echo
    echo "Checking database credentials"
    [ -n "$ROSE_MATRIX_DATABASE" ] ||
	die "error: database credentials are missing; set ROSE_MATRIX_SLAVE_DATABASE or ROSE_MATRIX_DATABASE"
}

#------------------------------------------------------------------------------------------------------------------------
# Get configuration, store it in the matrix-config file, and update shell variables.
matrix-get-slave-configuration() {
    echo
    echo
    echo "================================================================================"
    echo "== Obtaining current slave configuration from database server."
    echo "================================================================================"
    echo
    rose-matrix-slave-config -Fshell >matrix-config
    cat -n matrix-config
    . matrix-config
}

#------------------------------------------------------------------------------------------------------------------------
# Install the ROSE Meta Config system which is how this script and its Docker containers all manage to install many
# versions of software dependencies simultaneously.
matrix-install-rmc-spock() {
    echo
    echo
    echo "================================================================================"
    echo "== Installing ROSE Meta Config (RMC/Spock)"
    echo "================================================================================"
    echo

    local spock_repo="https://github.com/matzke1/rmc-spock"
    local needs_update=

    echo "Testing whether RMC/Spock is operational..."
    if ! spock-ls --version >/dev/null; then
	needs_update=yes
    elif ! spock-shell --with default-c++ c++ --version; then
	needs_update=yes
    elif [ ! -d rmc-spock ]; then
	needs_update=yes
    else
	pushd rmc-spock >/dev/null
	git fetch "$spock_repo"
	local latest_version="$(git rev-parse FETCH_HEAD)"
	local current_version="$(git rev-parse HEAD)"
	if [ "$latest_version" != "$current_version" ]; then
	    git reset --hard FETCH_HEAD
	    git clean -dfx
	    needs_update=yes
	fi
	popd >/dev/null
    fi

    if [ -n "$needs_update" ]; then
	echo
	echo "Update is necessary..."
	echo
	matrix-report-health run-rmc;
	
	rm -rf rose-installed # since about to blow away libraries used by ROSE
	rm -rf rmc-spock
	git clone "$spock_repo" rmc-spock
	(cd rmc-spock && ./scripts/bootstrap.sh --prefix="$SPOCK_ROOT")
	rm -rf rmc-spock/_build # clean up, but leave source code for next call to this function
    else
	echo
	echo "RMC/Spock is up to date and appears to work"
    fi

    spock-ls --shellvars --export
}

#------------------------------------------------------------------------------------------------------------------------
# In case we were last interrupted during the middle of building a software dependency, remove all failed build attempts.
# If we don't do this, then a subsequent attempt to build the same software will assume that it can't be done and will
# immediately fail.
matrix-clean-failed-dependencies() {
    rm -vf spock/var/installed/matrix-slave/*-build-log.txt
}

# If non-empty, then this very script that's running needs to be updated.
THIS_SCRIPT_OUT_OF_DATE=


#------------------------------------------------------------------------------------------------------------------------
# Install or update the ROSE Matrix Testing command-line tools. These are distributed as part of ROSE itself and depend
# on the ROSE library.
matrix-install-matrix-tools() {
    echo
    echo
    echo "================================================================================"
    echo "== Installing ROSE portability testing tools version \"$MATRIX_COMMITTISH\""
    echo "== Downloading from \"$MATRIX_REPOSITORY\""
    echo "================================================================================"
    echo

    # Decide whether we should install/update the tools
    local needs_update=
    local installed_version="$(cat rose-installed/latest/key 2>/dev/null)"
    local desired_version="$MATRIX_REPOSITORY $MATRIX_COMMITTISH"
    if [ ! -x rose-installed/latest/bin/rose-matrix-run ]; then
	needs_update=yes
    elif [ "$installed_version" != "$desired_version" ]; then
	needs_update=yes
    fi

    # If update is needed, make sure we know where to get the source code
    if [ -n "$needs_update" ]; then
	matrix-report-health run-tools "tools $MATRIX_COMMITTISH"

	if [ "$MATRIX_REPOSITORY" = "" -o "$MATRIX_COMMITTISH" = "" ]; then
	    die "error: no info for installing matrix tools (MATRIX_REPOSITORY, MATRIX_COMMITTISH)"
	fi

	# Get the source code
	if [ -d matrix-src ]; then
	    (
		cd matrix-src
		git fetch "$MATRIX_REPOSITORY" "$MATRIX_COMMITTISH"
		git reset --hard FETCH_HEAD
		git clean -dfxq
	    )
	else
	    git clone "$MATRIX_REPOSITORY" matrix-src
	    (
		cd matrix-src
		git reset --hard "$MATRIX_COMMITTISH" || git checkout origin/"$MATRIX_COMMITTISH"
		git clean -dfxq
	    )
	fi

	# Build the tools.
	(
	    mkdir matrix-src/_build
	    cd matrix-src/_build
	    INSTALL="$MATRIX_ROOT/rose-installed" BUILD=tup OPTIMIZE=yes BOOST=1.78 PQXX=6.4.3 WT=none \
		   rmc init --batch --project=matrix ..
	    rmc --install=yes build
	    rmc config
	    rmc install
	)

	[ -n "$SMALL_FOOTPRINT" ] && rm -rf matrix-src
	echo "$desired_version" >rose-installed/latest/key

	# Since we upgraded the tools, we might have a new version of the script that's running. Don't actually upgrade
	# this very script yet because we're running it and that would cause shell interpreter problems. Instead, only
	# record that it's out of date. (Note: diff exits non-zero (fails) if the files differ).
	if [ -x "$SELF" ]; then
	    if ! diff -q "$SELF" "$MATRIX_ROOT/rose-installed/latest/bin/$arg0"; then
		THIS_SCRIPT_OUT_OF_DATE=yes
	    fi
	else
	    die "error: where am I? (\$0=$0, self=$SELF, cwd=$(pwd))"
	fi
    else
	echo
	echo "Matrix tools are up-to-date"
    fi
}

#------------------------------------------------------------------------------------------------------------------------
# If the script that's running is different than the version that's installed, then replace the running script with the
# new version. This also requires that we restart the script from its beginning or immediately exit.
matrix-update-this-script() {
    local restart="$1"

    if [ -n "$THIS_SCRIPT_OUT_OF_DATE" ]; then
	matrix-report-health run-restart "run script updated"

	[ -x "$SELF" ] || die "error: where am I? (\$0=$0, self=$SELF, cwd=$(pwd))"

	cp "$MATRIX_ROOT/rose-installed/latest/bin/rose-matrix-slave-run" "$SELF"
	[ -n "$restart" ] && exec bash "$SELF"
	exit 0
    fi
}

#------------------------------------------------------------------------------------------------------------------------
# Amount of free disk space for filesystem containing the CWD, measured in kB
matrix-free-space() {
    (unset POSIXLY_CORRECT && df "$MATRIX_ROOT" |tail -n +2 |head -n1 |tr -s ' ' '\t' |cut -f4)
}

#------------------------------------------------------------------------------------------------------------------------
# Reclaim some disk free space by removing old software installed by this script.
matrix-reclaim-disk() {
    local min_free_space="$1" # kB
    echo
    echo
    echo "================================================================================"
    echo "== Freeing disk space to reach $[min_free_space / 1024 / 1024] GiB"
    echo "== Current free space is $[$(matrix-free-space) / 1024 / 1024] GiB"
    echo "================================================================================"
    echo

    if [ ! -d $MATRIX_ROOT/spock/var/installed ]; then
	echo "No RMC/Spock installed packages to remove"
	return 0
    fi

    (
	cd $MATRIX_ROOT/spock/var/installed
	ls -tr */*.used |sed 's/\.used//' |while read installed; do
	    local rmc_host="${installed%%/*}"
	    [ "$rmc_host" = "matrix-slave" ] && continue

	    # Check free space
	    if [ $(matrix-free-space) -lt $min_free_space ]; then
		# Get the name of the package
		local package_name="$(sed -n "/^package/ s/package:[ \t]*'\(.*\)'.*/\1/p" <"$installed.yaml")"
		if [ "$package_name" = "" ]; then
		    package_name="$(sed -n "/^package/ s/package:[ \t]*\([-_a-zA-Z0-9]*\)[ \t]*\$/\1/p" <"$installed.yaml")"
		    package_name="$(echo "$package_name" |tr -d "'")"
		fi

		# Avoid removing compilers and other important things.
		case "$package_name" in
		    spock)                # Spock itself
			continue
			;;
		    gnu-*|llvm-*|intel-*) # compilers
			continue
			;;
		    *-generation)       # compiler code generators
			continue
			;;

		esac

		echo "removing $package_name as $installed"
		rm -rf "$installed.used" "$installed.yaml" "$installed"
	    fi
	done
    )

    local have_free=$(matrix-free-space)
    if [ $have_free -lt $min_free_space ]; then
	local have_free_gb=$[have_free / 1024 / 1024]
	local min_free_gb=$[min_free_space / 1024 / 1024]
	die "error: not enough free disk space for running tests (have $have_free_gb but need $min_free_gb GB)"
    fi
}

#------------------------------------------------------------------------------------------------------------------------
# Remove images for all Docker containers
matrix-maybe-remove-os-images() {
    local installed_version="$(cat images-key 2>/dev/null)"
    local desired_version="$TEST_ENVIRONMENT_VERSION"

    if [ "$installed_version" != "$desired_version" ]; then
	if [ -n "$AWS_EC2_INSTANCE" ]; then
	    # Nuclear option tries to remove all containers and images
	    docker container rm $(docker container ls -a |tail +2 |cut -d' ' -f1) || true
	    docker container rm $(docker container ls -a |tail +2 |cut -d' ' -f1) || true
	    docker image rm $(docker image ls -a |tail +2 |tr -s ' ' '\t' |cut -f3) || true
	    docker image rm $(docker image ls -a |tail +2 |tr -s ' ' '\t' |cut -f3) || true
	else
	    # More precise
	    rose-matrix-run --rebuild-images
	fi
	echo "$desired_version" >images-key
    fi
}

#------------------------------------------------------------------------------------------------------------------------
# Get the test source that is to be tested.  This is efficient in that it only updates the source code if the current
# version is different than what we're supposed to be testing.
have_test_source=
matrix-get-test-source() {
    local key="$TEST_REPOSITORY $TEST_COMMITTISH"
    if [ "$key" != "$have_test_source" ]; then
	echo
	echo
	echo "================================================================================"
	echo "Getting new testable source code, version $TEST_COMMITTISH"
	echo "Downloading from $TEST_REPOSITORY"
	echo "================================================================================"
	echo
	matrix-report-health run-download "ROSE $TEST_COMMITTISH"

	# If the repository is already present, try to upgrade it instead of downloading the whole thing again.
	[ -d rose ] || git clone "$TEST_REPOSITORY" rose
	(
	    cd rose
	    git fetch "$TEST_REPOSITORY" "$TEST_COMMITTISH"
	    git reset --hard FETCH_HEAD
	    git submodule update
	    ./scripts/smgit clean -dfx || git clean -dfx
	)
	have_test_source="$key"
    fi
}

#------------------------------------------------------------------------------------------------------------------------
# Cause the next boot of this instance to automatically reconfigure itself and start running tests.
matrix-setup-cron-jobs() {
    echo
    echo "Activating cron jobs"
    cp "$MATRIX_ROOT/rose-installed/latest/bin/rose-matrix-slave-babysit" "${SELF}-babysit"
    echo "@reboot screen -d -m -e^Zz -S matrix -L /bin/bash ${SELF}-babysit $SELF" >crontab
    crontab crontab
}

#------------------------------------------------------------------------------------------------------------------------
# Clean up some things
matrix-cleanup() {
    : nothing to do right now
}

#------------------------------------------------------------------------------------------------------------------------
# Main program...

# All work is done from the portability testing root directory. This script takes care to not create or remove files
# anywhere else in the filesystem other than temporary files created in the usual temp directories. It will not clean
# up everything when it exits, because we want to be able to restart quickly when possible.
mkdir -p "$MATRIX_ROOT"
cd "$MATRIX_ROOT"

# Use our own installation of RMC/Spock so as to not interfere with other development that's happening on this machine.
export SPOCK_HOSTNAME=matrix-slave
export SPOCK_ROOT="$MATRIX_ROOT/spock"
export PATH="$SPOCK_ROOT/bin:$MATRIX_ROOT/rose-installed/latest/bin:$PATH"

# When using Tup to compile ROSE, we need to set this to non-empty, acknowledging that it's an experimental feature not
# intended for most users. If we don't set this, then the ROSE build using Tup will fail with a message about being
# experimental.
export TUP_ACKNOWLEDGMENT=yes

# Update software that will be needed to configure and compile the portability testing tools (and ROSE itself). If
# RMC/Spock needs to be updated, then any existing portability tools that are installed will no longer work (because
# their shared libraries were purged) and will be removed. Assume that since this is a ROSE developer's machine, that
# all the system prerequisites are already installed.
matrix-update-system-software
matrix-test-docker
matrix-get-initial-configuration
matrix-install-rmc-spock
matrix-clean-failed-dependencies

# Install initial version of portability testing tools if there are none installed (or if they were removed by prior
# steps of this script) or they're the wrong version. All slaves should be running the same software as told to us by
# the database. If we can't contact the database, then we'll first build the latest development version of the tools in
# order to contact the database -- this is relatively foolprove. If we built the wrong version, we'll fix that in the
# testing loop.
matrix-install-matrix-tools
matrix-update-this-script restart

# Here starts the actual testing loop.
test_number=0
while [ "$SETUP" = "" ]; do
    test_number=$[test_number + 1]

    # Delete software installed by the testing slaves until we have at least the specified amount of free space,
    # measured in kB. We do this by removing the least recently used packages first.
    matrix-reclaim-disk $[MIN_FREE_SPACE * 1024 * 1024]

    # Get that latest slave configuration and possibly update the portability testing tools. This is done inside the
    # testing loop so that we can upgrade all slaves even while they're running. Unfortunately, it's not practical
    # to update the script we're running (we can only do that during the initial setup, or when we're about to exit).
    matrix-get-slave-configuration
    matrix-install-matrix-tools

    # Obtain the software which is to be tested
    if [ "$TEST_REPOSITORY" = "" -o "$TEST_COMMITTISH" = "" ]; then
	echo "$arg0: testing is paused (no testable version specified)"
	matrix-report-health run-paused "nothing to test"
	sleep 300
	continue
    fi
    matrix-maybe-remove-os-images
    matrix-get-test-source

    echo
    echo
    echo "================================================================================"
    echo "== Starting test, loop iteration $test_number"
    echo "================================================================================"
    echo
    matrix-report-health run-test "iteration $test_number"
    rose-matrix-run --host-root="${MATRIX_HOST_ROOT}" --var="$MATRIX_ROOT" --slave="$SLAVE_NAME" $TEST_FLAGS -n1 $MATRIX_ROOT/rose
done

# Finish setup actions
if [ -n "$SETUP" ]; then
    if [ -n "$AWS_EC2_INSTANCE" ]; then
	matrix-setup-cron-jobs
	echo
	echo "AWS EC2 portability testing slave setup has been completed. This machine will"
	echo "  automatically start testing next time it is rebooted. If you want to test now,"
	echo "  run this script again but without any arguments."
    fi
fi

# Cleanup
matrix-cleanup
if [ -n "$SETUP" ]; then
    matrix-report-health run-stop "installation completed"
else
    matrix-report-health run-stop "testing completed"
fi

matrix-update-this-script
exit 0
