#!/bin/sh -ex
# it seems that we constantly get authentification problems... maybe its just because of the additional parameters


echo "Running curl... on build $BUILD_NUMBER"
echo "http://hudson-rose.llnl.gov:8080/job/v8-test-windows-node2/build?token=WIN\&BUILD_JOB_BUILD_NUMBER=$BUILD_NUMBER"

curl 'http://hudson-rose.llnl.gov:8080/job/v8-test-windows-node2/build?token=WIN\&BUILD_JOB_BUILD_NUMBER=$BUILD_NUMBER'

echo "Curl without apostrophes"
curl http://hudson-rose.llnl.gov:8080/job/v8-test-windows-node2/build?token=WIN\&BUILD_JOB_BUILD_NUMBER=$BUILD_NUMBER

echo Trying another project
curl  'http://hudson-rose.llnl.gov:8080/job/v7-opengl-wintest-scratch/build?token=WIN'

echo Trying another project without apostrophes
curl  http://hudson-rose.llnl.gov:8080/job/v7-opengl-wintest-scratch/build?token=WIN

echo "Done curl."
