#!/bin/sh -ex
# tps : This is a test to see if we can pass a parameter to a downstream test from a upstream test
# 
# So far this works only if no parameters are given


echo "Running curl... on build $BUILD_NUMBER"
echo "http://hudson-rose.llnl.gov:8080/job/v8-test-windows-node2/build?token=WIN\&BUILD_JOB_BUILD_NUMBER=$BUILD_NUMBER"

echo THIS does not work because it has a parameter BUILD_JOB_BUILD
echo ERROR WILL BE: authentification needed 
curl 'http://hudson-rose.llnl.gov:8080/job/v8-test-windows-node2/build?token=WIN\&BUILD_JOB_BUILD_NUMBER=$BUILD_NUMBER'

echo THIS works because it has no parameter
curl  'http://hudson-rose.llnl.gov:8080/job/v7-opengl-wintest-scratch/build?token=WIN\&BUILD_JOB_BUILD_NUMBER=$BUILD_NUMBER'


echo "Done curl."
