#! /bin/sh

# Parse command-line
do_quiet=yes
while [ "$#" -gt 0 ]; do
    arg="$1"; shift
    case "$arg" in
	--verbose)
	    do_quiet=no
	    ;;
        --quiet)
            echo "$0: warning: --quiet is now the default mode and is ignored"
            ;;
        *)
	    echo "$0: unrecognized argument: $arg" >&2
	    exit 1
	    ;;
    esac
done

# Debugging output is provided using the -x option as in "#! /bin/sh -x"

# DQ (12/22/2005): remove the autoconf caches
rm -rf autom4te.cache src/3rdPartyLibraries/PDFlib-Lite-6.0.2rv/autom4te.cache

./makelinks

# RV 9/14/2005 -- Upgrade of PDF library
(cd src/3rdPartyLibraries/PDFlib-Lite-6.0.2rv ; ./bootstrap)

aclocal -I ./config -I ./acmacros -I ./src/3rdPartyLibraries/libltdl -I /usr/share/aclocal || : exit 1

# autoheader --warnings=obsolete,all || : exit 1
autoheader || : exit 1

# autoconf --warnings=syntax,obsolete,all || : exit 1
autoconf || : exit 1

# automake -a -c --include-deps --foreign --verbose || : exit 1
# automake -a -c -i --foreign $AUTOMAKE_FLAGS || : exit 1
# automake -a -c -i --foreign |& grep -v "is not a standard library name" || : exit 1
# automake -a -c -i --foreign || : exit 1
automake -a -c -i --foreign 2>&1 | grep -v "is not a standard library name" 1>&2 || : exit 1

# Automake manual says that if we use AM_CONFIG_HEADER we have to build the stamp-h.in files
touch stamp-h.in  || : exit 1
touch stamp-h1.in || : exit 1

# Do the same steps in libltdl
(cd src/3rdPartyLibraries/libltdl && aclocal && automake --add-missing && autoconf)

# Rewrite a couple of makefile rules to be less verbose so (1) we can actually see the warning messages
# and (2) XEmacs doesn't get regexp stack overflows when parsing compiler output.
if [ "$do_quiet" = "yes" ]; then
    find . -name Makefile.in |xargs sed -i~ \
	-e 's/^\(LT\)\{0,1\}\(CXX\)\{0,1\}COMPILE =/& @echo "  COMPILE $@";/' \
	-e 's/^\(CXX\)\{0,1\}LINK =/& @echo "  LINK    $@";/'       \
	-e 's/@LIBTOOL@/& --quiet/g'
fi

echo "***** BUILD TERMINATED NORMALLY *****"

# run build or better yet RUN_ME_AFTER_CHECKOUT.sh
# echo "Call tests/performanceTests/BenchmarkBase/RUN_ME_AFTER_CHECKOUT.sh ..."
# cd tests/PerformanceTests/BenchmarkBase; RUN_ME_AFTER_CHECKOUT.sh; 
# cd ../../..;

