#! /bin/sh

# Use /bin/sh -x to see more output within debugging shell script

# Make sure we are run in the top level directory.
# if test ! -d src || test ! -d EDG || test ! -d ROSETTA || test ! -d SAGE ; then
if test ! -f configure.in; then
  echo "$0 has to be run in the top level ROSE directory (configure.in file not found)"
  exit 1
else
  echo "$0 is confirmed to be running in the top level ROSE directory (or at least the configure.in file was found)"
fi

# Make sure we have acmacros (if not check it out from where several projects share it, maintained by Brian Gunney).
#if test ! -d acmacros ; then
#  test -z "$CVSROOT_BTNG" && CVSROOT_BTNG=/usr/casc/samrai/gunney/cvsrepository
#  echo "No acmacros directory.  Using current version in $CVSROOT_BTNG"
#  if test -d CVS ; then
#    cvs -d $CVSROOT_BTNG checkout acmacros
#  else
## DQ (1/7/2008): Change suggested by Valentin David (10/10/2007)
##   cvs -d $CVSROOT_BTNG export acmacros
#    cvs -d $CVSROOT_BTNG export -r HEAD acmacros
#  fi
#fi

# Make sure we have Brian Miller's Performance Test Suite.
# if test ! -d tests/PerformanceTests/BenchmarkBase ; then
#  test "$CVSROOT_PERFORMANCE_TEST_SUITE" || CVSROOT_PERFORMANCE_TEST_SUITE=/usr/casc/overture/bmiller/Repository
#  echo "No Performance Test Suite directory.  Using current version in $CVSROOT_PERFORMANCE_TEST_SUITE"
#  mkdir -p tests/PerformanceTests
#  cd tests/PerformanceTests
#  if test -d ../CVS ; then
#    cvs -d $CVSROOT_PERFORMANCE_TEST_SUITE checkout BenchmarkBase
#  else
#    cvs -d $CVSROOT_PERFORMANCE_TEST_SUITE export -D "`date`" BenchmarkBase
#  fi
#  cd ../..
# fi

