#!/bin/sh 

# Basic test script
# (C) 2007 Adrian Prantl, Viktor Pavlu

FILES=`ls tests/*.[cC] tests/*.cpp`
ANALYSIS="./srw98_shape"
MODES="--textoutput --termoutput --sourceoutput --aliastextoutput --aliassourceoutput"
OPTIONS="--wholeprogram --preinfo --postinfo --foldgraphs --no_individualgraphs --summarygraph"
GENERATE_PERMUTATIONS="0" # 0=do not / 1=do generate permutations of OPTIONS

ALL=
SUCESS=
FAILED=

# possible buggy testcases

DELIM=%
PERMUTATIONS="$DELIM"
if [ $GENERATE_PERMUTATIONS -eq "0" ]; then
    PERMUTATIONS="$PERMUTATIONS $OPTIONS"
else
    for opt in $OPTIONS; do
        newperms=
        for perm in $PERMUTATIONS; do
            newperms="$newperms $perm"
            newperms="$newperms $perm$DELIM$opt"
        done
        PERMUTATIONS="$newperms"
    done
fi


echo "######## ######## Testing mode \"$MODES\""

for file in $FILES; do

    echo "######## on file $file"

    # for each option (even no options)
    #for option in $PERMUTATIONS; do

        #option_with_space=${option//$DELIM/ }
        option_with_space=$OPTIONS

        echo "$ANALYSIS $file $MODES $option_with_space"
        $ANALYSIS $file $MODES $option_with_space >/dev/null

        if [ $? -eq 0 ]; then SUCCESS="$SUCCESS $file$DELIM$MODES$DELIM$option"
        else FAILED="$FAILED $ANALYSIS$DELIM$file$DELIM$MODES$DELIM$option"; fi
        ALL="$ALL $ANALYSIS$DELIM$file$DELIM$MODES$DELIM$option"
    #done 
done



echo "########################################################################"
echo "# SATIrE automagic test report, `date`"
echo "########################################################################"
echo

TOTAL=`echo $ALL    |wc -w`
GOOD=`echo  $SUCCESS|wc -w`
BAD=`echo   $FAILED |wc -w`
GOOD_PERC=`echo $GOOD*100/$TOTAL|bc`
BAD_PERC=`echo $BAD*100/$TOTAL|bc`

echo "[$GOOD/$TOTAL] succeeded ($GOOD_PERC%)!" # FIXME: integer only
#if [ -n "$SUCCESS" ]; then 
#    echo [$SUCCESS]
#fi

echo "[$BAD/$TOTAL] failed ($BAD_PERC%):"
if [ -n "$FAILED" ]; then 
    for f in $FAILED; do
        f=${f//$DELIM/ }
	echo "  $f"
    done
    #echo "Press <Ctrl-C> to abort or <Return> to continue"
    #read 
    #exit 1
fi
echo "########################################################################"
