#!/bin/bash

for file in `ls /usr/bin | grep -v "\."` 
do
file='/usr/bin/'${file}
echo "Checking if $file exists."
if [ -f $file ]; then 
 echo "./binCompassMain $file -checkAST -gml -noedges "
 ./binCompassMain $file -checkAST -gml -noedges  
else
 echo "Failed to run $file"
fi
done
