#!/bin/echo "ERROR: Do not execute this script! Source it from bash:"
#
# Sets up the ROSE version and Intel compler variables for KULL.
# Sets:
#   AUTOMATION_HOME
#   ROSE_VERSION
#   CODE_BASE
#   *_COMPILER_*
#   ROSE_HOME
#   ROSE_LD_LIBRARY_PATH
#   ROSE_REPO:

set_ROSE_HOME_dir=`dirname ${BASH_SOURCE[0]}`
export AUTOMATION_HOME=`(cd ${set_ROSE_HOME_dir}/../..;pwd)`
set_ROSE_HOME_support_dir="${AUTOMATION_HOME}/ROSE"

# Declare define_component_variables, define_desired_export_vars:
source "${set_ROSE_HOME_support_dir}/set_ROSE_HOME_support.sh"

# Set:
#   ROSE_VERSION
#   CODE_BASE
#   *_COMPILER_*
#   ...
define_component_variables

#======================================
# FOR GCC 4.9.3 non-MPI (used by Kull):
#======================================
#
export ROSE_COMPILER_VERSIONED="${GCC_COMPILER_VERSIONED}"
export ROSE_COMPILER_HOME="${GCC_COMPILER_HOME}"
# ROSE configure wants these - anybody else?:
export  CC="${ROSE_COMPILER_HOME}/bin/gcc"
export CXX="${ROSE_COMPILER_HOME}/bin/g++"

export BACKEND_COMPILER_VERSIONED="${GCC_COMPILER_VERSIONED}"
export BACKEND_COMPILER_HOME="${GCC_COMPILER_HOME}"
export BACKEND_COMPILER_PATH="${BACKEND_COMPILER_HOME}/bin/g++"

#export ROSE_BUILD_PATH="${ROSE_REPO_PATH_VERSIONED}-${ROSE_COMPILER_VERSIONED}-${BACKEND_COMPILER_VERSIONED}"
export ROSE_BUILD_PATH="${ROSE_REPO_PATH_VERSIONED}-${ROSE_COMPILER_VERSIONED}"
#=====================================

# Set:
#   ROSE_HOME
#   ROSE_LD_LIBRARY_PATH
#   ROSE_REPO
define_desired_export_vars

