#ifndef ANALYSIS_PARAMETERS_H
#define ANALYSIS_PARAMETERS_H

namespace CodeThorn {
  
  enum ExplorationMode { EXPL_UNDEFINED, EXPL_DEPTH_FIRST, EXPL_BREADTH_FIRST, EXPL_LOOP_AWARE, EXPL_LOOP_AWARE_SYNC, EXPL_RANDOM_MODE1,EXPL_TOPOLOGIC_SORT };

} // end of namespace CodeThorn

#endif
