# libcodethorn.so source/header files

# Codethorn library header files without corresponding source files
set(CODETHORN_SOLO_HEADER_FILES
    AnalysisParameters.h
    CollectionOperators.h
    CtxAnalysis.h
    CtxAttribute.h
    CtxLattice.h
    CtxPropertyStateFactory.h
    CtxTransfer.h
    DataDependenceVisualizer.h
    EqualityMaintainer.h
    Evaluator.h
    ExecutionTrace.h
    HSetMaintainer.h
    Memoizer.h
    ReadWriteData.h
    Utility.h
    WorkListSeq.h
)

# Codethorn library header files (each with a corresponding source file)
set(CODETHORN_HEADER_FILES
    AbstractValue.h
    addressTakenAnalysis.h
    AliasAnalysis.h
    AstUtility.h
    AnalysisAstAnnotator.h
    AnalysisReporting.h
    CTAnalysis.h
    ArrayElementAccessData.h
    AstNodeInfo.h
    BoolLattice.h
    CallGraphAnalysis.h
    CallGraphExport.h
    CallString.h
    CFAnalysis.h
    ClassHierarchyAnalysis.h
    ClassHierarchyWriter.h
    CodeThornLib.h
    CodeThornPasses.h
    CommandLineOptions.h
    ContNodeAttribute.h
    CounterexampleGenerator.h
    CPAstAttribute.h
    CppLabeler.h
    CppStdUtilities.h
    CTIOLabeler.h
    CtxCallStrings.h
    CtxPrioritySolver.h
    CtxReachabilityLattice.h
    CtxSolver0.h
    CtxUnfoldedAnalysis.h
    DataDependenceVisualizer.h
    defUseQuery.h
    DFAbstractSolver.h
    DFAnalysisBaseWithoutData.h
    DFAnalysisBase.h
    CSDFAnalysisBase.h
    CSDFAnalysisBaseWithoutData.h
    ConstantConditionAnalysis.h
    DFTransferFunctions.h
    DotGraphCfgFrontend.h
    EState.h
    EStateTransferFunctions.h
    EStateWorkList.h
    EStatePriorityWorkList.h
    FIConstAnalysis.h
    Flow.h
    FunctionCallMapping.h
    FunctionCallMapping2.h
    FunctionCallTarget.h
    FunctionId.h
    FunctionIdMapping.h
    GeneralWorkList.h
    GeneralWorkList.C
    GeneralPriorityWorkList.h
    GeneralPriorityWorkList.C
    InputOutput.h
    InternalChecks.h
    IOAnalyzer.h
    IOSequenceGenerator.h
    IOSolver.h
    LanguageRestrictorCollection.h
    LanguageRestrictor.h
    Lattice.h
    LoopInfo.h
    Miscellaneous2.h
    Miscellaneous.h
    Normalization.h
    NormalizationCxx.h
    NormalizationInliner.h
    NormalizationOp.h
    NumberIntervalLattice.h
    Options.h
    CodeThornOptions.h
    ParProOptions.h
    LTLOptions.h
    LTLRersMapping.h
    DFSolver1.h
    DFSolver2.h
    ObjectLayoutAnalysis.h
    MemoryViolationAnalysis.h
    PointerAnalysisInterface.h
    PragmaHandler.h
    PredefinedSemanticFunctions.h
    ProgramAbstractionLayer.h
    ProgramInfo.h
    ProgramLocationsReport.h
    ProgramLocationsAnalysis.h
    PropertyState.h
    PropertyStateFactory.h
    PropertyValueTable.h
    PState.h
    ReachabilityAnalysis.h
    ReadWriteListener.h
    ReadWriteTraceAnalysis.h
    RersSpecialization.h
    RERS_empty_specialization.h
    RersCounterexample.h
    RewriteStatistics.h
    RewriteSystem.h
    RoseCompatibility.h
    Solver5.h
    Solver16.h
    Solver17.h
    Solver18.h
    Solver19.h
    Solver8.h
    Solver.h
    Specialization.h
    SvcompWitness.h
    TimeMeasurement.h
    TimingCollector.h
    TopologicalSort.h
    TransitionGraph.h
    TransitionGraphReducer.h
    TypeSizeMapping.h
    VariableIdUtils.h
    VariableIdMappingExtended.h
    VariableValueMonitor.h
    Visualizer.h
)

# Codethorn library source files (each with a corresponding header file)
set(CODETHORN_SOURCE_FILES
    AbstractValue.C
    addressTakenAnalysis.C
    AliasAnalysis.C
    AstUtility.C
    AnalysisAstAnnotator.C
    AnalysisReporting.C
    CTAnalysis.C
    ArrayElementAccessData.C
    AstNodeInfo.C
    BoolLattice.C
    CallGraphAnalysis.C
    CallGraphExport.C
    CallString.C
    CFAnalysis.C
    ClassHierarchyAnalysis.C
    ClassHierarchyWriter.C
    CodeThornLib.C
    CodeThornPasses.C
    CommandLineOptions.C
    ContNodeAttribute.C
    CounterexampleGenerator.C
    CPAstAttribute.C
    CppLabeler.C
    CppStdUtilities.C
    CTIOLabeler.C
    CtxCallStrings.C
    CtxPrioritySolver.C
    CtxReachabilityLattice.C
    CtxSolver0.C
    CtxUnfoldedAnalysis.C
    DataDependenceVisualizer.C
    defUseQuery.C
    DFAnalysisBaseWithoutData.C
    DFAnalysisBase.C
    CSDFAnalysisBase.C
    ConstantConditionAnalysis.C
    DFTransferFunctions.C
    DotGraphCfgFrontend.C
    EState.C
    EStateTransferFunctions.C
    EStateWorkList.C
    EStatePriorityWorkList.C
    FIConstAnalysis.C
    Flow.C
    FunctionCallMapping.C
    FunctionCallMapping2.C
    FunctionCallTarget.C
    FunctionId.C
    FunctionIdMapping.C
    InputOutput.C
    InternalChecks.C
    IOAnalyzer.C
    IOSequenceGenerator.C
    IOSolver.C
    LanguageRestrictorCollection.C
    LanguageRestrictor.C
    Lattice.C
    LoopInfo.C
    CodeThornOptions.C
    LTLOptions.C
    ParProOptions.C
    LTLRersMapping.C
    Miscellaneous2.C
    Miscellaneous.C
    Normalization.C
    NormalizationCxx.C
    NormalizationInliner.C
    NormalizationOp.C
    NumberIntervalLattice.C
    DFSolver1.C
    DFSolver2.C
    ObjectLayoutAnalysis.C
    MemoryViolationAnalysis.C
    PointerAnalysisInterface.C
    PragmaHandler.C
    PredefinedSemanticFunctions.C
    ProgramAbstractionLayer.C
    ProgramInfo.C
    ProgramLocationsReport.C
    ProgramLocationsAnalysis.C
    PropertyState.C
    PropertyStateFactory.C
    PropertyValueTable.C
    PState.C
    ReachabilityAnalysis.C
    ReadWriteListener.C
    ReadWriteTraceAnalysis.C
    RERS_empty_specialization.C
    RersCounterexample.C
    RewriteStatistics.C
    RewriteSystem.C
    RoseCompatibility.C
    Solver5.C
    Solver16.C
    Solver17.C
    Solver18.C
    Solver19.C
    Solver8.C
    Solver.C
    Specialization.C
    SvcompWitness.C
    TimeMeasurement.C
    TimingCollector.C
    TopologicalSort.C
    TransitionGraph.C
    TransitionGraphReducer.C
    TypeSizeMapping.C
    VariableIdUtils.C
    VariableIdMappingExtended.C
    VariableValueMonitor.C
    Visualizer.C
)
