# -*- makefile -*-

# All variables in this makefile begin with "nonsmoke_specimens_cil_" (since that's where this file is located in the
# directory hierarchy.

nonsmoke_specimens_cil_directory = $(top_srcdir)/tests/nonsmoke/specimens/cil

nonsmoke_specimens_cil_all =	\
  boxer.exe       \
  instance.exe    \
  loadToken.exe   \
  newarray.exe    \
  test1.exe       \
  test2.exe       \
  test3.exe       \
  test4.exe       \
  userstring.exe  

