#!/bin/sh

# Turn on error checking so that any error forces a failure of the script
set -e
set -x

if [ $# -ne 1 ]; then
  echo "Usage: $0 srcdir" 1>&2
  exit 1
fi

srcdir=$1

DIFF_OPTIONS="-U5 -b -d"
PREFIX=""

echo "Running tests: ./preTest $srcdir/pass1.C"
$PREFIX ./preTest $srcdir/pass1.C
echo "Checking Results: diff $DIFF_OPTIONS $srcdir/rose_pass1.C.save rose_pass1.C"
diff $DIFF_OPTIONS $srcdir/rose_pass1.C.save rose_pass1.C
# rm -f rose_pass1.C

echo "Running tests: ./preTest $srcdir/pass2.C"
$PREFIX ./preTest $srcdir/pass2.C
echo "Checking Results: diff $DIFF_OPTIONS $srcdir/rose_pass2.C.save rose_pass2.C"
diff $DIFF_OPTIONS $srcdir/rose_pass2.C.save rose_pass2.C
# rm -f rose_pass2.C

echo "Running tests: ./preTest $srcdir/pass3.C"
$PREFIX ./preTest $srcdir/pass3.C
echo "Checking Results: diff $DIFF_OPTIONS $srcdir/rose_pass3.C.save rose_pass3.C"
diff $DIFF_OPTIONS $srcdir/rose_pass3.C.save rose_pass3.C
# rm -f rose_pass3.C

echo "Running tests: ./patternRewriteTest $srcdir/rewrite_test1.C"
$PREFIX ./patternRewriteTest $srcdir/rewrite_test1.C
echo "Checking Results: diff $DIFF_OPTIONS $srcdir/rose_rewrite_test1.C.save rose_rewrite_test1.C"
diff $DIFF_OPTIONS $srcdir/rose_rewrite_test1.C.save rose_rewrite_test1.C
# rm -f rose_rewrite_test1.C

echo "Running tests: ./finiteDifferencingTest $srcdir/finitediff_test1.C"
$PREFIX ./finiteDifferencingTest $srcdir/finitediff_test1.C
echo "Checking Results: diff $DIFF_OPTIONS $srcdir/rose_finitediff_test1.C.save rose_finitediff_test1.C"
diff $DIFF_OPTIONS $srcdir/rose_finitediff_test1.C.save rose_finitediff_test1.C
# rm -f rose_finitediff_test1.C

echo "Running tests: ./finiteDifferencingTest $srcdir/finitediff_test2.C"
$PREFIX ./finiteDifferencingTest $srcdir/finitediff_test2.C
echo "Checking Results: diff $DIFF_OPTIONS $srcdir/rose_finitediff_test2.C.save rose_finitediff_test2.C"
diff $DIFF_OPTIONS $srcdir/rose_finitediff_test2.C.save rose_finitediff_test2.C
# rm -f rose_finitediff_test2.C

echo "Running tests: ./finiteDifferencingTest $srcdir/finitediff_test3.C"
$PREFIX ./finiteDifferencingTest $srcdir/finitediff_test3.C
echo "Checking Results: diff $DIFF_OPTIONS $srcdir/rose_finitediff_test3.C.save rose_finitediff_test3.C"
diff $DIFF_OPTIONS $srcdir/rose_finitediff_test3.C.save rose_finitediff_test3.C
# rm -f rose_finitediff_test3.C
