         "EOF expected",
         "number expected",
         "\"*\" expected",
         "\"/\" expected",
         "\"+\" expected",
         "\"-\" expected",
         "not expected",
         "unexpected symbol in AddOp",
         "unexpected symbol in Factor",
         "unexpected symbol in MulOp",
