// automatically generated by the FlatBuffers compiler, do not modify


#ifndef FLATBUFFERS_GENERATED_FLATBUFFERSCHEMA_ROSE_BINARYANALYSIS_SERIALIZATION_FLATBUFFERS_H_
#define FLATBUFFERS_GENERATED_FLATBUFFERSCHEMA_ROSE_BINARYANALYSIS_SERIALIZATION_FLATBUFFERS_H_

#include "flatbuffers/flatbuffers.h"

// Ensure the included flatbuffers.h is the same version as when this file was
// generated, otherwise it may not be compatible.
static_assert(FLATBUFFERS_VERSION_MAJOR == 25 &&
              FLATBUFFERS_VERSION_MINOR == 9 &&
              FLATBUFFERS_VERSION_REVISION == 23,
             "Non-compatible flatbuffers version included");

namespace Rose {
namespace BinaryAnalysis {
namespace Serialization {
namespace Flatbuffers {

struct Instruction;
struct InstructionBuilder;

struct BasicBlock;
struct BasicBlockBuilder;

struct DataBlock;
struct DataBlockBuilder;

struct SomeColumn;
struct SomeColumnBuilder;

struct None;
struct NoneBuilder;

struct SourceLocation;
struct SourceLocationBuilder;

struct BasicBlockRef;

struct InstructionRef;

struct DataBlockRef;

struct Function;
struct FunctionBuilder;

struct FunctionRef;

struct CFGVertex;
struct CFGVertexBuilder;

struct CFGEdge;
struct CFGEdgeBuilder;

struct CFG;
struct CFGBuilder;

struct Interval;
struct IntervalBuilder;

struct Segment;
struct SegmentBuilder;

struct IntervalSegment;
struct IntervalSegmentBuilder;

struct AddressMap;
struct AddressMapBuilder;

struct MemoryMap;
struct MemoryMapBuilder;

struct AddressUsageEntry;
struct AddressUsageEntryBuilder;

struct AddressUsageMap;
struct AddressUsageMapBuilder;

struct Partitioner;
struct PartitionerBuilder;

enum class Column : uint8_t {
  NONE = 0,
  SomeColumn = 1,
  None = 2,
  MIN = NONE,
  MAX = None
};

inline const Column (&EnumValuesColumn())[3] {
  static const Column values[] = {
    Column::NONE,
    Column::SomeColumn,
    Column::None
  };
  return values;
}

inline const char * const *EnumNamesColumn() {
  static const char * const names[4] = {
    "NONE",
    "SomeColumn",
    "None",
    nullptr
  };
  return names;
}

inline const char *EnumNameColumn(Column e) {
  if (::flatbuffers::IsOutRange(e, Column::NONE, Column::None)) return "";
  const size_t index = static_cast<size_t>(e);
  return EnumNamesColumn()[index];
}

template<typename T> struct ColumnTraits {
  static const Column enum_value = Column::NONE;
};

template<> struct ColumnTraits<Rose::BinaryAnalysis::Serialization::Flatbuffers::SomeColumn> {
  static const Column enum_value = Column::SomeColumn;
};

template<> struct ColumnTraits<Rose::BinaryAnalysis::Serialization::Flatbuffers::None> {
  static const Column enum_value = Column::None;
};

bool VerifyColumn(::flatbuffers::Verifier &verifier, const void *obj, Column type);
bool VerifyColumnVector(::flatbuffers::Verifier &verifier, const ::flatbuffers::Vector<::flatbuffers::Offset<void>> *values, const ::flatbuffers::Vector<Column> *types);

enum class CFGVertexType : uint8_t {
  V_BASIC_BLOCK = 0,
  V_UNDISCOVERED = 1,
  V_INDETERMINIATE = 2,
  V_NONEXISTING = 3,
  V_USER_DEFINED = 4,
  MIN = V_BASIC_BLOCK,
  MAX = V_USER_DEFINED
};

inline const CFGVertexType (&EnumValuesCFGVertexType())[5] {
  static const CFGVertexType values[] = {
    CFGVertexType::V_BASIC_BLOCK,
    CFGVertexType::V_UNDISCOVERED,
    CFGVertexType::V_INDETERMINIATE,
    CFGVertexType::V_NONEXISTING,
    CFGVertexType::V_USER_DEFINED
  };
  return values;
}

inline const char * const *EnumNamesCFGVertexType() {
  static const char * const names[6] = {
    "V_BASIC_BLOCK",
    "V_UNDISCOVERED",
    "V_INDETERMINIATE",
    "V_NONEXISTING",
    "V_USER_DEFINED",
    nullptr
  };
  return names;
}

inline const char *EnumNameCFGVertexType(CFGVertexType e) {
  if (::flatbuffers::IsOutRange(e, CFGVertexType::V_BASIC_BLOCK, CFGVertexType::V_USER_DEFINED)) return "";
  const size_t index = static_cast<size_t>(e);
  return EnumNamesCFGVertexType()[index];
}

enum class CFGEdgeType : uint8_t {
  E_NORMAL = 0,
  E_FUNCTION_CALL = 1,
  E_FUNCTION_RETURN = 2,
  E_CALL_RETURN = 3,
  E_FUNCTION_XFER = 4,
  E_USER_DEFINED = 5,
  MIN = E_NORMAL,
  MAX = E_USER_DEFINED
};

inline const CFGEdgeType (&EnumValuesCFGEdgeType())[6] {
  static const CFGEdgeType values[] = {
    CFGEdgeType::E_NORMAL,
    CFGEdgeType::E_FUNCTION_CALL,
    CFGEdgeType::E_FUNCTION_RETURN,
    CFGEdgeType::E_CALL_RETURN,
    CFGEdgeType::E_FUNCTION_XFER,
    CFGEdgeType::E_USER_DEFINED
  };
  return values;
}

inline const char * const *EnumNamesCFGEdgeType() {
  static const char * const names[7] = {
    "E_NORMAL",
    "E_FUNCTION_CALL",
    "E_FUNCTION_RETURN",
    "E_CALL_RETURN",
    "E_FUNCTION_XFER",
    "E_USER_DEFINED",
    nullptr
  };
  return names;
}

inline const char *EnumNameCFGEdgeType(CFGEdgeType e) {
  if (::flatbuffers::IsOutRange(e, CFGEdgeType::E_NORMAL, CFGEdgeType::E_USER_DEFINED)) return "";
  const size_t index = static_cast<size_t>(e);
  return EnumNamesCFGEdgeType()[index];
}

/// We don't know what ASSUMED means. It might mean that it was provided as input by the user via a configuration file.
/// PROVED means inferred via ROSE analysis (e.g., a fallthrough instruction)
/// TODO: should we represent this as a union
enum class CFGEdgeConfidence : uint8_t {
  ASSUMED = 0,
  PROVED = 1,
  MIN = ASSUMED,
  MAX = PROVED
};

inline const CFGEdgeConfidence (&EnumValuesCFGEdgeConfidence())[2] {
  static const CFGEdgeConfidence values[] = {
    CFGEdgeConfidence::ASSUMED,
    CFGEdgeConfidence::PROVED
  };
  return values;
}

inline const char * const *EnumNamesCFGEdgeConfidence() {
  static const char * const names[3] = {
    "ASSUMED",
    "PROVED",
    nullptr
  };
  return names;
}

inline const char *EnumNameCFGEdgeConfidence(CFGEdgeConfidence e) {
  if (::flatbuffers::IsOutRange(e, CFGEdgeConfidence::ASSUMED, CFGEdgeConfidence::PROVED)) return "";
  const size_t index = static_cast<size_t>(e);
  return EnumNamesCFGEdgeConfidence()[index];
}

/// We use explicit enum fields to enable OR'd together enums. 
enum class Accessibility : uint8_t {
  EXECUTABLE = 0,
  WRITABLE = 1,
  READABLE = 2,
  IMMUTABLE = 4,
  PRIVATE = 8,
  MIN = EXECUTABLE,
  MAX = PRIVATE
};

inline const Accessibility (&EnumValuesAccessibility())[5] {
  static const Accessibility values[] = {
    Accessibility::EXECUTABLE,
    Accessibility::WRITABLE,
    Accessibility::READABLE,
    Accessibility::IMMUTABLE,
    Accessibility::PRIVATE
  };
  return values;
}

inline const char * const *EnumNamesAccessibility() {
  static const char * const names[10] = {
    "EXECUTABLE",
    "WRITABLE",
    "READABLE",
    "",
    "IMMUTABLE",
    "",
    "",
    "",
    "PRIVATE",
    nullptr
  };
  return names;
}

inline const char *EnumNameAccessibility(Accessibility e) {
  if (::flatbuffers::IsOutRange(e, Accessibility::EXECUTABLE, Accessibility::PRIVATE)) return "";
  const size_t index = static_cast<size_t>(e);
  return EnumNamesAccessibility()[index];
}

enum class Endianness : uint8_t {
  ORDER_UNSPECIFIED = 0,
  ORDER_LSB = 1,
  ORDER_MSB = 2,
  MIN = ORDER_UNSPECIFIED,
  MAX = ORDER_MSB
};

inline const Endianness (&EnumValuesEndianness())[3] {
  static const Endianness values[] = {
    Endianness::ORDER_UNSPECIFIED,
    Endianness::ORDER_LSB,
    Endianness::ORDER_MSB
  };
  return values;
}

inline const char * const *EnumNamesEndianness() {
  static const char * const names[4] = {
    "ORDER_UNSPECIFIED",
    "ORDER_LSB",
    "ORDER_MSB",
    nullptr
  };
  return names;
}

inline const char *EnumNameEndianness(Endianness e) {
  if (::flatbuffers::IsOutRange(e, Endianness::ORDER_UNSPECIFIED, Endianness::ORDER_MSB)) return "";
  const size_t index = static_cast<size_t>(e);
  return EnumNamesEndianness()[index];
}

enum class AddressUser : uint8_t {
  NONE = 0,
  InstructionRef = 1,
  DataBlockRef = 2,
  MIN = NONE,
  MAX = DataBlockRef
};

inline const AddressUser (&EnumValuesAddressUser())[3] {
  static const AddressUser values[] = {
    AddressUser::NONE,
    AddressUser::InstructionRef,
    AddressUser::DataBlockRef
  };
  return values;
}

inline const char * const *EnumNamesAddressUser() {
  static const char * const names[4] = {
    "NONE",
    "InstructionRef",
    "DataBlockRef",
    nullptr
  };
  return names;
}

inline const char *EnumNameAddressUser(AddressUser e) {
  if (::flatbuffers::IsOutRange(e, AddressUser::NONE, AddressUser::DataBlockRef)) return "";
  const size_t index = static_cast<size_t>(e);
  return EnumNamesAddressUser()[index];
}

template<typename T> struct AddressUserTraits {
  static const AddressUser enum_value = AddressUser::NONE;
};

template<> struct AddressUserTraits<Rose::BinaryAnalysis::Serialization::Flatbuffers::InstructionRef> {
  static const AddressUser enum_value = AddressUser::InstructionRef;
};

template<> struct AddressUserTraits<Rose::BinaryAnalysis::Serialization::Flatbuffers::DataBlockRef> {
  static const AddressUser enum_value = AddressUser::DataBlockRef;
};

bool VerifyAddressUser(::flatbuffers::Verifier &verifier, const void *obj, AddressUser type);
bool VerifyAddressUserVector(::flatbuffers::Verifier &verifier, const ::flatbuffers::Vector<::flatbuffers::Offset<void>> *values, const ::flatbuffers::Vector<AddressUser> *types);

FLATBUFFERS_MANUALLY_ALIGNED_STRUCT(8) BasicBlockRef FLATBUFFERS_FINAL_CLASS {
 private:
  uint64_t address_;

 public:
  BasicBlockRef()
      : address_(0) {
  }
  BasicBlockRef(uint64_t _address)
      : address_(::flatbuffers::EndianScalar(_address)) {
  }
  uint64_t address() const {
    return ::flatbuffers::EndianScalar(address_);
  }
};
FLATBUFFERS_STRUCT_END(BasicBlockRef, 8);

FLATBUFFERS_MANUALLY_ALIGNED_STRUCT(8) InstructionRef FLATBUFFERS_FINAL_CLASS {
 private:
  uint64_t address_;

 public:
  InstructionRef()
      : address_(0) {
  }
  InstructionRef(uint64_t _address)
      : address_(::flatbuffers::EndianScalar(_address)) {
  }
  uint64_t address() const {
    return ::flatbuffers::EndianScalar(address_);
  }
};
FLATBUFFERS_STRUCT_END(InstructionRef, 8);

FLATBUFFERS_MANUALLY_ALIGNED_STRUCT(8) DataBlockRef FLATBUFFERS_FINAL_CLASS {
 private:
  uint64_t address_;

 public:
  DataBlockRef()
      : address_(0) {
  }
  DataBlockRef(uint64_t _address)
      : address_(::flatbuffers::EndianScalar(_address)) {
  }
  uint64_t address() const {
    return ::flatbuffers::EndianScalar(address_);
  }
};
FLATBUFFERS_STRUCT_END(DataBlockRef, 8);

FLATBUFFERS_MANUALLY_ALIGNED_STRUCT(8) FunctionRef FLATBUFFERS_FINAL_CLASS {
 private:
  uint64_t address_;

 public:
  FunctionRef()
      : address_(0) {
  }
  FunctionRef(uint64_t _address)
      : address_(::flatbuffers::EndianScalar(_address)) {
  }
  uint64_t address() const {
    return ::flatbuffers::EndianScalar(address_);
  }
};
FLATBUFFERS_STRUCT_END(FunctionRef, 8);

struct Instruction FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef InstructionBuilder Builder;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_ADDRESS = 4,
    VT_BYTES = 6
  };
  uint64_t address() const {
    return GetField<uint64_t>(VT_ADDRESS, 0);
  }
  const ::flatbuffers::Vector<uint8_t> *bytes() const {
    return GetPointer<const ::flatbuffers::Vector<uint8_t> *>(VT_BYTES);
  }
  bool Verify(::flatbuffers::Verifier &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyField<uint64_t>(verifier, VT_ADDRESS, 8) &&
           VerifyOffset(verifier, VT_BYTES) &&
           verifier.VerifyVector(bytes()) &&
           verifier.EndTable();
  }
};

struct InstructionBuilder {
  typedef Instruction Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_address(uint64_t address) {
    fbb_.AddElement<uint64_t>(Instruction::VT_ADDRESS, address, 0);
  }
  void add_bytes(::flatbuffers::Offset<::flatbuffers::Vector<uint8_t>> bytes) {
    fbb_.AddOffset(Instruction::VT_BYTES, bytes);
  }
  explicit InstructionBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<Instruction> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<Instruction>(end);
    return o;
  }
};

inline ::flatbuffers::Offset<Instruction> CreateInstruction(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    uint64_t address = 0,
    ::flatbuffers::Offset<::flatbuffers::Vector<uint8_t>> bytes = 0) {
  InstructionBuilder builder_(_fbb);
  builder_.add_address(address);
  builder_.add_bytes(bytes);
  return builder_.Finish();
}

inline ::flatbuffers::Offset<Instruction> CreateInstructionDirect(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    uint64_t address = 0,
    const std::vector<uint8_t> *bytes = nullptr) {
  auto bytes__ = bytes ? _fbb.CreateVector<uint8_t>(*bytes) : 0;
  return Rose::BinaryAnalysis::Serialization::Flatbuffers::CreateInstruction(
      _fbb,
      address,
      bytes__);
}

struct BasicBlock FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef BasicBlockBuilder Builder;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_ADDRESS = 4,
    VT_INSTRUCTIONS = 6
  };
  uint64_t address() const {
    return GetField<uint64_t>(VT_ADDRESS, 0);
  }
  /// We could factor this into a InstructionRef and save the Instructions in a top-level structure
  const ::flatbuffers::Vector<::flatbuffers::Offset<Rose::BinaryAnalysis::Serialization::Flatbuffers::Instruction>> *instructions() const {
    return GetPointer<const ::flatbuffers::Vector<::flatbuffers::Offset<Rose::BinaryAnalysis::Serialization::Flatbuffers::Instruction>> *>(VT_INSTRUCTIONS);
  }
  bool Verify(::flatbuffers::Verifier &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyField<uint64_t>(verifier, VT_ADDRESS, 8) &&
           VerifyOffset(verifier, VT_INSTRUCTIONS) &&
           verifier.VerifyVector(instructions()) &&
           verifier.VerifyVectorOfTables(instructions()) &&
           verifier.EndTable();
  }
};

struct BasicBlockBuilder {
  typedef BasicBlock Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_address(uint64_t address) {
    fbb_.AddElement<uint64_t>(BasicBlock::VT_ADDRESS, address, 0);
  }
  void add_instructions(::flatbuffers::Offset<::flatbuffers::Vector<::flatbuffers::Offset<Rose::BinaryAnalysis::Serialization::Flatbuffers::Instruction>>> instructions) {
    fbb_.AddOffset(BasicBlock::VT_INSTRUCTIONS, instructions);
  }
  explicit BasicBlockBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<BasicBlock> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<BasicBlock>(end);
    return o;
  }
};

inline ::flatbuffers::Offset<BasicBlock> CreateBasicBlock(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    uint64_t address = 0,
    ::flatbuffers::Offset<::flatbuffers::Vector<::flatbuffers::Offset<Rose::BinaryAnalysis::Serialization::Flatbuffers::Instruction>>> instructions = 0) {
  BasicBlockBuilder builder_(_fbb);
  builder_.add_address(address);
  builder_.add_instructions(instructions);
  return builder_.Finish();
}

inline ::flatbuffers::Offset<BasicBlock> CreateBasicBlockDirect(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    uint64_t address = 0,
    const std::vector<::flatbuffers::Offset<Rose::BinaryAnalysis::Serialization::Flatbuffers::Instruction>> *instructions = nullptr) {
  auto instructions__ = instructions ? _fbb.CreateVector<::flatbuffers::Offset<Rose::BinaryAnalysis::Serialization::Flatbuffers::Instruction>>(*instructions) : 0;
  return Rose::BinaryAnalysis::Serialization::Flatbuffers::CreateBasicBlock(
      _fbb,
      address,
      instructions__);
}

struct DataBlock FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef DataBlockBuilder Builder;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_ADDRESS = 4,
    VT_TYPE = 6,
    VT_COMMENT = 8
  };
  uint64_t address() const {
    return GetField<uint64_t>(VT_ADDRESS, 0);
  }
  /// This type field could have a richer representation
  const ::flatbuffers::Vector<uint8_t> *type() const {
    return GetPointer<const ::flatbuffers::Vector<uint8_t> *>(VT_TYPE);
  }
  const ::flatbuffers::String *comment() const {
    return GetPointer<const ::flatbuffers::String *>(VT_COMMENT);
  }
  bool Verify(::flatbuffers::Verifier &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyField<uint64_t>(verifier, VT_ADDRESS, 8) &&
           VerifyOffset(verifier, VT_TYPE) &&
           verifier.VerifyVector(type()) &&
           VerifyOffset(verifier, VT_COMMENT) &&
           verifier.VerifyString(comment()) &&
           verifier.EndTable();
  }
};

struct DataBlockBuilder {
  typedef DataBlock Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_address(uint64_t address) {
    fbb_.AddElement<uint64_t>(DataBlock::VT_ADDRESS, address, 0);
  }
  void add_type(::flatbuffers::Offset<::flatbuffers::Vector<uint8_t>> type) {
    fbb_.AddOffset(DataBlock::VT_TYPE, type);
  }
  void add_comment(::flatbuffers::Offset<::flatbuffers::String> comment) {
    fbb_.AddOffset(DataBlock::VT_COMMENT, comment);
  }
  explicit DataBlockBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<DataBlock> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<DataBlock>(end);
    return o;
  }
};

inline ::flatbuffers::Offset<DataBlock> CreateDataBlock(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    uint64_t address = 0,
    ::flatbuffers::Offset<::flatbuffers::Vector<uint8_t>> type = 0,
    ::flatbuffers::Offset<::flatbuffers::String> comment = 0) {
  DataBlockBuilder builder_(_fbb);
  builder_.add_address(address);
  builder_.add_comment(comment);
  builder_.add_type(type);
  return builder_.Finish();
}

inline ::flatbuffers::Offset<DataBlock> CreateDataBlockDirect(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    uint64_t address = 0,
    const std::vector<uint8_t> *type = nullptr,
    const char *comment = nullptr) {
  auto type__ = type ? _fbb.CreateVector<uint8_t>(*type) : 0;
  auto comment__ = comment ? _fbb.CreateString(comment) : 0;
  return Rose::BinaryAnalysis::Serialization::Flatbuffers::CreateDataBlock(
      _fbb,
      address,
      type__,
      comment__);
}

struct SomeColumn FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef SomeColumnBuilder Builder;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_COLUMN = 4
  };
  uint64_t column() const {
    return GetField<uint64_t>(VT_COLUMN, 0);
  }
  bool Verify(::flatbuffers::Verifier &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyField<uint64_t>(verifier, VT_COLUMN, 8) &&
           verifier.EndTable();
  }
};

struct SomeColumnBuilder {
  typedef SomeColumn Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_column(uint64_t column) {
    fbb_.AddElement<uint64_t>(SomeColumn::VT_COLUMN, column, 0);
  }
  explicit SomeColumnBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<SomeColumn> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<SomeColumn>(end);
    return o;
  }
};

inline ::flatbuffers::Offset<SomeColumn> CreateSomeColumn(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    uint64_t column = 0) {
  SomeColumnBuilder builder_(_fbb);
  builder_.add_column(column);
  return builder_.Finish();
}

struct None FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef NoneBuilder Builder;
  bool Verify(::flatbuffers::Verifier &verifier) const {
    return VerifyTableStart(verifier) &&
           verifier.EndTable();
  }
};

struct NoneBuilder {
  typedef None Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  explicit NoneBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<None> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<None>(end);
    return o;
  }
};

inline ::flatbuffers::Offset<None> CreateNone(
    ::flatbuffers::FlatBufferBuilder &_fbb) {
  NoneBuilder builder_(_fbb);
  return builder_.Finish();
}

struct SourceLocation FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef SourceLocationBuilder Builder;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_FILE_NAME = 4,
    VT_LINE = 6,
    VT_COLUMN_TYPE = 8,
    VT_COLUMN = 10
  };
  const ::flatbuffers::String *file_name() const {
    return GetPointer<const ::flatbuffers::String *>(VT_FILE_NAME);
  }
  uint64_t line() const {
    return GetField<uint64_t>(VT_LINE, 0);
  }
  Rose::BinaryAnalysis::Serialization::Flatbuffers::Column column_type() const {
    return static_cast<Rose::BinaryAnalysis::Serialization::Flatbuffers::Column>(GetField<uint8_t>(VT_COLUMN_TYPE, 0));
  }
  const void *column() const {
    return GetPointer<const void *>(VT_COLUMN);
  }
  template<typename T> const T *column_as() const;
  const Rose::BinaryAnalysis::Serialization::Flatbuffers::SomeColumn *column_as_SomeColumn() const {
    return column_type() == Rose::BinaryAnalysis::Serialization::Flatbuffers::Column::SomeColumn ? static_cast<const Rose::BinaryAnalysis::Serialization::Flatbuffers::SomeColumn *>(column()) : nullptr;
  }
  const Rose::BinaryAnalysis::Serialization::Flatbuffers::None *column_as_None() const {
    return column_type() == Rose::BinaryAnalysis::Serialization::Flatbuffers::Column::None ? static_cast<const Rose::BinaryAnalysis::Serialization::Flatbuffers::None *>(column()) : nullptr;
  }
  bool Verify(::flatbuffers::Verifier &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyOffset(verifier, VT_FILE_NAME) &&
           verifier.VerifyString(file_name()) &&
           VerifyField<uint64_t>(verifier, VT_LINE, 8) &&
           VerifyField<uint8_t>(verifier, VT_COLUMN_TYPE, 1) &&
           VerifyOffset(verifier, VT_COLUMN) &&
           VerifyColumn(verifier, column(), column_type()) &&
           verifier.EndTable();
  }
};

template<> inline const Rose::BinaryAnalysis::Serialization::Flatbuffers::SomeColumn *SourceLocation::column_as<Rose::BinaryAnalysis::Serialization::Flatbuffers::SomeColumn>() const {
  return column_as_SomeColumn();
}

template<> inline const Rose::BinaryAnalysis::Serialization::Flatbuffers::None *SourceLocation::column_as<Rose::BinaryAnalysis::Serialization::Flatbuffers::None>() const {
  return column_as_None();
}

struct SourceLocationBuilder {
  typedef SourceLocation Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_file_name(::flatbuffers::Offset<::flatbuffers::String> file_name) {
    fbb_.AddOffset(SourceLocation::VT_FILE_NAME, file_name);
  }
  void add_line(uint64_t line) {
    fbb_.AddElement<uint64_t>(SourceLocation::VT_LINE, line, 0);
  }
  void add_column_type(Rose::BinaryAnalysis::Serialization::Flatbuffers::Column column_type) {
    fbb_.AddElement<uint8_t>(SourceLocation::VT_COLUMN_TYPE, static_cast<uint8_t>(column_type), 0);
  }
  void add_column(::flatbuffers::Offset<void> column) {
    fbb_.AddOffset(SourceLocation::VT_COLUMN, column);
  }
  explicit SourceLocationBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<SourceLocation> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<SourceLocation>(end);
    return o;
  }
};

inline ::flatbuffers::Offset<SourceLocation> CreateSourceLocation(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    ::flatbuffers::Offset<::flatbuffers::String> file_name = 0,
    uint64_t line = 0,
    Rose::BinaryAnalysis::Serialization::Flatbuffers::Column column_type = Rose::BinaryAnalysis::Serialization::Flatbuffers::Column::NONE,
    ::flatbuffers::Offset<void> column = 0) {
  SourceLocationBuilder builder_(_fbb);
  builder_.add_line(line);
  builder_.add_column(column);
  builder_.add_file_name(file_name);
  builder_.add_column_type(column_type);
  return builder_.Finish();
}

inline ::flatbuffers::Offset<SourceLocation> CreateSourceLocationDirect(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    const char *file_name = nullptr,
    uint64_t line = 0,
    Rose::BinaryAnalysis::Serialization::Flatbuffers::Column column_type = Rose::BinaryAnalysis::Serialization::Flatbuffers::Column::NONE,
    ::flatbuffers::Offset<void> column = 0) {
  auto file_name__ = file_name ? _fbb.CreateString(file_name) : 0;
  return Rose::BinaryAnalysis::Serialization::Flatbuffers::CreateSourceLocation(
      _fbb,
      file_name__,
      line,
      column_type,
      column);
}

struct Function FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef FunctionBuilder Builder;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_ADDRESS = 4,
    VT_NAME = 6,
    VT_BASIC_BLOCKS = 8,
    VT_DATA_BLOCKS = 10,
    VT_LOCATION = 12
  };
  uint64_t address() const {
    return GetField<uint64_t>(VT_ADDRESS, 0);
  }
  const ::flatbuffers::String *name() const {
    return GetPointer<const ::flatbuffers::String *>(VT_NAME);
  }
  /// Addresses of owned BasicBlocks, which are saved in the CFG
  const ::flatbuffers::Vector<const Rose::BinaryAnalysis::Serialization::Flatbuffers::BasicBlockRef *> *basic_blocks() const {
    return GetPointer<const ::flatbuffers::Vector<const Rose::BinaryAnalysis::Serialization::Flatbuffers::BasicBlockRef *> *>(VT_BASIC_BLOCKS);
  }
  /// Addresses of owned DataBlocks, which are saved in the CFG
  const ::flatbuffers::Vector<const Rose::BinaryAnalysis::Serialization::Flatbuffers::DataBlockRef *> *data_blocks() const {
    return GetPointer<const ::flatbuffers::Vector<const Rose::BinaryAnalysis::Serialization::Flatbuffers::DataBlockRef *> *>(VT_DATA_BLOCKS);
  }
  const Rose::BinaryAnalysis::Serialization::Flatbuffers::SourceLocation *location() const {
    return GetPointer<const Rose::BinaryAnalysis::Serialization::Flatbuffers::SourceLocation *>(VT_LOCATION);
  }
  bool Verify(::flatbuffers::Verifier &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyField<uint64_t>(verifier, VT_ADDRESS, 8) &&
           VerifyOffset(verifier, VT_NAME) &&
           verifier.VerifyString(name()) &&
           VerifyOffset(verifier, VT_BASIC_BLOCKS) &&
           verifier.VerifyVector(basic_blocks()) &&
           VerifyOffset(verifier, VT_DATA_BLOCKS) &&
           verifier.VerifyVector(data_blocks()) &&
           VerifyOffset(verifier, VT_LOCATION) &&
           verifier.VerifyTable(location()) &&
           verifier.EndTable();
  }
};

struct FunctionBuilder {
  typedef Function Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_address(uint64_t address) {
    fbb_.AddElement<uint64_t>(Function::VT_ADDRESS, address, 0);
  }
  void add_name(::flatbuffers::Offset<::flatbuffers::String> name) {
    fbb_.AddOffset(Function::VT_NAME, name);
  }
  void add_basic_blocks(::flatbuffers::Offset<::flatbuffers::Vector<const Rose::BinaryAnalysis::Serialization::Flatbuffers::BasicBlockRef *>> basic_blocks) {
    fbb_.AddOffset(Function::VT_BASIC_BLOCKS, basic_blocks);
  }
  void add_data_blocks(::flatbuffers::Offset<::flatbuffers::Vector<const Rose::BinaryAnalysis::Serialization::Flatbuffers::DataBlockRef *>> data_blocks) {
    fbb_.AddOffset(Function::VT_DATA_BLOCKS, data_blocks);
  }
  void add_location(::flatbuffers::Offset<Rose::BinaryAnalysis::Serialization::Flatbuffers::SourceLocation> location) {
    fbb_.AddOffset(Function::VT_LOCATION, location);
  }
  explicit FunctionBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<Function> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<Function>(end);
    return o;
  }
};

inline ::flatbuffers::Offset<Function> CreateFunction(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    uint64_t address = 0,
    ::flatbuffers::Offset<::flatbuffers::String> name = 0,
    ::flatbuffers::Offset<::flatbuffers::Vector<const Rose::BinaryAnalysis::Serialization::Flatbuffers::BasicBlockRef *>> basic_blocks = 0,
    ::flatbuffers::Offset<::flatbuffers::Vector<const Rose::BinaryAnalysis::Serialization::Flatbuffers::DataBlockRef *>> data_blocks = 0,
    ::flatbuffers::Offset<Rose::BinaryAnalysis::Serialization::Flatbuffers::SourceLocation> location = 0) {
  FunctionBuilder builder_(_fbb);
  builder_.add_address(address);
  builder_.add_location(location);
  builder_.add_data_blocks(data_blocks);
  builder_.add_basic_blocks(basic_blocks);
  builder_.add_name(name);
  return builder_.Finish();
}

inline ::flatbuffers::Offset<Function> CreateFunctionDirect(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    uint64_t address = 0,
    const char *name = nullptr,
    const std::vector<Rose::BinaryAnalysis::Serialization::Flatbuffers::BasicBlockRef> *basic_blocks = nullptr,
    const std::vector<Rose::BinaryAnalysis::Serialization::Flatbuffers::DataBlockRef> *data_blocks = nullptr,
    ::flatbuffers::Offset<Rose::BinaryAnalysis::Serialization::Flatbuffers::SourceLocation> location = 0) {
  auto name__ = name ? _fbb.CreateString(name) : 0;
  auto basic_blocks__ = basic_blocks ? _fbb.CreateVectorOfStructs<Rose::BinaryAnalysis::Serialization::Flatbuffers::BasicBlockRef>(*basic_blocks) : 0;
  auto data_blocks__ = data_blocks ? _fbb.CreateVectorOfStructs<Rose::BinaryAnalysis::Serialization::Flatbuffers::DataBlockRef>(*data_blocks) : 0;
  return Rose::BinaryAnalysis::Serialization::Flatbuffers::CreateFunction(
      _fbb,
      address,
      name__,
      basic_blocks__,
      data_blocks__,
      location);
}

struct CFGVertex FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef CFGVertexBuilder Builder;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_ADDRESS = 4,
    VT_TYPE = 6,
    VT_FUNCTIONS = 8
  };
  uint64_t address() const {
    return GetField<uint64_t>(VT_ADDRESS, 0);
  }
  Rose::BinaryAnalysis::Serialization::Flatbuffers::CFGVertexType type() const {
    return static_cast<Rose::BinaryAnalysis::Serialization::Flatbuffers::CFGVertexType>(GetField<uint8_t>(VT_TYPE, 0));
  }
  /// Addresses of owned Functions, which are saved in the CFG
  const ::flatbuffers::Vector<const Rose::BinaryAnalysis::Serialization::Flatbuffers::FunctionRef *> *functions() const {
    return GetPointer<const ::flatbuffers::Vector<const Rose::BinaryAnalysis::Serialization::Flatbuffers::FunctionRef *> *>(VT_FUNCTIONS);
  }
  bool Verify(::flatbuffers::Verifier &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyField<uint64_t>(verifier, VT_ADDRESS, 8) &&
           VerifyField<uint8_t>(verifier, VT_TYPE, 1) &&
           VerifyOffset(verifier, VT_FUNCTIONS) &&
           verifier.VerifyVector(functions()) &&
           verifier.EndTable();
  }
};

struct CFGVertexBuilder {
  typedef CFGVertex Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_address(uint64_t address) {
    fbb_.AddElement<uint64_t>(CFGVertex::VT_ADDRESS, address, 0);
  }
  void add_type(Rose::BinaryAnalysis::Serialization::Flatbuffers::CFGVertexType type) {
    fbb_.AddElement<uint8_t>(CFGVertex::VT_TYPE, static_cast<uint8_t>(type), 0);
  }
  void add_functions(::flatbuffers::Offset<::flatbuffers::Vector<const Rose::BinaryAnalysis::Serialization::Flatbuffers::FunctionRef *>> functions) {
    fbb_.AddOffset(CFGVertex::VT_FUNCTIONS, functions);
  }
  explicit CFGVertexBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<CFGVertex> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<CFGVertex>(end);
    return o;
  }
};

inline ::flatbuffers::Offset<CFGVertex> CreateCFGVertex(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    uint64_t address = 0,
    Rose::BinaryAnalysis::Serialization::Flatbuffers::CFGVertexType type = Rose::BinaryAnalysis::Serialization::Flatbuffers::CFGVertexType::V_BASIC_BLOCK,
    ::flatbuffers::Offset<::flatbuffers::Vector<const Rose::BinaryAnalysis::Serialization::Flatbuffers::FunctionRef *>> functions = 0) {
  CFGVertexBuilder builder_(_fbb);
  builder_.add_address(address);
  builder_.add_functions(functions);
  builder_.add_type(type);
  return builder_.Finish();
}

inline ::flatbuffers::Offset<CFGVertex> CreateCFGVertexDirect(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    uint64_t address = 0,
    Rose::BinaryAnalysis::Serialization::Flatbuffers::CFGVertexType type = Rose::BinaryAnalysis::Serialization::Flatbuffers::CFGVertexType::V_BASIC_BLOCK,
    const std::vector<Rose::BinaryAnalysis::Serialization::Flatbuffers::FunctionRef> *functions = nullptr) {
  auto functions__ = functions ? _fbb.CreateVectorOfStructs<Rose::BinaryAnalysis::Serialization::Flatbuffers::FunctionRef>(*functions) : 0;
  return Rose::BinaryAnalysis::Serialization::Flatbuffers::CreateCFGVertex(
      _fbb,
      address,
      type,
      functions__);
}

struct CFGEdge FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef CFGEdgeBuilder Builder;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_FROM = 4,
    VT_TO = 6,
    VT_TYPE = 8,
    VT_CONFIDENCE = 10
  };
  uint64_t from() const {
    return GetField<uint64_t>(VT_FROM, 0);
  }
  uint64_t to() const {
    return GetField<uint64_t>(VT_TO, 0);
  }
  Rose::BinaryAnalysis::Serialization::Flatbuffers::CFGEdgeType type() const {
    return static_cast<Rose::BinaryAnalysis::Serialization::Flatbuffers::CFGEdgeType>(GetField<uint8_t>(VT_TYPE, 0));
  }
  Rose::BinaryAnalysis::Serialization::Flatbuffers::CFGEdgeConfidence confidence() const {
    return static_cast<Rose::BinaryAnalysis::Serialization::Flatbuffers::CFGEdgeConfidence>(GetField<uint8_t>(VT_CONFIDENCE, 0));
  }
  bool Verify(::flatbuffers::Verifier &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyField<uint64_t>(verifier, VT_FROM, 8) &&
           VerifyField<uint64_t>(verifier, VT_TO, 8) &&
           VerifyField<uint8_t>(verifier, VT_TYPE, 1) &&
           VerifyField<uint8_t>(verifier, VT_CONFIDENCE, 1) &&
           verifier.EndTable();
  }
};

struct CFGEdgeBuilder {
  typedef CFGEdge Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_from(uint64_t from) {
    fbb_.AddElement<uint64_t>(CFGEdge::VT_FROM, from, 0);
  }
  void add_to(uint64_t to) {
    fbb_.AddElement<uint64_t>(CFGEdge::VT_TO, to, 0);
  }
  void add_type(Rose::BinaryAnalysis::Serialization::Flatbuffers::CFGEdgeType type) {
    fbb_.AddElement<uint8_t>(CFGEdge::VT_TYPE, static_cast<uint8_t>(type), 0);
  }
  void add_confidence(Rose::BinaryAnalysis::Serialization::Flatbuffers::CFGEdgeConfidence confidence) {
    fbb_.AddElement<uint8_t>(CFGEdge::VT_CONFIDENCE, static_cast<uint8_t>(confidence), 0);
  }
  explicit CFGEdgeBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<CFGEdge> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<CFGEdge>(end);
    return o;
  }
};

inline ::flatbuffers::Offset<CFGEdge> CreateCFGEdge(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    uint64_t from = 0,
    uint64_t to = 0,
    Rose::BinaryAnalysis::Serialization::Flatbuffers::CFGEdgeType type = Rose::BinaryAnalysis::Serialization::Flatbuffers::CFGEdgeType::E_NORMAL,
    Rose::BinaryAnalysis::Serialization::Flatbuffers::CFGEdgeConfidence confidence = Rose::BinaryAnalysis::Serialization::Flatbuffers::CFGEdgeConfidence::ASSUMED) {
  CFGEdgeBuilder builder_(_fbb);
  builder_.add_to(to);
  builder_.add_from(from);
  builder_.add_confidence(confidence);
  builder_.add_type(type);
  return builder_.Finish();
}

struct CFG FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef CFGBuilder Builder;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_VERTICES = 4,
    VT_EDGES = 6,
    VT_BASIC_BLOCKS = 8,
    VT_FUNCTIONS = 10
  };
  const ::flatbuffers::Vector<::flatbuffers::Offset<Rose::BinaryAnalysis::Serialization::Flatbuffers::CFGVertex>> *vertices() const {
    return GetPointer<const ::flatbuffers::Vector<::flatbuffers::Offset<Rose::BinaryAnalysis::Serialization::Flatbuffers::CFGVertex>> *>(VT_VERTICES);
  }
  const ::flatbuffers::Vector<::flatbuffers::Offset<Rose::BinaryAnalysis::Serialization::Flatbuffers::CFGEdge>> *edges() const {
    return GetPointer<const ::flatbuffers::Vector<::flatbuffers::Offset<Rose::BinaryAnalysis::Serialization::Flatbuffers::CFGEdge>> *>(VT_EDGES);
  }
  const ::flatbuffers::Vector<::flatbuffers::Offset<Rose::BinaryAnalysis::Serialization::Flatbuffers::BasicBlock>> *basic_blocks() const {
    return GetPointer<const ::flatbuffers::Vector<::flatbuffers::Offset<Rose::BinaryAnalysis::Serialization::Flatbuffers::BasicBlock>> *>(VT_BASIC_BLOCKS);
  }
  const ::flatbuffers::Vector<::flatbuffers::Offset<Rose::BinaryAnalysis::Serialization::Flatbuffers::Function>> *functions() const {
    return GetPointer<const ::flatbuffers::Vector<::flatbuffers::Offset<Rose::BinaryAnalysis::Serialization::Flatbuffers::Function>> *>(VT_FUNCTIONS);
  }
  bool Verify(::flatbuffers::Verifier &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyOffset(verifier, VT_VERTICES) &&
           verifier.VerifyVector(vertices()) &&
           verifier.VerifyVectorOfTables(vertices()) &&
           VerifyOffset(verifier, VT_EDGES) &&
           verifier.VerifyVector(edges()) &&
           verifier.VerifyVectorOfTables(edges()) &&
           VerifyOffset(verifier, VT_BASIC_BLOCKS) &&
           verifier.VerifyVector(basic_blocks()) &&
           verifier.VerifyVectorOfTables(basic_blocks()) &&
           VerifyOffset(verifier, VT_FUNCTIONS) &&
           verifier.VerifyVector(functions()) &&
           verifier.VerifyVectorOfTables(functions()) &&
           verifier.EndTable();
  }
};

struct CFGBuilder {
  typedef CFG Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_vertices(::flatbuffers::Offset<::flatbuffers::Vector<::flatbuffers::Offset<Rose::BinaryAnalysis::Serialization::Flatbuffers::CFGVertex>>> vertices) {
    fbb_.AddOffset(CFG::VT_VERTICES, vertices);
  }
  void add_edges(::flatbuffers::Offset<::flatbuffers::Vector<::flatbuffers::Offset<Rose::BinaryAnalysis::Serialization::Flatbuffers::CFGEdge>>> edges) {
    fbb_.AddOffset(CFG::VT_EDGES, edges);
  }
  void add_basic_blocks(::flatbuffers::Offset<::flatbuffers::Vector<::flatbuffers::Offset<Rose::BinaryAnalysis::Serialization::Flatbuffers::BasicBlock>>> basic_blocks) {
    fbb_.AddOffset(CFG::VT_BASIC_BLOCKS, basic_blocks);
  }
  void add_functions(::flatbuffers::Offset<::flatbuffers::Vector<::flatbuffers::Offset<Rose::BinaryAnalysis::Serialization::Flatbuffers::Function>>> functions) {
    fbb_.AddOffset(CFG::VT_FUNCTIONS, functions);
  }
  explicit CFGBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<CFG> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<CFG>(end);
    return o;
  }
};

inline ::flatbuffers::Offset<CFG> CreateCFG(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    ::flatbuffers::Offset<::flatbuffers::Vector<::flatbuffers::Offset<Rose::BinaryAnalysis::Serialization::Flatbuffers::CFGVertex>>> vertices = 0,
    ::flatbuffers::Offset<::flatbuffers::Vector<::flatbuffers::Offset<Rose::BinaryAnalysis::Serialization::Flatbuffers::CFGEdge>>> edges = 0,
    ::flatbuffers::Offset<::flatbuffers::Vector<::flatbuffers::Offset<Rose::BinaryAnalysis::Serialization::Flatbuffers::BasicBlock>>> basic_blocks = 0,
    ::flatbuffers::Offset<::flatbuffers::Vector<::flatbuffers::Offset<Rose::BinaryAnalysis::Serialization::Flatbuffers::Function>>> functions = 0) {
  CFGBuilder builder_(_fbb);
  builder_.add_functions(functions);
  builder_.add_basic_blocks(basic_blocks);
  builder_.add_edges(edges);
  builder_.add_vertices(vertices);
  return builder_.Finish();
}

inline ::flatbuffers::Offset<CFG> CreateCFGDirect(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    const std::vector<::flatbuffers::Offset<Rose::BinaryAnalysis::Serialization::Flatbuffers::CFGVertex>> *vertices = nullptr,
    const std::vector<::flatbuffers::Offset<Rose::BinaryAnalysis::Serialization::Flatbuffers::CFGEdge>> *edges = nullptr,
    const std::vector<::flatbuffers::Offset<Rose::BinaryAnalysis::Serialization::Flatbuffers::BasicBlock>> *basic_blocks = nullptr,
    const std::vector<::flatbuffers::Offset<Rose::BinaryAnalysis::Serialization::Flatbuffers::Function>> *functions = nullptr) {
  auto vertices__ = vertices ? _fbb.CreateVector<::flatbuffers::Offset<Rose::BinaryAnalysis::Serialization::Flatbuffers::CFGVertex>>(*vertices) : 0;
  auto edges__ = edges ? _fbb.CreateVector<::flatbuffers::Offset<Rose::BinaryAnalysis::Serialization::Flatbuffers::CFGEdge>>(*edges) : 0;
  auto basic_blocks__ = basic_blocks ? _fbb.CreateVector<::flatbuffers::Offset<Rose::BinaryAnalysis::Serialization::Flatbuffers::BasicBlock>>(*basic_blocks) : 0;
  auto functions__ = functions ? _fbb.CreateVector<::flatbuffers::Offset<Rose::BinaryAnalysis::Serialization::Flatbuffers::Function>>(*functions) : 0;
  return Rose::BinaryAnalysis::Serialization::Flatbuffers::CreateCFG(
      _fbb,
      vertices__,
      edges__,
      basic_blocks__,
      functions__);
}

struct Interval FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef IntervalBuilder Builder;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_LO = 4,
    VT_HI = 6
  };
  uint64_t lo() const {
    return GetField<uint64_t>(VT_LO, 0);
  }
  uint64_t hi() const {
    return GetField<uint64_t>(VT_HI, 0);
  }
  bool Verify(::flatbuffers::Verifier &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyField<uint64_t>(verifier, VT_LO, 8) &&
           VerifyField<uint64_t>(verifier, VT_HI, 8) &&
           verifier.EndTable();
  }
};

struct IntervalBuilder {
  typedef Interval Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_lo(uint64_t lo) {
    fbb_.AddElement<uint64_t>(Interval::VT_LO, lo, 0);
  }
  void add_hi(uint64_t hi) {
    fbb_.AddElement<uint64_t>(Interval::VT_HI, hi, 0);
  }
  explicit IntervalBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<Interval> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<Interval>(end);
    return o;
  }
};

inline ::flatbuffers::Offset<Interval> CreateInterval(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    uint64_t lo = 0,
    uint64_t hi = 0) {
  IntervalBuilder builder_(_fbb);
  builder_.add_hi(hi);
  builder_.add_lo(lo);
  return builder_.Finish();
}

struct Segment FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef SegmentBuilder Builder;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_DATA = 4,
    VT_OFFSET = 6,
    VT_ACCESSIBILITY = 8
  };
  const ::flatbuffers::Vector<uint8_t> *data() const {
    return GetPointer<const ::flatbuffers::Vector<uint8_t> *>(VT_DATA);
  }
  uint64_t offset() const {
    return GetField<uint64_t>(VT_OFFSET, 0);
  }
  /// Since the flag is OR'd together, we serialize a ubyte instead of the enum directly.
  uint8_t accessibility() const {
    return GetField<uint8_t>(VT_ACCESSIBILITY, 0);
  }
  bool Verify(::flatbuffers::Verifier &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyOffset(verifier, VT_DATA) &&
           verifier.VerifyVector(data()) &&
           VerifyField<uint64_t>(verifier, VT_OFFSET, 8) &&
           VerifyField<uint8_t>(verifier, VT_ACCESSIBILITY, 1) &&
           verifier.EndTable();
  }
};

struct SegmentBuilder {
  typedef Segment Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_data(::flatbuffers::Offset<::flatbuffers::Vector<uint8_t>> data) {
    fbb_.AddOffset(Segment::VT_DATA, data);
  }
  void add_offset(uint64_t offset) {
    fbb_.AddElement<uint64_t>(Segment::VT_OFFSET, offset, 0);
  }
  void add_accessibility(uint8_t accessibility) {
    fbb_.AddElement<uint8_t>(Segment::VT_ACCESSIBILITY, accessibility, 0);
  }
  explicit SegmentBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<Segment> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<Segment>(end);
    return o;
  }
};

inline ::flatbuffers::Offset<Segment> CreateSegment(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    ::flatbuffers::Offset<::flatbuffers::Vector<uint8_t>> data = 0,
    uint64_t offset = 0,
    uint8_t accessibility = 0) {
  SegmentBuilder builder_(_fbb);
  builder_.add_offset(offset);
  builder_.add_data(data);
  builder_.add_accessibility(accessibility);
  return builder_.Finish();
}

inline ::flatbuffers::Offset<Segment> CreateSegmentDirect(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    const std::vector<uint8_t> *data = nullptr,
    uint64_t offset = 0,
    uint8_t accessibility = 0) {
  auto data__ = data ? _fbb.CreateVector<uint8_t>(*data) : 0;
  return Rose::BinaryAnalysis::Serialization::Flatbuffers::CreateSegment(
      _fbb,
      data__,
      offset,
      accessibility);
}

struct IntervalSegment FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef IntervalSegmentBuilder Builder;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_INTERVAL = 4,
    VT_SEGMENT = 6
  };
  const Rose::BinaryAnalysis::Serialization::Flatbuffers::Interval *interval() const {
    return GetPointer<const Rose::BinaryAnalysis::Serialization::Flatbuffers::Interval *>(VT_INTERVAL);
  }
  const Rose::BinaryAnalysis::Serialization::Flatbuffers::Segment *segment() const {
    return GetPointer<const Rose::BinaryAnalysis::Serialization::Flatbuffers::Segment *>(VT_SEGMENT);
  }
  bool Verify(::flatbuffers::Verifier &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyOffset(verifier, VT_INTERVAL) &&
           verifier.VerifyTable(interval()) &&
           VerifyOffset(verifier, VT_SEGMENT) &&
           verifier.VerifyTable(segment()) &&
           verifier.EndTable();
  }
};

struct IntervalSegmentBuilder {
  typedef IntervalSegment Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_interval(::flatbuffers::Offset<Rose::BinaryAnalysis::Serialization::Flatbuffers::Interval> interval) {
    fbb_.AddOffset(IntervalSegment::VT_INTERVAL, interval);
  }
  void add_segment(::flatbuffers::Offset<Rose::BinaryAnalysis::Serialization::Flatbuffers::Segment> segment) {
    fbb_.AddOffset(IntervalSegment::VT_SEGMENT, segment);
  }
  explicit IntervalSegmentBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<IntervalSegment> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<IntervalSegment>(end);
    return o;
  }
};

inline ::flatbuffers::Offset<IntervalSegment> CreateIntervalSegment(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    ::flatbuffers::Offset<Rose::BinaryAnalysis::Serialization::Flatbuffers::Interval> interval = 0,
    ::flatbuffers::Offset<Rose::BinaryAnalysis::Serialization::Flatbuffers::Segment> segment = 0) {
  IntervalSegmentBuilder builder_(_fbb);
  builder_.add_segment(segment);
  builder_.add_interval(interval);
  return builder_.Finish();
}

/// Notice that this datastructure and the inline bytes for instructions are redundant for non-self-modifying code
/// Self-modifying code will still need explicit instructions
struct AddressMap FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef AddressMapBuilder Builder;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_ENTRIES = 4
  };
  const ::flatbuffers::Vector<::flatbuffers::Offset<Rose::BinaryAnalysis::Serialization::Flatbuffers::IntervalSegment>> *entries() const {
    return GetPointer<const ::flatbuffers::Vector<::flatbuffers::Offset<Rose::BinaryAnalysis::Serialization::Flatbuffers::IntervalSegment>> *>(VT_ENTRIES);
  }
  bool Verify(::flatbuffers::Verifier &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyOffset(verifier, VT_ENTRIES) &&
           verifier.VerifyVector(entries()) &&
           verifier.VerifyVectorOfTables(entries()) &&
           verifier.EndTable();
  }
};

struct AddressMapBuilder {
  typedef AddressMap Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_entries(::flatbuffers::Offset<::flatbuffers::Vector<::flatbuffers::Offset<Rose::BinaryAnalysis::Serialization::Flatbuffers::IntervalSegment>>> entries) {
    fbb_.AddOffset(AddressMap::VT_ENTRIES, entries);
  }
  explicit AddressMapBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<AddressMap> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<AddressMap>(end);
    return o;
  }
};

inline ::flatbuffers::Offset<AddressMap> CreateAddressMap(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    ::flatbuffers::Offset<::flatbuffers::Vector<::flatbuffers::Offset<Rose::BinaryAnalysis::Serialization::Flatbuffers::IntervalSegment>>> entries = 0) {
  AddressMapBuilder builder_(_fbb);
  builder_.add_entries(entries);
  return builder_.Finish();
}

inline ::flatbuffers::Offset<AddressMap> CreateAddressMapDirect(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    const std::vector<::flatbuffers::Offset<Rose::BinaryAnalysis::Serialization::Flatbuffers::IntervalSegment>> *entries = nullptr) {
  auto entries__ = entries ? _fbb.CreateVector<::flatbuffers::Offset<Rose::BinaryAnalysis::Serialization::Flatbuffers::IntervalSegment>>(*entries) : 0;
  return Rose::BinaryAnalysis::Serialization::Flatbuffers::CreateAddressMap(
      _fbb,
      entries__);
}

struct MemoryMap FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef MemoryMapBuilder Builder;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_DATA = 4,
    VT_ENDIANNESS = 6,
    VT_NAME = 8
  };
  const Rose::BinaryAnalysis::Serialization::Flatbuffers::AddressMap *data() const {
    return GetPointer<const Rose::BinaryAnalysis::Serialization::Flatbuffers::AddressMap *>(VT_DATA);
  }
  Rose::BinaryAnalysis::Serialization::Flatbuffers::Endianness endianness() const {
    return static_cast<Rose::BinaryAnalysis::Serialization::Flatbuffers::Endianness>(GetField<uint8_t>(VT_ENDIANNESS, 0));
  }
  const ::flatbuffers::String *name() const {
    return GetPointer<const ::flatbuffers::String *>(VT_NAME);
  }
  bool Verify(::flatbuffers::Verifier &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyOffset(verifier, VT_DATA) &&
           verifier.VerifyTable(data()) &&
           VerifyField<uint8_t>(verifier, VT_ENDIANNESS, 1) &&
           VerifyOffset(verifier, VT_NAME) &&
           verifier.VerifyString(name()) &&
           verifier.EndTable();
  }
};

struct MemoryMapBuilder {
  typedef MemoryMap Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_data(::flatbuffers::Offset<Rose::BinaryAnalysis::Serialization::Flatbuffers::AddressMap> data) {
    fbb_.AddOffset(MemoryMap::VT_DATA, data);
  }
  void add_endianness(Rose::BinaryAnalysis::Serialization::Flatbuffers::Endianness endianness) {
    fbb_.AddElement<uint8_t>(MemoryMap::VT_ENDIANNESS, static_cast<uint8_t>(endianness), 0);
  }
  void add_name(::flatbuffers::Offset<::flatbuffers::String> name) {
    fbb_.AddOffset(MemoryMap::VT_NAME, name);
  }
  explicit MemoryMapBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<MemoryMap> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<MemoryMap>(end);
    return o;
  }
};

inline ::flatbuffers::Offset<MemoryMap> CreateMemoryMap(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    ::flatbuffers::Offset<Rose::BinaryAnalysis::Serialization::Flatbuffers::AddressMap> data = 0,
    Rose::BinaryAnalysis::Serialization::Flatbuffers::Endianness endianness = Rose::BinaryAnalysis::Serialization::Flatbuffers::Endianness::ORDER_UNSPECIFIED,
    ::flatbuffers::Offset<::flatbuffers::String> name = 0) {
  MemoryMapBuilder builder_(_fbb);
  builder_.add_name(name);
  builder_.add_data(data);
  builder_.add_endianness(endianness);
  return builder_.Finish();
}

inline ::flatbuffers::Offset<MemoryMap> CreateMemoryMapDirect(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    ::flatbuffers::Offset<Rose::BinaryAnalysis::Serialization::Flatbuffers::AddressMap> data = 0,
    Rose::BinaryAnalysis::Serialization::Flatbuffers::Endianness endianness = Rose::BinaryAnalysis::Serialization::Flatbuffers::Endianness::ORDER_UNSPECIFIED,
    const char *name = nullptr) {
  auto name__ = name ? _fbb.CreateString(name) : 0;
  return Rose::BinaryAnalysis::Serialization::Flatbuffers::CreateMemoryMap(
      _fbb,
      data,
      endianness,
      name__);
}

struct AddressUsageEntry FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef AddressUsageEntryBuilder Builder;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_INTERVAL = 4,
    VT_USER_TYPE = 6,
    VT_USER = 8
  };
  const Rose::BinaryAnalysis::Serialization::Flatbuffers::Interval *interval() const {
    return GetPointer<const Rose::BinaryAnalysis::Serialization::Flatbuffers::Interval *>(VT_INTERVAL);
  }
  Rose::BinaryAnalysis::Serialization::Flatbuffers::AddressUser user_type() const {
    return static_cast<Rose::BinaryAnalysis::Serialization::Flatbuffers::AddressUser>(GetField<uint8_t>(VT_USER_TYPE, 0));
  }
  const void *user() const {
    return GetPointer<const void *>(VT_USER);
  }
  template<typename T> const T *user_as() const;
  const Rose::BinaryAnalysis::Serialization::Flatbuffers::InstructionRef *user_as_InstructionRef() const {
    return user_type() == Rose::BinaryAnalysis::Serialization::Flatbuffers::AddressUser::InstructionRef ? static_cast<const Rose::BinaryAnalysis::Serialization::Flatbuffers::InstructionRef *>(user()) : nullptr;
  }
  const Rose::BinaryAnalysis::Serialization::Flatbuffers::DataBlockRef *user_as_DataBlockRef() const {
    return user_type() == Rose::BinaryAnalysis::Serialization::Flatbuffers::AddressUser::DataBlockRef ? static_cast<const Rose::BinaryAnalysis::Serialization::Flatbuffers::DataBlockRef *>(user()) : nullptr;
  }
  bool Verify(::flatbuffers::Verifier &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyOffset(verifier, VT_INTERVAL) &&
           verifier.VerifyTable(interval()) &&
           VerifyField<uint8_t>(verifier, VT_USER_TYPE, 1) &&
           VerifyOffset(verifier, VT_USER) &&
           VerifyAddressUser(verifier, user(), user_type()) &&
           verifier.EndTable();
  }
};

template<> inline const Rose::BinaryAnalysis::Serialization::Flatbuffers::InstructionRef *AddressUsageEntry::user_as<Rose::BinaryAnalysis::Serialization::Flatbuffers::InstructionRef>() const {
  return user_as_InstructionRef();
}

template<> inline const Rose::BinaryAnalysis::Serialization::Flatbuffers::DataBlockRef *AddressUsageEntry::user_as<Rose::BinaryAnalysis::Serialization::Flatbuffers::DataBlockRef>() const {
  return user_as_DataBlockRef();
}

struct AddressUsageEntryBuilder {
  typedef AddressUsageEntry Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_interval(::flatbuffers::Offset<Rose::BinaryAnalysis::Serialization::Flatbuffers::Interval> interval) {
    fbb_.AddOffset(AddressUsageEntry::VT_INTERVAL, interval);
  }
  void add_user_type(Rose::BinaryAnalysis::Serialization::Flatbuffers::AddressUser user_type) {
    fbb_.AddElement<uint8_t>(AddressUsageEntry::VT_USER_TYPE, static_cast<uint8_t>(user_type), 0);
  }
  void add_user(::flatbuffers::Offset<void> user) {
    fbb_.AddOffset(AddressUsageEntry::VT_USER, user);
  }
  explicit AddressUsageEntryBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<AddressUsageEntry> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<AddressUsageEntry>(end);
    return o;
  }
};

inline ::flatbuffers::Offset<AddressUsageEntry> CreateAddressUsageEntry(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    ::flatbuffers::Offset<Rose::BinaryAnalysis::Serialization::Flatbuffers::Interval> interval = 0,
    Rose::BinaryAnalysis::Serialization::Flatbuffers::AddressUser user_type = Rose::BinaryAnalysis::Serialization::Flatbuffers::AddressUser::NONE,
    ::flatbuffers::Offset<void> user = 0) {
  AddressUsageEntryBuilder builder_(_fbb);
  builder_.add_user(user);
  builder_.add_interval(interval);
  builder_.add_user_type(user_type);
  return builder_.Finish();
}

struct AddressUsageMap FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef AddressUsageMapBuilder Builder;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_ENTRIES = 4
  };
  const ::flatbuffers::Vector<::flatbuffers::Offset<Rose::BinaryAnalysis::Serialization::Flatbuffers::AddressUsageEntry>> *entries() const {
    return GetPointer<const ::flatbuffers::Vector<::flatbuffers::Offset<Rose::BinaryAnalysis::Serialization::Flatbuffers::AddressUsageEntry>> *>(VT_ENTRIES);
  }
  bool Verify(::flatbuffers::Verifier &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyOffset(verifier, VT_ENTRIES) &&
           verifier.VerifyVector(entries()) &&
           verifier.VerifyVectorOfTables(entries()) &&
           verifier.EndTable();
  }
};

struct AddressUsageMapBuilder {
  typedef AddressUsageMap Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_entries(::flatbuffers::Offset<::flatbuffers::Vector<::flatbuffers::Offset<Rose::BinaryAnalysis::Serialization::Flatbuffers::AddressUsageEntry>>> entries) {
    fbb_.AddOffset(AddressUsageMap::VT_ENTRIES, entries);
  }
  explicit AddressUsageMapBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<AddressUsageMap> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<AddressUsageMap>(end);
    return o;
  }
};

inline ::flatbuffers::Offset<AddressUsageMap> CreateAddressUsageMap(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    ::flatbuffers::Offset<::flatbuffers::Vector<::flatbuffers::Offset<Rose::BinaryAnalysis::Serialization::Flatbuffers::AddressUsageEntry>>> entries = 0) {
  AddressUsageMapBuilder builder_(_fbb);
  builder_.add_entries(entries);
  return builder_.Finish();
}

inline ::flatbuffers::Offset<AddressUsageMap> CreateAddressUsageMapDirect(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    const std::vector<::flatbuffers::Offset<Rose::BinaryAnalysis::Serialization::Flatbuffers::AddressUsageEntry>> *entries = nullptr) {
  auto entries__ = entries ? _fbb.CreateVector<::flatbuffers::Offset<Rose::BinaryAnalysis::Serialization::Flatbuffers::AddressUsageEntry>>(*entries) : 0;
  return Rose::BinaryAnalysis::Serialization::Flatbuffers::CreateAddressUsageMap(
      _fbb,
      entries__);
}

struct Partitioner FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef PartitionerBuilder Builder;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_VERSION = 4,
    VT_ARCHITECTURE_NAME = 6,
    VT_CFG = 8,
    VT_MEMORY_MAP = 10,
    VT_AUM = 12
  };
  uint32_t version() const {
    return GetField<uint32_t>(VT_VERSION, 0);
  }
  const ::flatbuffers::String *architecture_name() const {
    return GetPointer<const ::flatbuffers::String *>(VT_ARCHITECTURE_NAME);
  }
  const Rose::BinaryAnalysis::Serialization::Flatbuffers::CFG *cfg() const {
    return GetPointer<const Rose::BinaryAnalysis::Serialization::Flatbuffers::CFG *>(VT_CFG);
  }
  const Rose::BinaryAnalysis::Serialization::Flatbuffers::MemoryMap *memory_map() const {
    return GetPointer<const Rose::BinaryAnalysis::Serialization::Flatbuffers::MemoryMap *>(VT_MEMORY_MAP);
  }
  const Rose::BinaryAnalysis::Serialization::Flatbuffers::AddressUsageMap *aum() const {
    return GetPointer<const Rose::BinaryAnalysis::Serialization::Flatbuffers::AddressUsageMap *>(VT_AUM);
  }
  bool Verify(::flatbuffers::Verifier &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyField<uint32_t>(verifier, VT_VERSION, 4) &&
           VerifyOffset(verifier, VT_ARCHITECTURE_NAME) &&
           verifier.VerifyString(architecture_name()) &&
           VerifyOffset(verifier, VT_CFG) &&
           verifier.VerifyTable(cfg()) &&
           VerifyOffset(verifier, VT_MEMORY_MAP) &&
           verifier.VerifyTable(memory_map()) &&
           VerifyOffset(verifier, VT_AUM) &&
           verifier.VerifyTable(aum()) &&
           verifier.EndTable();
  }
};

struct PartitionerBuilder {
  typedef Partitioner Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_version(uint32_t version) {
    fbb_.AddElement<uint32_t>(Partitioner::VT_VERSION, version, 0);
  }
  void add_architecture_name(::flatbuffers::Offset<::flatbuffers::String> architecture_name) {
    fbb_.AddOffset(Partitioner::VT_ARCHITECTURE_NAME, architecture_name);
  }
  void add_cfg(::flatbuffers::Offset<Rose::BinaryAnalysis::Serialization::Flatbuffers::CFG> cfg) {
    fbb_.AddOffset(Partitioner::VT_CFG, cfg);
  }
  void add_memory_map(::flatbuffers::Offset<Rose::BinaryAnalysis::Serialization::Flatbuffers::MemoryMap> memory_map) {
    fbb_.AddOffset(Partitioner::VT_MEMORY_MAP, memory_map);
  }
  void add_aum(::flatbuffers::Offset<Rose::BinaryAnalysis::Serialization::Flatbuffers::AddressUsageMap> aum) {
    fbb_.AddOffset(Partitioner::VT_AUM, aum);
  }
  explicit PartitionerBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<Partitioner> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<Partitioner>(end);
    return o;
  }
};

inline ::flatbuffers::Offset<Partitioner> CreatePartitioner(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    uint32_t version = 0,
    ::flatbuffers::Offset<::flatbuffers::String> architecture_name = 0,
    ::flatbuffers::Offset<Rose::BinaryAnalysis::Serialization::Flatbuffers::CFG> cfg = 0,
    ::flatbuffers::Offset<Rose::BinaryAnalysis::Serialization::Flatbuffers::MemoryMap> memory_map = 0,
    ::flatbuffers::Offset<Rose::BinaryAnalysis::Serialization::Flatbuffers::AddressUsageMap> aum = 0) {
  PartitionerBuilder builder_(_fbb);
  builder_.add_aum(aum);
  builder_.add_memory_map(memory_map);
  builder_.add_cfg(cfg);
  builder_.add_architecture_name(architecture_name);
  builder_.add_version(version);
  return builder_.Finish();
}

inline ::flatbuffers::Offset<Partitioner> CreatePartitionerDirect(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    uint32_t version = 0,
    const char *architecture_name = nullptr,
    ::flatbuffers::Offset<Rose::BinaryAnalysis::Serialization::Flatbuffers::CFG> cfg = 0,
    ::flatbuffers::Offset<Rose::BinaryAnalysis::Serialization::Flatbuffers::MemoryMap> memory_map = 0,
    ::flatbuffers::Offset<Rose::BinaryAnalysis::Serialization::Flatbuffers::AddressUsageMap> aum = 0) {
  auto architecture_name__ = architecture_name ? _fbb.CreateString(architecture_name) : 0;
  return Rose::BinaryAnalysis::Serialization::Flatbuffers::CreatePartitioner(
      _fbb,
      version,
      architecture_name__,
      cfg,
      memory_map,
      aum);
}

inline bool VerifyColumn(::flatbuffers::Verifier &verifier, const void *obj, Column type) {
  switch (type) {
    case Column::NONE: {
      return true;
    }
    case Column::SomeColumn: {
      auto ptr = reinterpret_cast<const Rose::BinaryAnalysis::Serialization::Flatbuffers::SomeColumn *>(obj);
      return verifier.VerifyTable(ptr);
    }
    case Column::None: {
      auto ptr = reinterpret_cast<const Rose::BinaryAnalysis::Serialization::Flatbuffers::None *>(obj);
      return verifier.VerifyTable(ptr);
    }
    default: return true;
  }
}

inline bool VerifyColumnVector(::flatbuffers::Verifier &verifier, const ::flatbuffers::Vector<::flatbuffers::Offset<void>> *values, const ::flatbuffers::Vector<Column> *types) {
  if (!values || !types) return !values && !types;
  if (values->size() != types->size()) return false;
  for (::flatbuffers::uoffset_t i = 0; i < values->size(); ++i) {
    if (!VerifyColumn(
        verifier,  values->Get(i), types->GetEnum<Column>(i))) {
      return false;
    }
  }
  return true;
}

inline bool VerifyAddressUser(::flatbuffers::Verifier &verifier, const void *obj, AddressUser type) {
  switch (type) {
    case AddressUser::NONE: {
      return true;
    }
    case AddressUser::InstructionRef: {
      return verifier.VerifyField<Rose::BinaryAnalysis::Serialization::Flatbuffers::InstructionRef>(static_cast<const uint8_t *>(obj), 0, 8);
    }
    case AddressUser::DataBlockRef: {
      return verifier.VerifyField<Rose::BinaryAnalysis::Serialization::Flatbuffers::DataBlockRef>(static_cast<const uint8_t *>(obj), 0, 8);
    }
    default: return true;
  }
}

inline bool VerifyAddressUserVector(::flatbuffers::Verifier &verifier, const ::flatbuffers::Vector<::flatbuffers::Offset<void>> *values, const ::flatbuffers::Vector<AddressUser> *types) {
  if (!values || !types) return !values && !types;
  if (values->size() != types->size()) return false;
  for (::flatbuffers::uoffset_t i = 0; i < values->size(); ++i) {
    if (!VerifyAddressUser(
        verifier,  values->Get(i), types->GetEnum<AddressUser>(i))) {
      return false;
    }
  }
  return true;
}

inline const Rose::BinaryAnalysis::Serialization::Flatbuffers::Partitioner *GetPartitioner(const void *buf) {
  return ::flatbuffers::GetRoot<Rose::BinaryAnalysis::Serialization::Flatbuffers::Partitioner>(buf);
}

inline const Rose::BinaryAnalysis::Serialization::Flatbuffers::Partitioner *GetSizePrefixedPartitioner(const void *buf) {
  return ::flatbuffers::GetSizePrefixedRoot<Rose::BinaryAnalysis::Serialization::Flatbuffers::Partitioner>(buf);
}

inline bool VerifyPartitionerBuffer(
    ::flatbuffers::Verifier &verifier) {
  return verifier.VerifyBuffer<Rose::BinaryAnalysis::Serialization::Flatbuffers::Partitioner>(nullptr);
}

inline bool VerifySizePrefixedPartitionerBuffer(
    ::flatbuffers::Verifier &verifier) {
  return verifier.VerifySizePrefixedBuffer<Rose::BinaryAnalysis::Serialization::Flatbuffers::Partitioner>(nullptr);
}

inline void FinishPartitionerBuffer(
    ::flatbuffers::FlatBufferBuilder &fbb,
    ::flatbuffers::Offset<Rose::BinaryAnalysis::Serialization::Flatbuffers::Partitioner> root) {
  fbb.Finish(root);
}

inline void FinishSizePrefixedPartitionerBuffer(
    ::flatbuffers::FlatBufferBuilder &fbb,
    ::flatbuffers::Offset<Rose::BinaryAnalysis::Serialization::Flatbuffers::Partitioner> root) {
  fbb.FinishSizePrefixed(root);
}

}  // namespace Flatbuffers
}  // namespace Serialization
}  // namespace BinaryAnalysis
}  // namespace Rose

#endif  // FLATBUFFERS_GENERATED_FLATBUFFERSCHEMA_ROSE_BINARYANALYSIS_SERIALIZATION_FLATBUFFERS_H_
