/*------------------------------------------------------------------------------
 *
 *    Copyright (C) 1998 : Space Systems Finland Ltd.
 *
 * Space Systems Finland Ltd (SSF) allows you to use this version of
 * the DEBIE-I DPU software for the specific purpose and under the
 * specific conditions set forth in the Terms Of Use document enclosed
 * with or attached to this software. In particular, the software
 * remains the property of SSF and you must not distribute the software
 * to third parties without written and signed authorization from SSF.
 *
 *    System Name:   DEBIE DPU SW
 *    Subsystem  :   DAS
 *    Module     :   classtab.c
 *
 * Table for classifying event according to multiple measurements.
 *
 * Based on the SSF file classtab.c, rev 1.2, Thu Feb 18 15:12:22 1999.
 *      
 *- * --------------------------------------------------------------------------
 */

#include "keyword.h"

unsigned char EXTERNAL event_class[256] = {
         /* Que  Qui  P1  P2  Qle  dTei     dTep     dTip       */
    0,   /*  0    0    0   0   0   OUTSIDE  OUTSIDE  OUTSIDE    */
    0,   /*  0    0    0   0   0   OUTSIDE  OUTSIDE  INSIDE     */
    0,   /*  0    0    0   0   0   OUTSIDE  INSIDE   OUTSIDE    */
    0,   /*  0    0    0   0   0   OUTSIDE  INSIDE   INSIDE     */
    0,   /*  0    0    0   0   0   INSIDE   OUTSIDE  OUTSIDE    */
    0,   /*  0    0    0   0   0   INSIDE   OUTSIDE  INSIDE     */
    0,   /*  0    0    0   0   0   INSIDE   INSIDE   OUTSIDE    */
    0,   /*  0    0    0   0   0   INSIDE   INSIDE   INSIDE     */
    0,   /*  0    0    0   0   1   OUTSIDE  OUTSIDE  OUTSIDE    */
    0,   /*  0    0    0   0   1   OUTSIDE  OUTSIDE  INSIDE     */
    0,   /*  0    0    0   0   1   OUTSIDE  INSIDE   OUTSIDE    */
    0,   /*  0    0    0   0   1   OUTSIDE  INSIDE   INSIDE     */
    0,   /*  0    0    0   0   1   INSIDE   OUTSIDE  OUTSIDE    */
    0,   /*  0    0    0   0   1   INSIDE   OUTSIDE  INSIDE     */
    0,   /*  0    0    0   0   1   INSIDE   INSIDE   OUTSIDE    */
    0,   /*  0    0    0   0   1   INSIDE   INSIDE   INSIDE     */
    0,   /*  0    0    0   1   0   OUTSIDE  OUTSIDE  OUTSIDE    */
    0,   /*  0    0    0   1   0   OUTSIDE  OUTSIDE  INSIDE     */
    0,   /*  0    0    0   1   0   OUTSIDE  INSIDE   OUTSIDE    */
    0,   /*  0    0    0   1   0   OUTSIDE  INSIDE   INSIDE     */
    0,   /*  0    0    0   1   0   INSIDE   OUTSIDE  OUTSIDE    */
    0,   /*  0    0    0   1   0   INSIDE   OUTSIDE  INSIDE     */
    0,   /*  0    0    0   1   0   INSIDE   INSIDE   OUTSIDE    */
    0,   /*  0    0    0   1   0   INSIDE   INSIDE   INSIDE     */
    3,   /*  0    0    0   1   1   OUTSIDE  OUTSIDE  OUTSIDE    */
    3,   /*  0    0    0   1   1   OUTSIDE  OUTSIDE  INSIDE     */
    3,   /*  0    0    0   1   1   OUTSIDE  INSIDE   OUTSIDE    */
    3,   /*  0    0    0   1   1   OUTSIDE  INSIDE   INSIDE     */
    3,   /*  0    0    0   1   1   INSIDE   OUTSIDE  OUTSIDE    */
    3,   /*  0    0    0   1   1   INSIDE   OUTSIDE  INSIDE     */
    3,   /*  0    0    0   1   1   INSIDE   INSIDE   OUTSIDE    */
    3,   /*  0    0    0   1   1   INSIDE   INSIDE   INSIDE     */
    0,   /*  0    0    1   0   0   OUTSIDE  OUTSIDE  OUTSIDE    */
    0,   /*  0    0    1   0   0   OUTSIDE  OUTSIDE  INSIDE     */
    0,   /*  0    0    1   0   0   OUTSIDE  INSIDE   OUTSIDE    */
    0,   /*  0    0    1   0   0   OUTSIDE  INSIDE   INSIDE     */
    0,   /*  0    0    1   0   0   INSIDE   OUTSIDE  OUTSIDE    */
    0,   /*  0    0    1   0   0   INSIDE   OUTSIDE  INSIDE     */
    0,   /*  0    0    1   0   0   INSIDE   INSIDE   OUTSIDE    */
    0,   /*  0    0    1   0   0   INSIDE   INSIDE   INSIDE     */
    3,   /*  0    0    1   0   1   OUTSIDE  OUTSIDE  OUTSIDE    */
    3,   /*  0    0    1   0   1   OUTSIDE  OUTSIDE  INSIDE     */
    3,   /*  0    0    1   0   1   OUTSIDE  INSIDE   OUTSIDE    */
    3,   /*  0    0    1   0   1   OUTSIDE  INSIDE   INSIDE     */
    3,   /*  0    0    1   0   1   INSIDE   OUTSIDE  OUTSIDE    */
    3,   /*  0    0    1   0   1   INSIDE   OUTSIDE  INSIDE     */
    3,   /*  0    0    1   0   1   INSIDE   INSIDE   OUTSIDE    */
    3,   /*  0    0    1   0   1   INSIDE   INSIDE   INSIDE     */
    5,   /*  0    0    1   1   0   OUTSIDE  OUTSIDE  OUTSIDE    */
    5,   /*  0    0    1   1   0   OUTSIDE  OUTSIDE  INSIDE     */
    5,   /*  0    0    1   1   0   OUTSIDE  INSIDE   OUTSIDE    */
    5,   /*  0    0    1   1   0   OUTSIDE  INSIDE   INSIDE     */
    5,   /*  0    0    1   1   0   INSIDE   OUTSIDE  OUTSIDE    */
    5,   /*  0    0    1   1   0   INSIDE   OUTSIDE  INSIDE     */
    5,   /*  0    0    1   1   0   INSIDE   INSIDE   OUTSIDE    */
    5,   /*  0    0    1   1   0   INSIDE   INSIDE   INSIDE     */
    8,   /*  0    0    1   1   1   OUTSIDE  OUTSIDE  OUTSIDE    */
    8,   /*  0    0    1   1   1   OUTSIDE  OUTSIDE  INSIDE     */
    8,   /*  0    0    1   1   1   OUTSIDE  INSIDE   OUTSIDE    */
    8,   /*  0    0    1   1   1   OUTSIDE  INSIDE   INSIDE     */
    8,   /*  0    0    1   1   1   INSIDE   OUTSIDE  OUTSIDE    */
    8,   /*  0    0    1   1   1   INSIDE   OUTSIDE  INSIDE     */
    8,   /*  0    0    1   1   1   INSIDE   INSIDE   OUTSIDE    */
    8,   /*  0    0    1   1   1   INSIDE   INSIDE   INSIDE     */
    0,   /*  0    1    0   0   0   OUTSIDE  OUTSIDE  OUTSIDE    */
    0,   /*  0    1    0   0   0   OUTSIDE  OUTSIDE  INSIDE     */
    0,   /*  0    1    0   0   0   OUTSIDE  INSIDE   OUTSIDE    */
    0,   /*  0    1    0   0   0   OUTSIDE  INSIDE   INSIDE     */
    0,   /*  0    1    0   0   0   INSIDE   OUTSIDE  OUTSIDE    */
    0,   /*  0    1    0   0   0   INSIDE   OUTSIDE  INSIDE     */
    0,   /*  0    1    0   0   0   INSIDE   INSIDE   OUTSIDE    */
    0,   /*  0    1    0   0   0   INSIDE   INSIDE   INSIDE     */
    3,   /*  0    1    0   0   1   OUTSIDE  OUTSIDE  OUTSIDE    */
    3,   /*  0    1    0   0   1   OUTSIDE  OUTSIDE  INSIDE     */
    3,   /*  0    1    0   0   1   OUTSIDE  INSIDE   OUTSIDE    */
    3,   /*  0    1    0   0   1   OUTSIDE  INSIDE   INSIDE     */
    3,   /*  0    1    0   0   1   INSIDE   OUTSIDE  OUTSIDE    */
    3,   /*  0    1    0   0   1   INSIDE   OUTSIDE  INSIDE     */
    3,   /*  0    1    0   0   1   INSIDE   INSIDE   OUTSIDE    */
    3,   /*  0    1    0   0   1   INSIDE   INSIDE   INSIDE     */
    1,   /*  0    1    0   1   0   OUTSIDE  OUTSIDE  OUTSIDE    */
    3,   /*  0    1    0   1   0   OUTSIDE  OUTSIDE  INSIDE     */
    1,   /*  0    1    0   1   0   OUTSIDE  INSIDE   OUTSIDE    */
    3,   /*  0    1    0   1   0   OUTSIDE  INSIDE   INSIDE     */
    1,   /*  0    1    0   1   0   INSIDE   OUTSIDE  OUTSIDE    */
    3,   /*  0    1    0   1   0   INSIDE   OUTSIDE  INSIDE     */
    1,   /*  0    1    0   1   0   INSIDE   INSIDE   OUTSIDE    */
    3,   /*  0    1    0   1   0   INSIDE   INSIDE   INSIDE     */
    1,   /*  0    1    0   1   1   OUTSIDE  OUTSIDE  OUTSIDE    */
    4,   /*  0    1    0   1   1   OUTSIDE  OUTSIDE  INSIDE     */
    1,   /*  0    1    0   1   1   OUTSIDE  INSIDE   OUTSIDE    */
    4,   /*  0    1    0   1   1   OUTSIDE  INSIDE   INSIDE     */
    1,   /*  0    1    0   1   1   INSIDE   OUTSIDE  OUTSIDE    */
    4,   /*  0    1    0   1   1   INSIDE   OUTSIDE  INSIDE     */
    1,   /*  0    1    0   1   1   INSIDE   INSIDE   OUTSIDE    */
    4,   /*  0    1    0   1   1   INSIDE   INSIDE   INSIDE     */
    1,   /*  0    1    1   0   0   OUTSIDE  OUTSIDE  OUTSIDE    */
    3,   /*  0    1    1   0   0   OUTSIDE  OUTSIDE  INSIDE     */
    1,   /*  0    1    1   0   0   OUTSIDE  INSIDE   OUTSIDE    */
    3,   /*  0    1    1   0   0   OUTSIDE  INSIDE   INSIDE     */
    1,   /*  0    1    1   0   0   INSIDE   OUTSIDE  OUTSIDE    */
    3,   /*  0    1    1   0   0   INSIDE   OUTSIDE  INSIDE     */
    1,   /*  0    1    1   0   0   INSIDE   INSIDE   OUTSIDE    */
    3,   /*  0    1    1   0   0   INSIDE   INSIDE   INSIDE     */
    1,   /*  0    1    1   0   1   OUTSIDE  OUTSIDE  OUTSIDE    */
    4,   /*  0    1    1   0   1   OUTSIDE  OUTSIDE  INSIDE     */
    1,   /*  0    1    1   0   1   OUTSIDE  INSIDE   OUTSIDE    */
    4,   /*  0    1    1   0   1   OUTSIDE  INSIDE   INSIDE     */
    1,   /*  0    1    1   0   1   INSIDE   OUTSIDE  OUTSIDE    */
    4,   /*  0    1    1   0   1   INSIDE   OUTSIDE  INSIDE     */
    1,   /*  0    1    1   0   1   INSIDE   INSIDE   OUTSIDE    */
    4,   /*  0    1    1   0   1   INSIDE   INSIDE   INSIDE     */
    1,   /*  0    1    1   1   0   OUTSIDE  OUTSIDE  OUTSIDE    */
    5,   /*  0    1    1   1   0   OUTSIDE  OUTSIDE  INSIDE     */
    1,   /*  0    1    1   1   0   OUTSIDE  INSIDE   OUTSIDE    */
    5,   /*  0    1    1   1   0   OUTSIDE  INSIDE   INSIDE     */
    1,   /*  0    1    1   1   0   INSIDE   OUTSIDE  OUTSIDE    */
    5,   /*  0    1    1   1   0   INSIDE   OUTSIDE  INSIDE     */
    1,   /*  0    1    1   1   0   INSIDE   INSIDE   OUTSIDE    */
    5,   /*  0    1    1   1   0   INSIDE   INSIDE   INSIDE     */
    1,   /*  0    1    1   1   1   OUTSIDE  OUTSIDE  OUTSIDE    */
    8,   /*  0    1    1   1   1   OUTSIDE  OUTSIDE  INSIDE     */
    1,   /*  0    1    1   1   1   OUTSIDE  INSIDE   OUTSIDE    */
    8,   /*  0    1    1   1   1   OUTSIDE  INSIDE   INSIDE     */
    1,   /*  0    1    1   1   1   INSIDE   OUTSIDE  OUTSIDE    */
    8,   /*  0    1    1   1   1   INSIDE   OUTSIDE  INSIDE     */
    1,   /*  0    1    1   1   1   INSIDE   INSIDE   OUTSIDE    */
    8,   /*  0    1    1   1   1   INSIDE   INSIDE   INSIDE     */
    0,   /*  1    0    0   0   0   OUTSIDE  OUTSIDE  OUTSIDE    */
    0,   /*  1    0    0   0   0   OUTSIDE  OUTSIDE  INSIDE     */
    0,   /*  1    0    0   0   0   OUTSIDE  INSIDE   OUTSIDE    */
    0,   /*  1    0    0   0   0   OUTSIDE  INSIDE   INSIDE     */
    0,   /*  1    0    0   0   0   INSIDE   OUTSIDE  OUTSIDE    */
    0,   /*  1    0    0   0   0   INSIDE   OUTSIDE  INSIDE     */
    0,   /*  1    0    0   0   0   INSIDE   INSIDE   OUTSIDE    */
    0,   /*  1    0    0   0   0   INSIDE   INSIDE   INSIDE     */
    3,   /*  1    0    0   0   1   OUTSIDE  OUTSIDE  OUTSIDE    */
    3,   /*  1    0    0   0   1   OUTSIDE  OUTSIDE  INSIDE     */
    3,   /*  1    0    0   0   1   OUTSIDE  INSIDE   OUTSIDE    */
    3,   /*  1    0    0   0   1   OUTSIDE  INSIDE   INSIDE     */
    3,   /*  1    0    0   0   1   INSIDE   OUTSIDE  OUTSIDE    */
    3,   /*  1    0    0   0   1   INSIDE   OUTSIDE  INSIDE     */
    3,   /*  1    0    0   0   1   INSIDE   INSIDE   OUTSIDE    */
    3,   /*  1    0    0   0   1   INSIDE   INSIDE   INSIDE     */
    1,   /*  1    0    0   1   0   OUTSIDE  OUTSIDE  OUTSIDE    */
    3,   /*  1    0    0   1   0   OUTSIDE  OUTSIDE  INSIDE     */
    1,   /*  1    0    0   1   0   OUTSIDE  INSIDE   OUTSIDE    */
    3,   /*  1    0    0   1   0   OUTSIDE  INSIDE   INSIDE     */
    1,   /*  1    0    0   1   0   INSIDE   OUTSIDE  OUTSIDE    */
    3,   /*  1    0    0   1   0   INSIDE   OUTSIDE  INSIDE     */
    1,   /*  1    0    0   1   0   INSIDE   INSIDE   OUTSIDE    */
    3,   /*  1    0    0   1   0   INSIDE   INSIDE   INSIDE     */
    1,   /*  1    0    0   1   1   OUTSIDE  OUTSIDE  OUTSIDE    */
    1,   /*  1    0    0   1   1   OUTSIDE  OUTSIDE  INSIDE     */
    4,   /*  1    0    0   1   1   OUTSIDE  INSIDE   OUTSIDE    */
    4,   /*  1    0    0   1   1   OUTSIDE  INSIDE   INSIDE     */
    1,   /*  1    0    0   1   1   INSIDE   OUTSIDE  OUTSIDE    */
    1,   /*  1    0    0   1   1   INSIDE   OUTSIDE  INSIDE     */
    4,   /*  1    0    0   1   1   INSIDE   INSIDE   OUTSIDE    */
    4,   /*  1    0    0   1   1   INSIDE   INSIDE   INSIDE     */
    1,   /*  1    0    1   0   0   OUTSIDE  OUTSIDE  OUTSIDE    */
    1,   /*  1    0    1   0   0   OUTSIDE  OUTSIDE  INSIDE     */
    3,   /*  1    0    1   0   0   OUTSIDE  INSIDE   OUTSIDE    */
    3,   /*  1    0    1   0   0   OUTSIDE  INSIDE   INSIDE     */
    1,   /*  1    0    1   0   0   INSIDE   OUTSIDE  OUTSIDE    */
    1,   /*  1    0    1   0   0   INSIDE   OUTSIDE  INSIDE     */
    3,   /*  1    0    1   0   0   INSIDE   INSIDE   OUTSIDE    */
    3,   /*  1    0    1   0   0   INSIDE   INSIDE   INSIDE     */
    1,   /*  1    0    1   0   1   OUTSIDE  OUTSIDE  OUTSIDE    */
    1,   /*  1    0    1   0   1   OUTSIDE  OUTSIDE  INSIDE     */
    4,   /*  1    0    1   0   1   OUTSIDE  INSIDE   OUTSIDE    */
    4,   /*  1    0    1   0   1   OUTSIDE  INSIDE   INSIDE     */
    1,   /*  1    0    1   0   1   INSIDE   OUTSIDE  OUTSIDE    */
    1,   /*  1    0    1   0   1   INSIDE   OUTSIDE  INSIDE     */
    4,   /*  1    0    1   0   1   INSIDE   INSIDE   OUTSIDE    */
    4,   /*  1    0    1   0   1   INSIDE   INSIDE   INSIDE     */
    1,   /*  1    0    1   1   0   OUTSIDE  OUTSIDE  OUTSIDE    */
    1,   /*  1    0    1   1   0   OUTSIDE  OUTSIDE  INSIDE     */
    5,   /*  1    0    1   1   0   OUTSIDE  INSIDE   OUTSIDE    */
    5,   /*  1    0    1   1   0   OUTSIDE  INSIDE   INSIDE     */
    1,   /*  1    0    1   1   0   INSIDE   OUTSIDE  OUTSIDE    */
    1,   /*  1    0    1   1   0   INSIDE   OUTSIDE  INSIDE     */
    5,   /*  1    0    1   1   0   INSIDE   INSIDE   OUTSIDE    */
    5,   /*  1    0    1   1   0   INSIDE   INSIDE   INSIDE     */
    1,   /*  1    0    1   1   1   OUTSIDE  OUTSIDE  OUTSIDE    */
    1,   /*  1    0    1   1   1   OUTSIDE  OUTSIDE  INSIDE     */
    8,   /*  1    0    1   1   1   OUTSIDE  INSIDE   OUTSIDE    */
    8,   /*  1    0    1   1   1   OUTSIDE  INSIDE   INSIDE     */
    1,   /*  1    0    1   1   1   INSIDE   OUTSIDE  OUTSIDE    */
    1,   /*  1    0    1   1   1   INSIDE   OUTSIDE  INSIDE     */
    8,   /*  1    0    1   1   1   INSIDE   INSIDE   OUTSIDE    */
    8,   /*  1    0    1   1   1   INSIDE   INSIDE   INSIDE     */
    1,   /*  1    1    0   0   0   OUTSIDE  OUTSIDE  OUTSIDE    */
    1,   /*  1    1    0   0   0   OUTSIDE  OUTSIDE  INSIDE     */
    1,   /*  1    1    0   0   0   OUTSIDE  INSIDE   OUTSIDE    */
    1,   /*  1    1    0   0   0   OUTSIDE  INSIDE   INSIDE     */
    6,   /*  1    1    0   0   0   INSIDE   OUTSIDE  OUTSIDE    */
    6,   /*  1    1    0   0   0   INSIDE   OUTSIDE  INSIDE     */
    6,   /*  1    1    0   0   0   INSIDE   INSIDE   OUTSIDE    */
    6,   /*  1    1    0   0   0   INSIDE   INSIDE   INSIDE     */
    1,   /*  1    1    0   0   1   OUTSIDE  OUTSIDE  OUTSIDE    */
    1,   /*  1    1    0   0   1   OUTSIDE  OUTSIDE  INSIDE     */
    1,   /*  1    1    0   0   1   OUTSIDE  INSIDE   OUTSIDE    */
    1,   /*  1    1    0   0   1   OUTSIDE  INSIDE   INSIDE     */
    7,   /*  1    1    0   0   1   INSIDE   OUTSIDE  OUTSIDE    */
    7,   /*  1    1    0   0   1   INSIDE   OUTSIDE  INSIDE     */
    7,   /*  1    1    0   0   1   INSIDE   INSIDE   OUTSIDE    */
    7,   /*  1    1    0   0   1   INSIDE   INSIDE   INSIDE     */
    2,   /*  1    1    0   1   0   OUTSIDE  OUTSIDE  OUTSIDE    */
    2,   /*  1    1    0   1   0   OUTSIDE  OUTSIDE  INSIDE     */
    2,   /*  1    1    0   1   0   OUTSIDE  INSIDE   OUTSIDE    */
    2,   /*  1    1    0   1   0   OUTSIDE  INSIDE   INSIDE     */
    2,   /*  1    1    0   1   0   INSIDE   OUTSIDE  OUTSIDE    */
    2,   /*  1    1    0   1   0   INSIDE   OUTSIDE  INSIDE     */
    2,   /*  1    1    0   1   0   INSIDE   INSIDE   OUTSIDE    */
    7,   /*  1    1    0   1   0   INSIDE   INSIDE   INSIDE     */
    2,   /*  1    1    0   1   1   OUTSIDE  OUTSIDE  OUTSIDE    */
    2,   /*  1    1    0   1   1   OUTSIDE  OUTSIDE  INSIDE     */
    2,   /*  1    1    0   1   1   OUTSIDE  INSIDE   OUTSIDE    */
    2,   /*  1    1    0   1   1   OUTSIDE  INSIDE   INSIDE     */
    2,   /*  1    1    0   1   1   INSIDE   OUTSIDE  OUTSIDE    */
    2,   /*  1    1    0   1   1   INSIDE   OUTSIDE  INSIDE     */
    2,   /*  1    1    0   1   1   INSIDE   INSIDE   OUTSIDE    */
    9,   /*  1    1    0   1   1   INSIDE   INSIDE   INSIDE     */
    2,   /*  1    1    1   0   0   OUTSIDE  OUTSIDE  OUTSIDE    */
    2,   /*  1    1    1   0   0   OUTSIDE  OUTSIDE  INSIDE     */
    2,   /*  1    1    1   0   0   OUTSIDE  INSIDE   OUTSIDE    */
    2,   /*  1    1    1   0   0   OUTSIDE  INSIDE   INSIDE     */
    2,   /*  1    1    1   0   0   INSIDE   OUTSIDE  OUTSIDE    */
    2,   /*  1    1    1   0   0   INSIDE   OUTSIDE  INSIDE     */
    2,   /*  1    1    1   0   0   INSIDE   INSIDE   OUTSIDE    */
    7,   /*  1    1    1   0   0   INSIDE   INSIDE   INSIDE     */
    2,   /*  1    1    1   0   1   OUTSIDE  OUTSIDE  OUTSIDE    */
    2,   /*  1    1    1   0   1   OUTSIDE  OUTSIDE  INSIDE     */
    2,   /*  1    1    1   0   1   OUTSIDE  INSIDE   OUTSIDE    */
    2,   /*  1    1    1   0   1   OUTSIDE  INSIDE   INSIDE     */
    2,   /*  1    1    1   0   1   INSIDE   OUTSIDE  OUTSIDE    */
    2,   /*  1    1    1   0   1   INSIDE   OUTSIDE  INSIDE     */
    2,   /*  1    1    1   0   1   INSIDE   INSIDE   OUTSIDE    */
    9,   /*  1    1    1   0   1   INSIDE   INSIDE   INSIDE     */
    2,   /*  1    1    1   1   0   OUTSIDE  OUTSIDE  OUTSIDE    */
    2,   /*  1    1    1   1   0   OUTSIDE  OUTSIDE  INSIDE     */
    2,   /*  1    1    1   1   0   OUTSIDE  INSIDE   OUTSIDE    */
    2,   /*  1    1    1   1   0   OUTSIDE  INSIDE   INSIDE     */
    2,   /*  1    1    1   1   0   INSIDE   OUTSIDE  OUTSIDE    */
    2,   /*  1    1    1   1   0   INSIDE   OUTSIDE  INSIDE     */
    2,   /*  1    1    1   1   0   INSIDE   INSIDE   OUTSIDE    */
    7,   /*  1    1    1   1   0   INSIDE   INSIDE   INSIDE     */
    2,   /*  1    1    1   1   1   OUTSIDE  OUTSIDE  OUTSIDE    */
    2,   /*  1    1    1   1   1   OUTSIDE  OUTSIDE  INSIDE     */
    2,   /*  1    1    1   1   1   OUTSIDE  INSIDE   OUTSIDE    */
    2,   /*  1    1    1   1   1   OUTSIDE  INSIDE   INSIDE     */
    2,   /*  1    1    1   1   1   INSIDE   OUTSIDE  OUTSIDE    */
    2,   /*  1    1    1   1   1   INSIDE   OUTSIDE  INSIDE     */
    2,   /*  1    1    1   1   1   INSIDE   INSIDE   OUTSIDE    */
    9    /*  1    1    1   1   1   INSIDE   INSIDE   INSIDE     */
     };
