MODULE ex
10 PRIVATE 
PUBLIC boo, ASSIGNMENT(=)
PUBLIC binky, bonky, OPERATOR(+)
INTERFACE ASSIGNMENT(=)
SUBROUTINE LOGICAL_TO_NUMERIC(N,B)
INTEGER, INTENT(OUT) :: N
LOGICAL, INTENT(IN) :: B
END SUBROUTINE LOGICAL_TO_NUMERIC

END INTERFACE ASSIGNMENT(=)
INTERFACE OPERATOR(+)
LOGICAL FUNCTION LOGICAL_ADD(N,B)
LOGICAL, INTENT(IN) :: N
LOGICAL, INTENT(IN) :: B
END FUNCTION LOGICAL_ADD
END INTERFACE OPERATOR(+)
END MODULE ex
