INTEGER, ALLOCATABLE :: a, b, X(:), Y(:,:)
CHARACTER(4) :: blah = "blah"
10 ALLOCATE(a,b)
ALLOCATE(INTEGER:: a,b)
ALLOCATE(a, STAT=i, ERRMSG=blah, SOURCE=k)
ALLOCATE(X(N),Y(-3:M,0:9), STAT=IERR_ALLOC)
END PROGRAM
