#!/bin/bash
#
# Generates the corresponding Ada spec from a C++ header file.
#

# Defines log, log_and_run, etc.:
source `which utility_functions.sh`

# Make GNAT compiler and gprbuild available:
use_gnat () {
  # Loads the default gnat, if that is the one you want:
  module load gnat
}

log_start
log_invocation "$@"
use_gnat

# GNAT g++ options:
# -fdump-ada-spec
#  Generate Ada spec files for the given header files transitively (including all header files that these headers depend upon). 
# -fdump-ada-spec-slim
#  Generate a single Ada file and not the transitive closure.
# -fada-spec-parent=`unit' 
#  All files generated by `-fdump-ada-spec*' are to be child units of the specified parent unit.
# -C 
#  Extract comments from headers and attempt to generate corresponding Ada comments.
# -D<macro> 
#  Define <macro>

# -gnatceg
#  Generate a _C_ header from an _Ada_ spec (includes withed specs).
log_then_run g++ -c -fdump-ada-spec $1 || exit $?
log_end

