#define EOF_Sym	0	/* EOF */
#define identSym	1	/* ident */
#define stringSym	2	/* string */
#define badstringSym	3	/* badstring */
#define numberSym	4	/* number */
#define COMPILERSym	5	/* "COMPILER" */
#define PRODUCTIONSSym	6	/* "PRODUCTIONS" */
#define EqualSym	7	/* "=" */
#define PointSym	8	/* "." */
#define ENDSym	9	/* "END" */
#define CHARACTERSSym	10	/* "CHARACTERS" */
#define TOKENSSym	11	/* "TOKENS" */
#define NAMESSym	12	/* "NAMES" */
#define PRAGMASSym	13	/* "PRAGMAS" */
#define COMMENTSSym	14	/* "COMMENTS" */
#define FROMSym	15	/* "FROM" */
#define TOSym	16	/* "TO" */
#define NESTEDSym	17	/* "NESTED" */
#define IGNORESym	18	/* "IGNORE" */
#define CASESym	19	/* "CASE" */
#define PlusSym	20	/* "+" */
#define MinusSym	21	/* "-" */
#define Range	22	/* ".." */
#define ANYSym	23	/* "ANY" */
#define CHRSym	24	/* "CHR" */
#define LparenSym	25	/* "(" */
#define RparenSym	26	/* ")" */
#define BarSym	27	/* "|" */
#define WEAKSym	28	/* "WEAK" */
#define LbrackSym	29	/* "[" */
#define RbrackSym	30	/* "]" */
#define LbraceSym	31	/* "{" */
#define RbraceSym	32	/* "}" */
#define SYNCSym	33	/* "SYNC" */
#define CONTEXTSym	34	/* "CONTEXT" */
#define LessSym	35	/* "<" */
#define GreaterSym	36	/* ">" */
#define LessPointSym	37	/* "<." */
#define PointGreaterSym	38	/* ".>" */
#define LparenPointSym	39	/* "(." */
#define PointRparenSym	40	/* ".)" */
#define No_Sym	41	/* not */
#define OptionsSym	42	/* Options */
#define MAXT	No_Sym	/* Max Terminals */

