         "EOF expected",
         "ident expected",
         "string expected",
         "badstring expected",
         "number expected",
         "\"COMPILER\" expected",
         "\"PRODUCTIONS\" expected",
         "\"=\" expected",
         "\".\" expected",
         "\"END\" expected",
         "\"CHARACTERS\" expected",
         "\"TOKENS\" expected",
         "\"NAMES\" expected",
         "\"PRAGMAS\" expected",
         "\"COMMENTS\" expected",
         "\"FROM\" expected",
         "\"TO\" expected",
         "\"NESTED\" expected",
         "\"IGNORE\" expected",
         "\"CASE\" expected",
         "\"+\" expected",
         "\"-\" expected",
         "\"..\" expected",
         "\"ANY\" expected",
         "\"CHR\" expected",
         "\"(\" expected",
         "\")\" expected",
         "\"|\" expected",
         "\"WEAK\" expected",
         "\"[\" expected",
         "\"]\" expected",
         "\"{\" expected",
         "\"}\" expected",
         "\"SYNC\" expected",
         "\"CONTEXT\" expected",
         "\"<\" expected",
         "\">\" expected",
         "\"<.\" expected",
         "\".>\" expected",
         "\"(.\" expected",
         "\".)\" expected",
         "not expected",
         "Options expected",
         "unexpected symbol in CR",
         "unexpected symbol in CR",
         "unexpected symbol in Declaration",
         "unexpected symbol in Declaration",
         "unexpected symbol in Attribs",
         "unexpected symbol in Attribs",
         "unexpected symbol in Attribs",
         "unexpected symbol in SemText",
         "unexpected symbol in TokenDecl",
         "unexpected symbol in TokenDecl",
         "unexpected symbol in TokenDecl",
         "unexpected symbol in NameDecl",
         "unexpected symbol in CompSet",
         "unexpected symbol in SimSet",
         "unexpected symbol in SimSet",
         "unexpected symbol in ChrSet",
         "unexpected symbol in Factor",
         "unexpected symbol in Factor",
         "unexpected symbol in Symbol",
         "unexpected symbol in TokenFactor",

