#
# This file should be deleted.
# Use autoconf/automake instead
#

# Example Makefile for ROSE users
# This makefile is provided as an example of how to use ROSE when ROSE is
# installed (using "make install").  This makefile is tested as part of the
# "make distcheck" rule (run as part of tests before any CVS checkin).
# The test of this makefile can also be run by using the "make installcheck"
# rule (run as part of "make distcheck").


UNROLL_OBJS = src/mainLoopUnroller.lo src/loopunroller/loopUnroller.lo src/loopunroller/loopUnrollerTraversal.lo src/loopunroller/loopAttributes.lo

# Location of include directory after "make install"
ROSE_INCLUDE_DIR = ${ROSE_HOME}/include

# Location of Boost include directory
BOOST_CPPFLAGS = -pthread -I${BOOST_HOME}/include

# Location of Dwarf include and lib (if ROSE is configured to use Dwarf)
ROSE_DWARF_INCLUDES = 
ROSE_DWARF_LIBS_WITH_PATH = 
ROSE_INCLUDE_DIR += $(ROSE_DWARF_INCLUDES)
ROSE_LIBS += $(ROSE_DWARF_LIBS_WITH_PATH)

CC                    = gcc
CXX                   = g++
CPPFLAGS              = -Isrc/loopunroller/include
#CXXCPPFLAGS           = @CXXCPPFLAGS@
CXXFLAGS              = -Wno-deprecated -Wall -Wextra -g -O0
LDFLAGS               = $(ROSE_LDFLAGS)

# Location of library directory after "make install"
ROSE_LIB_DIR = ${ROSE_HOME}/lib

ROSE_LDFLAGS = -lrose -L$(ROSE_INCLUDE_DIR)

ROSE_SOURCE_DIR = .

# Default make rule to use
all: src/loopunroller mainLoopUnroller
	@if [ x$${ROSE_IN_BUILD_TREE:+present} = xpresent ]; then echo "ROSE_IN_BUILD_TREE should not be set" >&2; exit 1; fi

# Example suffix rule for more experienced makefile users
#.C.o:
#	g++ -c -I$(ROSE_INCLUDE_DIR) -o $@ $(@:.o=.C)

%.lo:%.cc
	libtool --mode=compile $(CXX) $(CXXFLAGS) $(CPPFLAGS) -I$(ROSE_INCLUDE_DIR) $(BOOST_CPPFLAGS) -c -o $@ $^

mainLoopUnroller: $(UNROLL_OBJS) 
	libtool --mode=link $(CXX) $(LDFLAGS) -o loopUnroller -Isrc/loopunroller/include $(UNROLL_OBJS) $(ROSE_LIBS)

clean:
	rm -rf src/loopunroller/*.o src/loopunroller/*.lo src/loopunroller/.libs src/*.o src/*.lo src/.libs src/loopUnroller
