#!/bin/bash

 runtimesystem=""
 stdlib=""
 rtedlib=""
 upcflags="-O0 -g -dwarf-2-upc -DWITH_UPC=1 -Wall -Wextra"
 cxxflags="-O0 -g -DWITH_UPC=1 -Wall -Wextra"

 for var in "$@"
 do
    parameter="$var"
    if [ "$parameter" = "-o" ]; then
      remove=$parameter;
    elif [ "x$parameter" = "x-pthread" ] ; then
     remove=$parameter;
    elif [ "x$parameter" = "xCppRuntimeSystem/libCppRuntimeSystem.la" ]; then
#     newOption=$newOption" CppRuntimeSystem/.libs/libCppRuntimeSystem.so";
     remove=$parameter
    elif [ "x$parameter" = "x-Winvalid-pch" ]; then
     remove=$parameter;
    elif [ "x$parameter" = "x-fPIC" ]; then
     remove=$parameter;
    elif [ "x$parameter" = "x-rose:UPC" ]; then
     remove=$parameter;
    elif [[ $parameter == *RuntimeSystem.cpp ]]; then
     runtimesystem=$parameter
    elif [[ $parameter == *.upc ]]; then
      filename=`basename $parameter .upc`
      inpfiles="$inpfiles $parameter"
      objfiles="$objfiles $filename.o"
    elif [[ $parameter == *.bin ]]; then
      executable="-o $parameter"
    else
      newOption=$newOption" "$parameter;
    fi
#    echo "$remove";
# --------- $parameter";
 done
#echo "REMOVED :: $remove"
#echo "KEPT :: $newOption"
#echo $newOption;

# compiling with C++ and RTED runtime?
if [ "$runtimesystem" != "" ]; then
  rtedsrcdir=`dirname $runtimesystem`

  echo "g++ $cxxflags -c $runtimesystem"
  g++ $cxxflags -c $runtimesystem

  echo "upc $upcflags -c $rtedsrcdir/ParallelRTS.upc $rtedsrcdir/workzone.upc"
  upc $upcflags -c $rtedsrcdir/ParallelRTS.upc $rtedsrcdir/workzone.upc

  rtedlib="-L./CppRuntimeSystem/.libs/ -lCppRuntimeSystem"
  objfiles="$objfiles ParallelRTS.o workzone.o RuntimeSystem.o"
fi

echo "upc $upcflags $newOption -c $inpfiles"
upc $upcflags $newOption -c $inpfiles

echo "upc++link -dwarf-2-upc $executable $objfiles $rtedlib"
upc++link -dwarf-2-upc $executable $objfiles $rtedlib

#echo "rm $objfiles"
#rm $objfiles
