#!/bin/bash

 runtimesystem=""
 stdlib=""
 rtedlib=""
 upcflags="-O0 -g -dwarf-2-upc"

 for var in "$@"
 do
    parameter="$var"
    if [ "$parameter" = "-o" ]; then
      remove=$parameter;
    elif [ "x$parameter" = "x-pthread" ] ; then
     remove=$parameter;
    elif [ "x$parameter" = "xCppRuntimeSystem/libCppRuntimeSystem.la" ]; then
#     newOption=$newOption" CppRuntimeSystem/.libs/libCppRuntimeSystem.so";
     remove=$parameter
    elif [ "x$parameter" = "x-Winvalid-pch" ]; then
     remove=$parameter;
    elif [ "x$parameter" = "x-fPIC" ]; then
     remove=$parameter;
    elif [ "x$parameter" = "x-rose:UPC" ]; then
     remove=$parameter;
    elif [[ $parameter == *RuntimeSystem.cpp ]]; then
     runtimesystem=$parameter
    elif [[ $parameter == *.upc ]]; then
      filename=`basename $parameter .upc`
      inpfiles="$inpfiles $parameter"
      objfiles="$objfiles $filename.o"
    elif [[ $parameter == *.bin ]]; then
     executable=$parameter;
    else
      newOption=$newOption" "$parameter;
    fi
#    echo "$remove";
# --------- $parameter";
 done
#echo "REMOVED :: $remove"
#echo "KEPT :: $newOption"
#echo $newOption;

# compiling with C++ and RTED runtime?
if [ "$runtimesystem" != "" ]; then
  echo "g++ -g -DWITH_UPC=1 -c $runtimesystem"
  g++ -g -DWITH_UPC=1 -c $runtimesystem

  echo "upc $upcflags -DWITH_UPC=1 -c ParallelRTS.upc"
  upc $upcflags -DWITH_UPC=1 -c ParallelRTS.upc

  # find the libstdc++ that the C++ compiler would use
  rtedlib="ParallelRTS.o RuntimeSystem.o -L./CppRuntimeSystem/.libs/ -lCppRuntimeSystem"
fi

echo "upc -O0 -dwarf-2-upc $newOption -c $inpfiles"
upc $upcflags $newOption -c $inpfiles

echo "upc++link -o $executable $objfiles $rtedlib $stdlib"
upc++link -dwarf-2-upc -o $executable $objfiles $rtedlib

echo "$objfiles"
rm $objfiles
