//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (http://www.swig.org).
// Version 3.0.12
//
// Do not make changes to this file unless you know what you are doing--modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------


public enum SeqKind {
  GLOBALSCOPESEQ = 2,
  CLASSMEMBERSEQ = 3,
  PARAMETERSEQ = 4,
  METHODBODYSEQ = 5,
  EXPRLISTSEQ = 6,
  IFSTMT = 7,
  FORSTMT = 8,
  WHILESTMT = 9
}
