         "EOF expected",
         "ident expected",
         "string expected",
         "badstring expected",
         "number expected",
         "\"COMPILER\" expected",
         "\"PRODUCTIONS\" expected",
         "\"END\" expected",
         "\".\" expected",
         "\"=\" expected",
         "\"|\" expected",
         "\"{\" expected",
         "\"}\" expected",
         "\"[\" expected",
         "\"]\" expected",
         "\"TOKENS\" expected",
         "\"<\" expected",
         "\">\" expected",
         "\"<.\" expected",
         "\".>\" expected",
         "\"(.\" expected",
         "\".)\" expected",
         "not expected",
         "Options expected",
         "unexpected symbol in AGPP",
         "unexpected symbol in Attribs",
         "unexpected symbol in Attribs",
         "unexpected symbol in Attribs",
         "unexpected symbol in Rhs",
         "unexpected symbol in NonTerminalExp",
         "unexpected symbol in SemText",
