/* rose_config.h.  Generated by configure.  */
/* rose_config.h.in.  Generated from configure.in by autoheader.  */
/* this public header generated by ../scripts/publicConfiguration.pl */

/* Define to 1 if you have the <pthread.h> header file. */
#define ROSE_HAVE_PTHREAD_H 1
