rwAccessLabeler_OBJ = ${ANALYSIS_ROOT}/src/rwAccessLabeler/obj/rwAccessLabeler.o
rwAccessLabeler_H = ${ANALYSIS_ROOT}/src/rwAccessLabeler/rwAccessLabeler.h

.PHONY: rwAccessLabeler
rwAccessLabeler:
	cd ${ANALYSIS_ROOT}/src/rwAccessLabeler; ${MAKE} all; cd ${ANALYSIS_ROOT}/src/${Component}
