compass_srcdir=$(top_srcdir)/projects/compass/src
compass_tooldir=$(top_srcdir)/projects/compass/tools
compass_extdir=$(top_srcdir)/projects/compass/extensions

compass_build_srcdir=$(top_builddir)/projects/compass/src
compass_build_tooldir=$(top_builddir)/projects/compass/tools
compass_build_extdir=$(top_builddir)/projects/compass/extensions

compass_prereqs_dir=$(compass_extdir)/prerequisites
compass_checker_dir=$(compass_extdir)/checkers
compass_checker_repository=$(compass_checker_dir)/repository
compass_support_dir=$(compass_srcdir)/compassSupport
compass_scripts_dir=$(compass_srcdir)/compass_scripts
compass_input_dir=$(compass_srcdir)/in
compass_test_dir=$(compass_srcdir)/tests

compass_checker_bdir=$(compass_build_extdir)/checkers
compass_support_bdir=$(compass_build_srcdir)/compassSupport
