asrcdir=$(realpath $(srcdir))
DIRS = \
	bcast \
	collect \
	diffusion2 \
	exchange \
	gausselim_par \
	hellow \
	jacobi \
	jacobi2 \
	jacobicmpl \
	master-slave \
	mpi-ex1 \
	ring \
	sample1 \
	sample2 \
	sample3 \
	sample4 \
	sample5 \
	sample7 \
	sample8 \
	sample9 \
	sampleA \
	scatterv \
	t1 \
	t2 \
	t3 \
	t4 \
	t5 \
	t6 \
	t7 \
	t8 \
	t9 \
	t10 \
	t11 \
	t12 \
	t13 \
	t14 \
	t16 \
	t17 \
        t19 \
        t20 \
        t21 \
        t22 \
        t25 \
        t26 \
        t27 \
        t28 \
        t29 \
        t30 \
        t31 \
        t32 \
        t33 \
        t34 \
        t35 \
        t36 \
        t37 \
        t38 \
        t39
#       t23 \      # Failing now
#       t24 \      # Failing now

# These, we expect to fail, in anti-tests/ for now:
#    t15 \
#    t18 \
# TODO: We need to add more like this.

MARKS=$(addsuffix /testmark, ${DIRS})
LISTS=$(addsuffix /files, ${DIRS})
ALL_OUTS=$(foreach list, ${LISTS}, $(addprefix $(dir ${list}), $(addprefix rose_, $(shell cat ${list}))))
ALL_OBJS=$(addsuffix .o, $(basename ${ALL_OUTS}))
ALL_EXPECTED=$(wildcard $(addsuffix /*.expected, ${DIRS}))
ALL_TI=$(shell find . -name "*.ti")

SKFLAGS=-I$(asrcdir)/../mpi-fakeheader -skel:spec $(asrcdir)/../apis.coll

%/testmark: %/files
	(cd $* && ${EXEC} ${SKFLAGS} `cat files` && touch $(@F))

%/testmark-outline: %/files
	(cd $* && ${EXEC} ${SKFLAGS} -skel:o `cat files` && touch $(@F))

%.o: %.c
	${CC} -I$(asrcdir)/../mpi-fakeheader -c -o $@ $<

%.o: %.cc
	${CXX} -I$(asrcdir)/../mpi-fakeheader -c -o $@ $<

%.comp: % %.expected
	- diff -w $?

clean:
	rm -f ${ALL_OUTS} ${ALL_OBJS} ${MARKS} ${ALL_TI}

show:
	@echo $($(VALUE))              # note: this expands!
