srcdir=.
EXEC=../../extractMPISkeleton

all: test

include Makefile_variables

test:
	${MAKE} -f Makefile.manual ${MARKS}
	${MAKE} -f Makefile.manual ${ALL_OBJS}
	${MAKE} -f Makefile.manual ${ALL_EXPECTED:.expected=.comp}

clean:
	rm -f ${ALL_OUTS} ${ALL_OBJS} ${MARKS} */*.sig */*.sig.tc */*.ti
