#!/bin/sh
set -e
if [ $# -ne 1 ]; then
  echo "Usage: $0 srcdir" 1>&2
  exit 1
fi
srcdir=$1

ROSE_OPTIONS="--edg:no_warnings -w -c"
DIFF_OPTIONS="-U5 -b -d"
# PREFIX="libtool --mode=execute /usr/bin/valgrind"
PREFIX=""

test1="$PREFIX ./LoopProcessor $ROSE_OPTIONS -bk1 -fs0 -I$srcdir $srcdir/mm.C"
echo $test1
$test1
echo "diff $DIFF_OPTIONS $srcdir/rose_mm.C.save rose_mm.C"
diff $DIFF_OPTIONS $srcdir/rose_mm.C.save rose_mm.C
rm rose_mm.C

test2="$PREFIX ./LoopProcessor $ROSE_OPTIONS -bk1 -fs0 -annot $srcdir/funcs.annot -I$srcdir $srcdir/lufac.C"
echo $test2
$test2
echo "diff $DIFF_OPTIONS $srcdir/rose_lufac.C.save rose_lufac.C"
diff $DIFF_OPTIONS $srcdir/rose_lufac.C.save rose_lufac.C
rm rose_lufac.C

test3="$PREFIX ./LoopProcessor $ROSE_OPTIONS -bk1 -fs0  -splitloop -annot $srcdir/funcs.annot -I$srcdir $srcdir/lufac.C"
echo $test3
$test3
echo "diff $DIFF_OPTIONS $srcdir/rose_lufac_split.C.save rose_lufac.C"
diff $DIFF_OPTIONS $srcdir/rose_lufac_split.C.save rose_lufac.C
rm rose_lufac.C

test4="$PREFIX ./LoopProcessor $ROSE_OPTIONS -fs2 -ic1 -opt 1 $srcdir/tridvpk.C"
echo $test4
$test4
echo "diff $DIFF_OPTIONS $srcdir/rose_tridvpk.C.save rose_tridvpk.C"
diff $DIFF_OPTIONS $srcdir/rose_tridvpk.C.save rose_tridvpk.C
rm rose_tridvpk.C

test5="$PREFIX ./LoopProcessor $ROSE_OPTIONS -bs 60 -fs01 $srcdir/rmatmult3.C"
echo $test5
$test5
echo "diff $DIFF_OPTIONS $srcdir/rose_rmatmult3.C.save rose_rmatmult3.C"
diff $DIFF_OPTIONS $srcdir/rose_rmatmult3.C.save rose_rmatmult3.C
rm rose_rmatmult3.C

test6="$PREFIX ./LoopProcessor $ROSE_OPTIONS -bk1 -unroll nvar 16 $srcdir/dgemm.C"
echo $test6
$test6
echo "diff $DIFF_OPTIONS $srcdir/rose_dgemm.C.save rose_dgemm.C"
diff $DIFF_OPTIONS $srcdir/rose_dgemm.C.save rose_dgemm.C
rm rose_dgemm.C

test7="$PREFIX ./LoopProcessor $ROSE_OPTIONS -fs2  -I$srcdir $srcdir/fusiontest1.C"
echo $test7
$test7
echo "diff $DIFF_OPTIONS $srcdir/rose_fusiontest1.C.save rose_fusiontest1.C"
diff $DIFF_OPTIONS $srcdir/rose_fusiontest1.C.save rose_fusiontest1.C
rm rose_fusiontest1.C

test8="$PREFIX ./LoopProcessor $ROSE_OPTIONS -cp 0  -I$srcdir $srcdir/mm.C"
echo $test8
$test8
echo "diff $DIFF_OPTIONS $srcdir/rose_mm_cp0.C.save rose_mm.C"
diff $DIFF_OPTIONS $srcdir/rose_mm_cp0.C.save rose_mm.C
rm rose_mm.C
                                                                                             
test9="$PREFIX ./LoopProcessor $ROSE_OPTIONS -cp 0  -annot $srcdir/funcs.annot -I$srcdir $srcdir/lufac.C"
echo $test9
$test9
echo "diff $DIFF_OPTIONS $srcdir/rose_lufac_cp0.C.save rose_lufac.C"
diff $DIFF_OPTIONS $srcdir/rose_lufac_cp0.C.save rose_lufac.C
rm rose_lufac.C

test10="$PREFIX ./LoopProcessor $ROSE_OPTIONS -cp 2 -bk3 -I$srcdir $srcdir/mm.C"
echo $test10
$test10
echo "diff $DIFF_OPTIONS $srcdir/rose_mm_cp2_bk3.C.save rose_mm.C"
diff $DIFF_OPTIONS $srcdir/rose_mm_cp2_bk3.C.save rose_mm.C
rm rose_mm.C

