#!/bin/sh

./sl1rd --output-gdl=tests/rdtest1.gdl tests/rdtest1.C  || exit 1
./sl1rd --callstringlength=1 tests/rdtest2.C || exit 1
./sl1rd --output-source=tests/rdtest3.annotated.C tests/rdtest3.C || exit 1
