#!/bin/bash

if [ -d ../../../.RosePolly ]
then
	cd src
	for _FILE in *.cpp
	do
		if [ $_FILE -nt $(find ../../../../.RosePolly/src -name $_FILE -print | head -1) ] 
		then
			echo "copying ... "
			echo $_FILE
			cp $_FILE ../../../../.RosePolly/src
		fi
		
	done
	cd ../include
	for _FILE in *.h
	do
		if [ $_FILE -nt $(find ../../../../.RosePolly/include -name $_FILE -print | head -1) ] 
		then
			echo "copying ... "
			echo $_FILE
			cp $_FILE ../../../../.RosePolly/include
		fi
		
	done
	cd ../../../../.RosePolly
	make
	
else
	mkdir ../../../.RosePolly
	cp -rf * ../../../.RosePolly
	cd ../../../.RosePolly
	
	if autoreconf --install
	then
		if ./configure
		then
			make
		else
			cd ../
			rm -rf ./.RosePolly
		fi
	else
		cd ../
		rm -rf ./.RosePolly
	fi
fi

exit 0
