OvertureInclude=  -I.
A++ =  $(APlusPlus)

Include =     -I. -I$(A++)/include $(OvertureInclude)

CCFLAGS=    $(Include)  -g -cg92 $(Include) 

FC=         f77
FFLAGS=     -g 
FFLAGS=      -g 

CLIBS=      -L$(OvertureLib) -lOverture -lOverture_static $(AppLib) \
            -L$(HDF)/lib -lmfhdf -ldf -ljpeg -lz -lnsl

FLIBS=      -lF77 -lM77 -lV77 -lsunmath

GLIBS=   -L$(OpenGL)/lib $(GL_LIBS) -lnsl \
         -L$(MOTIF) -lXm -L$(XLIBS) -lXt -lXmu -lXi -lXext -lX11 -lm


.SUFFIXES:
.SUFFIXES:.f .o .C .o .F .f .c
.C.o:; $(CC)  $(CCFLAGS) -c $*.C
.c.o:; $(cc)  -g -I.  -c $*.c
.f.o:; $(FC) $(FFLAGS) -c $*.f
.F.f:; cpp -DSUN $*.f



all = xFDerivative.o


SRC = *.C


#		//
#		// DEPENDENCIES
#		//

# to remake the dependencies: make dep
dep:;
	makeDepend -fdepend -Y -- $(CCFLAGS) -- $(SRC)

# include the dependencies here
include depend


.PRECIOUS:$(MAPLIB)

