/* This file was generated by the configure script */
#ifndef OVERTURE_DEFINE_H
#define OVERTURE_DEFINE_H

#define OVERTURE_HOME "/home/henshaw/Overture.v18c.gcc"

#define OV_USE_DOUBLE
#define OV_BOOL_DEFINED
#define OV_USE_MESA
#define OV_EXCEPTIONS_NOT_SUPPORTED
#undef OV_USE_OLD_STL_HEADERS
#undef OV_NO_DEFAULT_TEMPL_ARGS
#define OV_USINGNAMESPACE(x)
#define EXPLICIT

#ifndef BL_Solaris
#define BL_Solaris
#endif

#undef OV_USE_LESSTIF

/*  the next line needed for gnu and kcc */
#ifndef BL_AUTO_INSTANTIATE
#define BL_AUTO_INSTANTIATE
#endif

#endif
