include $(top_srcdir)/config/Makefile.for.ROSE.includes.and.libs

SUBDIRS = astInterface astSupport  symbolicVal  annotation

## The grammar generator (ROSETTA) should use its own template repository
CXX_TEMPLATE_REPOSITORY_PATH = .

clean-local:

distclean-local:








EXTRA_DIST = CMakeLists.txt
