#!/bin/bash

#$1: CodeThorn's src directory
#$2: CodeThorn's build directory

SRCDIR=$1
BUILDDIR=$2

MAKE_CHECK="_make_check"

echo ".==================================================================."
echo "| testing memory bound STG computation (RERS 1603, 1GB, 4 threads) |"
echo "*==================================================================*"

#create a temp directory
CURRENT_TIME=`date '+%m-%d-%y_%H:%M:%S'`
TEMP_DIR="make_check_log_memorybound_${CURRENT_TIME}_$$"
mkdir ${2}/${TEMP_DIR}
echo "created directory for temporary files: <CodeThorn build dir>/src/${TEMP_DIR}"

#check problem specific ltl formulae/reachability of failing assertions and generate the results. Use 4 threads
$BUILDDIR/codethorn ${SRCDIR}/tests/rers/Problem1603_opt.c --solver=12 --exploration-mode=breadth-first --edg:no_warnings --rersmode=yes --with-counterexamples=no --input-values="{1,2,3,4,5,6,7,8,9,10}" --ltl-in-alphabet="{1,2,3,4,5,6,7,8,9,10}" --ltl-out-alphabet="{15,16,17,18,19,20,21,22,23,24,25,26}" --max-memory=1000000000 --check-ltl=$SRCDIR/tests/rers/constraints-RERS16-Problem3.txt --csv-spot-ltl="${2}/${TEMP_DIR}/Problem1603_ltl_results_maxmemory_1000000000_n_bf${MAKE_CHECK}.csv" --threads=4 
RES=$?
if [ ! $RES -eq 0 ] 
then
    echo "Error (script runRersMemoryTest): RERS LTL regression data could not be reproduced."
    echo "(codethorn exit: $RES)"
    exit 1 
fi

#compare with regression data
${SRCDIR}/scripts/check_consistency ${2}/${TEMP_DIR}/Problem1603_ltl_results_maxmemory_1000000000_n_bf${MAKE_CHECK}.csv ${SRCDIR}/regressiondata2/Problem1603_ltl_solutions.csv 2>&1
if [ ! $? -eq 0 ] 
then 
  echo "ERROR: RERS LTL regression data could not be correctly reproduced."
  echo "(Please take a look at directory <CodeThorn build dir>/src/${TEMP_DIR} for files that could not be matched)"
  exit 1 
else
  echo "Success: all results for verified/falsified properties are correct."
fi

#remove temp directory, including files
rm -rf ${2}/${TEMP_DIR}
echo "removed directory for temporary files: <CodeThorn build dir>/src/${TEMP_DIR}"
    
echo ".=================================================================."
echo "| STG memory bound tested succesfully (RERS 1603, 1GB, 4 threads) |"
echo "*=================================================================*"

