#!/bin/bash

#$1: CodeThorn's src directory
#$2: CodeThorn's build directory

SRCDIR=$1
BUILDDIR=$2

MAKE_CHECK="_make_check"

echo ".==============================================."
echo "| testing RERS problem 1403 (arrays, 1 thread) |"
echo "*==============================================*"

#create a temp directory
CURRENT_TIME=`date '+%m-%d-%y_%H:%M:%S'`
TEMP_DIR="make_check_log_arraytest_${CURRENT_TIME}_$$"
mkdir ${2}/${TEMP_DIR}
echo "created directory for temporary files: <CodeThorn build dir>/src/${TEMP_DIR}"

#check problem specific ltl formulae/reachability of failing assertions and generate the results.
$BUILDDIR/codethorn $SRCDIR/tests/rers/Problem1403_opt.c --solver=5 --exploration-mode=breadth-first --edg:no_warnings --rersmode=yes --with-counterexamples=no --ltl-in-alphabet="{1,2,3,4,5}" --ltl-out-alphabet="{18,19,20,21,22,23,24,25,26}" --max-transitions=50000 --check-ltl=$SRCDIR/tests/rers/constraints-RERS14-5.txt --csv-spot-ltl="${2}/${TEMP_DIR}/Problem1403_ltl_results_maxtrans_50000_n_bf${MAKE_CHECK}.csv" --csv-assert="${2}/${TEMP_DIR}/Problem1403_assert_results_maxtrans_50000_n_bf${MAKE_CHECK}.csv"
if [ ! $? -eq 0 ] 
then 
    eval echo "ERROR: codethorn failed in runRersArrayProblemTest."
    exit 1 
fi

#compare with regression data
diff ${2}/${TEMP_DIR}/Problem1403_assert_results_maxtrans_50000_n_bf${MAKE_CHECK}.csv $SRCDIR/regressiondata2/Problem1403_assert_results_maxtrans_50000_n_bf.csv >/dev/null 2>&1
if [ ! $? -eq 0 ] 
then 
    eval echo "ERROR: RERS assertion regression data could not be correctly reproduced."
    echo "(Please look at directory ${2}/${TEMP_DIR} for files that could not be matched)"
    exit 1 
else
    echo "Success: all results for verified/falsified properties are correct."
fi
diff ${2}/${TEMP_DIR}/Problem1403_ltl_results_maxtrans_50000_n_bf${MAKE_CHECK}.csv $SRCDIR/regressiondata2/Problem1403_ltl_results_maxtrans_50000_n_bf.csv >/dev/null 2>&1
if [ ! $? -eq 0 ] 
then 
    eval echo "ERROR: RERS ltl regression data could not be correctly reproduced."
    echo "(Please look at directory ${2}/${TEMP_DIR} for files that could not be matched)"
    exit 1 
else
    echo "Success: all results for unreachable/reachable failing assertions are correct."
fi
    

#remove temp directory, including files
rm -rf ${2}/${TEMP_DIR}
echo "removed directory for temporary files: <CodeThorn build dir>/src/${TEMP_DIR}"
    
echo ".=========================================================."
echo "| RERS problem 1403 tested succesfully (arrays, 1 thread) |"
echo "*=========================================================*"

