#!/bin/bash

#$1: CodeThorn's src directory
#$2: CodeThorn's build directory

SRCDIR=$1
BUILDDIR=$2
MAX_TIME=$3
THREADS=$4

if [[ $# -ne 4 ]]; then
    echo "Wrong number of arguments. 4 arguments required: SRCDIR BUILDDIR MAXTIME"
    exit 1
fi

MAKE_CHECK="_make_check"

echo ".======================================================================."
echo "| testing timeout of STG computation (${MAX_TIME} seconds, RERS 1402, $THREADS threads) |"
echo "*======================================================================*"
#echo "using solver 12 originally, switched to solver 5"

#create a temp directory
CURRENT_TIME=`date '+%m-%d-%y_%H:%M:%S'`
# use $$ to get a different PID for each invocation of this script (it is invoked in parallel in different tests)
TEMP_DIR="make_check_log_ltlrerstimeout_${CURRENT_TIME}_$$"
mkdir ${2}/${TEMP_DIR}
echo "created directory for temporary files: <CodeThorn build dir>/src/${TEMP_DIR}"

#check problem specific ltl formulae/reachability of failing assertions and generate the results. Use $THREADS threads
$BUILDDIR/codethorn $SRCDIR/tests/rers/Problem1402_opt.c --solver=5 --exploration-mode=loop-aware --edg:no_warnings --rersmode=yes --with-counterexamples=no --ltl-in-alphabet="{1,2,3,4,5}" --ltl-out-alphabet="{18,19,20,21,22,23,24,25,26}" --max-time=$MAX_TIME --check-ltl=$SRCDIR/tests/rers/constraints-RERS14-5.txt --csv-spot-ltl="${2}/${TEMP_DIR}/Problem1402_ltl_results_maxtime_${MAX_TIME}_n_la${MAKE_CHECK}.csv" --csv-assert="${2}/${TEMP_DIR}/Problem1402_assert_results_maxtime_${MAX_TIME}_n_la${MAKE_CHECK}.csv" --threads=$THREADS --status

#compare with regression data
$SRCDIR/scripts/check_consistency ${2}/${TEMP_DIR}/Problem1402_ltl_results_maxtime_${MAX_TIME}_n_la${MAKE_CHECK}.csv $SRCDIR/regressiondata2/Problem1402_ltl_solutions.csv 2>&1
if [ ! $? -eq 0 ] 
then 
  echo "ERROR: RERS LTL regression data could not be correctly reproduced."
  echo "(Please take a look at directory <CodeThorn build dir>/src/${TEMP_DIR} for files that could not be matched)"
  exit 1 
else
  echo "Success: all results for verified/falsified properties are correct."
fi

$SRCDIR/scripts/check_consistency ${2}/${TEMP_DIR}/Problem1402_assert_results_maxtime_${MAX_TIME}_n_la${MAKE_CHECK}.csv $SRCDIR/regressiondata2/Problem1402_reachability_solutions.csv 2>&1
if [ ! $? -eq 0 ] 
then 
  echo "ERROR: RERS reachability regression data could not be correctly reproduced."
  echo "(Please take a look at directory <CodeThorn build dir>/src/${TEMP_DIR} for files that could not be matched)"
  exit 1 
else
  echo "Success: all results for unreachable/reachable failing assertions are correct."
fi

#remove temp directory, including files
rm -rf ${2}/${TEMP_DIR}
echo "removed directory for temporary files: <CodeThorn build dir>/src/${TEMP_DIR}"
    
echo ".==============================================================================."
echo "| STG computation timeout tested succesfully (${MAX_TIME} seconds, RERS 1402, $THREADS threads) |"
echo "*==============================================================================*"

