PROCEDURE Z IS
     CONSTRAINT_ERROR : EXCEPTION;
BEGIN
     RAISE CONSTRAINT_ERROR;
     RAISE CONSTRAINT_ERROR with "Why now?";
     --~ RAISE STANDARD.CONSTRAINT_ERROR;
EXCEPTION
     WHEN STANDARD.CONSTRAINT_ERROR => Raise;
     WHEN CONSTRAINT_ERROR => null;
     WHEN OTHERS =>
          null;
END Z;

