
package Rep_Database is

  type Page_Id_Type is (None,
                        Dddddup_Page,
                        Egg1_Page,
                        Egg2_Page,
                        Egg3_Page,
                        Egg4_Page,
                        Gaslit1_Page,
                        Gaslit2_Page,
                        Gaslit3_Page,
                        Gaslit4_Page,
                        Gaslit5_Page,
                        Cobtest1_Page,
                        Cobtest2_Page,
                        End_Page);

type Name_Type is
   (None,          Bbbbb,                  Hz,                Dddddup,           Dddddld,
    Dddstat,       Almonds_aaa,            Eat_My_Pies,       Dacid,             Verb,
    Mode,          Ddd,                    Cob,               Waypoints,         French_Fries,
    Exam_Test,     Pie_Test,               Status,            Cruise,            Time,
    My_Keys,       My_stat,                My_bit,            Bom,               Eee,
    MandMs1,       MandMs2,
    MandMs3,       MandMs4,                MandMs5,           MandMs6,           MandMs7,
    MandMs8,       MandMs9,                MandMs10,          MandMs11,          Corn1,
    Corn2,         Corn3,                  Corn4,             Corn5,             Corn6,
    Corn7,         Corn8,                  Corn9,             Corn10,            Corn11
    );

  -- Defines the special characters
  type Special_Char_Type is (None,
                             Slash,
                             Colon,
                             Star,
                             Pound,
                             Question,
                             Plus,
                             Minus,
                             Equal,
                             Zero,
                             One,
                             Two,
                             Three,
                             Four,
                             Five,
                             Six,
                             Seven,
                             Eight,
                             Nine,
                             Degree,
                             Period);

  subtype Db_Range_Type is Integer range 1 .. 573;
  subtype X_Range_Type is Integer range 1 .. 23;
  subtype Y_Range_Type is Integer range 1 .. 11;

  type Element_Type is
    record
      Pageid  : Page_Id_Type;
      X       : X_Range_Type;
      Y       : Y_Range_Type;
      Special : Special_Char_Type;
      The_Name : Name_Type;
    end record;

  type Db_Array_Type is array (Db_Range_Type) of Element_Type;

  -- The database of elements listed by page id.
  -- (PageID, Col, Row, Special, The)Name)
  Db : constant Db_Array_Type :=
   ((Pageid => None, X => 1,  Y => 1, Special => None, The_Name => None),

    (Pageid => Egg1_Page, X => 2,  Y => 3, Special => None, The_Name => Ddd),
    (Pageid => Egg1_Page, X => 2,  Y => 5, Special => None, The_Name => Bom),
    (Pageid => Egg1_Page, X => 17, Y => 3, Special => None, The_Name => Dddddup),
    (Pageid => Egg1_Page, X => 17, Y => 5, Special => None, The_Name => Dddddld),
    (Pageid => Egg1_Page, X => 17, Y => 7, Special => None, The_Name => Dddstat),

    (Pageid => Egg1_Page, X => 2,  Y => 3, Special => None, The_Name => Bom),
    (Pageid => Egg1_Page, X => 2,  Y => 5, Special => None, The_Name => Almonds_aaa),
    (Pageid => Egg1_Page, X => 2,  Y => 7, Special => None, The_Name => Eat_My_Pies),

    (Pageid  => Egg1_Page,
     X       => 2,
     Y       => 9,
     Special => None,
     The_Name => Bom),

    (Pageid => Egg1_Page, X => 20, Y => 7, Special => None, The_Name => Ddd),
    (Pageid => Egg1_Page, X => 21, Y => 9, Special => None, The_Name => Ddd),

    (Pageid => Egg1_Page, X => 2,  Y => 3, Special => None, The_Name => Dacid),
    (Pageid => Egg1_Page, X => 2,  Y => 4, Special => None, The_Name => Verb),
    (Pageid => Egg1_Page, X => 2,  Y => 5, Special => None, The_Name => Mode),
    (Pageid => Egg1_Page, X => 15, Y => 4, Special => None, The_Name => Ddd),
    (Pageid => Egg1_Page, X => 2,  Y => 6, Special => None, The_Name => Exam_Test),
    (Pageid => Egg1_Page, X => 2,  Y => 8, Special => None, The_Name => Pie_Test),
    (Pageid => Egg1_Page, X => 12, Y => 6, Special => None, The_Name => Status),
    (Pageid => Egg1_Page, X => 21, Y => 9, Special => None, The_Name => Ddd),

    (Pageid => Dddddup_Page, X => 2,  Y => 3, Special => None,  The_Name => Ddd),
    (Pageid => Dddddup_Page, X => 2,  Y => 4, Special => None,  The_Name => Ddd),
    (Pageid => Dddddup_Page, X => 2,  Y => 5, Special => None,  The_Name => Ddd),
    (Pageid => Dddddup_Page, X => 2,  Y => 6, Special => None,  The_Name => Ddd),
    (Pageid => Dddddup_Page, X => 15, Y => 3, Special => None,  The_Name => Cob),
    (Pageid => Dddddup_Page, X => 18, Y => 3, Special => Slash, The_Name => None),
    (Pageid => Dddddup_Page, X => 19, Y => 3, Special => None,  The_Name => Ddd),

    (Pageid  => Dddddup_Page,
     X       => 13,
     Y       => 4,
     Special => None,
     The_Name => Ddd),

    (Pageid  => Dddddup_Page,
     X       => 2,
     Y       => 9,
     Special => None,
     The_Name => Ddd),

    (Pageid => Dddddup_Page, X => 21, Y => 9, Special => None,  The_Name => Ddd),

    (Pageid => Egg1_Page, X => 2,  Y => 3, Special => None, The_Name => Ddd),
    (Pageid => Egg1_Page, X => 10, Y => 3, Special => None, The_Name => Ddd),
    (Pageid => Egg1_Page, X => 18, Y => 3, Special => None, The_Name => Ddd),
    (Pageid => Egg1_Page, X => 5,  Y => 4, Special => None, The_Name => Ddd),
    (Pageid => Egg1_Page, X => 11, Y => 7, Special => None, The_Name => Bom),
    (Pageid => Egg1_Page, X => 2,  Y => 8, Special => None, The_Name => Ddd),
    (Pageid => Egg1_Page, X => 10, Y => 8, Special => None, The_Name => Ddd),
    (Pageid => Egg1_Page, X => 18, Y => 8, Special => None, The_Name => Ddd),

    (Pageid => Egg2_Page, X => 2,  Y => 3, Special => None, The_Name => Bom),
    (Pageid => Egg2_Page, X => 2,  Y => 4, Special => None, The_Name => Bom),
    (Pageid => Egg2_Page, X => 2,  Y => 5, Special => None, The_Name => Bom),
    (Pageid => Egg2_Page, X => 2,  Y => 6, Special => None, The_Name => Bom),
    (Pageid => Egg2_Page, X => 2,  Y => 7, Special => None, The_Name => Bom),
    (Pageid => Egg2_Page, X => 2,  Y => 8, Special => None, The_Name => Bom),
    (Pageid => Egg2_Page, X => 2,  Y => 9, Special => None, The_Name => Bom),
    (Pageid => Egg2_Page, X => 15, Y => 3, Special => None, The_Name => Bom),
    (Pageid => Egg2_Page, X => 15, Y => 4, Special => None, The_Name => Bom),
    (Pageid => Egg2_Page, X => 15, Y => 5, Special => None, The_Name => Bom),

    (Pageid => Egg3_Page, X => 2,  Y => 3, Special => None, The_Name => MandMs1),
    (Pageid => Egg3_Page, X => 2,  Y => 4, Special => None, The_Name => MandMs2),
    (Pageid => Egg3_Page, X => 2,  Y => 5, Special => None, The_Name => MandMs3),
    (Pageid => Egg3_Page, X => 2,  Y => 6, Special => None, The_Name => MandMs4),
    (Pageid => Egg3_Page, X => 2,  Y => 7, Special => None, The_Name => MandMs5),
    (Pageid => Egg3_Page, X => 2,  Y => 8, Special => None, The_Name => MandMs6),
    (Pageid => Egg3_Page, X => 2,  Y => 9, Special => None, The_Name => MandMs7),
    (Pageid => Egg3_Page, X => 14, Y => 3, Special => None, The_Name => MandMs8),
    (Pageid => Egg3_Page, X => 14, Y => 4, Special => None, The_Name => MandMs9),
    (Pageid => Egg3_Page, X => 14, Y => 5, Special => None, The_Name => MandMs10),
    (Pageid => Egg3_Page, X => 14, Y => 6, Special => None, The_Name => MandMs11),
    (Pageid => Egg3_Page, X => 14, Y => 7, Special => None, The_Name => Bom),

    (Pageid => Egg4_Page, X => 2,  Y => 3, Special => None, The_Name => Corn1),
    (Pageid => Egg4_Page, X => 2,  Y => 4, Special => None, The_Name => Corn2),
    (Pageid => Egg4_Page, X => 2,  Y => 5, Special => None, The_Name => Corn3),
    (Pageid => Egg4_Page, X => 2,  Y => 6, Special => None, The_Name => Corn4),
    (Pageid => Egg4_Page, X => 2,  Y => 7, Special => None, The_Name => Corn5),
    (Pageid => Egg4_Page, X => 2,  Y => 8, Special => None, The_Name => Corn6),
    (Pageid => Egg4_Page, X => 2,  Y => 9, Special => None, The_Name => Corn7),
    (Pageid => Egg4_Page, X => 14, Y => 3, Special => None, The_Name => Corn8),
    (Pageid => Egg4_Page, X => 14, Y => 4, Special => None, The_Name => Corn9),
    (Pageid => Egg4_Page, X => 14, Y => 5, Special => None, The_Name => Corn10),
    (Pageid => Egg4_Page, X => 14, Y => 6, Special => None, The_Name => Corn11),
    (Pageid => Egg4_Page, X => 14, Y => 7, Special => None, The_Name => Bom),

    (Pageid => Egg1_Page, X => 2,  Y => 3, Special => None, The_Name => Bom),
    (Pageid => Egg1_Page, X => 8,  Y => 3, Special => None, The_Name => Bom),
    (Pageid => Egg1_Page, X => 8,  Y => 4, Special => None, The_Name => Eee),
    (Pageid => Egg1_Page, X => 2,  Y => 5, Special => None, The_Name => Bom),
    (Pageid => Egg1_Page, X => 8,  Y => 5, Special => None, The_Name => Bom),
    (Pageid => Egg1_Page, X => 8,  Y => 6, Special => None, The_Name => Bom),
    (Pageid => Egg1_Page, X => 8,  Y => 7, Special => None, The_Name => Bom),
    (Pageid => Egg1_Page, X => 17, Y => 3, Special => None, The_Name => My_stat),
    (Pageid => Egg1_Page, X => 18, Y => 5, Special => None, The_Name => My_bit),
    (Pageid => Egg1_Page, X => 20, Y => 7, Special => None, The_Name => Bom),
    (Pageid => Egg1_Page, X => 17, Y => 9, Special => None, The_Name => My_Keys),

    (Pageid => Gaslit1_Page, X => 2,  Y => 3, Special => None, The_Name => Bom),
    (Pageid => Gaslit1_Page, X => 13, Y => 3, Special => None, The_Name => Bom),

    (Pageid  => Gaslit1_Page,
     X       => 2,
     Y       => 4,
     Special => None,
     The_Name => Bom),

    (Pageid  => Gaslit1_Page,
     X       => 2,
     Y       => 5,
     Special => None,
     The_Name => Bom),

    (Pageid  => Gaslit1_Page,
     X       => 2,
     Y       => 6,
     Special => None,
     The_Name => Bom),

    (Pageid  => Gaslit1_Page,
     X       => 2,
     Y       => 7,
     Special => None,
     The_Name => Bom),

    (Pageid  => Gaslit1_Page,
     X       => 3,
     Y       => 8,
     Special => None,
     The_Name => Bom),

    (Pageid => Gaslit1_Page, X => 21, Y => 9, Special => None, The_Name => Bom),

    (Pageid  => Gaslit2_Page,
     X       => 2,
     Y       => 3,
     Special => None,
     The_Name => Bom),

    (Pageid => Gaslit2_Page, X => 21, Y => 9, Special => None, The_Name => Bom),

    (Pageid  => Gaslit3_Page,
     X       => 2,
     Y       => 3,
     Special => None,
     The_Name => Bom),

    (Pageid => Gaslit3_Page, X => 21, Y => 9, Special => None, The_Name => Bom),

    (Pageid => Gaslit4_Page, X => 2,  Y => 3, Special => None, The_Name => Bom),
    (Pageid => Gaslit4_Page, X => 10, Y => 3, Special => None, The_Name => Bom),
    (Pageid => Gaslit4_Page, X => 13, Y => 3, Special => None, The_Name => Bom),
    (Pageid => Gaslit4_Page, X => 21, Y => 9, Special => None, The_Name => Bom),

    (Pageid => Gaslit5_Page, X => 2,  Y => 3, Special => None, The_Name => Bom),
    (Pageid => Gaslit5_Page, X => 7,  Y => 3, Special => None, The_Name => Bom),
    (Pageid => Gaslit5_Page, X => 10, Y => 3, Special => None, The_Name => Bom),
    (Pageid => Gaslit5_Page, X => 21, Y => 9, Special => None, The_Name => Bom),

    (Pageid => Egg1_Page, X => 2,  Y => 3, Special => None,  The_Name => Bom),
    (Pageid => Egg1_Page, X => 6,  Y => 3, Special => Minus, The_Name => None),
    (Pageid => Egg1_Page, X => 7,  Y => 3, Special => None,  The_Name => Bom),
    (Pageid => Egg1_Page, X => 2,  Y => 7, Special => None,  The_Name => Bom),
    (Pageid => Egg1_Page, X => 2,  Y => 9, Special => None,  The_Name => Bom),
    (Pageid => Egg1_Page, X => 21, Y => 9, Special => None,  The_Name => Bom),

    (Pageid => Egg1_Page, X => 2,  Y => 4, Special => None, The_Name => Bom),
    (Pageid => Egg1_Page, X => 2,  Y => 5, Special => None, The_Name => Bom),
    (Pageid => Egg1_Page, X => 2,  Y => 6, Special => None, The_Name => Bom),
    (Pageid => Egg1_Page, X => 2,  Y => 7, Special => None, The_Name => Bom),
    (Pageid => Egg1_Page, X => 2,  Y => 8, Special => None, The_Name => Bom),
    (Pageid => Egg1_Page, X => 2,  Y => 9, Special => None, The_Name => Bom),
    (Pageid => Egg1_Page, X => 14, Y => 3, Special => None, The_Name => Bom),
    (Pageid => Egg1_Page, X => 14, Y => 5, Special => None, The_Name => Bom),
    (Pageid => Egg1_Page, X => 14, Y => 6, Special => None, The_Name => Bom),
    (Pageid => Egg1_Page, X => 14, Y => 7, Special => None, The_Name => Bom),
    (Pageid => Egg1_Page, X => 14, Y => 8, Special => None, The_Name => Bom),
    (Pageid => Egg1_Page, X => 21, Y => 9, Special => None, The_Name => Bom),

    (Pageid => Egg1_Page, X => 2,  Y => 3, Special => None, The_Name => Bom),
    (Pageid => Egg1_Page, X => 2,  Y => 4, Special => Four, The_Name => None),
    (Pageid => Egg1_Page, X => 3,  Y => 4, Special => None, The_Name => Bom),
    (Pageid => Egg1_Page, X => 2,  Y => 5, Special => None, The_Name => Bom),
    (Pageid => Egg1_Page, X => 2,  Y => 7, Special => None, The_Name => Bom),

    (Pageid  => Egg1_Page,
     X       => 2,
     Y       => 8,
     Special => None,
     The_Name => Bom),

    (Pageid => Egg1_Page, X => 13, Y => 3, Special => None, The_Name => Bom),
    (Pageid => Egg1_Page, X => 13, Y => 4, Special => None, The_Name => Bom),
    (Pageid => Egg1_Page, X => 13, Y => 5, Special => None, The_Name => Bom),
    (Pageid => Egg1_Page, X => 21, Y => 9, Special => None, The_Name => Bom),

    (Pageid => Egg1_Page, X => 2,  Y => 3, Special => None, The_Name => Bom),
    (Pageid => Egg1_Page, X => 2,  Y => 7, Special => None, The_Name => Bom),
    (Pageid => Egg1_Page, X => 16, Y => 3, Special => None, The_Name => Bom),
    (Pageid => Egg1_Page, X => 16, Y => 5, Special => None, The_Name => Bom),
    (Pageid => Egg1_Page, X => 16, Y => 7, Special => None, The_Name => Bom),

    (Pageid => Egg1_Page, X => 2,  Y => 3, Special => None, The_Name => Bom),
    (Pageid => Egg1_Page, X => 2,  Y => 5, Special => None, The_Name => Bom),
    (Pageid => Egg1_Page, X => 2,  Y => 7, Special => None, The_Name => Bom),
    (Pageid => Egg1_Page, X => 2,  Y => 9, Special => None, The_Name => Bom),
    (Pageid => Egg1_Page, X => 17, Y => 3, Special => None, The_Name => Bom),
    (Pageid => Egg1_Page, X => 18, Y => 5, Special => None, The_Name => Bom),

    (Pageid => Egg1_Page, X => 2,  Y => 3, Special => None,  The_Name => Mode),
    (Pageid => Egg1_Page, X => 6,  Y => 3, Special => Colon, The_Name => None),
    (Pageid => Egg1_Page, X => 18, Y => 3, Special => None,  The_Name => Bom),
    (Pageid => Egg1_Page, X => 10, Y => 4, Special => None,  The_Name => Bom),
    (Pageid => Egg1_Page, X => 10, Y => 5, Special => None,  The_Name => Bom),
    (Pageid => Egg1_Page, X => 10, Y => 6, Special => None,  The_Name => Bom),
    (Pageid => Egg1_Page, X => 2,  Y => 5, Special => None,  The_Name => Bom),
    (Pageid => Egg1_Page, X => 2,  Y => 9, Special => None,  The_Name => Bom),
    (Pageid => Egg1_Page, X => 10, Y => 7, Special => None,  The_Name => Bom),
    (Pageid => Egg1_Page, X => 10, Y => 8, Special => None,  The_Name => Bom),
    (Pageid => Egg1_Page, X => 10, Y => 9, Special => None,  The_Name => Bom),

    (Pageid => Egg1_Page, X => 2,  Y => 3, Special => None,  The_Name => Bom),
    (Pageid => Egg1_Page, X => 2,  Y => 5, Special => None,  The_Name => Bom),
    (Pageid => Egg1_Page, X => 2,  Y => 7, Special => None,  The_Name => Bom),
    (Pageid => Egg1_Page, X => 2,  Y => 9, Special => None,  The_Name => Bom),
    (Pageid => Egg1_Page, X => 14, Y => 5, Special => None,  The_Name => Bom),
    (Pageid => Egg1_Page, X => 17, Y => 7, Special => None,  The_Name => Bom),
    (Pageid => Egg1_Page, X => 18, Y => 9, Special => None,  The_Name => Bom),

    (Pageid => Egg1_Page, X => 15, Y => 4,  Special => None,  The_Name => Bom),
    (Pageid => Egg1_Page, X => 19, Y => 4,  Special => Colon, The_Name => Bom),
    (Pageid => Egg1_Page, X => 1,  Y => 6,  Special => None,  The_Name => Bom),
    (Pageid => Egg1_Page, X => 4,  Y => 6,  Special => Colon, The_Name => None),
    (Pageid => Egg1_Page, X => 1,  Y => 7,  Special => None,  The_Name => Bom),
    (Pageid => Egg1_Page, X => 4,  Y => 7,  Special => Colon, The_Name => None),
    (Pageid => Egg1_Page, X => 1,  Y => 8,  Special => None,  The_Name => Bom),
    (Pageid => Egg1_Page, X => 4,  Y => 8,  Special => Colon, The_Name => None),
    (Pageid => Egg1_Page, X => 1,  Y => 9,  Special => None,  The_Name => Bom),
    (Pageid => Egg1_Page, X => 4,  Y => 9,  Special => Colon, The_Name => None),
    (Pageid => Egg1_Page, X => 1,  Y => 10, Special => None,  The_Name => Bom),
    (Pageid => Egg1_Page, X => 4,  Y => 10, Special => Colon, The_Name => None),

    (Pageid => Egg1_Page, X => 2,  Y => 3, Special => None,  The_Name => Bom),
    (Pageid => Egg1_Page, X => 18, Y => 3, Special => None,  The_Name => Bom),
    (Pageid => Egg1_Page, X => 19, Y => 5, Special => None,  The_Name => Bom),
    (Pageid => Egg1_Page, X => 21, Y => 7, Special => None,  The_Name => Bom),
    (Pageid => Egg1_Page, X => 21, Y => 9, Special => None,  The_Name => Bom),
    (Pageid => Egg1_Page, X => 4,  Y => 8, Special => None,  The_Name => Bom),
    (Pageid => Egg1_Page, X => 5,  Y => 8, Special => Equal, The_Name => None),

    (Pageid => Egg1_Page, X => 2,  Y => 3, Special => None,  The_Name => Bom),
    (Pageid => Egg1_Page, X => 20, Y => 3, Special => None,  The_Name => Bom),
    (Pageid => Egg1_Page, X => 21, Y => 7, Special => None,  The_Name => Bom),
    (Pageid => Egg1_Page, X => 4,  Y => 8, Special => None,  The_Name => Bom),
    (Pageid => Egg1_Page, X => 5,  Y => 8, Special => Equal, The_Name => None),
    (Pageid => Egg1_Page, X => 21, Y => 9, Special => None,  The_Name => Bom),

    (Pageid => Egg1_Page, X => 1, Y => 1, Special => None, The_Name => None),

    (Pageid  => Egg1_Page,
     X       => 2,
     Y       => 3,
     Special => None,
     The_Name => Bom),

    (Pageid => Egg1_Page, X => 2,  Y => 5, Special => None,  The_Name => Bom),
    (Pageid => Egg1_Page, X => 7,  Y => 5, Special => Colon, The_Name => None),
    (Pageid => Egg1_Page, X => 2,  Y => 7, Special => None,  The_Name => Bom),
    (Pageid => Egg1_Page, X => 7,  Y => 7, Special => Colon, The_Name => None),
    (Pageid => Egg1_Page, X => 15, Y => 5, Special => None,  The_Name => Bom),
    (Pageid => Egg1_Page, X => 23, Y => 5, Special => Colon, The_Name => None),
    (Pageid => Egg1_Page, X => 2,  Y => 9, Special => None,  The_Name => Bom),
    (Pageid => Egg1_Page, X => 5,  Y => 9, Special => Colon, The_Name => None),
    (Pageid => Egg1_Page, X => 14, Y => 9, Special => None,  The_Name => Bom),
    (Pageid => Egg1_Page, X => 17, Y => 9, Special => Colon, The_Name => None),

    (Pageid => Egg1_Page, X => 2, Y => 8, Special => None, The_Name => Bom),
    (Pageid => Egg1_Page, X => 2, Y => 9, Special => None, The_Name => Bom),

    (Pageid => Egg1_Page, X => 2,  Y => 4, Special => None, The_Name => Bom),
    (Pageid => Egg1_Page, X => 2,  Y => 5, Special => None, The_Name => Bom),
    (Pageid => Egg1_Page, X => 2,  Y => 6, Special => None, The_Name => Bom),
    (Pageid => Egg1_Page, X => 2,  Y => 9, Special => None, The_Name => Bom),
    (Pageid => Egg1_Page, X => 12, Y => 5, Special => None, The_Name => Bom),
    (Pageid => Egg1_Page, X => 12, Y => 6, Special => None, The_Name => Bom),
    (Pageid => Egg1_Page, X => 13, Y => 8, Special => None, The_Name => Bom),

    (Pageid => Egg1_Page, X => 2,  Y => 5, Special => None,  The_Name => Bom),
    (Pageid => Egg1_Page, X => 19, Y => 5, Special => Slash, The_Name => Bom),
    (Pageid => Egg1_Page, X => 2,  Y => 7, Special => None,  The_Name => Bom),
    (Pageid => Egg1_Page, X => 15, Y => 7, Special => None,  The_Name => Bom),
    (Pageid => Egg1_Page, X => 5,  Y => 9, Special => Slash, The_Name => None),
    (Pageid => Egg1_Page, X => 19, Y => 9, Special => Slash, The_Name => None),

    (Pageid => Egg1_Page, X => 2,  Y => 9, Special => None, The_Name => Bom),
    (Pageid => Egg1_Page, X => 15, Y => 4, Special => None, The_Name => Bom),
    (Pageid => Egg1_Page, X => 16, Y => 5, Special => None, The_Name => Bom),
    (Pageid => Egg1_Page, X => 23, Y => 7, Special => None, The_Name => Bom),
    (Pageid => Egg1_Page, X => 15, Y => 9, Special => None, The_Name => Bom),

    (Pageid => Egg1_Page, X => 8,  Y => 4, Special => None, The_Name => Bom),
    (Pageid => Egg1_Page, X => 8,  Y => 6, Special => None, The_Name => Bom),
    (Pageid => Egg1_Page, X => 17, Y => 9, Special => None, The_Name => Bom),

    (Pageid  => Egg1_Page,
     X       => 2,
     Y       => 5,
     Special => None,
     The_Name => Bom),

    (Pageid => Egg1_Page, X => 18, Y => 5, Special => None, The_Name => Bom),
    (Pageid => Egg1_Page, X => 17, Y => 7, Special => None, The_Name => Bom),
    (Pageid => Egg1_Page, X => 16, Y => 8, Special => None, The_Name => Bom),
    (Pageid => Egg1_Page, X => 17, Y => 9, Special => None, The_Name => Bom),

    (Pageid => Egg1_Page, X => 2,  Y => 3, Special => None, The_Name => Bom),
    (Pageid => Egg1_Page, X => 2,  Y => 4, Special => None, The_Name => Bom),
    (Pageid => Egg1_Page, X => 2,  Y => 5, Special => None, The_Name => Bom),
    (Pageid => Egg1_Page, X => 2,  Y => 6, Special => None, The_Name => Bom),
    (Pageid => Egg1_Page, X => 2,  Y => 7, Special => None, The_Name => Bom),
    (Pageid => Egg1_Page, X => 2,  Y => 8, Special => None, The_Name => Bom),
    (Pageid => Egg1_Page, X => 2,  Y => 9, Special => None, The_Name => Bom),
    (Pageid => Egg1_Page, X => 16, Y => 3, Special => None, The_Name => Bom),

    (Pageid => Egg2_Page, X => 2,  Y => 3, Special => None, The_Name => Bom),
    (Pageid => Egg2_Page, X => 2,  Y => 5, Special => None, The_Name => Bom),
    (Pageid => Egg2_Page, X => 2,  Y => 7, Special => None, The_Name => Bom),
    (Pageid => Egg2_Page, X => 2,  Y => 9, Special => None, The_Name => Bom),
    (Pageid => Egg2_Page, X => 18, Y => 3, Special => None, The_Name => Bom),

    (Pageid => Egg2_Page, X => 2,  Y => 3, Special => None, The_Name => Bom),
    (Pageid => Egg2_Page, X => 2,  Y => 5, Special => None, The_Name => Bom),
    (Pageid => Egg2_Page, X => 2,  Y => 6, Special => None, The_Name => Bom),
    (Pageid => Egg2_Page, X => 2,  Y => 7, Special => None, The_Name => Bom),
    (Pageid => Egg2_Page, X => 2,  Y => 8, Special => None, The_Name => Bom),
    (Pageid => Egg2_Page, X => 2,  Y => 9, Special => None, The_Name => Bom),
    (Pageid => Egg2_Page, X => 17, Y => 3, Special => None, The_Name => Bom),
    (Pageid => Egg2_Page, X => 20, Y => 9, Special => None, The_Name => Bom),

    (Pageid => Egg2_Page, X => 17, Y => 5, Special => None, The_Name => Bom),
    (Pageid => Egg2_Page, X => 19, Y => 9, Special => None, The_Name => Bom),
    (Pageid => Egg2_Page, X => 2,  Y => 4, Special => None, The_Name => Bom),
    (Pageid => Egg2_Page, X => 7,  Y => 4, Special => None, The_Name => Bom),
    (Pageid => Egg2_Page, X => 13, Y => 4, Special => None, The_Name => Bom),

    (Pageid => Egg2_Page, X => 17, Y => 5, Special => None, The_Name => Bom),
    (Pageid => Egg2_Page, X => 19, Y => 9, Special => None, The_Name => Bom),

    (Pageid => Egg2_Page, X => 20, Y => 3, Special => None, The_Name => Bom),
    (Pageid => Egg2_Page, X => 2,  Y => 4, Special => None, The_Name => Bom),
    (Pageid => Egg2_Page, X => 12, Y => 4, Special => None, The_Name => Bom),
    (Pageid => Egg2_Page, X => 20, Y => 4, Special => None, The_Name => Bom),

    (Pageid => Egg2_Page, X => 1, Y => 1, Special => None, The_Name => None),

    (Pageid => Cobtest1_Page, X => 2,  Y => 3, Special => None,  The_Name => Bom),
    (Pageid => Cobtest1_Page, X => 8,  Y => 3, Special => Colon, The_Name => None),
    (Pageid => Cobtest1_Page, X => 2,  Y => 4, Special => None,  The_Name => Bom),
    (Pageid => Cobtest1_Page, X => 8,  Y => 4, Special => Colon, The_Name => None),
    (Pageid => Cobtest1_Page, X => 2,  Y => 5, Special => None,  The_Name => Bom),
    (Pageid => Cobtest1_Page, X => 8,  Y => 5, Special => Colon, The_Name => None),
    (Pageid => Cobtest1_Page, X => 2,  Y => 6, Special => None,  The_Name => Bom),
    (Pageid => Cobtest1_Page, X => 8,  Y => 6, Special => Colon, The_Name => None),
    (Pageid => Cobtest1_Page, X => 13, Y => 3, Special => None,  The_Name => Bom),
    (Pageid => Cobtest1_Page, X => 19, Y => 3, Special => Slash, The_Name => None),
    (Pageid => Cobtest1_Page, X => 20, Y => 3, Special => None,  The_Name => Bom),
    (Pageid => Cobtest1_Page, X => 21, Y => 3, Special => Colon, The_Name => None),

    (Pageid  => Cobtest1_Page,
     X       => 13,
     Y       => 4,
     Special => None,
     The_Name => Bom),

    (Pageid => Cobtest1_Page, X => 18, Y => 4, Special => None,  The_Name => Bom),
    (Pageid => Cobtest1_Page, X => 21, Y => 4, Special => Colon, The_Name => None),
    (Pageid => Cobtest1_Page, X => 2,  Y => 9, Special => None,  The_Name => Bom),
    (Pageid => Cobtest1_Page, X => 19, Y => 5, Special => None,  The_Name => Bom),
    (Pageid => Cobtest1_Page, X => 11, Y => 7, Special => None,  The_Name => Bom),
    (Pageid => Cobtest1_Page, X => 17, Y => 9, Special => None,  The_Name => Bom),

    (Pageid  => Cobtest2_Page,
     X       => 2,
     Y       => 3,
     Special => None,
     The_Name => Bom),

    (Pageid => Cobtest2_Page, X => 2,  Y => 5, Special => None, The_Name => Bom),
    (Pageid => Cobtest2_Page, X => 10, Y => 5, Special => None, The_Name => Bom),

    (Pageid => Cobtest1_Page, X => 2,  Y => 3, Special => None, The_Name => Bom),
    (Pageid => Cobtest1_Page, X => 2,  Y => 5, Special => None, The_Name => Bom),
    (Pageid => Cobtest1_Page, X => 2,  Y => 7, Special => None, The_Name => Cob),
    (Pageid => Cobtest1_Page, X => 18, Y => 3, Special => None, The_Name => Ddd),
    (Pageid => Cobtest1_Page, X => 17, Y => 5, Special => None, The_Name => Bom),

    (Pageid  => Cobtest1_Page,
     X       => 18,
     Y       => 7,
     Special => None,
     The_Name => Bom),


    (Pageid => Cobtest1_Page, X => 2,  Y => 3, Special => None, The_Name => Bom),
    (Pageid => Cobtest1_Page, X => 2,  Y => 5, Special => None, The_Name => Bom),
    (Pageid => Cobtest1_Page, X => 2,  Y => 7, Special => None, The_Name => Bom),
    (Pageid => Cobtest1_Page, X => 2,  Y => 9, Special => None, The_Name => Bom),
    (Pageid => Cobtest1_Page, X => 17, Y => 9, Special => None, The_Name => Bom),

    (Pageid => Cobtest1_Page, X => 2,  Y => 3, Special => None, The_Name => Bom),
    (Pageid => Cobtest1_Page, X => 2,  Y => 5, Special => None, The_Name => Bom),
    (Pageid => Cobtest1_Page, X => 2,  Y => 7, Special => None, The_Name => Bom),
    (Pageid => Cobtest1_Page, X => 2,  Y => 9, Special => None, The_Name => Bom),
    (Pageid => Cobtest1_Page, X => 18, Y => 3, Special => None, The_Name => Bom),
    (Pageid => Cobtest1_Page, X => 18, Y => 4, Special => None, The_Name => Bom),
    (Pageid => Cobtest1_Page, X => 19, Y => 5, Special => None, The_Name => Ddd),
    (Pageid => Cobtest1_Page, X => 19, Y => 6, Special => None, The_Name => Cob),
    (Pageid => Cobtest1_Page, X => 19, Y => 7, Special => None, The_Name => Bom),
    (Pageid => Cobtest1_Page, X => 19, Y => 8, Special => None, The_Name => Bom),

    (Pageid => Cobtest2_Page, X => 2,  Y => 3, Special => None,  The_Name => Bom),
    (Pageid => Cobtest2_Page, X => 2,  Y => 5, Special => None,  The_Name => Bom),
    (Pageid => Cobtest2_Page, X => 2,  Y => 7, Special => None,  The_Name => Bom),
    (Pageid => Cobtest2_Page, X => 2,  Y => 8, Special => None,  The_Name => Bom),
    (Pageid => Cobtest2_Page, X => 17, Y => 3, Special => None,  The_Name => Bom),
    (Pageid => Cobtest2_Page, X => 17, Y => 4, Special => None,  The_Name => Bom),
    (Pageid => Cobtest2_Page, X => 17, Y => 5, Special => None,  The_Name => Bom),
    (Pageid => Cobtest2_Page, X => 17, Y => 6, Special => None,  The_Name => Bom),
    (Pageid => Cobtest2_Page, X => 21, Y => 8, Special => None,  The_Name => Bom),
    (Pageid => Cobtest2_Page, X => 22, Y => 9, Special => None,  The_Name => Bom),

    (Pageid => Cobtest2_Page, X => 2,  Y => 3, Special => None, The_Name => Bom),
    (Pageid => Cobtest2_Page, X => 2,  Y => 5, Special => None, The_Name => Bom),
    (Pageid => Cobtest2_Page, X => 2,  Y => 7, Special => None, The_Name => Bom),
    (Pageid => Cobtest2_Page, X => 18, Y => 3, Special => None, The_Name => Bom),
    (Pageid => Cobtest2_Page, X => 18, Y => 5, Special => None, The_Name => Bom),
    (Pageid => Cobtest2_Page, X => 19, Y => 7, Special => None, The_Name => Ddd),

    (Pageid => Cobtest2_Page, X => 2,  Y => 3, Special => None, The_Name => Bom),
    (Pageid => Cobtest2_Page, X => 2,  Y => 5, Special => None, The_Name => Bom),
    (Pageid => Cobtest2_Page, X => 2,  Y => 7, Special => None, The_Name => Bom),
    (Pageid => Cobtest2_Page, X => 2,  Y => 9, Special => None, The_Name => Bom),
    (Pageid => Cobtest2_Page, X => 19, Y => 3, Special => None, The_Name => Bom),
    (Pageid => Cobtest2_Page, X => 20, Y => 5, Special => None, The_Name => Bom),
    (Pageid => Cobtest2_Page, X => 19, Y => 7, Special => None, The_Name => Bom),
    (Pageid => Cobtest2_Page, X => 19, Y => 9, Special => None, The_Name => Bom),

    (Pageid => Cobtest2_Page, X => 2,  Y => 3, Special => None, The_Name => Ddd),
    (Pageid => Cobtest2_Page, X => 2,  Y => 5, Special => None, The_Name => Bom),
    (Pageid => Cobtest2_Page, X => 2,  Y => 9, Special => None, The_Name => Bom),
    (Pageid => Cobtest2_Page, X => 20, Y => 3, Special => None, The_Name => Bom),
    (Pageid => Cobtest2_Page, X => 17, Y => 5, Special => None, The_Name => Bom),
    (Pageid => Cobtest2_Page, X => 19, Y => 9, Special => None, The_Name => Bom),

    (Pageid => Cobtest2_Page, X => 2,  Y => 3, Special => None, The_Name => Bom),

    (Pageid => Cobtest1_Page, X => 2, Y => 3, Special => None, The_Name => Cob),
    (Pageid => Cobtest1_Page, X => 6, Y => 3, Special => None, The_Name => Bom),
    (Pageid => Cobtest1_Page, X => 2, Y => 5, Special => None, The_Name => Cob),
    (Pageid => Cobtest1_Page, X => 6, Y => 5, Special => None, The_Name => Bom),
    (Pageid => Cobtest1_Page, X => 2, Y => 7, Special => None, The_Name => Ddd),

    (Pageid => Cobtest2_Page, X => 2, Y => 3, Special => None, The_Name => Bom),
    (Pageid => Cobtest2_Page, X => 2, Y => 5, Special => None, The_Name => Bom),
    (Pageid => Cobtest2_Page, X => 6, Y => 5, Special => None, The_Name => Bom),
    (Pageid => Cobtest2_Page, X => 2, Y => 7, Special => None, The_Name => Bom),

    (Pageid => Cobtest2_Page, X => 2, Y => 3, Special => None, The_Name => Bom),

    (Pageid => Egg1_Page, X => 0, Y => 0, Special => None, The_Name => None),

    (Pageid => Egg1_Page, X => 2,  Y => 3, Special => None,  The_Name => Bom),
    (Pageid => Egg1_Page, X => 4,  Y => 3, Special => Colon, The_Name => None),

    (Pageid => Cobtest2_Page, X => 2,  Y => 3, Special => None,  The_Name => Bom),
    (Pageid => Cobtest2_Page, X => 7,  Y => 3, Special => Colon, The_Name => None),
    (Pageid => Cobtest2_Page, X => 2,  Y => 5, Special => None,  The_Name => Bom),
    (Pageid => Cobtest2_Page, X => 7,  Y => 5, Special => Colon, The_Name => None),
    (Pageid => Cobtest2_Page, X => 18, Y => 3, Special => None,  The_Name => Bom),
    (Pageid => Cobtest2_Page, X => 20, Y => 3, Special => Colon, The_Name => None),
    (Pageid => Cobtest2_Page, X => 14, Y => 5, Special => None,  The_Name => Bom),
    (Pageid => Cobtest2_Page, X => 23, Y => 5, Special => Colon, The_Name => None),
    (Pageid => Cobtest2_Page, X => 2,  Y => 7, Special => None,  The_Name => Bom),
    (Pageid => Cobtest2_Page, X => 6,  Y => 7, Special => Colon, The_Name => None),
    (Pageid => Cobtest2_Page, X => 17, Y => 7, Special => None,  The_Name => Bom),
    (Pageid => Cobtest2_Page, X => 23, Y => 7, Special => Colon, The_Name => None),
    (Pageid => Cobtest2_Page, X => 2,  Y => 9, Special => None,  The_Name => Bom),
    (Pageid => Cobtest2_Page, X => 6,  Y => 9, Special => Colon, The_Name => None),

    (Pageid => Cobtest2_Page, X => 17, Y => 5, Special => None,  The_Name => Bom),
    (Pageid => Cobtest2_Page, X => 19, Y => 5, Special => Slash, The_Name => None),
    (Pageid => Cobtest2_Page, X => 20, Y => 5, Special => None,  The_Name => Bom),
    (Pageid => Cobtest2_Page, X => 23, Y => 5, Special => Colon, The_Name => None),
    (Pageid => Cobtest2_Page, X => 19, Y => 6, Special => Slash, The_Name => None),

    (Pageid => Cobtest2_Page, X => 2, Y => 6, Special => None, The_Name => Bom),
    (Pageid => Cobtest2_Page, X => 2, Y => 7, Special => None, The_Name => Bom),
    (Pageid => Cobtest2_Page, X => 2, Y => 8, Special => None, The_Name => Bom),
    (Pageid => Cobtest2_Page, X => 2, Y => 9, Special => None, The_Name => Bom),

    (Pageid => Cobtest2_Page, X => 0, Y => 0, Special => None, The_Name => None),

    (Pageid => Cobtest2_Page, X => 2,  Y => 3, Special => None, The_Name => Bom),
    (Pageid => Cobtest2_Page, X => 2,  Y => 5, Special => None, The_Name => Bom),
    (Pageid => Cobtest2_Page, X => 16, Y => 3, Special => None, The_Name => Bom),
    (Pageid => Cobtest2_Page, X => 17, Y => 5, Special => None, The_Name => Bom),

    (Pageid => Cobtest2_Page, X => 2,  Y => 5, Special => None,  The_Name => Bom),
    (Pageid => Cobtest2_Page, X => 4,  Y => 5, Special => Colon, The_Name => None),
    (Pageid => Cobtest2_Page, X => 20, Y => 5, Special => None,  The_Name => Bom),
    (Pageid => Cobtest2_Page, X => 13, Y => 8, Special => None,  The_Name => Bom),

    (Pageid => Cobtest2_Page, X => 2,  Y => 3, Special => None,  The_Name => Bom),
    (Pageid => Cobtest2_Page, X => 7,  Y => 3, Special => Colon, The_Name => None),
    (Pageid => Cobtest2_Page, X => 17, Y => 3, Special => None,  The_Name => Bom),
    (Pageid => Cobtest2_Page, X => 2,  Y => 5, Special => None,  The_Name => Bom),
    (Pageid => Cobtest2_Page, X => 7,  Y => 5, Special => Colon, The_Name => None),
    (Pageid => Cobtest2_Page, X => 14, Y => 5, Special => None,  The_Name => Bom),
    (Pageid => Cobtest2_Page, X => 23, Y => 5, Special => Colon, The_Name => None),
    (Pageid => Cobtest2_Page, X => 2,  Y => 7, Special => None,  The_Name => Bom),
    (Pageid => Cobtest2_Page, X => 6,  Y => 7, Special => Colon, The_Name => None),
    (Pageid => Cobtest2_Page, X => 17, Y => 7, Special => None,  The_Name => Bom),
    (Pageid => Cobtest2_Page, X => 23, Y => 7, Special => Colon, The_Name => None),
    (Pageid => Cobtest2_Page, X => 2,  Y => 9, Special => None,  The_Name => Bom),
    (Pageid => Cobtest2_Page, X => 6,  Y => 9, Special => Colon, The_Name => None),

    (Pageid => Egg3_Page, X => 2,  Y => 3, Special => None, The_Name => Bom),
    (Pageid => Egg3_Page, X => 2,  Y => 4, Special => None, The_Name => Bom),
    (Pageid => Egg3_Page, X => 10, Y => 4, Special => None, The_Name => Bom),
    (Pageid => Egg3_Page, X => 15, Y => 4, Special => None, The_Name => Bom),
    (Pageid => Egg3_Page, X => 20, Y => 3, Special => None, The_Name => Bom),
    (Pageid => Egg3_Page, X => 19, Y => 7, Special => None, The_Name => Bom),
    (Pageid => Egg3_Page, X => 2,  Y => 7, Special => None, The_Name => Bom),
    (Pageid => Egg3_Page, X => 2,  Y => 9, Special => None, The_Name => Bom),

    (Pageid => Egg3_Page, X => 2,  Y => 3, Special => None, The_Name => Bom),
    (Pageid => Egg3_Page, X => 2,  Y => 5, Special => None, The_Name => Bom),
    (Pageid => Egg3_Page, X => 2,  Y => 7, Special => None, The_Name => Bom),
    (Pageid => Egg3_Page, X => 19, Y => 3, Special => None, The_Name => Bom),
    (Pageid => Egg3_Page, X => 19, Y => 5, Special => None, The_Name => Bom),
    (Pageid => Egg3_Page, X => 19, Y => 9, Special => None, The_Name => Bom),

    (Pageid => Egg3_Page, X => 2,  Y => 3, Special => None, The_Name => Bom),
    (Pageid => Egg3_Page, X => 12, Y => 3, Special => None, The_Name => Bom),
    (Pageid => Egg3_Page, X => 18, Y => 3, Special => None, The_Name => Bom),
    (Pageid => Egg3_Page, X => 19, Y => 9, Special => None, The_Name => Bom),

    (Pageid => Egg3_Page, X => 1,  Y => 3, Special => None, The_Name => Bom),
    (Pageid => Egg3_Page, X => 10, Y => 3, Special => None, The_Name => Bom),
    (Pageid => Egg3_Page, X => 19, Y => 3, Special => None, The_Name => Bom),
    (Pageid => Egg3_Page, X => 19, Y => 9, Special => None, The_Name => Bom),

    (Pageid => Egg2_Page, X => 7,  Y => 3, Special => None,  The_Name => Bom),
    (Pageid => Egg2_Page, X => 4,  Y => 5, Special => None,  The_Name => Bom),
    (Pageid => Egg2_Page, X => 15, Y => 5, Special => None,  The_Name => Bom),
    (Pageid => Egg2_Page, X => 17, Y => 5, Special => Slash, The_Name => None),
    (Pageid => Egg2_Page, X => 18, Y => 5, Special => None,  The_Name => Bom),
    (Pageid => Egg2_Page, X => 4,  Y => 7, Special => None,  The_Name => Bom),
    (Pageid => Egg2_Page, X => 15, Y => 7, Special => None,  The_Name => Bom),
    (Pageid => Egg2_Page, X => 17, Y => 7, Special => Slash, The_Name => None),
    (Pageid => Egg2_Page, X => 18, Y => 7, Special => None,  The_Name => Bom),
    (Pageid => Egg2_Page, X => 19, Y => 9, Special => None,  The_Name => Bom),

    (Pageid => Egg1_Page, X => 2,  Y => 3, Special => None, The_Name => Bom),
    (Pageid => Egg1_Page, X => 12, Y => 3, Special => None, The_Name => Bom),
    (Pageid => Egg1_Page, X => 17, Y => 3, Special => None, The_Name => Bom),
    (Pageid => Egg1_Page, X => 19, Y => 9, Special => None, The_Name => Bom),

    (Pageid => Gaslit1_Page, X => 2,  Y => 3, Special => None, The_Name => Bom),
    (Pageid => Gaslit1_Page, X => 2,  Y => 5, Special => None, The_Name => Bom),
    (Pageid => Gaslit1_Page, X => 19, Y => 3, Special => None, The_Name => Bom),
    (Pageid => Gaslit1_Page, X => 19, Y => 5, Special => None, The_Name => Bom),
    (Pageid => Gaslit1_Page, X => 19, Y => 7, Special => None, The_Name => Bom),
    (Pageid => Gaslit1_Page, X => 19, Y => 9, Special => None, The_Name => Bom),

    (Pageid => Gaslit1_Page, X => 2,  Y => 3, Special => None, The_Name => Bom),
    (Pageid => Gaslit1_Page, X => 2,  Y => 4, Special => None, The_Name => Bom),
    (Pageid => Gaslit1_Page, X => 2,  Y => 5, Special => None, The_Name => Bom),
    (Pageid => Gaslit1_Page, X => 2,  Y => 6, Special => None, The_Name => Bom),
    (Pageid => Gaslit1_Page, X => 2,  Y => 7, Special => None, The_Name => Bom),
    (Pageid => Gaslit1_Page, X => 2,  Y => 8, Special => None, The_Name => Bom),
    (Pageid => Gaslit1_Page, X => 19, Y => 9, Special => None, The_Name => Bom),

    (Pageid => Gaslit1_Page, X => 2,  Y => 4, Special => None, The_Name => Bom),
    (Pageid => Gaslit1_Page, X => 2,  Y => 6, Special => None, The_Name => Bom),
    (Pageid => Gaslit1_Page, X => 19, Y => 9, Special => None, The_Name => Bom),

    (Pageid => Gaslit2_Page, X => 2,  Y => 3, Special => None,  The_Name => Bom),
    (Pageid => Gaslit2_Page, X => 8,  Y => 3, Special => Colon, The_Name => None),
    (Pageid => Gaslit2_Page, X => 2,  Y => 4, Special => None,  The_Name => Bom),
    (Pageid => Gaslit2_Page, X => 8,  Y => 4, Special => Colon, The_Name => None),
    (Pageid => Gaslit2_Page, X => 2,  Y => 5, Special => None,  The_Name => Bom),
    (Pageid => Gaslit2_Page, X => 8,  Y => 5, Special => Colon, The_Name => None),
    (Pageid => Gaslit2_Page, X => 2,  Y => 6, Special => None,  The_Name => Bom),
    (Pageid => Gaslit2_Page, X => 8,  Y => 6, Special => Colon, The_Name => None),
    (Pageid => Gaslit2_Page, X => 13, Y => 3, Special => None,  The_Name => Bom),
    (Pageid => Gaslit2_Page, X => 18, Y => 3, Special => None,  The_Name => Bom),
    (Pageid => Gaslit2_Page, X => 19, Y => 3, Special => Slash, The_Name => None),
    (Pageid => Gaslit2_Page, X => 20, Y => 3, Special => None,  The_Name => Bom),
    (Pageid => Gaslit2_Page, X => 21, Y => 3, Special => Colon, The_Name => None),
    (Pageid => Gaslit2_Page, X => 13, Y => 4, Special => None,  The_Name => Bom),
    (Pageid => Gaslit2_Page, X => 21, Y => 4, Special => Colon, The_Name => None),
    (Pageid => Gaslit2_Page, X => 13, Y => 5, Special => None,  The_Name => Bom),
    (Pageid => Gaslit2_Page, X => 14, Y => 5, Special => Slash, The_Name => None),
    (Pageid => Gaslit2_Page, X => 15, Y => 5, Special => None,  The_Name => Bom),
    (Pageid => Gaslit2_Page, X => 21, Y => 5, Special => Colon, The_Name => None),
    (Pageid => Gaslit2_Page, X => 13, Y => 6, Special => None,  The_Name => Bom),
    (Pageid => Gaslit2_Page, X => 21, Y => 6, Special => Colon, The_Name => None),
    (Pageid => Gaslit2_Page, X => 19, Y => 9, Special => None,  The_Name => Bom),

    (Pageid => Gaslit2_Page, X => 7,  Y => 3, Special => None, The_Name => Bom),
    (Pageid => Gaslit2_Page, X => 19, Y => 9, Special => None, The_Name => Bom),

    (Pageid => Gaslit2_Page, X => 2,  Y => 3, Special => None, The_Name => None),
    (Pageid => Gaslit2_Page, X => 2,  Y => 5, Special => None, The_Name => None),
    (Pageid => Gaslit2_Page, X => 2,  Y => 7, Special => None, The_Name => None),
    (Pageid => Gaslit2_Page, X => 19, Y => 9, Special => None, The_Name => None),

    (Pageid => Gaslit3_Page, X => 2,  Y => 3, Special => None, The_Name => None),
    (Pageid => Gaslit3_Page, X => 2,  Y => 4, Special => None, The_Name => None),
    (Pageid => Gaslit3_Page, X => 2,  Y => 5, Special => None, The_Name => None),

    (Pageid  => Gaslit3_Page,
     X       => 2,
     Y       => 6,
     Special => None,
     The_Name => None),

    (Pageid => Gaslit3_Page, X => 19, Y => 9, Special => None, The_Name => None),

    (Pageid => Gaslit3_Page, X => 2,  Y => 3, Special => None, The_Name => MandMs1),
    (Pageid => Gaslit3_Page, X => 2,  Y => 4, Special => None, The_Name => MandMs2),
    (Pageid => Gaslit3_Page, X => 2,  Y => 5, Special => None, The_Name => MandMs3),
    (Pageid => Gaslit3_Page, X => 2,  Y => 6, Special => None, The_Name => MandMs4),
    (Pageid => Gaslit3_Page, X => 2,  Y => 7, Special => None, The_Name => MandMs5),
    (Pageid => Gaslit3_Page, X => 2,  Y => 8, Special => None, The_Name => MandMs6),
    (Pageid => Gaslit3_Page, X => 2,  Y => 9, Special => None, The_Name => MandMs7),
    (Pageid => Gaslit3_Page, X => 13, Y => 3, Special => None, The_Name => MandMs8),
    (Pageid => Gaslit3_Page, X => 13, Y => 4, Special => None, The_Name => MandMs9),
    (Pageid => Gaslit3_Page, X => 13, Y => 5, Special => None, The_Name => MandMs10),
    (Pageid => Gaslit3_Page, X => 13, Y => 6, Special => None, The_Name => MandMs11),
    (Pageid => Gaslit3_Page, X => 19, Y => 9, Special => None, The_Name => Bom),

    (Pageid => Gaslit3_Page, X => 2,  Y => 3, Special => None, The_Name => Corn1),
    (Pageid => Gaslit3_Page, X => 2,  Y => 4, Special => None, The_Name => Corn2),
    (Pageid => Gaslit3_Page, X => 2,  Y => 5, Special => None, The_Name => Corn3),
    (Pageid => Gaslit3_Page, X => 2,  Y => 6, Special => None, The_Name => Corn4),
    (Pageid => Gaslit3_Page, X => 2,  Y => 7, Special => None, The_Name => Corn5),
    (Pageid => Gaslit3_Page, X => 2,  Y => 8, Special => None, The_Name => Corn6),
    (Pageid => Gaslit3_Page, X => 2,  Y => 9, Special => None, The_Name => Corn7),
    (Pageid => Gaslit3_Page, X => 13, Y => 3, Special => None, The_Name => Corn8),
    (Pageid => Gaslit3_Page, X => 13, Y => 4, Special => None, The_Name => Corn9),
    (Pageid => Gaslit3_Page, X => 13, Y => 5, Special => None, The_Name => Corn10),
    (Pageid => Gaslit3_Page, X => 13, Y => 6, Special => None, The_Name => Corn11),
    (Pageid => Gaslit3_Page, X => 19, Y => 9, Special => None, The_Name => Bom),

    (Pageid => Gaslit4_Page, X => 2,  Y => 3, Special => None, The_Name => Bom),
    (Pageid => Gaslit4_Page, X => 2,  Y => 5, Special => None, The_Name => Bom),
    (Pageid => Gaslit4_Page, X => 2,  Y => 6, Special => None, The_Name => Bom),
    (Pageid => Gaslit4_Page, X => 2,  Y => 7, Special => None, The_Name => Bom),
    (Pageid => Gaslit4_Page, X => 2,  Y => 8, Special => None, The_Name => Bom),
    (Pageid => Gaslit4_Page, X => 2,  Y => 9, Special => None, The_Name => Bom),
    (Pageid => Gaslit4_Page, X => 19, Y => 9, Special => None, The_Name => Bom),

    (Pageid => Gaslit4_Page, X => 2,  Y => 3, Special => None, The_Name => Bom),
    (Pageid => Gaslit4_Page, X => 2,  Y => 4, Special => None, The_Name => Bom),
    (Pageid => Gaslit4_Page, X => 2,  Y => 5, Special => None, The_Name => Bom),
    (Pageid => Gaslit4_Page, X => 2,  Y => 6, Special => None, The_Name => Bom),

    (Pageid  => Gaslit4_Page,
     X       => 2,
     Y       => 7,
     Special => None,
     The_Name => Bom),

    (Pageid => Gaslit4_Page, X => 2,  Y => 9, Special => None, The_Name => Bom),
    (Pageid => Gaslit4_Page, X => 19, Y => 9, Special => None, The_Name => Bom),

    (Pageid => Gaslit4_Page, X => 2,  Y => 3, Special => None, The_Name => MandMs1),
    (Pageid => Gaslit4_Page, X => 2,  Y => 4, Special => None, The_Name => MandMs2),
    (Pageid => Gaslit4_Page, X => 2,  Y => 5, Special => None, The_Name => MandMs3),
    (Pageid => Gaslit4_Page, X => 2,  Y => 6, Special => None, The_Name => MandMs4),
    (Pageid => Gaslit4_Page, X => 2,  Y => 7, Special => None, The_Name => MandMs5),
    (Pageid => Gaslit4_Page, X => 2,  Y => 8, Special => None, The_Name => MandMs6),
    (Pageid => Gaslit4_Page, X => 13, Y => 3, Special => None, The_Name => MandMs7),
    (Pageid => Gaslit4_Page, X => 13, Y => 4, Special => None, The_Name => MandMs8),
    (Pageid => Gaslit4_Page, X => 13, Y => 5, Special => None, The_Name => MandMs9),
    (Pageid => Gaslit4_Page, X => 13, Y => 6, Special => None, The_Name => MandMs10),
    (Pageid => Gaslit4_Page, X => 13, Y => 7, Special => None, The_Name => MandMs11),
    (Pageid => Gaslit4_Page, X => 19, Y => 9, Special => None, The_Name => None),

    (Pageid => Gaslit4_Page, X => 2,  Y => 3, Special => None, The_Name => Corn1),
    (Pageid => Gaslit4_Page, X => 2,  Y => 4, Special => None, The_Name => Corn2),
    (Pageid => Gaslit4_Page, X => 2,  Y => 5, Special => None, The_Name => Corn3),
    (Pageid => Gaslit4_Page, X => 2,  Y => 6, Special => None, The_Name => Corn4),
    (Pageid => Gaslit4_Page, X => 2,  Y => 7, Special => None, The_Name => Corn5),
    (Pageid => Gaslit4_Page, X => 2,  Y => 8, Special => None, The_Name => Corn6),
    (Pageid => Gaslit4_Page, X => 13, Y => 3, Special => None, The_Name => Corn7),
    (Pageid => Gaslit4_Page, X => 13, Y => 4, Special => None, The_Name => Corn8),
    (Pageid => Gaslit4_Page, X => 13, Y => 5, Special => None, The_Name => Corn9),
    (Pageid => Gaslit4_Page, X => 13, Y => 6, Special => None, The_Name => Corn10),
    (Pageid => Gaslit4_Page, X => 13, Y => 7, Special => None, The_Name => Corn11),
    (Pageid => Gaslit4_Page, X => 19, Y => 9, Special => None, The_Name => None),

    (Pageid => Gaslit4_Page, X => 2,  Y => 3, Special => None, The_Name => None),
    (Pageid => Gaslit4_Page, X => 14, Y => 3, Special => None, The_Name => None),

    (Pageid  => Gaslit4_Page,
     X       => 2,
     Y       => 4,
     Special => None,
     The_Name => Bom),

    (Pageid  => Gaslit4_Page,
     X       => 2,
     Y       => 5,
     Special => None,
     The_Name => Bom),

    (Pageid  => Gaslit4_Page,
     X       => 2,
     Y       => 6,
     Special => None,
     The_Name => Bom),

    (Pageid  => Gaslit4_Page,
     X       => 2,
     Y       => 7,
     Special => None,
     The_Name => Bom),

    (Pageid => Gaslit4_Page, X => 2,  Y => 8, Special => None, The_Name => Bom),
    (Pageid => Gaslit4_Page, X => 19, Y => 9, Special => None, The_Name => Bom),

    (Pageid  => Gaslit4_Page,
     X       => 2,
     Y       => 3,
     Special => None,
     The_Name => Bom),

    (Pageid => Gaslit4_Page, X => 19, Y => 9, Special => None, The_Name => Bom),

    (Pageid  => Gaslit4_Page,
     X       => 2,
     Y       => 3,
     Special => None,
     The_Name => Bom),

    (Pageid => Gaslit4_Page, X => 19, Y => 9, Special => None, The_Name => Bom),

    (Pageid => Gaslit4_Page, X => 2,  Y => 3, Special => None, The_Name => Bom),
    (Pageid => Gaslit4_Page, X => 10, Y => 3, Special => None, The_Name => Bom),
    (Pageid => Gaslit4_Page, X => 15, Y => 3, Special => None, The_Name => Bom),
    (Pageid => Gaslit4_Page, X => 19, Y => 9, Special => None, The_Name => Bom),

    (Pageid => Gaslit4_Page, X => 2,  Y => 3, Special => None, The_Name => Bom),
    (Pageid => Gaslit4_Page, X => 9,  Y => 3, Special => None, The_Name => Bom),
    (Pageid => Gaslit4_Page, X => 15, Y => 3, Special => None, The_Name => Bom),
    (Pageid => Gaslit4_Page, X => 19, Y => 9, Special => None, The_Name => Bom),

    (Pageid => Gaslit5_Page, X => 2,  Y => 3, Special => None, The_Name => Bom),
    (Pageid => Gaslit5_Page, X => 2,  Y => 5, Special => None, The_Name => Bom),
    (Pageid => Gaslit5_Page, X => 2,  Y => 7, Special => None, The_Name => Bom),
    (Pageid => Gaslit5_Page, X => 2,  Y => 9, Special => None, The_Name => Bom),
    (Pageid => Gaslit5_Page, X => 19, Y => 3, Special => None, The_Name => Bom),
    (Pageid => Gaslit5_Page, X => 19, Y => 7, Special => None, The_Name => Bom),
    (Pageid => Gaslit5_Page, X => 17, Y => 9, Special => None, The_Name => Bom),

    (Pageid => Gaslit5_Page, X => 0, Y => 0, Special => None, The_Name => Bom),

    (Pageid => Gaslit5_Page, X => 0, Y => 0, Special => None, The_Name => None),

    (Pageid => Gaslit5_Page, X => 2,  Y => 3, Special => None, The_Name => Bom),
    (Pageid => Gaslit5_Page, X => 2,  Y => 4, Special => None, The_Name => Bom),
    (Pageid => Gaslit5_Page, X => 2,  Y => 5, Special => None, The_Name => Bom),
    (Pageid => Gaslit5_Page, X => 18, Y => 5, Special => None, The_Name => Bom),
    (Pageid => Gaslit5_Page, X => 2,  Y => 6, Special => None, The_Name => Bom),
    (Pageid => Gaslit5_Page, X => 2,  Y => 7, Special => None, The_Name => Bom),

    (Pageid => End_Page, X => 1, Y => 1, Special => None, The_Name => None));

end Rep_Database;
