;;;
;;; API specification based on MPICH2 1.4.1p2
;;;
(api-spec MPI

  ;
  ; four dependency types are available:
  ;
  ;   payload  : this relates to data being transported 
  ;              (including its size and type)
  ;   topology : rank related parameters
  ;   tag      : tag related parameters
  ;   other    : everything else
  ;
  ( dep-types payload topology tag other )

  ; default to the "everything else" class
  ( default_deptype other )

  ( 
    ; book keeping
    (MPI_Init              2 )
    (MPI_Finalize          0 )
    (MPI_Abort             2 )

    ; communicator manipulation
    (MPI_Comm_rank         2  (topology 1) )
    (MPI_Comm_size         2  (topology 1) )
    (MPI_Comm_split        4 )

    ; waits
    (MPI_Wait              2 )

    ; pairwise operators
    (MPI_Send              6  (payload 0 1 2) (topology 3) (tag 4) )
    (MPI_Bsend             6  (payload 0 1 2) (topology 3) (tag 4) )
    (MPI_Ssend             6  (payload 0 1 2) (topology 3) (tag 4) )
    (MPI_Rsend             6  (payload 0 1 2) (topology 3) (tag 4) )
    (MPI_Isend             7  (payload 0 1 2) (topology 3) (tag 4) )
    (MPI_Issend            7  (payload 0 1 2) (topology 3) (tag 4) )
    (MPI_Ibsend            7  (payload 0 1 2) (topology 3) (tag 4) )
    (MPI_Irsend            7  (payload 0 1 2) (topology 3) (tag 4) )

    (MPI_Recv              7  (payload 0 1 2) (topology 3) (tag 4) )
    (MPI_Irecv             7  (payload 0 1 2) (topology 3) (tag 4) )



    ; collectives
    (MPI_Barrier           1 )
    (MPI_Bcast             5  (payload 0 1 2) (topology 3) )
    (MPI_Scatter           8  (payload 0 1 2 3 4 5) (topology 6) )
    (MPI_Scatterv          9  (payload 0 1 2 3 4 5 6) (topology 7) )
    (MPI_Allgather         7  (payload 0 1 2 3 4 5) )
    (MPI_Allgatherv        8  (payload 0 1 2 3 4 5 6) )
    (MPI_Gather            8  (payload 0 1 2 3 4 5) (topology 6) )
    (MPI_Gatherv           9  (payload 0 1 2 3 4 5 6) (topology 7) )
    (MPI_Reduce            7  (payload 0 1 2 3) (topology 5))
    (MPI_Scan              6  (payload 0 1 2 3) )
    (MPI_Allreduce         6  (payload 0 1 2 3) )
    (MPI_Alltoall          7  (payload 0 1 2 3 4 5) )
    (MPI_Alltoallv         9  (payload 0 1 2 3 4 5 6 7 8) )

    (MPI_Sendrecv          12 (payload 0 1 2 5 6 7) (topology 3 8) (tag 4 9) )
    (MPI_Sendrecv_replace  9  (payload 0 1 2) (topology 3 5) (tag 4 6) )

    (MPI_Reduce_scatter    6  (payload 0 1 2 3) ) 

    (MPI_Op_create         3 )
    (MPI_Op_free           1 )

    (MPI_Get               8  (payload 0 1 2 4 5 6) (topology 3) )
    (MPI_Put               8  (payload 0 1 2 4 5 6) (topology 3) )

    (MPI_Cart_create       6  (topology 0 1 2 3 4 5))
    (MPI_Cart_get          5  (topology 0 1 2 3 4))
    (MPI_Cart_shift        5  (topology 0 1 2 3 4))

;;;
;;; BELOW ARE THE REMAINING MPI API FUNCTIONS AS GENERATED AUTOMATICALLY FROM
;;; MPI.H FROM MPICH2.
;;;
;;; NOTE THAT SOME OF THESE MAY HAVE ARGUMENTS THAT SHOULD BE ANNOTATED, BUT
;;; WE HAVE NOT BOTHERED GIVEN THAT THESE FUNCTIONS APPEAR FAR LESS FREQUENTLY THAN
;;; THOSE ABOVE.  IF YOU MODIFY ANY OF THE FUNCTIONS BELOW THIS POINT, PLEASE MOVE
;;; THEM ABOVE THIS COMMENT SO WE CAN DISTINGUISH THE AUTO-GENNED ONES FROM THOSE
;;; THAT HAVE BEEN HUMAN-MODIFIED
;;;

    (MPI_Get_count 3)
    (MPI_Buffer_attach 2)
    (MPI_Buffer_detach 2)
    (MPI_Request_free 1)
    (MPI_Test 3)
    (MPI_Test_cancelled 2)
    (MPI_Send_init 7)
    (MPI_Bsend_init 7)
    (MPI_Ssend_init 7)
    (MPI_Rsend_init 7)
    (MPI_Recv_init 7)
    (MPI_Start 1)
    (MPI_Startall 2)
    (MPI_Type_contiguous 3)
    (MPI_Type_vector 5)
    (MPI_Type_hvector 5)
    (MPI_Type_indexed 5)
    (MPI_Type_hindexed 5)
    (MPI_Type_struct 5)
    (MPI_Address 2)
    (MPI_Type_extent 2)
    (MPI_Type_size 2)
    (MPI_Type_lb 2)
    (MPI_Type_ub 2)
    (MPI_Type_commit 1)
    (MPI_Type_free 1)
    (MPI_Get_elements 3)
    (MPI_Pack 7)
    (MPI_Unpack 7)
    (MPI_Pack_size 4)
    (MPI_Group_size 2)
    (MPI_Group_rank 2)
    (MPI_Group_translate_ranks 5)
    (MPI_Group_compare 3)
    (MPI_Comm_group 2)
    (MPI_Group_union 3)
    (MPI_Group_intersection 3)
    (MPI_Group_difference 3)
    (MPI_Group_incl 4)
    (MPI_Group_excl 4)
    (MPI_Group_range_incl 4)
    (MPI_Group_range_excl 4)
    (MPI_Group_free 1)
    (MPI_Intercomm_create 6)
    (MPI_Intercomm_merge 3)
    (MPI_Keyval_create 4)
    (MPI_Keyval_free 1)
    (MPI_Attr_put 3)
    (MPI_Attr_get 4)
    (MPI_Attr_delete 2)
    (MPI_Topo_test 2)

    (MPI_Dims_create 3)
    (MPI_Graph_create 6)
    (MPI_Graphdims_get 3)
    (MPI_Graph_get 5)
    (MPI_Cartdim_get 2)
    (MPI_Cart_rank 3)
    (MPI_Cart_coords 4)
    (MPI_Graph_neighbors_count 3)
    (MPI_Graph_neighbors 4)
    (MPI_Cart_sub 3)
    (MPI_Cart_map 5)
    (MPI_Graph_map 5)
    (MPI_Get_processor_name 2)
    (MPI_Get_version 2)
    (MPI_Errhandler_create 2)
    (MPI_Errhandler_set 2)
    (MPI_Errhandler_get 2)
    (MPI_Errhandler_free 1)
    (MPI_Error_string 3)
    (MPI_Error_class 2)
    (MPI_Wtime 1)
    (MPI_Wtick 1)
    (MPI_Initialized 1)
    (MPI_Pcontrol 2)
    (MPIR_Dup_fn 6)
    (MPI_Close_port 1)
    (MPI_Comm_accept 5)
    (MPI_Comm_connect 5)
    (MPI_Comm_disconnect 1)
    (MPI_Comm_get_parent 1)
    (MPI_Comm_join 2)
    (MPI_Comm_spawn 8)
    (MPI_Comm_spawn_multiple 9)
    (MPI_Lookup_name 3)
    (MPI_Open_port 2)
    (MPI_Publish_name 3)
    (MPI_Unpublish_name 3)
    (MPI_Accumulate 9)
    (MPI_Win_complete 1)
    (MPI_Win_create 6)
    (MPI_Win_fence 2)
    (MPI_Win_free 1)
    (MPI_Win_get_group 2)
    (MPI_Win_lock 4)
    (MPI_Win_post 3)
    (MPI_Win_start 3)
    (MPI_Win_test 2)
    (MPI_Win_unlock 2)
    (MPI_Win_wait 1)
    (MPI_Alltoallw 9)
    (MPI_Exscan 6)
    (MPI_Add_error_class 1)
    (MPI_Add_error_code 2)
    (MPI_Add_error_string 2)
    (MPI_Comm_call_errhandler 2)
    (MPI_Comm_create_keyval 4)
    (MPI_Comm_delete_attr 2)
    (MPI_Comm_free_keyval 1)
    (MPI_Comm_get_attr 4)
    (MPI_Comm_get_name 3)
    (MPI_Comm_set_attr 3)
    (MPI_Comm_set_name 2)
    (MPI_File_call_errhandler 2)
    (MPI_Grequest_complete 1)
    (MPI_Grequest_start 5)
    (MPI_Init_thread 4)
    (MPI_Is_thread_main 1)
    (MPI_Query_thread 1)
    (MPI_Status_set_cancelled 2)
    (MPI_Status_set_elements 3)
    (MPI_Type_create_keyval 4)
    (MPI_Type_delete_attr 2)
    (MPI_Type_dup 2)
    (MPI_Type_free_keyval 1)
    (MPI_Type_get_attr 4)
    (MPI_Type_get_contents 7)
    (MPI_Type_get_envelope 5)
    (MPI_Type_get_name 3)
    (MPI_Type_set_attr 3)
    (MPI_Type_set_name 2)
    (MPI_Type_match_size 3)
    (MPI_Win_call_errhandler 2)
    (MPI_Win_create_keyval 4)
    (MPI_Win_delete_attr 2)
    (MPI_Win_free_keyval 1)
    (MPI_Win_get_attr 4)
    (MPI_Win_get_name 3)
    (MPI_Win_set_attr 3)
    (MPI_Win_set_name 2)
    (MPI_Alloc_mem 3)
    (MPI_Comm_create_errhandler 2)
    (MPI_Comm_get_errhandler 2)
    (MPI_Comm_set_errhandler 2)
    (MPI_File_create_errhandler 2)
    (MPI_File_get_errhandler 2)
    (MPI_File_set_errhandler 2)
    (MPI_Finalized 1)
    (MPI_Free_mem 1)
    (MPI_Get_address 2)
    (MPI_Info_create 1)
    (MPI_Info_delete 2)
    (MPI_Info_dup 2)
    (MPI_Info_free 1)
    (MPI_Info_get 5)
    (MPI_Info_get_nkeys 2)
    (MPI_Info_get_nthkey 3)
    (MPI_Info_get_valuelen 4)
    (MPI_Info_set 3)
    (MPI_Pack_external 7)
    (MPI_Pack_external_size 4)
    (MPI_Request_get_status 3)
    (MPI_Status_c2f 2)
    (MPI_Status_f2c 2)
    (MPI_Type_create_darray 10)
    (MPI_Type_create_hindexed 5)
    (MPI_Type_create_hvector 5)
    (MPI_Type_create_indexed_block 5)
    (MPI_Type_create_resized 4)
    (MPI_Type_create_struct 5)
    (MPI_Type_create_subarray 7)
    (MPI_Type_get_extent 3)
    (MPI_Type_get_true_extent 3)
    (MPI_Unpack_external 7)
    (MPI_Win_create_errhandler 2)
    (MPI_Win_get_errhandler 2)
    (MPI_Win_set_errhandler 2)
    (MPI_Type_create_f90_integer 2)
    (MPI_Type_create_f90_real 3)
    (MPI_Type_create_f90_complex 3)
    (MPI_Reduce_local 5)
    (MPI_Op_commutative 2)
    (MPI_Reduce_scatter_block 6)
    (MPI_Dist_graph_create_adjacent 10)
    (MPI_Dist_graph_create 9)
    (MPI_Dist_graph_neighbors_count 4)
    (MPI_Dist_graph_neighbors 7)
    (MPIX_Grequest_class_create 6)
    (MPIX_Grequest_class_allocate 3)
    (MPIX_Grequest_start 7)

;;;
;;; END OF AUTOGENNED FUNCTIONS
;;;
  )
)
