#!/bin/sh
set -e
if [ $# -ne 1 ]; then
  echo "Usage: $0 srcdir" 1>&2
  exit 1
fi
srcdir=$1
echo "testing interp1.C"
../CPAnalysis/ContainerAnalyzer --edg:no_warnings -w -annot $srcdir/Container.annot -I$srcdir $srcdir/UserDefList2b.C  
diff UserDefList2b.C.out $srcdir/UserDefList2b.C.out.save
rm UserDefList2b.C.out
../CPAnalysis/ContainerAnalyzer --edg:no_warnings -w -annot $srcdir/Container.annot -I$srcdir $srcdir/UserDefList2c.C
diff UserDefList2c.C.out $srcdir/UserDefList2c.C.out.save
rm UserDefList2c.C.out
../CPAnalysis/ContainerAnalyzer --edg:no_warnings -w -annot $srcdir/Container.annot -I$srcdir $srcdir/UserDefList3.C
diff UserDefList3.C.out $srcdir/UserDefList3.C.out.save
rm UserDefList3.C.out
../CPAnalysis/ContainerAnalyzer --edg:no_warnings -w -annot $srcdir/Container.annot -I$srcdir $srcdir/UserDefList2.C
diff UserDefList2.C.out $srcdir/UserDefList2.C.out.save
rm UserDefList2.C.out
../CPAnalysis/ContainerAnalyzer --edg:no_warnings -w -annot $srcdir/Container.annot -I$srcdir $srcdir/UserDefList2d.C
diff UserDefList2d.C.out $srcdir/UserDefList2d.C.out.save
rm UserDefList2d.C.out
../CPAnalysis/ContainerAnalyzer --edg:no_warnings -w -annot $srcdir/Container.annot -I$srcdir $srcdir/UserDefList.C
diff UserDefList.C.out $srcdir/UserDefList.C.out.save
rm UserDefList.C.out
