// Example relaxation code to experiment with TMR transformations

// Things to do in this code:
// 1) Simplify the algorithm-based distribution.
// 2) Add support for ghost boundary halos (arbritrary width).
// 3) Hierarchy of use (nesting of MulticoreArray)
// 4) Dynamic data
// 5) Better use of OpenMP (specify parallel region "#pragma parallel")

// Use "ManyCoreArrayRuntimeSupport" as the name of this class/project...


#include<stdio.h>
#include<stdlib.h>

#include<assert.h>

#include<vector>
#include<string>

// This header file can't be found (unless John Van Zant installs the libnuma development version or the RPM).
// Note that libnuma will return a NULL pointer when ask to allocate zero bytes (C++ allocation will alternatively
// allocated memory returning a valid pointer; so the two are semantically different on minor points). We now
// handle this case to preserve the same semantics; when using libnuma we check for this case of zero bytes and 
// use the C++ allocation to get a valid pointer.
#if HAVE_NUMA_H
   #include<numa.h>
#endif

// Support for timing
#include <iostream>
#include <time.h>

// Local support for a timer better than clock().
#include "highresTimer.h"

using namespace std;

#include "stencil.h"

// *********************************************************************
// *********************************************************************
// Examples of the use of the Core<T> and MulticoreArray<T> abstractions
// *********************************************************************
// *********************************************************************


template <typename T>
void
lower_level_relax ( MulticoreArray<T> & array, MulticoreArray<T> & old_array )
   {
  // The code in this function is what we would want to have ben generated by the compiler.

     const int numberOfCores = array.get_numberOfCores();

  // Make sure that these are distributed using the same approach (table-based or via an algorithmic approach).
     assert(array.get_tableBasedDistribution() == old_array.get_tableBasedDistribution());

// Use OpenMP to support the parallel threads on each core.
#pragma omp parallel for
     for (int p = 0; p < numberOfCores; p++)
        {
       // Refactored form of relaxation on the interior.
          relax(p,array,old_array,1);

       // **************************************************************
       // Fixup internal bounaries of the memory allocated to each core.
       // **************************************************************

       // Refactored form of relaxation on the interior.
          relax_on_boundary(p,array,old_array,1);
        }
   }



// ****************************************************
// ****************************************************
// Main test function for MulticoreArray<T> abstraction
// ****************************************************
// ****************************************************

int main ()
   {
  // A multidimensional array support would have to include inter-array padding (to allow the seperate rows to work well with the cache).
  // If multiple arrays are used then intra-array padding will separate them from each other and permit them to work well with cache.

     int numaSupport = -1;
// #ifdef NUMA_NUM_NODES
#if HAVE_NUMA_H
  // A return value of -1 means that all other functions in this library are undefined.
     numaSupport = numa_available();
#endif

     if (numaSupport != -1)
        {
          printf ("NUMA support is AVAILABLE \n");
        }
       else
        {
          printf ("NUMA support is NOT available numaSupport = %d \n",numaSupport);
        }

     int arraySize[DIM]              = {0,0,0};
     int numberOfCoresArraySize[DIM] = {0,0,0};

     int interArraySubsectionPadding =  0; // Page size to avoid cache conflicts with memory allocted for use by each core

#if 1
  // 10x10x10 is 1 million elements
     int global_arraySize = 1024;

     arraySize[0] = global_arraySize;
     arraySize[1] = global_arraySize;
     arraySize[2] = global_arraySize;

     int numberOfCores =  4; // Number of cores to use (each axis)
     numberOfCoresArraySize[0] = numberOfCores;
     numberOfCoresArraySize[1] = numberOfCores;
     numberOfCoresArraySize[2] = numberOfCores;

#if 0
     numberOfCoresArraySize[0] = 2;
     numberOfCoresArraySize[1] = 2;
     numberOfCoresArraySize[2] = 2;
#endif

  // Array constructor call
     printf ("Allocate array1 \n");
     MulticoreArray<double> array1    (arraySize[0],arraySize[1],arraySize[2],numberOfCoresArraySize[0],numberOfCoresArraySize[1],numberOfCoresArraySize[2],interArraySubsectionPadding,false);
     printf ("Allocate array1 \n");
     MulticoreArray<double> old_array1(arraySize[0],arraySize[1],arraySize[2],numberOfCoresArraySize[0],numberOfCoresArraySize[1],numberOfCoresArraySize[2],interArraySubsectionPadding,false);
     printf ("Allocate array2 \n");
     MulticoreArray<double> array2    (arraySize[0],arraySize[1],arraySize[2],numberOfCoresArraySize[0],numberOfCoresArraySize[1],numberOfCoresArraySize[2],interArraySubsectionPadding,true);
     printf ("Allocate array2 \n");
     MulticoreArray<double> old_array2(arraySize[0],arraySize[1],arraySize[2],numberOfCoresArraySize[0],numberOfCoresArraySize[1],numberOfCoresArraySize[2],interArraySubsectionPadding,true);
     printf ("DONE: Allocate array2 \n");

#if 0
     array1.display    ("initial values: array1");
     array2.display    ("initial values: array2");
     old_array1.display("initial values: old_array1");
     old_array2.display("initial values: old_array2");
#endif

#if 0
  // Initialize to non-zero value.
     array1 = 1.0;
     array2 = 1.0;
#endif

#if 1
     printf ("Initialize the array1 \n");
     old_array1.sequenceFill3D(120.0);
     printf ("Initialize the array2 \n");
     old_array2.sequenceFill3D(120.0);
#endif

#if 0
     array1.display    ("after initialization: array1");
     array2.display    ("after initialization: array2");
     old_array1.display("after initialization: old_array1");
     old_array2.display("after initialization: old_array2");
#endif

  // Initialize the boundary
     int boundaryValue = 0;
     printf ("Initialize the boundary of array1 \n");
     array1.initializeBoundary(boundaryValue);
     old_array1.initializeBoundary(boundaryValue);
     printf ("Initialize the boundary of array2 \n");
     array2.initializeBoundary(boundaryValue);
     old_array2.initializeBoundary(boundaryValue);

#if 0
     array1.display    ("after initialization of boundary: array1");
     array2.display    ("after initialization of boundary: array2");
     old_array1.display("after initialization of boundary: old_array1");
     old_array2.display("after initialization of boundary: old_array2");
#endif

     printf ("Call relaxation \n");

#ifndef __APPLE__
  // Setup timer
     timespec time1, time2;
     clock_gettime(CLOCK_REALTIME, &time1);
#endif

  // Call relaxation on array
     int numberOfIterations = 10;
     for (int i = 0; i < numberOfIterations; i++)
        {
#if 0
          printf ("Calling relaxation on large array \n");
#endif
          lower_level_relax(array2,old_array2);
#endif
        }

#ifndef __APPLE__
  // Get and report the time.
     clock_gettime(CLOCK_REALTIME, &time2);
     cout << diff(time1,time2).tv_sec << ":" << diff(time1,time2).tv_nsec << endl;
#endif

#if 0
  // Output the result
     array1.display("result: array1");
     array2.display("result: array2");
#endif

  // Make sure that the results are the same.
//     assert(array1 == array2);

#if 0
  // Test refactored version of operator.
     relax2D(array1,old_array1);
#endif

#if 1
#ifndef __APPLE__
  // Setup timer
     clock_gettime(CLOCK_REALTIME, &time1);
#endif
  // Test refactored version of operator.
     array1 = 0.0;
     for (int i = 0; i < numberOfIterations; i++)
     {
       relax3D_midlevel(array1,old_array1);
     }
//     assert(array1 == array2);
#ifndef __APPLE__
  // Get and report the time.
     clock_gettime(CLOCK_REALTIME, &time2);
     cout << diff(time1,time2).tv_sec << ":" << diff(time1,time2).tv_nsec << endl;
#endif
#endif

#if 0
  // Output the result
     old_array1.display("After relax2D_highlevel(): old_array1");
     array1.display("After relax2D_highlevel(): array1");
     array2.display("After relax2D_highlevel(): array2");
#endif

  // Make sure that the results are the same.

#if 1
#ifndef __APPLE__
  // Setup timer
     clock_gettime(CLOCK_REALTIME, &time1);
#endif
  // Test refactored version of operator.
     array1 = 0.0;
     for (int i = 0; i < numberOfIterations; i++)
     {
       relax3D_highlevel(array1,old_array1);
     }
     assert(array1 == array2);
#ifndef __APPLE__
  // Get and report the time.
     clock_gettime(CLOCK_REALTIME, &time2);
     cout << diff(time1,time2).tv_sec << ":" << diff(time1,time2).tv_nsec << endl;
#endif
//     array1.display("after 3D relaxation: array1");
#endif

     return 0;
   }

