// from the kernel; this checks that if you are in C mode, don't add
// the implicit typedef generated by a struct to the namespace; note
// the two meanings of 'dongle' below.

struct dongle_reg {
  int type;
};

void irda_device_unregister_dongle_R40b68423(struct dongle_reg *dongle)
{
  struct dongle *node;
  dongle->type;
}
