#!/bin/sh
set -e
if [ $# -ne 2 ]; then
  echo "Usage: $0 srcdir exedir" 1>&2
  exit 1
fi
srcdir=$1

DIFF="diff -U5"

test1="$2/ArrayProcessor -c -fs2 -annot $srcdir/floatArray.annot -annot $srcdir/funcs.annot -annot $srcdir/Index.annot $srcdir/interp1.C"
echo $test1
$test1
#${DIFF} $srcdir/rose_interp1.C.save rose_interp1.C
#rm rose_interp1.C

test2="$2/ArrayProcessor -c -fs2 -annot $srcdir/floatArray.annot -annot $srcdir/funcs.annot -annot $srcdir/Index.annot $srcdir/redBlack1.C"
echo $test2
$test2
#${DIFF} $srcdir/rose_redBlack1.C.save rose_redBlack1.C
#rm rose_redBlack1.C

# Infinite running for some reason
#test3="$2/ArrayProcessor -c -fs2 -annot $srcdir/floatArray.annot -annot $srcdir/funcs.annot -annot $srcdir/Index.annot -splitloop $srcdir/redBlack1.C"
#echo $test3
#$test3
#${DIFF} $srcdir/rose_redBlack1_split.C.save rose_redBlack1.C
#rm rose_redBlack1.C
