#!/bin/sh 

# Basic test script
# (C) 2007 Adrian Prantl, Viktor Pavlu

FILES=`ls tests/*.[cC]`
ANALYSIS="./constprop"
MODES="--textoutput --termoutput --sourceoutput"
OPTIONS="--wholeprogram --preinfo --postinfo"

ALL=
SUCESS=
FAILED=

# known to work
$ANALYSIS tests/classes2.C >/dev/null || exit 1
$ANALYSIS tests/blocks.c   >/dev/null || exit 1

$ANALYSIS tests/blocks.c --textoutput   >/dev/null || exit 1
$ANALYSIS tests/blocks.c --termoutput   >/dev/null || exit 1
$ANALYSIS tests/blocks.c --sourceoutput >/dev/null || exit 1

# possible buggy testcases

# generate all permutations of options
DELIM=§
PERMUTATIONS="$DELIM"
for opt in $OPTIONS; do
    newperms=
    for perm in $PERMUTATIONS; do
        newperms="$newperms $perm"
        newperms="$newperms $perm$DELIM$opt"
    done
    PERMUTATIONS="$newperms"
done

for mode in $MODES; do

    echo "######## ######## Testing mode \"$mode\""

    for file in $FILES; do

	echo "######## on file $file"

	# for each option (even no options)
	for option in $PERMUTATIONS; do

            option_with_space=${option//$DELIM/ }

	    echo "$ANALYSIS $file $mode $option_with_space"
	    $ANALYSIS $file $mode $option_with_space >/dev/null

	    if [ $? -eq 0 ]; then SUCCESS="$SUCCESS $file$DELIM$mode$DELIM$option"
	    else FAILED="$FAILED $ANALYSIS$DELIM$file$DELIM$mode$DELIM$option"; fi
	    ALL="$ALL $ANALYSIS$DELIM$file$DELIM$mode$DELIM$option"
	done 
    done
done



echo "########################################################################"
echo "# SATIrE automagic test report, `date`"
echo "########################################################################"
echo

TOTAL=`echo $ALL    |wc -w`
GOOD=`echo  $SUCCESS|wc -w`
BAD=`echo   $FAILED |wc -w`
PERCENT=`echo $GOOD*100/$TOTAL|bc`

echo "[$GOOD/$TOTAL] succeeded ($PERCENT%)!" # FIXME: integer only
#if [ -n "$SUCCESS" ]; then 
#    echo [$SUCCESS]
#fi

echo "[$BAD/$TOTAL] failed:"
if [ -n "$FAILED" ]; then 
    for f in $FAILED; do
        f=${f//$DELIM/ }
	echo "  $f"
    done
    echo "Press <Ctrl-C> to abort or <Return> to continue"
    read 
    #exit 1
fi
echo "########################################################################"
