#!/bin/sh 

FILES=`ls tests/*.[cC]`
MODES="--textoutput --termoutput --sourceoutput"
OPTIONS="--wholeprogram --preinfo --postinfo"

# Known to work
./constprop tests/classes2.C >/dev/null || exit 1
./constprop tests/blocks.c   >/dev/null || exit 1

./constprop tests/blocks.c --textoutput   >/dev/null || exit 1
./constprop tests/blocks.c --termoutput   >/dev/null || exit 1
./constprop tests/blocks.c --sourceoutput >/dev/null || exit 1

# possibly buggy
for mode in $MODES; do

    echo "######## ######## Testing mode \"$mode\""

    for file in $FILES; do

	echo "######## on file $file"

	# Without options
	echo "./constprop $file $mode >/dev/null || exit 1"
	./constprop $file $mode >/dev/null || exit 1

	# for each option
	# TODO: for each combination of options
	for option in $OPTIONS; do

	    echo "./constprop $file $mode $option >/dev/null || exit 1"
	    ./constprop $file $mode $option >/dev/null || exit 1
	done 
    done
done