#include <sage3basic.h>

void
SgTemplateFunctionRefExp::post_construction_initialization()
   {
   }

SgTemplateFunctionSymbol*
SgTemplateFunctionRefExp::get_symbol() const
   {
  // return isSgTemplateFunctionSymbol(get_symbol_i());
     return get_symbol_i();
   }

void
SgTemplateFunctionRefExp::set_symbol(SgTemplateFunctionSymbol * symbol)
   {
     set_symbol_i(symbol);
   }

SgTemplateFunctionDeclaration*
SgTemplateFunctionRefExp::getAssociatedFunctionDeclaration() const
   {
  // This is helpful in chasing down the associated declaration to this function reference.
     SgTemplateFunctionDeclaration* returnFunctionDeclaration = NULL;
     SgTemplateFunctionSymbol*      functionSymbol            = this->get_symbol();

     ROSE_ASSERT(functionSymbol != NULL);

     if (functionSymbol != NULL)
          returnFunctionDeclaration = isSgTemplateFunctionDeclaration(functionSymbol->get_declaration());

     return returnFunctionDeclaration;
   }

// DQ (6/11/2015): Moved these six access functions, they should not be generated by ROSETTA
// so that we could avoid them setting the isModified flag which is a problem in the
// name qualification support for C++ (interfering with the token-based unparsing).
int
SgTemplateFunctionRefExp::get_name_qualification_length () const
   {
     ROSE_ASSERT (this != NULL);
     return p_name_qualification_length;
   }

void
SgTemplateFunctionRefExp::set_name_qualification_length ( int name_qualification_length )
   {
     ROSE_ASSERT (this != NULL);
  // This can't be called by the name qualification API (see test2015_26.C).
  // set_isModified(true);

     p_name_qualification_length = name_qualification_length;
   }

bool
SgTemplateFunctionRefExp::get_type_elaboration_required () const
   {
     ROSE_ASSERT (this != NULL);
     return p_type_elaboration_required;
   }

void
SgTemplateFunctionRefExp::set_type_elaboration_required ( bool type_elaboration_required )
   {
     ROSE_ASSERT (this != NULL);
  // This can't be called by the name qualification API (see test2015_26.C).
  // set_isModified(true);

     p_type_elaboration_required = type_elaboration_required;
   }

bool
SgTemplateFunctionRefExp::get_global_qualification_required () const
   {
     ROSE_ASSERT (this != NULL);
     return p_global_qualification_required;
   }

void
SgTemplateFunctionRefExp::set_global_qualification_required ( bool global_qualification_required )
   {
     ROSE_ASSERT (this != NULL);

  // This can't be called by the name qualification API (see test2015_26.C).
  // set_isModified(true);

     p_global_qualification_required = global_qualification_required;
   }
