#include <sage3basic.h>

void
SgTemplateMemberFunctionRefExp::post_construction_initialization()
   {
   }

SgTemplateMemberFunctionSymbol*
SgTemplateMemberFunctionRefExp::get_symbol() const
   {
  // return isSgTemplateMemberFunctionSymbol(get_symbol_i());
     return get_symbol_i();
   }

void
SgTemplateMemberFunctionRefExp::set_symbol(SgTemplateMemberFunctionSymbol * symbol)
   {
     set_symbol_i(symbol);
   }

// DQ (2/8/2009): I always wanted to have this function!
SgTemplateMemberFunctionDeclaration*
SgTemplateMemberFunctionRefExp::getAssociatedMemberFunctionDeclaration() const
   {
  // This is helpful in chasing down the associated declaration to this member function reference.
     SgTemplateMemberFunctionDeclaration* returnMemberFunctionDeclaration = NULL;
     SgTemplateMemberFunctionSymbol*      memberFunctionSymbol            = this->get_symbol();

     ROSE_ASSERT(memberFunctionSymbol != NULL);

     if (memberFunctionSymbol != NULL)
          returnMemberFunctionDeclaration = isSgTemplateMemberFunctionDeclaration(memberFunctionSymbol->get_declaration());

     return returnMemberFunctionDeclaration;
   }

// DQ (6/11/2015): Moved these six access functions, they should not be generated by ROSETTA
// so that we could avoid them setting the isModified flag which is a problem in the
// name qualification support for C++ (interfering with the token-based unparsing).
int
SgTemplateMemberFunctionRefExp::get_name_qualification_length () const
   {
     ROSE_ASSERT (this != NULL);
     return p_name_qualification_length;
   }

void
SgTemplateMemberFunctionRefExp::set_name_qualification_length ( int name_qualification_length )
   {
     ROSE_ASSERT (this != NULL);
  // This can't be called by the name qualification API (see test2015_26.C).
  // set_isModified(true);

     p_name_qualification_length = name_qualification_length;
   }

bool
SgTemplateMemberFunctionRefExp::get_type_elaboration_required () const
   {
     ROSE_ASSERT (this != NULL);
     return p_type_elaboration_required;
   }

void
SgTemplateMemberFunctionRefExp::set_type_elaboration_required ( bool type_elaboration_required )
   {
     ROSE_ASSERT (this != NULL);
  // This can't be called by the name qualification API (see test2015_26.C).
  // set_isModified(true);

     p_type_elaboration_required = type_elaboration_required;
   }

bool
SgTemplateMemberFunctionRefExp::get_global_qualification_required () const
   {
     ROSE_ASSERT (this != NULL);
     return p_global_qualification_required;
   }

void
SgTemplateMemberFunctionRefExp::set_global_qualification_required ( bool global_qualification_required )
   {
     ROSE_ASSERT (this != NULL);

  // This can't be called by the name qualification API (see test2015_26.C).
  // set_isModified(true);

     p_global_qualification_required = global_qualification_required;
   }
