#!/bin/bash

if [ $# -ne 2 ]
then
	echo "usage: $0 input_file output_file"
else
	echo "Running source creator on $1"
	echo "Output written to $2"
	# this sed thing is a quick & dirty hack to remove global namespace
	# qualifiers that startle EDG
	term2rose < $1 |sed -e 's/ ::/ /g'>$2
	exit $?
fi
