#!/bin/bash
set -ex

specimen="$1"
llvm_version="$(llvm-as --version 2>&1 |sed -nr '/LLVM version/ s/.*version ([0-9]+\.[0-9]+\.[0-9]+).*/\1/p')"
llvm_version_major="$(echo "$llvm_version" |cut -d. -f1)"
output=llvmTranscoder-$(basename $specimen).ll

./llvmTranscoder --llvm=${llvm_version} ${specimen} > ${output}
wc -l ${output}

if [ "$llvm_version_major" -lt 13 ] && llvm-as --version && opt --version; then
    llvm-as -o - ${output} | opt -analyze -lint
else
    echo "test skipped -- unsupported LLVM version"
fi
