      SUBROUTINE A16(X, Y)
!$OMP PARALLEL 

!$OMP CRITICAL(XAXIS)
      CALL DEQUEUE()
!$OMP END CRITICAL(XAXIS)

      CALL WORK()

!$OMP CRITICAL
      CALL DEQUEUE()
!$OMP END CRITICAL

      CALL WORK()
!$OMP END PARALLEL

      END SUBROUTINE A16
