#!/bin/sh

# Turn on error checking so that any error forces a failure of the script
set -e

if [ $# -ne 1 ]; then
  echo "Usage: $0 srcdir" 1>&2
  exit 1
fi

srcdir=$1

echo ./steensgaardTest1 8
./steensgaardTest1 8 > out
echo "Calling: diff out $srcdir/steensgaardTest1.out"
diff out $srcdir/steensgaardTest1.out
rm out

echo ./PtrAnalTest $srcdir/testPtr1.C
./PtrAnalTest $srcdir/testPtr1.C  > out
echo "Calling: diff out $srcdir/PtrAnalTest.out1"
diff out $srcdir/PtrAnalTest.out1
rm out

echo ./PtrAnalTest $srcdir/testPtr2.C
./PtrAnalTest $srcdir/testPtr2.C  > out
echo "Calling: diff out $srcdir/PtrAnalTest.out2"
diff out $srcdir/PtrAnalTest.out2
rm out

echo ./steensgaardTest2 $srcdir/testPtr1.C
./steensgaardTest2 $srcdir/testPtr1.C  > out
echo "Calling: diff out $srcdir/steensgaardTest2.out1"
diff out $srcdir/steensgaardTest2.out1
rm out

echo ./steensgaardTest2 $srcdir/testPtr2.C
#./steensgaardTest2 $srcdir/testPtr2.C  > out
#echo "Calling: diff out $srcdir/steensgaardTest2.out2"
#diff out $srcdir/steensgaardTest2.out2
#rm out
# DQ (2/9/2008): This test fails on my 64-bit Red Hat system using the g++ version 3.4.6 compiler
echo "This test fails on my 64-bit Red Hat system using the g++ version 3.4.6 compiler..."

echo ./CFGTest -I$srcdir $srcdir/testfile1.c
./CFGTest -I$srcdir $srcdir/testfile1.c
echo "Calling: diff testfile1.c.out $srcdir/testfile1.c.cfg"
diff testfile1.c.out $srcdir/testfile1.c.cfg
rm testfile1.c.out

echo ./DataFlowTest -I$srcdir $srcdir/testfile1.c
./DataFlowTest -I$srcdir $srcdir/testfile1.c
echo "Calling: diff testfile1.c.out $srcdir/testfile1.c.du"
diff testfile1.c.out $srcdir/testfile1.c.du
rm testfile1.c.out

echo ./StmtRefTest -I$srcdir $srcdir/testfile1.c
./StmtRefTest -I$srcdir $srcdir/testfile1.c
echo "diff testfile1.c.out $srcdir/testfile1.c.ref"
diff testfile1.c.out $srcdir/testfile1.c.ref
rm testfile1.c.out

echo ./CFGTest -I$srcdir $srcdir/testfile2.c
./CFGTest -I$srcdir $srcdir/testfile2.c
echo "diff testfile2.c.out $srcdir/testfile2.c.cfg"
diff testfile2.c.out $srcdir/testfile2.c.cfg
rm testfile2.c.out

echo ./DataFlowTest -I$srcdir $srcdir/testfile2.c
./DataFlowTest -I$srcdir $srcdir/testfile2.c
echo "diff testfile2.c.out $srcdir/testfile2.c.du"
diff testfile2.c.out $srcdir/testfile2.c.du
rm testfile2.c.out

echo ./StmtRefTest -I$srcdir $srcdir/testfile2.c
./StmtRefTest -I$srcdir $srcdir/testfile2.c
echo "diff testfile2.c.out $srcdir/testfile2.c.ref"
diff testfile2.c.out $srcdir/testfile2.c.ref
rm testfile2.c.out

echo ./CFGTest -I$srcdir $srcdir/testfile3.c
./CFGTest -I$srcdir $srcdir/testfile3.c
echo "diff testfile3.c.out $srcdir/testfile3.c.cfg"
diff testfile3.c.out $srcdir/testfile3.c.cfg
rm testfile3.c.out

echo ./DataFlowTest -I$srcdir $srcdir/testfile3.c
./DataFlowTest -I$srcdir $srcdir/testfile3.c
echo "diff testfile3.c.out $srcdir/testfile3.c.du"
diff testfile3.c.out $srcdir/testfile3.c.du
rm testfile3.c.out

echo ./StmtRefTest -I$srcdir $srcdir/testfile3.c
./StmtRefTest -I$srcdir $srcdir/testfile3.c
echo "diff testfile3.c.out $srcdir/testfile3.c.ref"
diff testfile3.c.out $srcdir/testfile3.c.ref
rm testfile3.c.out

echo ./DataFlowTest -I$srcdir $srcdir/testfile4.c
./DataFlowTest -I$srcdir $srcdir/testfile4.c
echo "diff testfile4.c.out $srcdir/testfile4.c.du"
diff testfile4.c.out $srcdir/testfile4.c.du
rm testfile4.c.out
                                                                                                  
