#!/bin/sh

# Turn on error checking so that any error forces a failure of the script
set -e

if [ $# -ne 1 ]; then
  echo "Usage: $0 srcdir" 1>&2
  exit 1
fi

srcdir=$1

echo ./CFGTest -I$srcdir $srcdir/testfile1.c
./CFGTest -I$srcdir $srcdir/testfile1.c
echo "Calling: diff testfile1.c.out $srcdir/testfile1.c.cfg"
# PC (9/19/2006): files may be different under cygwin because of differences in
# system header files
diff testfile1.c.out $srcdir/testfile1.c.cfg || true
rm testfile1.c.out

echo ./DataFlowTest -I$srcdir $srcdir/testfile1.c
./DataFlowTest -I$srcdir $srcdir/testfile1.c
echo "Calling: diff testfile1.c.out $srcdir/testfile1.c.du"
# PC (9/18/2006): if DataFlowTest fails because of cygwin, ignore missing file
# PC (9/19/2006): files may be different under cygwin because of differences in
# system header files
test ! -f testfile1.c.out || diff testfile1.c.out $srcdir/testfile1.c.du || true
rm -f testfile1.c.out

echo ./StmtRefTest -I$srcdir $srcdir/testfile1.c
./StmtRefTest -I$srcdir $srcdir/testfile1.c
echo "diff testfile1.c.out $srcdir/testfile1.c.ref"
# PC (9/18/2006): if StmtRefTest fails because of cygwin, ignore missing file
# PC (9/19/2006): files may be different under cygwin because of differences in
# system header files
test ! -f testfile1.c.out || diff testfile1.c.out $srcdir/testfile1.c.ref || true
rm -f testfile1.c.out

echo ./CFGTest -I$srcdir $srcdir/testfile2.c
./CFGTest -I$srcdir $srcdir/testfile2.c
echo "diff testfile2.c.out $srcdir/testfile2.c.cfg"
diff testfile2.c.out $srcdir/testfile2.c.cfg || true
rm testfile2.c.out

echo ./DataFlowTest -I$srcdir $srcdir/testfile2.c
./DataFlowTest -I$srcdir $srcdir/testfile2.c
echo "diff testfile2.c.out $srcdir/testfile2.c.du"
# PC (9/18/2006): if DataFlowTest fails because of cygwin, ignore missing file
# PC (9/19/2006): files may be different under cygwin because of differences in
# system header files
test ! -f testfile2.c.out || diff testfile2.c.out $srcdir/testfile2.c.du || true
rm -f testfile2.c.out

echo ./StmtRefTest -I$srcdir $srcdir/testfile2.c
./StmtRefTest -I$srcdir $srcdir/testfile2.c
echo "diff testfile2.c.out $srcdir/testfile2.c.ref"
# PC (9/18/2006): if StmtRefTest fails because of cygwin, ignore missing file
# PC (9/19/2006): files may be different under cygwin because of differences in
# system header files
test ! -f testfile2.c.out || diff testfile2.c.out $srcdir/testfile2.c.ref || true
rm -f testfile2.c.out

echo ./CFGTest -I$srcdir $srcdir/testfile3.c
./CFGTest -I$srcdir $srcdir/testfile3.c
echo "diff testfile3.c.out $srcdir/testfile3.c.cfg"
# PC (9/19/2006): files may be different under cygwin because of differences in
# system header files
diff testfile3.c.out $srcdir/testfile3.c.cfg || true
rm testfile3.c.out

echo ./DataFlowTest -I$srcdir $srcdir/testfile3.c
./DataFlowTest -I$srcdir $srcdir/testfile3.c
echo "diff testfile3.c.out $srcdir/testfile3.c.du"
# PC (9/18/2006): if DataFlowTest fails because of cygwin, ignore missing file
# PC (9/19/2006): files may be different under cygwin because of differences in
# system header files
test ! -f testfile3.c.out || diff testfile3.c.out $srcdir/testfile3.c.du || true
rm -f testfile3.c.out

echo ./StmtRefTest -I$srcdir $srcdir/testfile3.c
./StmtRefTest -I$srcdir $srcdir/testfile3.c
echo "diff testfile3.c.out $srcdir/testfile3.c.ref"
# PC (9/18/2006): if StmtRefTest fails because of cygwin, ignore missing file
# PC (9/19/2006): files may be different under cygwin because of differences in
# system header files
test ! -f testfile3.c.out || diff testfile3.c.out $srcdir/testfile3.c.ref || true
rm -f testfile3.c.out

echo ./DataFlowTest -I$srcdir $srcdir/testfile4.c
./DataFlowTest -I$srcdir $srcdir/testfile4.c
echo "diff testfile4.c.out $srcdir/testfile4.c.du"
# PC (9/18/2006): if DataFlowTest fails because of cygwin, ignore missing file
# PC (9/19/2006): files may be different under cygwin because of differences in
# system header files
test ! -f testfile4.c.out || diff testfile4.c.out $srcdir/testfile4.c.du || true
rm -f testfile4.c.out
                                                                                                  
