#!/bin/bash

TESTPATH1=../../../tests/nonsmoke/functional/CompileTests/Cxx_tests
TESTPATH2=../../../tests/nonsmoke/functional/CompileTests/Cxx11_tests
PARSER1=sglr
PARSER2=sglri

./checkparser $PARSER1 $TESTPATH1
./checkparser $PARSER1 $TESTPATH2
./checkparser $PARSER2 $TESTPATH1
./checkparser $PARSER2 $TESTPATH2

