replace_varbasetype;f0;a;float
replace_varbasetype;f0;b;float
replace_varbasetype;f0;c;float
replace_varbasetype;f0;d;float
replace_varbasetype;f0;e;float
replace_varbasetype;f0;f;float
replace_varbasetype;f0;g;float
replace_varbasetype;f0;h;float
replace_varbasetype;f0;i;float
replace_varbasetype;f0;j;float
replace_varbasetype;f0;k;float
replace_vartype;f0;a;AD_real
replace_vartype;f0;b;AD_real
replace_vartype;f0;c;AD_real
replace_vartype;f0;d;AD_real
replace_vartype;f0;e;AD_real
replace_vartype;f0;f;AD_real
replace_vartype;f0;g;AD_real
replace_vartype;f0;h;AD_real
replace_vartype;f0;i;AD_real
replace_vartype;f0;j;AD_real
replace_vartype;f0;k;AD_real
replace_basetype;f1:args,body,ret;double=>float
replace_basetype;$global;double=>float
replace_varbasetype;$global;ga;AD_real
replace_varbasetype;$global;gb;AD_real
