replace_type;f1:args;A=>X
replace_type;f1:args;B=>Y
replace_type;f2:args;A*=>X
replace_type;f2:args;A**=>X*
replace_type;f3:args;A**=>X&
replace_type;f3:args;A=>X&
replace_type;f3:args;B=>Y*
replace_type;f4:args;A=>const X&
replace_type;f4:args;B=>Y&
replace_type;f5:args;A**=>const X&
replace_type;f4:args;B**=>Y&
replace_type;f1:body;A=>X
replace_type;f1:body;B=>Y
replace_type;f2:body;A*=>X**
replace_type;f2:body;A=>X
replace_type;f2:body;B=>Y
replace_vartype;f0;a1;AD_real
replace_vartype;f0;b;float
replace_vartype;f0;x;AD_real
replace_vartype;f0;y;float&
replace_vartype;f0;z;MyType**
replace_vartype;f6;a;float
replace_vartype;f6;b;float
replace_vartype;f6;c;float
replace_vartype;f6;d;float
replace_vartype;f6;e;float
replace_vartype;f6;f;float
replace_vartype;f6;g;float
replace_vartype;f6;h;float
replace_vartype;f6;i;float
replace_vartype;f6;j;float
replace_vartype;f6;k;float
replace_vartype;f6;l;float
replace_vartype;f6;m;float
