#!/bin/bash

# "Check 1: Parse ARAL file and generate ARAL file"
# "Check 2: Parse generated ARAL file"

echo
echo -e "File \t\t          Chk1    Chk2"
for i in tests/*.aral 
do echo -e -n "$i\t:";
if (./aral < $i > tmptest.aral) >& /dev/null; then
  echo -n " PASS"
else 
  echo -n " FAIL: ";
fi
if ./aral < tmptest.aral &>/dev/null; then
  echo -n "    PASS"
else
  echo -n "    FAIL: "
fi
echo
done
rm -f tmptest.aral
