#!/bin/sh -xv
# This script add the newly built EDG binaries into the internal ROSE svn repository. 
set -e
if test "x$SVN" = "x"; then SVN=svn; fi
if test $# -ne 3; then
  echo "Usage: $0 rose-repository-url-or-top_srcdir build-triplet" >&2
  exit 1
fi
if test -f rose_binary_compatibility_signature; then
  :
else
  echo "Error: this code should be run in the directory with rose_binary_compatibility_signature" >&2
  exit 1
fi
roseRepositoryUrl="$1"
buildTriplet="$2"
buildCompiler="$3"
signature=`cat rose_binary_compatibility_signature`
binaryEdgTarball="roseBinaryEDG-${buildTriplet}-${buildCompiler}-${signature}.tar.gz"
if test -f ${binaryEdgTarball}; then
  :
else
  echo "Error: this code should be run in the directory with the EDG tarball ${binaryEdgTarball}" >&2
  exit 1
fi
checkoutDir=tempCheckout_CxxFrontend_`hostname`_$$
${SVN} checkout -N ${roseRepositoryUrl}/src/frontend/CxxFrontend ${checkoutDir} # FIXME Not secure
# This reports the binaries not matching the current signature and removes them from svn.
${SVN} ls ${checkoutDir} | grep -x 'roseBinaryEDG-.*-.*\.tar\.gz' | grep -vx 'roseBinaryEDG-.*-'${signature}'\.tar\.gz' | while read oldBinary; do ${SVN} rm ${checkoutDir}/${oldBinary}; done
# cp ${binaryEdgTarball} ${checkoutDir}/${binaryEdgTarball}
if test -e ${checkoutDir}/${binaryEdgTarball}; then
  echo "File already exists, skip copying it ..."
else
  cp ${binaryEdgTarball} ${checkoutDir}/${binaryEdgTarball}
fi
${SVN} add ${checkoutDir}/${binaryEdgTarball}
${SVN} status ${checkoutDir}
${SVN} commit -m"Automatic updates of binary EDG tarballs." ${checkoutDir}
rm -rf ${checkoutDir}
