#!/bin/sh -xv
# This script add the newly built EDG binaries into the internal ROSE svn repository. 
set -e
if test "x$SVN" = "x"; then SVN=svn; fi
if test $# -ne 4; then
  echo "Usage: $0 rose-repository-url-or-top_srcdir build-triplet revision-number" >&2
  exit 1
fi

if test -f rose_binary_compatibility_signature; then
  :
else
  echo "Error: this code should be run in the directory with rose_binary_compatibility_signature" >&2
  exit 1
fi
roseRepositoryUrl="$1"
buildTriplet="$2"
buildCompiler="$3"
revisionNumber="$4" # add revision number to be aware possible stale binary
signature=`cat rose_binary_compatibility_signature`
binaryEdgTarball="roseBinaryEDG-${buildTriplet}-${buildCompiler}-${signature}.tar.gz"
if test -f ${binaryEdgTarball}; then
  :
else
  echo "Error: this code should be run in the directory with the EDG tarball ${binaryEdgTarball}" >&2
  exit 1
fi
checkoutDir=tempCheckout_CxxFrontend_`hostname`_$$
${SVN} checkout -N ${roseRepositoryUrl}/src/frontend/CxxFrontend ${checkoutDir} # FIXME Not secure
# This reports the binaries not matching the current signature and removes them from svn.
${SVN} ls ${checkoutDir} | grep -x 'roseBinaryEDG-.*-.*\.tar\.gz' | grep -vx 'roseBinaryEDG-.*-'${signature}'\.tar\.gz' | while read oldBinary; do ${SVN} rm ${checkoutDir}/${oldBinary}; done
# cp ${binaryEdgTarball} ${checkoutDir}/${binaryEdgTarball}
if test -e ${checkoutDir}/${binaryEdgTarball}; then
  echo "File already exists, skip copying it ..."
else
  cp ${binaryEdgTarball} ${checkoutDir}/${binaryEdgTarball}
fi

# Liao, 9/25/2009
# make sure the binary is not stale, based on its revision number and the latest binary file's revision number in the repository
mytempfile=ttt$$
# DQ (9/26/2009): Suggested fix by Liao (-l option only works with SVN 1.5)
# svn log -l 100 file:///usr/casc/overture/ROSE/svn/ROSE/trunk/ROSE > $mytempfile
# ${SVN} log --limit 100 file:///usr/casc/overture/ROSE/svn/ROSE/trunk/ROSE > $mytempfile

# DQ (9/28/2009): Note that "-l" is not in svn 1.4 (where it is "--limit") and even 
# "--limit" is not in older versions of SVN.  So since this is such a problem, output
# the version of SVN so that if it fails we can better debug this.  Many machines have
# quite old versions of SVN installed by default.
${SVN} --version

# DQ (9/27/2009): for the Mac OSX we are not directly connected to the LC so the reference 
# to file:///usr/casc/overture/ROSE/svn/ROSE/trunk/ROSE fails and we have to use:
# svn+ssh://tux270.llnl.gov/usr/casc/overture/ROSE/svn/ROSE/trunk/ROSE
# This test will at least work on ninjai which is running "Darwin" OSX.
if test `uname` = "Darwin"; then
# Must use: svn+ssh://tux270.llnl.gov/usr/casc/overture/ROSE/svn/ROSE/trunk/ROSE
  echo "Running on OSX (special handling for svn repository access is required)"
  ${SVN} log --limit 100 svn+ssh://tux270.llnl.gov/usr/casc/overture/ROSE/svn/ROSE/trunk/ROSE > $mytempfile
else
# This is the non-OSX case that is what everyone but Dan sees.
  ${SVN} log --limit 100 file:///usr/casc/overture/ROSE/svn/ROSE/trunk/ROSE > $mytempfile
fi

LASTEST_BIN_REV_NO=`cat $mytempfile | grep -m 1 "Automatic updates of binary EDG" | cut -f 10 -d' '`
rm -rf $mytempfile

# be prepared that the log message has no 10th field at all
if [ "x$LASTEST_BIN_REV_NO" != "x" ]; then
  if [ 0$LASTEST_BIN_REV_NO -ne 0 ]; then
     if test $revisionNumber -lt $LASTEST_BIN_REV_NO ; then
       echo "Trying to commit a stale binary  which is  generated from rev $revisionNumber"
       echo "while the repository already has a binary from rev $LASTEST_BIN_REV_NO."
       rm -rf ${checkoutDir}
       exit 1 
     fi
  else
    echo "cannot find the revision number of the most recent binary file in the repository. Proceed to commit anyway."
  fi
else
  echo "cannot find the revision number of the most recent binary file in the repository. Proceed to commit anyway."
fi


${SVN} add ${checkoutDir}/${binaryEdgTarball}
${SVN} status ${checkoutDir}
# Liao, 9/25/2009 the last field of the commit message must be a revision number only, without period or so.
${SVN} commit -m"Automatic updates of binary EDG tarballs based on rev ${revisionNumber} for ${buildTriplet}-${buildCompiler}" ${checkoutDir}
rm -rf ${checkoutDir}
