#!/bin/sh -xv
# This script copy the newly-built EDG binaries to the source tree
set -e
if test $# -ne 3; then
  echo "Usage: $0 top_srcdir build-triplet" >&2
  exit 1
fi
if test -f rose_binary_compatibility_signature; then
  :
else
  echo "Error: this code should be run in the directory with rose_binary_compatibility_signature" >&2
  exit 1
fi
top_srcdir="$1"
buildTriplet="$2"
buildCompiler="$3"
signature=`cat rose_binary_compatibility_signature`
binaryEdgTarball="roseBinaryEDG-${buildTriplet}-${buildCompiler}-${signature}.tar.gz"
if test -f ${binaryEdgTarball}; then
  :
else
  echo "Error: this code should be run in the directory with the EDG tarball ${binaryEdgTarball}" >&2
  exit 1
fi
ls -1 ${top_srcdir}/src/frontend/CxxFrontend | grep -x 'roseBinaryEDG-.*-.*\.tar\.gz' | grep -vx 'roseBinaryEDG-.*-'${signature}'\.tar\.gz' | while read oldBinary; do rm ${top_srcdir}/src/frontend/CxxFrontend/${oldBinary}; done
cp ${binaryEdgTarball} ${top_srcdir}/src/frontend/CxxFrontend/${binaryEdgTarball}
