#!/bin/bash

# Run this script with "--help" to see nicely formatted info; or just read the perldoc here...
:<<=cut

=head1 NAME

edg-generate-sig - generate or find an EDG binary tarball version number

=head1 SYNOPSIS

edg-generate-sig TOP_SRCDIR TOP_BLDDIR

=head1 DESCRIPTION

End users do not generally have licenses for EDG source code. Therefore, the ROSE team compiles an EDG binary library
for most ROSE public releases.  EDG binary version numbers are based upon the ROSE version number but only needs to be
incremented when a change is made that will modify the binary file.

=head1 AUTHORS

Robb Matzke.
Nathan Pinnow.

Copyright Lawrence Livermore National Security

Licensed under Revised BSD License (see COPYRIGHT file at the top of the ROSE source tree)

=cut
#------------------------------------------------------------------------------------------------------------------------

myname="${0##*/}"
mydir="${0%$myname}"
myname="${myname-edg-generate-sig}"

help () {
    LESS="$LESS -R"
    (pod2man $0 |nroff -man || pod2text $0 || sed -ne '/^=pod/,/^=cut/p' $0) 2>/dev/null | ${PAGER-less}
}

# Parse command-line switches
do_dump=
while [ "$#" -gt 0 ]; do
    case "$1" in
	--help|-h|-\?) help; exit 0 ;;
	--dump) do_dump=yes; shift ;;
	-*) echo "$myname: unrecognized switch: $1" >&2; exit 1 ;;
	*) break
    esac
done

if [ "$#" -ne 2 ]; then
    echo "usage: $myname TOP_SRCDIR TOP_BLDDIR" >&2
    echo "       for details, see: $0 --help" >&2
    exit 1;
fi

ROSE_SRC="$1"
ROSE_BLD="$2"

# These are the ROSETTA-generated files on which the EDG binary tarball depends
EDG_GENERATED_DEPENDENCIES=("$ROSE_BLD/src/frontend/SageIII/Cxx_Grammar.h"
			    "$ROSE_BLD/src/frontend/SageIII/Cxx_GrammarDeclarations.h"
			    "$ROSE_BLD/src/frontend/SageIII/Cxx_GrammarDowncast.h"
			    "$ROSE_BLD/src/frontend/SageIII/Cxx_GrammarStorageClasses.h"
			    "$ROSE_BLD/src/frontend/SageIII/Cxx_GrammarSgNodeDefinitions.h"
			    "$ROSE_BLD/src/frontend/SageIII/Cxx_GrammarSgAsmNodeDefinitions.h"
			    "$ROSE_BLD/src/frontend/SageIII/Cxx_GrammarSgAsmCilNodeDefinitions.h"
			    "$ROSE_BLD/src/frontend/SageIII/Cxx_GrammarSgAsmDwarfNodeDefinitions.h"
			    "$ROSE_BLD/src/frontend/SageIII/Cxx_GrammarSgAsmJvmNodeDefinitions.h"
			    "$ROSE_BLD/src/frontend/SageIII/Cxx_GrammarVariants.h"
			    "$ROSE_BLD/src/frontend/SageIII/Cxx_GrammarVisitorSupport.h"
			    "$ROSE_BLD/src/frontend/SageIII/AstQueryMemoryPool.h"
			    "$ROSE_BLD/src/frontend/SageIII/Cxx_GrammarTreeTraversalAccessEnums.h"
			    "$ROSE_BLD/src/frontend/SageIII/Cxx_GrammarMemoryPoolSupport.h"
			    "$ROSE_BLD/src/frontend/SageIII/AST_FILE_IO.h"
			    "$ROSE_BLD/src/frontend/SageIII/StorageClasses.h"
			    "$ROSE_BLD/src/frontend/SageIII/SgNode.h"
                            "$ROSE_BLD/src/frontend/SageIII/SgAsmAarch32Coprocessor.h"
                            "$ROSE_BLD/src/frontend/SageIII/SgAsmAarch32Instruction.h"
                            "$ROSE_BLD/src/frontend/SageIII/SgAsmAarch64AtOperand.h"
                            "$ROSE_BLD/src/frontend/SageIII/SgAsmAarch64BarrierOperand.h"
                            "$ROSE_BLD/src/frontend/SageIII/SgAsmAarch64CImmediateOperand.h"
                            "$ROSE_BLD/src/frontend/SageIII/SgAsmAarch64Instruction.h"
                            "$ROSE_BLD/src/frontend/SageIII/SgAsmAarch64PrefetchOperand.h"
                            "$ROSE_BLD/src/frontend/SageIII/SgAsmAarch64SysMoveOperand.h"
                            "$ROSE_BLD/src/frontend/SageIII/SgAsmBasicString.h"
                            "$ROSE_BLD/src/frontend/SageIII/SgAsmBinaryAdd.h"
                            "$ROSE_BLD/src/frontend/SageIII/SgAsmBinaryAsr.h"
                            "$ROSE_BLD/src/frontend/SageIII/SgAsmBinaryConcat.h"
                            "$ROSE_BLD/src/frontend/SageIII/SgAsmBinaryDivide.h"
                            "$ROSE_BLD/src/frontend/SageIII/SgAsmBinaryExpression.h"
                            "$ROSE_BLD/src/frontend/SageIII/SgAsmBinaryLsl.h"
                            "$ROSE_BLD/src/frontend/SageIII/SgAsmBinaryLsr.h"
                            "$ROSE_BLD/src/frontend/SageIII/SgAsmBinaryMod.h"
                            "$ROSE_BLD/src/frontend/SageIII/SgAsmBinaryMsl.h"
                            "$ROSE_BLD/src/frontend/SageIII/SgAsmBinaryMultiply.h"
                            "$ROSE_BLD/src/frontend/SageIII/SgAsmBinaryPostupdate.h"
                            "$ROSE_BLD/src/frontend/SageIII/SgAsmBinaryPreupdate.h"
                            "$ROSE_BLD/src/frontend/SageIII/SgAsmBinaryRor.h"
                            "$ROSE_BLD/src/frontend/SageIII/SgAsmBinarySubtract.h"
                            "$ROSE_BLD/src/frontend/SageIII/SgAsmBlock.h"
                            "$ROSE_BLD/src/frontend/SageIII/SgAsmByteOrder.h"
                            "$ROSE_BLD/src/frontend/SageIII/SgAsmCilAssembly.h"
                            "$ROSE_BLD/src/frontend/SageIII/SgAsmCilAssemblyOS.h"
                            "$ROSE_BLD/src/frontend/SageIII/SgAsmCilAssemblyOSTable.h"
                            "$ROSE_BLD/src/frontend/SageIII/SgAsmCilAssemblyProcessor.h"
                            "$ROSE_BLD/src/frontend/SageIII/SgAsmCilAssemblyProcessorTable.h"
                            "$ROSE_BLD/src/frontend/SageIII/SgAsmCilAssemblyRef.h"
                            "$ROSE_BLD/src/frontend/SageIII/SgAsmCilAssemblyRefOS.h"
                            "$ROSE_BLD/src/frontend/SageIII/SgAsmCilAssemblyRefOSTable.h"
                            "$ROSE_BLD/src/frontend/SageIII/SgAsmCilAssemblyRefProcessor.h"
                            "$ROSE_BLD/src/frontend/SageIII/SgAsmCilAssemblyRefProcessorTable.h"
                            "$ROSE_BLD/src/frontend/SageIII/SgAsmCilAssemblyRefTable.h"
                            "$ROSE_BLD/src/frontend/SageIII/SgAsmCilAssemblyTable.h"
                            "$ROSE_BLD/src/frontend/SageIII/SgAsmCilClassLayout.h"
                            "$ROSE_BLD/src/frontend/SageIII/SgAsmCilClassLayoutTable.h"
                            "$ROSE_BLD/src/frontend/SageIII/SgAsmCilConstant.h"
                            "$ROSE_BLD/src/frontend/SageIII/SgAsmCilConstantTable.h"
                            "$ROSE_BLD/src/frontend/SageIII/SgAsmCilCustomAttribute.h"
                            "$ROSE_BLD/src/frontend/SageIII/SgAsmCilCustomAttributeTable.h"
                            "$ROSE_BLD/src/frontend/SageIII/SgAsmCilDataStream.h"
                            "$ROSE_BLD/src/frontend/SageIII/SgAsmCilDeclSecurity.h"
                            "$ROSE_BLD/src/frontend/SageIII/SgAsmCilDeclSecurityTable.h"
                            "$ROSE_BLD/src/frontend/SageIII/SgAsmCilEvent.h"
                            "$ROSE_BLD/src/frontend/SageIII/SgAsmCilEventMap.h"
                            "$ROSE_BLD/src/frontend/SageIII/SgAsmCilEventMapTable.h"
                            "$ROSE_BLD/src/frontend/SageIII/SgAsmCilEventTable.h"
                            "$ROSE_BLD/src/frontend/SageIII/SgAsmCilExportedType.h"
                            "$ROSE_BLD/src/frontend/SageIII/SgAsmCilExportedTypeTable.h"
                            "$ROSE_BLD/src/frontend/SageIII/SgAsmCilField.h"
                            "$ROSE_BLD/src/frontend/SageIII/SgAsmCilFieldLayout.h"
                            "$ROSE_BLD/src/frontend/SageIII/SgAsmCilFieldLayoutTable.h"
                            "$ROSE_BLD/src/frontend/SageIII/SgAsmCilFieldMarshal.h"
                            "$ROSE_BLD/src/frontend/SageIII/SgAsmCilFieldMarshalTable.h"
                            "$ROSE_BLD/src/frontend/SageIII/SgAsmCilFieldRVA.h"
                            "$ROSE_BLD/src/frontend/SageIII/SgAsmCilFieldRVATable.h"
                            "$ROSE_BLD/src/frontend/SageIII/SgAsmCilFieldTable.h"
                            "$ROSE_BLD/src/frontend/SageIII/SgAsmCilFile.h"
                            "$ROSE_BLD/src/frontend/SageIII/SgAsmCilFileTable.h"
                            "$ROSE_BLD/src/frontend/SageIII/SgAsmCilGenericParamConstraint.h"
                            "$ROSE_BLD/src/frontend/SageIII/SgAsmCilGenericParamConstraintTable.h"
                            "$ROSE_BLD/src/frontend/SageIII/SgAsmCilGenericParam.h"
                            "$ROSE_BLD/src/frontend/SageIII/SgAsmCilGenericParamTable.h"
                            "$ROSE_BLD/src/frontend/SageIII/SgAsmCilImplMap.h"
                            "$ROSE_BLD/src/frontend/SageIII/SgAsmCilImplMapTable.h"
                            "$ROSE_BLD/src/frontend/SageIII/SgAsmCilInstruction.h"
                            "$ROSE_BLD/src/frontend/SageIII/SgAsmCilInterfaceImpl.h"
                            "$ROSE_BLD/src/frontend/SageIII/SgAsmCilInterfaceImplTable.h"
                            "$ROSE_BLD/src/frontend/SageIII/SgAsmCilManifestResource.h"
                            "$ROSE_BLD/src/frontend/SageIII/SgAsmCilManifestResourceTable.h"
                            "$ROSE_BLD/src/frontend/SageIII/SgAsmCilMemberRef.h"
                            "$ROSE_BLD/src/frontend/SageIII/SgAsmCilMemberRefTable.h"
                            "$ROSE_BLD/src/frontend/SageIII/SgAsmCilMetadata.h"
                            "$ROSE_BLD/src/frontend/SageIII/SgAsmCilMetadataHeap.h"
                            "$ROSE_BLD/src/frontend/SageIII/SgAsmCilMetadataRoot.h"
                            "$ROSE_BLD/src/frontend/SageIII/SgAsmCilMethodDef.h"
                            "$ROSE_BLD/src/frontend/SageIII/SgAsmCilMethodDefTable.h"
                            "$ROSE_BLD/src/frontend/SageIII/SgAsmCilMethodImpl.h"
                            "$ROSE_BLD/src/frontend/SageIII/SgAsmCilMethodImplTable.h"
                            "$ROSE_BLD/src/frontend/SageIII/SgAsmCilMethodSemantics.h"
                            "$ROSE_BLD/src/frontend/SageIII/SgAsmCilMethodSemanticsTable.h"
                            "$ROSE_BLD/src/frontend/SageIII/SgAsmCilMethodSpec.h"
                            "$ROSE_BLD/src/frontend/SageIII/SgAsmCilMethodSpecTable.h"
                            "$ROSE_BLD/src/frontend/SageIII/SgAsmCilModule.h"
                            "$ROSE_BLD/src/frontend/SageIII/SgAsmCilModuleRef.h"
                            "$ROSE_BLD/src/frontend/SageIII/SgAsmCilModuleRefTable.h"
                            "$ROSE_BLD/src/frontend/SageIII/SgAsmCilModuleTable.h"
                            "$ROSE_BLD/src/frontend/SageIII/SgAsmCilNestedClass.h"
                            "$ROSE_BLD/src/frontend/SageIII/SgAsmCilNestedClassTable.h"
                            "$ROSE_BLD/src/frontend/SageIII/SgAsmCilNode.h"
                            "$ROSE_BLD/src/frontend/SageIII/SgAsmCilParam.h"
                            "$ROSE_BLD/src/frontend/SageIII/SgAsmCilParamTable.h"
                            "$ROSE_BLD/src/frontend/SageIII/SgAsmCilProperty.h"
                            "$ROSE_BLD/src/frontend/SageIII/SgAsmCilPropertyMap.h"
                            "$ROSE_BLD/src/frontend/SageIII/SgAsmCilPropertyMapTable.h"
                            "$ROSE_BLD/src/frontend/SageIII/SgAsmCilPropertyTable.h"
                            "$ROSE_BLD/src/frontend/SageIII/SgAsmCilStandAloneSig.h"
                            "$ROSE_BLD/src/frontend/SageIII/SgAsmCilStandAloneSigTable.h"
                            "$ROSE_BLD/src/frontend/SageIII/SgAsmCilTypeDef.h"
                            "$ROSE_BLD/src/frontend/SageIII/SgAsmCilTypeDefTable.h"
                            "$ROSE_BLD/src/frontend/SageIII/SgAsmCilTypeRef.h"
                            "$ROSE_BLD/src/frontend/SageIII/SgAsmCilTypeRefTable.h"
                            "$ROSE_BLD/src/frontend/SageIII/SgAsmCilTypeSpec.h"
                            "$ROSE_BLD/src/frontend/SageIII/SgAsmCilTypeSpecTable.h"
                            "$ROSE_BLD/src/frontend/SageIII/SgAsmCilUint32Heap.h"
                            "$ROSE_BLD/src/frontend/SageIII/SgAsmCilUint8Heap.h"
                            "$ROSE_BLD/src/frontend/SageIII/SgAsmCliHeader.h"
                            "$ROSE_BLD/src/frontend/SageIII/SgAsmCoffStrtab.h"
                            "$ROSE_BLD/src/frontend/SageIII/SgAsmCoffSymbol.h"
                            "$ROSE_BLD/src/frontend/SageIII/SgAsmCoffSymbolList.h"
                            "$ROSE_BLD/src/frontend/SageIII/SgAsmCoffSymbolTable.h"
                            "$ROSE_BLD/src/frontend/SageIII/SgAsmCommonSubExpression.h"
                            "$ROSE_BLD/src/frontend/SageIII/SgAsmConstantExpression.h"
                            "$ROSE_BLD/src/frontend/SageIII/SgAsmControlFlagsExpression.h"
                            "$ROSE_BLD/src/frontend/SageIII/SgAsmDirectRegisterExpression.h"
                            "$ROSE_BLD/src/frontend/SageIII/SgAsmDOSExtendedHeader.h"
                            "$ROSE_BLD/src/frontend/SageIII/SgAsmDOSFileHeader.h"
                            "$ROSE_BLD/src/frontend/SageIII/SgAsmDwarfAccessDeclaration.h"
                            "$ROSE_BLD/src/frontend/SageIII/SgAsmDwarfArrayType.h"
                            "$ROSE_BLD/src/frontend/SageIII/SgAsmDwarfBaseType.h"
                            "$ROSE_BLD/src/frontend/SageIII/SgAsmDwarfCatchBlock.h"
                            "$ROSE_BLD/src/frontend/SageIII/SgAsmDwarfClassTemplate.h"
                            "$ROSE_BLD/src/frontend/SageIII/SgAsmDwarfClassType.h"
                            "$ROSE_BLD/src/frontend/SageIII/SgAsmDwarfCommonBlock.h"
                            "$ROSE_BLD/src/frontend/SageIII/SgAsmDwarfCommonInclusion.h"
                            "$ROSE_BLD/src/frontend/SageIII/SgAsmDwarfCompilationUnit.h"
                            "$ROSE_BLD/src/frontend/SageIII/SgAsmDwarfCompilationUnitList.h"
                            "$ROSE_BLD/src/frontend/SageIII/SgAsmDwarfCondition.h"
                            "$ROSE_BLD/src/frontend/SageIII/SgAsmDwarfConstant.h"
                            "$ROSE_BLD/src/frontend/SageIII/SgAsmDwarfConstruct.h"
                            "$ROSE_BLD/src/frontend/SageIII/SgAsmDwarfConstructList.h"
                            "$ROSE_BLD/src/frontend/SageIII/SgAsmDwarfConstType.h"
                            "$ROSE_BLD/src/frontend/SageIII/SgAsmDwarfDwarfProcedure.h"
                            "$ROSE_BLD/src/frontend/SageIII/SgAsmDwarfEntryPoint.h"
                            "$ROSE_BLD/src/frontend/SageIII/SgAsmDwarfEnumerationType.h"
                            "$ROSE_BLD/src/frontend/SageIII/SgAsmDwarfEnumerator.h"
                            "$ROSE_BLD/src/frontend/SageIII/SgAsmDwarfFileType.h"
                            "$ROSE_BLD/src/frontend/SageIII/SgAsmDwarfFormalParameter.h"
                            "$ROSE_BLD/src/frontend/SageIII/SgAsmDwarfFormatLabel.h"
                            "$ROSE_BLD/src/frontend/SageIII/SgAsmDwarfFriend.h"
                            "$ROSE_BLD/src/frontend/SageIII/SgAsmDwarfFunctionTemplate.h"
                            "$ROSE_BLD/src/frontend/SageIII/SgAsmDwarfImportedDeclaration.h"
                            "$ROSE_BLD/src/frontend/SageIII/SgAsmDwarfImportedModule.h"
                            "$ROSE_BLD/src/frontend/SageIII/SgAsmDwarfImportedUnit.h"
                            "$ROSE_BLD/src/frontend/SageIII/SgAsmDwarfInformation.h"
                            "$ROSE_BLD/src/frontend/SageIII/SgAsmDwarfInheritance.h"
                            "$ROSE_BLD/src/frontend/SageIII/SgAsmDwarfInlinedSubroutine.h"
                            "$ROSE_BLD/src/frontend/SageIII/SgAsmDwarfInterfaceType.h"
                            "$ROSE_BLD/src/frontend/SageIII/SgAsmDwarfLabel.h"
                            "$ROSE_BLD/src/frontend/SageIII/SgAsmDwarfLexicalBlock.h"
                            "$ROSE_BLD/src/frontend/SageIII/SgAsmDwarfLine.h"
                            "$ROSE_BLD/src/frontend/SageIII/SgAsmDwarfLineList.h"
                            "$ROSE_BLD/src/frontend/SageIII/SgAsmDwarfMacro.h"
                            "$ROSE_BLD/src/frontend/SageIII/SgAsmDwarfMacroList.h"
                            "$ROSE_BLD/src/frontend/SageIII/SgAsmDwarfMember.h"
                            "$ROSE_BLD/src/frontend/SageIII/SgAsmDwarfModule.h"
                            "$ROSE_BLD/src/frontend/SageIII/SgAsmDwarfMutableType.h"
                            "$ROSE_BLD/src/frontend/SageIII/SgAsmDwarfNamelist.h"
                            "$ROSE_BLD/src/frontend/SageIII/SgAsmDwarfNamelistItem.h"
                            "$ROSE_BLD/src/frontend/SageIII/SgAsmDwarfNamespace.h"
                            "$ROSE_BLD/src/frontend/SageIII/SgAsmDwarfPackedType.h"
                            "$ROSE_BLD/src/frontend/SageIII/SgAsmDwarfPartialUnit.h"
                            "$ROSE_BLD/src/frontend/SageIII/SgAsmDwarfPointerType.h"
                            "$ROSE_BLD/src/frontend/SageIII/SgAsmDwarfPtrToMemberType.h"
                            "$ROSE_BLD/src/frontend/SageIII/SgAsmDwarfReferenceType.h"
                            "$ROSE_BLD/src/frontend/SageIII/SgAsmDwarfRestrictType.h"
                            "$ROSE_BLD/src/frontend/SageIII/SgAsmDwarfSetType.h"
                            "$ROSE_BLD/src/frontend/SageIII/SgAsmDwarfSharedType.h"
                            "$ROSE_BLD/src/frontend/SageIII/SgAsmDwarfStringType.h"
                            "$ROSE_BLD/src/frontend/SageIII/SgAsmDwarfStructureType.h"
                            "$ROSE_BLD/src/frontend/SageIII/SgAsmDwarfSubprogram.h"
                            "$ROSE_BLD/src/frontend/SageIII/SgAsmDwarfSubrangeType.h"
                            "$ROSE_BLD/src/frontend/SageIII/SgAsmDwarfSubroutineType.h"
                            "$ROSE_BLD/src/frontend/SageIII/SgAsmDwarfTemplateTypeParameter.h"
                            "$ROSE_BLD/src/frontend/SageIII/SgAsmDwarfTemplateValueParameter.h"
                            "$ROSE_BLD/src/frontend/SageIII/SgAsmDwarfThrownType.h"
                            "$ROSE_BLD/src/frontend/SageIII/SgAsmDwarfTryBlock.h"
                            "$ROSE_BLD/src/frontend/SageIII/SgAsmDwarfTypedef.h"
                            "$ROSE_BLD/src/frontend/SageIII/SgAsmDwarfUnionType.h"
                            "$ROSE_BLD/src/frontend/SageIII/SgAsmDwarfUnknownConstruct.h"
                            "$ROSE_BLD/src/frontend/SageIII/SgAsmDwarfUnspecifiedParameters.h"
                            "$ROSE_BLD/src/frontend/SageIII/SgAsmDwarfUnspecifiedType.h"
                            "$ROSE_BLD/src/frontend/SageIII/SgAsmDwarfUpcRelaxedType.h"
                            "$ROSE_BLD/src/frontend/SageIII/SgAsmDwarfUpcSharedType.h"
                            "$ROSE_BLD/src/frontend/SageIII/SgAsmDwarfUpcStrictType.h"
                            "$ROSE_BLD/src/frontend/SageIII/SgAsmDwarfVariable.h"
                            "$ROSE_BLD/src/frontend/SageIII/SgAsmDwarfVariant.h"
                            "$ROSE_BLD/src/frontend/SageIII/SgAsmDwarfVariantPart.h"
                            "$ROSE_BLD/src/frontend/SageIII/SgAsmDwarfVolatileType.h"
                            "$ROSE_BLD/src/frontend/SageIII/SgAsmDwarfWithStmt.h"
                            "$ROSE_BLD/src/frontend/SageIII/SgAsmElfDynamicEntry.h"
                            "$ROSE_BLD/src/frontend/SageIII/SgAsmElfDynamicEntryList.h"
                            "$ROSE_BLD/src/frontend/SageIII/SgAsmElfDynamicSection.h"
                            "$ROSE_BLD/src/frontend/SageIII/SgAsmElfEHFrameEntryCI.h"
                            "$ROSE_BLD/src/frontend/SageIII/SgAsmElfEHFrameEntryCIList.h"
                            "$ROSE_BLD/src/frontend/SageIII/SgAsmElfEHFrameEntryFD.h"
                            "$ROSE_BLD/src/frontend/SageIII/SgAsmElfEHFrameEntryFDList.h"
                            "$ROSE_BLD/src/frontend/SageIII/SgAsmElfEHFrameSection.h"
                            "$ROSE_BLD/src/frontend/SageIII/SgAsmElfFileHeader.h"
                            "$ROSE_BLD/src/frontend/SageIII/SgAsmElfNoteEntry.h"
                            "$ROSE_BLD/src/frontend/SageIII/SgAsmElfNoteEntryList.h"
                            "$ROSE_BLD/src/frontend/SageIII/SgAsmElfNoteSection.h"
                            "$ROSE_BLD/src/frontend/SageIII/SgAsmElfRelocEntry.h"
                            "$ROSE_BLD/src/frontend/SageIII/SgAsmElfRelocEntryList.h"
                            "$ROSE_BLD/src/frontend/SageIII/SgAsmElfRelocSection.h"
                            "$ROSE_BLD/src/frontend/SageIII/SgAsmElfSection.h"
                            "$ROSE_BLD/src/frontend/SageIII/SgAsmElfSectionTableEntry.h"
                            "$ROSE_BLD/src/frontend/SageIII/SgAsmElfSectionTable.h"
                            "$ROSE_BLD/src/frontend/SageIII/SgAsmElfSegmentTableEntry.h"
                            "$ROSE_BLD/src/frontend/SageIII/SgAsmElfSegmentTableEntryList.h"
                            "$ROSE_BLD/src/frontend/SageIII/SgAsmElfSegmentTable.h"
                            "$ROSE_BLD/src/frontend/SageIII/SgAsmElfStringSection.h"
                            "$ROSE_BLD/src/frontend/SageIII/SgAsmElfStrtab.h"
                            "$ROSE_BLD/src/frontend/SageIII/SgAsmElfSymbol.h"
                            "$ROSE_BLD/src/frontend/SageIII/SgAsmElfSymbolList.h"
                            "$ROSE_BLD/src/frontend/SageIII/SgAsmElfSymbolSection.h"
                            "$ROSE_BLD/src/frontend/SageIII/SgAsmElfSymverDefinedAux.h"
                            "$ROSE_BLD/src/frontend/SageIII/SgAsmElfSymverDefinedAuxList.h"
                            "$ROSE_BLD/src/frontend/SageIII/SgAsmElfSymverDefinedEntry.h"
                            "$ROSE_BLD/src/frontend/SageIII/SgAsmElfSymverDefinedEntryList.h"
                            "$ROSE_BLD/src/frontend/SageIII/SgAsmElfSymverDefinedSection.h"
                            "$ROSE_BLD/src/frontend/SageIII/SgAsmElfSymverEntry.h"
                            "$ROSE_BLD/src/frontend/SageIII/SgAsmElfSymverEntryList.h"
                            "$ROSE_BLD/src/frontend/SageIII/SgAsmElfSymverNeededAux.h"
                            "$ROSE_BLD/src/frontend/SageIII/SgAsmElfSymverNeededAuxList.h"
                            "$ROSE_BLD/src/frontend/SageIII/SgAsmElfSymverNeededEntry.h"
                            "$ROSE_BLD/src/frontend/SageIII/SgAsmElfSymverNeededEntryList.h"
                            "$ROSE_BLD/src/frontend/SageIII/SgAsmElfSymverNeededSection.h"
                            "$ROSE_BLD/src/frontend/SageIII/SgAsmElfSymverSection.h"
                            "$ROSE_BLD/src/frontend/SageIII/SgAsmExecutableFileFormat.h"
                            "$ROSE_BLD/src/frontend/SageIII/SgAsmExpression.h"
                            "$ROSE_BLD/src/frontend/SageIII/SgAsmExprListExp.h"
                            "$ROSE_BLD/src/frontend/SageIII/SgAsmFloatType.h"
                            "$ROSE_BLD/src/frontend/SageIII/SgAsmFloatValueExpression.h"
                            "$ROSE_BLD/src/frontend/SageIII/SgAsmFunction.h"
                            "$ROSE_BLD/src/frontend/SageIII/SgAsmGenericDLL.h"
                            "$ROSE_BLD/src/frontend/SageIII/SgAsmGenericDLLList.h"
                            "$ROSE_BLD/src/frontend/SageIII/SgAsmGenericFile.h"
                            "$ROSE_BLD/src/frontend/SageIII/SgAsmGenericFileList.h"
                            "$ROSE_BLD/src/frontend/SageIII/SgAsmGenericFormat.h"
                            "$ROSE_BLD/src/frontend/SageIII/SgAsmGenericHeader.h"
                            "$ROSE_BLD/src/frontend/SageIII/SgAsmGenericHeaderList.h"
                            "$ROSE_BLD/src/frontend/SageIII/SgAsmGenericSection.h"
                            "$ROSE_BLD/src/frontend/SageIII/SgAsmGenericSectionList.h"
                            "$ROSE_BLD/src/frontend/SageIII/SgAsmGenericString.h"
                            "$ROSE_BLD/src/frontend/SageIII/SgAsmGenericStrtab.h"
                            "$ROSE_BLD/src/frontend/SageIII/SgAsmGenericSymbol.h"
                            "$ROSE_BLD/src/frontend/SageIII/SgAsmGenericSymbolList.h"
                            "$ROSE_BLD/src/frontend/SageIII/SgAsmIndirectRegisterExpression.h"
                            "$ROSE_BLD/src/frontend/SageIII/SgAsmInstruction.h"
                            "$ROSE_BLD/src/frontend/SageIII/SgAsmInstructionList.h"
                            "$ROSE_BLD/src/frontend/SageIII/SgAsmIntegerType.h"
                            "$ROSE_BLD/src/frontend/SageIII/SgAsmIntegerValueExpression.h"
                            "$ROSE_BLD/src/frontend/SageIII/SgAsmInterpretation.h"
                            "$ROSE_BLD/src/frontend/SageIII/SgAsmInterpretationList.h"
                            "$ROSE_BLD/src/frontend/SageIII/SgAsmJvmAttribute.h"
                            "$ROSE_BLD/src/frontend/SageIII/SgAsmJvmAttributeTable.h"
                            "$ROSE_BLD/src/frontend/SageIII/SgAsmJvmBootstrapMethod.h"
                            "$ROSE_BLD/src/frontend/SageIII/SgAsmJvmBootstrapMethods.h"
                            "$ROSE_BLD/src/frontend/SageIII/SgAsmJvmClass.h"
                            "$ROSE_BLD/src/frontend/SageIII/SgAsmJvmCodeAttribute.h"
                            "$ROSE_BLD/src/frontend/SageIII/SgAsmJvmConstantPoolEntry.h"
                            "$ROSE_BLD/src/frontend/SageIII/SgAsmJvmConstantPool.h"
                            "$ROSE_BLD/src/frontend/SageIII/SgAsmJvmConstantValue.h"
                            "$ROSE_BLD/src/frontend/SageIII/SgAsmJvmEnclosingMethod.h"
                            "$ROSE_BLD/src/frontend/SageIII/SgAsmJvmExceptionHandler.h"
                            "$ROSE_BLD/src/frontend/SageIII/SgAsmJvmExceptions.h"
                            "$ROSE_BLD/src/frontend/SageIII/SgAsmJvmExceptionTable.h"
                            "$ROSE_BLD/src/frontend/SageIII/SgAsmJvmField.h"
                            "$ROSE_BLD/src/frontend/SageIII/SgAsmJvmFieldTable.h"
                            "$ROSE_BLD/src/frontend/SageIII/SgAsmJvmFileHeader.h"
                            "$ROSE_BLD/src/frontend/SageIII/SgAsmJvmInnerClassesEntry.h"
                            "$ROSE_BLD/src/frontend/SageIII/SgAsmJvmInnerClasses.h"
                            "$ROSE_BLD/src/frontend/SageIII/SgAsmJvmInstruction.h"
                            "$ROSE_BLD/src/frontend/SageIII/SgAsmJvmLineNumberEntry.h"
                            "$ROSE_BLD/src/frontend/SageIII/SgAsmJvmLineNumberTable.h"
                            "$ROSE_BLD/src/frontend/SageIII/SgAsmJvmLocalVariableEntry.h"
                            "$ROSE_BLD/src/frontend/SageIII/SgAsmJvmLocalVariableTable.h"
                            "$ROSE_BLD/src/frontend/SageIII/SgAsmJvmLocalVariableTypeEntry.h"
                            "$ROSE_BLD/src/frontend/SageIII/SgAsmJvmLocalVariableTypeTable.h"
                            "$ROSE_BLD/src/frontend/SageIII/SgAsmJvmMethod.h"
                            "$ROSE_BLD/src/frontend/SageIII/SgAsmJvmMethodParametersEntry.h"
                            "$ROSE_BLD/src/frontend/SageIII/SgAsmJvmMethodParameters.h"
                            "$ROSE_BLD/src/frontend/SageIII/SgAsmJvmMethodTable.h"
                            "$ROSE_BLD/src/frontend/SageIII/SgAsmJvmModuleMainClass.h"
                            "$ROSE_BLD/src/frontend/SageIII/SgAsmJvmNestHost.h"
                            "$ROSE_BLD/src/frontend/SageIII/SgAsmJvmNestMembers.h"
                            "$ROSE_BLD/src/frontend/SageIII/SgAsmJvmNode.h"
                            "$ROSE_BLD/src/frontend/SageIII/SgAsmJvmSignature.h"
                            "$ROSE_BLD/src/frontend/SageIII/SgAsmJvmSourceFile.h"
                            "$ROSE_BLD/src/frontend/SageIII/SgAsmJvmStackMapFrame.h"
                            "$ROSE_BLD/src/frontend/SageIII/SgAsmJvmStackMapTable.h"
                            "$ROSE_BLD/src/frontend/SageIII/SgAsmJvmStackMapVerificationType.h"
                            "$ROSE_BLD/src/frontend/SageIII/SgAsmLEEntryPoint.h"
                            "$ROSE_BLD/src/frontend/SageIII/SgAsmLEEntryTable.h"
                            "$ROSE_BLD/src/frontend/SageIII/SgAsmLEFileHeader.h"
                            "$ROSE_BLD/src/frontend/SageIII/SgAsmLENameTable.h"
                            "$ROSE_BLD/src/frontend/SageIII/SgAsmLEPageTableEntry.h"
                            "$ROSE_BLD/src/frontend/SageIII/SgAsmLEPageTable.h"
                            "$ROSE_BLD/src/frontend/SageIII/SgAsmLERelocTable.h"
                            "$ROSE_BLD/src/frontend/SageIII/SgAsmLESection.h"
                            "$ROSE_BLD/src/frontend/SageIII/SgAsmLESectionTableEntry.h"
                            "$ROSE_BLD/src/frontend/SageIII/SgAsmLESectionTable.h"
                            "$ROSE_BLD/src/frontend/SageIII/SgAsmM68kInstruction.h"
                            "$ROSE_BLD/src/frontend/SageIII/SgAsmMemoryReferenceExpression.h"
                            "$ROSE_BLD/src/frontend/SageIII/SgAsmMipsInstruction.h"
                            "$ROSE_BLD/src/frontend/SageIII/SgAsmNEEntryPoint.h"
                            "$ROSE_BLD/src/frontend/SageIII/SgAsmNEEntryTable.h"
                            "$ROSE_BLD/src/frontend/SageIII/SgAsmNEFileHeader.h"
                            "$ROSE_BLD/src/frontend/SageIII/SgAsmNEModuleTable.h"
                            "$ROSE_BLD/src/frontend/SageIII/SgAsmNENameTable.h"
                            "$ROSE_BLD/src/frontend/SageIII/SgAsmNERelocEntry.h"
                            "$ROSE_BLD/src/frontend/SageIII/SgAsmNERelocTable.h"
                            "$ROSE_BLD/src/frontend/SageIII/SgAsmNESection.h"
                            "$ROSE_BLD/src/frontend/SageIII/SgAsmNESectionTableEntry.h"
                            "$ROSE_BLD/src/frontend/SageIII/SgAsmNESectionTable.h"
                            "$ROSE_BLD/src/frontend/SageIII/SgAsmNEStringTable.h"
                            "$ROSE_BLD/src/frontend/SageIII/SgAsmNode.h"
                            "$ROSE_BLD/src/frontend/SageIII/SgAsmNullInstruction.h"
                            "$ROSE_BLD/src/frontend/SageIII/SgAsmOperandList.h"
                            "$ROSE_BLD/src/frontend/SageIII/SgAsmPEExportDirectory.h"
                            "$ROSE_BLD/src/frontend/SageIII/SgAsmPEExportEntry.h"
                            "$ROSE_BLD/src/frontend/SageIII/SgAsmPEExportEntryList.h"
                            "$ROSE_BLD/src/frontend/SageIII/SgAsmPEExportSection.h"
                            "$ROSE_BLD/src/frontend/SageIII/SgAsmPEFileHeader.h"
                            "$ROSE_BLD/src/frontend/SageIII/SgAsmPEImportDirectory.h"
                            "$ROSE_BLD/src/frontend/SageIII/SgAsmPEImportDirectoryList.h"
                            "$ROSE_BLD/src/frontend/SageIII/SgAsmPEImportItem.h"
                            "$ROSE_BLD/src/frontend/SageIII/SgAsmPEImportItemList.h"
                            "$ROSE_BLD/src/frontend/SageIII/SgAsmPEImportSection.h"
                            "$ROSE_BLD/src/frontend/SageIII/SgAsmPERVASizePair.h"
                            "$ROSE_BLD/src/frontend/SageIII/SgAsmPERVASizePairList.h"
                            "$ROSE_BLD/src/frontend/SageIII/SgAsmPESection.h"
                            "$ROSE_BLD/src/frontend/SageIII/SgAsmPESectionTableEntry.h"
                            "$ROSE_BLD/src/frontend/SageIII/SgAsmPESectionTable.h"
                            "$ROSE_BLD/src/frontend/SageIII/SgAsmPEStringSection.h"
                            "$ROSE_BLD/src/frontend/SageIII/SgAsmPointerType.h"
                            "$ROSE_BLD/src/frontend/SageIII/SgAsmPowerpcInstruction.h"
                            "$ROSE_BLD/src/frontend/SageIII/SgAsmRegisterNames.h"
                            "$ROSE_BLD/src/frontend/SageIII/SgAsmRegisterReferenceExpression.h"
                            "$ROSE_BLD/src/frontend/SageIII/SgAsmRiscOperation.h"
                            "$ROSE_BLD/src/frontend/SageIII/SgAsmScalarType.h"
                            "$ROSE_BLD/src/frontend/SageIII/SgAsmStackExpression.h"
                            "$ROSE_BLD/src/frontend/SageIII/SgAsmStatement.h"
                            "$ROSE_BLD/src/frontend/SageIII/SgAsmStaticData.h"
                            "$ROSE_BLD/src/frontend/SageIII/SgAsmStoredString.h"
                            "$ROSE_BLD/src/frontend/SageIII/SgAsmStringStorage.h"
                            "$ROSE_BLD/src/frontend/SageIII/SgAsmSynthesizedDataStructureDeclaration.h"
                            "$ROSE_BLD/src/frontend/SageIII/SgAsmSynthesizedDeclaration.h"
                            "$ROSE_BLD/src/frontend/SageIII/SgAsmSynthesizedFieldDeclaration.h"
                            "$ROSE_BLD/src/frontend/SageIII/SgAsmType.h"
                            "$ROSE_BLD/src/frontend/SageIII/SgAsmUnaryExpression.h"
                            "$ROSE_BLD/src/frontend/SageIII/SgAsmUnaryMinus.h"
                            "$ROSE_BLD/src/frontend/SageIII/SgAsmUnaryPlus.h"
                            "$ROSE_BLD/src/frontend/SageIII/SgAsmUnaryRrx.h"
                            "$ROSE_BLD/src/frontend/SageIII/SgAsmUnarySignedExtend.h"
                            "$ROSE_BLD/src/frontend/SageIII/SgAsmUnaryTruncate.h"
                            "$ROSE_BLD/src/frontend/SageIII/SgAsmUnaryUnsignedExtend.h"
                            "$ROSE_BLD/src/frontend/SageIII/SgAsmUserInstruction.h"
                            "$ROSE_BLD/src/frontend/SageIII/SgAsmValueExpression.h"
                            "$ROSE_BLD/src/frontend/SageIII/SgAsmVectorType.h"
                            "$ROSE_BLD/src/frontend/SageIII/SgAsmVoidType.h"
                            "$ROSE_BLD/src/frontend/SageIII/SgAsmX86Instruction.h"
			   )

#------------------------------------------------------------------------------------------------------------------------
# Make sure ROSE source and build directories exist and that they look reasonable.
check_directories() {
    if [ ! -d "$ROSE_SRC/." ]; then
	echo "$myname: ROSE source directory not found: $ROSE_SRC" >&2
	exit 1
    fi
    if [ ! -d "$ROSE_SRC/scripts" ]; then
	echo "$myname: doesn't seem to be the top of the ROSE source tree: $ROSE_SRC" >&2
	exit 1
    fi
    if [ ! -d "$ROSE_BLD/." ]; then
	echo "$myname: ROSE build directory not found: $ROSE_BLD" >&2
	exit 1
    fi
    if [ ! -d "$ROSE_BLD/src/frontend/SageIII" ]; then
	echo "$myname: doesn't seem to be the top of the ROSE build tree: $ROSE_BLD" >&2
	exit 1
    fi
}

#------------------------------------------------------------------------------------------------------------------------
# Generate the SHA1 hash by for the source files (some generated) on which EDG depends.
generate_edg_hash() {
    local sha1sum_exe=`which sha1sum`

    if [ -f "$ROSE_SRC/src/frontend/CxxFrontend/EDG_VERSION" ] ; then
        EDG_VERSION=$(cat "$ROSE_SRC/src/frontend/CxxFrontend/EDG_VERSION")
        if [ "x$EDG_VERSION" == "x" ] ; then
            echo "Error: EDG_VERSION file empty"
            exit 1
        fi
    else
        echo "Error: $ROSE_SRC/src/frontend/CxxFrontend/EDG_VERSION does not exist"
        exit 1
    fi

    echo "5.$EDG_VERSION"		# this is version 5 of edg dependency hashing
}

#------------------------------------------------------------------------------------------------------------------------

check_directories
generate_edg_hash
exit 0
