#!/bin/sh

versiontocheckout="$1"
if [ "x$versiontocheckout" = "x" ]; then
  versiontocheckout=""
else
  versiontocheckout="-r $1"
fi

svnrepository="`sed -n 5p < .svn/entries`"
versioninfo="`svn -q ${versiontocheckout} log ${svnrepository} | sed -n 2p`"
version=`echo "${versioninfo}" | cut -f1 -d \ `
modificationdate=`echo "${versioninfo}" | cut -f5 -d \ `

year=`echo ${modificationdate} | cut -f 1 -d -`
month=`echo ${modificationdate} | cut -f 2 -d - | sed 's,^0*,,'`
monthname=`echo Jan Feb Mar Apr May Jun Jul Aug Sep Oct Nov Dec | cut -f $month -d \ `
day=`echo ${modificationdate} | cut -f 3 -d -`

branchname="`basename ${svnrepository}`"

dirnameBase="${branchname}-svn-${monthname}${day}-${year}-${version}"

if [ -e "${dirnameBase}" ]; then
  echo "File or directory ${dirnameBase} already exists -- please remove it" 1>&2
  exit 1
fi
if [ -e "${dirnameBase}.tar.gz" ]; then
  echo "Already have a tarball ${dirnameBase}.tar.gz -- don't need to rebuild it" 1>&2
  exit 1
fi
#svn export "${svnrepository}" "${dirnameBase}"
svn checkout "-${version}" "${svnrepository}" "${dirnameBase}"; # $version has an "r" on the beginning already
tar zcf "${dirnameBase}.tar.gz" "${dirnameBase}/"
rm -rf "${dirnameBase}/"
echo "Built tarball ${dirnameBase}.tar.gz from SVN revision ${version}"
exit 0
