#!/bin/bash

#GNU
# g++ -trigraphs -D__STDC_UTF_16__ $@
# g++ -trigraphs -Dsize_t=`unsigned long` $@
g++ -trigraphs $@

#EDG
#/home/yuan5/NEW_ROSE/ROSE/src/frontend/EDG/EDG_3.3/bin/eccp $@
#/home/yuan5/NEW_ROSE/ROSE/src/frontend/EDG/EDG_3.3/src/edgcpfe $@

#MPI
#mpicxx $@

# ROSE
#identityTranslator $@
