#!/bin/bash -v
#
# A script to mirror a cleaned ROSE repository without EDG to an external repository
# Another script generateRoseReposWithoutEDG has to be invoked before this.
#
# by Liao, 7/29/2008
# Last Modified: 7/29/2008

# -------------variable definitions---------------
SVN_PATH=/nfs/apps/subversion/1.4.5/bin
SCRIPT_PATH=/home/liao6/rose/scripts

# source of the synchronization 
CLEANED_REPOS=/usr/casc/overture/ROSE/svn/ROSE.CLEANED

# destination of the synchronization
#MIRROR_REPOS=https://outreach.scidac.gov/svn/rose
MIRROR_REPOS=/home/liao6/test/ROSE.MIRROR

#--------one time initialization for the external repos--------
#Only admin of the destination repos can do it
rm -rf ${MIRROR_REPOS} &&\
${SVN_PATH}/svnadmin create ${MIRROR_REPOS}  &&\
cp ${SCRIPT_PATH}/pre-revprop-change ${MIRROR_REPOS}/hooks/.&&\
${SVN_PATH}/svnsync initialize file://${MIRROR_REPOS} file://${CLEANED_REPOS}

#----------- actual synchronization----------------
${SVN_PATH}/svnsync synchronize file://${MIRROR_REPOS}
