formulae = [
    ( Not $ ( F $ Out 'W' )),
    ( F $ Out 'X' ),
    ( F $ Out 'Y' ),
    ( Not $ ( G $ Not $ Out 'Y' )),
    ( G $ Not $ ( Out 'X' ) `And` ( Out 'Y' )),
    ( G $ ( Out 'Y' ) `Or` ( Out 'X' )),
    ( ( ( Out 'X' ) `WU` (( Out 'Y' ) `And` ( Not $ Out 'X' )))),
    ( Out 'Y' ) `WU` (( Out 'X' ) `And` ( Not $ Out 'Y' )),
    ( F $ ( Out 'Y' ) `WU` (( Out 'X' ) `And` ( Not $ Out 'Y' ))),
    ( Not $ Out 'Y' ) `WU` ( Out 'X' ),
    (     F $ ( Out 'Y' ) `WU` ( Out 'X' )),
    (   ( F $ ( Out 'Y' ) `U` ( Out 'X' ))),
    (     F $ ( Out 'Y' ) `WU` ( Out 'Z' )),
    ( Not $ ( F $ ( Out 'Y' ) `U` ( Out 'Z' ))),
    ( F $ ( Out 'X' ) `U` ( Out 'Y' )),
    ( Not $ ( F $ ( Out 'Y' ) `R` ( Out 'X' ))),
    ( G $ Not $ In 'X' ),
    ( F $ In 'V' ),
    ( G $ Not $ ( Out 'X' ) `And` ( Out 'W' )),
    ( Out 'X' ) `U` ( Out 'Y' ),
    (( Not $ ( X $ Out 'Y' )) `And` ( X $ ( Not $ Out 'Y' ))) `Or` (( Not $ ( Not $ ( X $ Out 'Y' ))) `And` ( Not $ ( X $ ( Not $ Out 'Y' )))),
    (( Not $ ( F $ Out 'Y' )) `And` ( G $ ( Not $ Out 'Y' ))) `Or` (( Not $ ( Not $ ( F $ Out 'Y' ))) `And` ( Not $ ( G $ ( Not $ Out 'Y' )))),
    (( Not $ ( G $ Out 'Y' )) `And` ( F $ ( Not $ Out 'Y' ))) `Or` (( Not $ ( Not $ ( G $ Out 'Y' ))) `And` ( Not $ ( F $ ( Not $ Out 'Y' )))),
    ((( Not $ ( Out 'Y' ) `U` ( Out 'X' ))) `And` (( Not $ Out 'Y' ) `R` ( Not $ Out 'X' ))) `Or` ((( Not $  Not $ ( Out 'Y' ) `U` ( Out 'X' ))) `And` ( Not $ ( Not $ Out 'Y' ) `R` ( Not $ Out 'X' ))),
    ((( Not $ ( Out 'Y' ) `R` ( Out 'X' ))) `And` (( Not $ Out 'Y' ) `U` ( Not $ Out 'X' ))) `Or` ((( Not $  Not $ ( Out 'Y' ) `R` ( Out 'X' ))) `And` ( Not $ ( Not $ Out 'Y' ) `U` ( Not $ Out 'X' ))),
    ((( Out 'Y' ) `R` ( Out 'X' )) `And` (( Not $ ( Not $ Out 'Y' ) `U` ( Not $ Out 'X' )))) `Or` ((( Not $ ( Out 'Y' ) `R` ( Out 'X' ))) `And` ( Not $  Not $ ( Not $ Out 'Y' ) `U` ( Not $ Out 'X' ))),
    ( G $ Not $ Out 'W' ),
    (( G $ Not $ Out 'X' )) `Or` (( F $ ( Out 'X' ) `And` (( F $ Out 'Y' )))),
    ( Not $ (( G $ Not $ Out 'Y' )) `Or` (( F $ ( Out 'Y' ) `And` (( F $ Out 'X' ))))),
    None]
