formulae = [
    ( Not $ Out 'Z' ) `WU` (( Out 'U' ) `And` ( Not $ Out 'Z' )),
    ( G $ ( Not $ In 'C' ) `Or` (( F $ Out 'Z' ))),
    (( G $ Not $ Out 'W' )) `Or` (( F $ ( Out 'W' ) `And` (( F $ Out 'U' )))),
    ( G $ ( Not $ In 'E' ) `Or` (( F $ Out 'Y' ))),
    ( G $ ( Not $ ( In 'B' ) `And` ( Not $ Out 'U' )) `Or` (( Not $ Out 'V' ) `WU` ( Out 'U' ))),
    ( Not $ Out 'V' ) `WU` ( Out 'X' ),
    (( G $ Not $ Out 'W' )) `Or` (( F $ ( Out 'W' ) `And` (( F $ Out 'U' )))),
    ( Not $ Out 'U' ) `WU` (( Out 'X' ) `And` ( Not $ Out 'U' )),
    ( G $ ( Not $ ( In 'D' ) `And` ( Not $ Out 'Z' )) `Or` (( Not $ Out 'Z' ) `U` (( Out 'X' ) `And` ( Not $ Out 'Z' )))),
    ( G $ ( Not $ ( Out 'U' ) `And` ( Not $ Out 'W' )) `Or` (( Not $ Out 'W' ) `U` (( Out 'Z' ) `And` ( Not $ Out 'W' )))),
    ( G $ ( Not $ (( In 'C' ) `And` ( Not $ Out 'V' )) `And` (( F $ Out 'V' ))) `Or` (( Not $ Out 'Z' ) `U` ( Out 'V' ))),
    ( G $ ( Not $ ( In 'F' ) `And` ( Not $ Out 'Z' )) `Or` (( Not $ Out 'Z' ) `U` (( Out 'W' ) `And` ( Not $ Out 'Z' )))),
    ( G $ Not $ Out 'U' ),
    ( Not $ In 'C' ) `WU` (( Out 'Z' ) `And` ( Not $ In 'C' )),
    ( Not $ In 'B' ) `WU` (( Out 'X' ) `And` ( Not $ In 'B' )),
    ( G $ ( Not $ In 'B' ) `Or` (( G $ Not $ Out 'X' ))),
    ( G $ ( Not $ ( In 'D' ) `And` ( Not $ In 'F' )) `Or` (( Not $ In 'F' ) `U` (( Out 'Z' ) `And` ( Not $ In 'F' )))),
    ( G $ Not $ Out 'X' ),
    ( Not $ Out 'Z' ) `WU` (( Out 'Z' ) `WU` (( Not $ Out 'Z' ) `WU` (( Out 'Z' ) `WU` (( G $ Not $ Out 'Z' ))))),
    ( Not $ Out 'U' ) `WU` ( Out 'Z' ),
    ( Not $ In 'C' ) `WU` (( Out 'Y' ) `And` ( Not $ In 'C' )),
    ( G $ ( Not $ In 'A' ) `Or` (( G $ Not $ Out 'X' ))),
    ( Not $ Out 'U' ) `WU` (( Out 'V' ) `And` ( Not $ Out 'U' )),
    ( G $ ( Not $ In 'A' ) `Or` (( F $ Out 'V' ))),
    (( G $ Not $ Out 'Z' )) `Or` (( F $ ( Out 'Z' ) `And` (( F $ Out 'V' )))),
    (( G $ Not $ In 'C' )) `Or` (( F $ ( In 'C' ) `And` (( F $ Out 'W' )))),
    ( Not $ ( F $ In 'F' )) `Or` (( Not $ Out 'Y' ) `U` (( In 'E' ) `Or` ( In 'F' ))),
    ( G $ ( Not $ ( In 'C' ) `And` ( Not $ In 'D' )) `Or` (( Not $ Out 'U' ) `WU` ( In 'D' ))),
    ( Not $ Out 'U' ) `WU` ( Out 'Z' ),
    ( G $ ( Not $ (( In 'A' ) `And` ( Not $ In 'B' )) `And` (( F $ In 'B' ))) `Or` (( Not $ Out 'Y' ) `U` ( In 'B' ))),
    ( Not $ ( F $ In 'D' )) `Or` ((( Not $ Out 'X' ) `And` ( Not $ In 'D' ) ) `U` (( In 'D' ) `Or` ((( Out 'X' ) `And` ( Not $ In 'D' ) ) `U` (( In 'D' ) `Or` ((( Not $ Out 'X' ) `And` ( Not $ In 'D' ) ) `U` (( In 'D' ) `Or` ((( Out 'X' ) `And` ( Not $ In 'D' ) ) `U` (( In 'D' ) `Or` (( Not $ Out 'X' ) `U` ( In 'D' )))))))))),
    ( G $ Not $ Out 'Z' ),
    ( G $ ( Not $ Out 'W' ) `Or` (( F $ Out 'V' ))),
    ( G $ ( Not $ ( In 'C' ) `And` ( Not $ Out 'X' )) `Or` (( Not $ Out 'X' ) `WU` (( Out 'Z' ) `And` ( Not $ Out 'X' )))),
    ( Not $ Out 'X' ) `WU` (( Out 'X' ) `WU` (( Not $ Out 'X' ) `WU` (( Out 'X' ) `WU` (( G $ Not $ Out 'X' ))))),
    ( G $ ( Not $ (( In 'F' ) `And` ( Not $ Out 'V' )) `And` (( F $ Out 'V' ))) `Or` (( Not $ Out 'Z' ) `U` ( Out 'V' ))),
    ( G $ ( Not $ In 'F' ) `Or` (( F $ Out 'U' ))),
    ( Not $ Out 'W' ) `WU` (( Out 'W' ) `WU` (( Not $ Out 'W' ) `WU` (( Out 'W' ) `WU` (( G $ Not $ Out 'W' ))))),
    ( Not $ Out 'U' ) `WU` (( Out 'U' ) `WU` (( Not $ Out 'U' ) `WU` (( Out 'U' ) `WU` (( G $ Not $ Out 'U' ))))),
    ( Not $ Out 'X' ) `WU` ( Out 'Y' ),
    (( G $ Not $ Out 'X' )) `Or` (( F $ ( Out 'X' ) `And` (( F $ Out 'U' )))),
    ( Not $ Out 'W' ) `WU` (( Out 'U' ) `And` ( Not $ Out 'W' )),
    ( Not $ Out 'Y' ) `WU` ( In 'B' ),
    ( G $ ( Not $ ( In 'F' ) `And` ( Not $ In 'E' )) `Or` (( Not $ Out 'Y' ) `WU` ( In 'E' ))),
    ( G $ ( Not $ ( In 'A' ) `And` ( Not $ Out 'Y' )) `Or` (( Not $ Out 'Y' ) `U` (( Out 'U' ) `And` ( Not $ Out 'Y' )))),
    ( G $ Not $ Out 'W' ),
    ( F $ Out 'W' ),
    ( G $ ( Not $ Out 'Z' ) `Or` (( F $ Out 'X' ))),
    ( G $ ( Not $ ( Out 'Z' ) `And` ( Not $ Out 'X' )) `Or` (( Not $ Out 'X' ) `U` (( Out 'U' ) `And` ( Not $ Out 'X' )))),
    ( Not $ ( F $ Out 'X' )) `Or` (( Not $ Out 'U' ) `U` (( Out 'Z' ) `Or` ( Out 'X' ))),
    ( G $ ( Not $ ( Out 'U' ) `And` ( Not $ In 'D' )) `Or` (( Not $ In 'D' ) `U` (( Out 'V' ) `And` ( Not $ In 'D' )))),
    ( Not $ Out 'X' ) `WU` ( In 'D' ),
    ( Not $ In 'C' ) `WU` (( Out 'U' ) `And` ( Not $ In 'C' )),
    ( G $ ( Not $ ( In 'B' ) `And` ( Not $ Out 'X' )) `Or` (( Not $ Out 'W' ) `WU` ( Out 'X' ))),
    ( Not $ Out 'W' ) `WU` (( Out 'Y' ) `And` ( Not $ Out 'W' )),
    ( Not $ Out 'V' ) `WU` (( Out 'X' ) `And` ( Not $ Out 'V' )),
    ( Not $ ( F $ In 'B' )) `Or` (( Not $ Out 'U' ) `U` (( Out 'X' ) `Or` ( In 'B' ))),
    ( Not $ Out 'W' ) `WU` ( In 'D' ),
    ( F $ Out 'Z' ),
    ( F $ Out 'V' ),
    ( Not $ In 'F' ) `WU` (( Out 'Z' ) `And` ( Not $ In 'F' )),
    ( Not $ Out 'Y' ) `WU` (( Out 'Y' ) `WU` (( Not $ Out 'Y' ) `WU` (( Out 'Y' ) `WU` (( G $ Not $ Out 'Y' ))))),
    ( G $ ( Not $ (( In 'D' ) `And` ( Not $ Out 'U' )) `And` (( F $ Out 'U' ))) `Or` (( Not $ Out 'V' ) `U` ( Out 'U' ))),
    ( G $ ( Not $ (( Out 'U' ) `And` ( Not $ Out 'X' )) `And` (( F $ Out 'X' ))) `Or` (( Not $ Out 'W' ) `U` ( Out 'X' ))),
    (( G $ Not $ Out 'Y' )) `Or` (( F $ ( Out 'Y' ) `And` (( F $ Out 'W' )))),
    ( Not $ ( F $ Out 'U' )) `Or` ((( Not $ Out 'Z' ) `And` ( Not $ Out 'U' ) ) `U` (( Out 'U' ) `Or` ((( Out 'Z' ) `And` ( Not $ Out 'U' ) ) `U` (( Out 'U' ) `Or` ((( Not $ Out 'Z' ) `And` ( Not $ Out 'U' ) ) `U` (( Out 'U' ) `Or` ((( Out 'Z' ) `And` ( Not $ Out 'U' ) ) `U` (( Out 'U' ) `Or` (( Not $ Out 'Z' ) `U` ( Out 'U' )))))))))),
    ( Not $ ( F $ Out 'X' )) `Or` (( Not $ Out 'Y' ) `U` (( In 'B' ) `Or` ( Out 'X' ))),
    ( Not $ ( F $ Out 'X' )) `Or` ((( Not $ Out 'V' ) `And` ( Not $ Out 'X' ) ) `U` (( Out 'X' ) `Or` ((( Out 'V' ) `And` ( Not $ Out 'X' ) ) `U` (( Out 'X' ) `Or` ((( Not $ Out 'V' ) `And` ( Not $ Out 'X' ) ) `U` (( Out 'X' ) `Or` ((( Out 'V' ) `And` ( Not $ Out 'X' ) ) `U` (( Out 'X' ) `Or` (( Not $ Out 'V' ) `U` ( Out 'X' )))))))))),
    ( G $ ( Not $ ( In 'B' ) `And` ( Not $ Out 'X' )) `Or` (( Not $ Out 'Y' ) `WU` ( Out 'X' ))),
    ( G $ ( Not $ (( Out 'W' ) `And` ( Not $ In 'E' )) `And` (( F $ In 'E' ))) `Or` (( Not $ Out 'Z' ) `U` ( In 'E' ))),
    ( G $ ( Not $ (( Out 'Z' ) `And` ( Not $ In 'F' )) `And` (( F $ In 'F' ))) `Or` (( Not $ Out 'U' ) `U` ( In 'F' ))),
    ( Not $ Out 'Z' ) `WU` (( Out 'X' ) `And` ( Not $ Out 'Z' )),
    ( G $ ( Not $ ( In 'F' ) `And` ( Not $ In 'D' )) `Or` (( Not $ Out 'X' ) `WU` ( In 'D' ))),
    ( Not $ Out 'W' ) `WU` (( Out 'W' ) `WU` (( Not $ Out 'W' ) `WU` (( Out 'W' ) `WU` (( G $ Not $ Out 'W' ))))),
    ( G $ ( Not $ ( Out 'Z' ) `And` ( Not $ In 'D' )) `Or` (( Not $ In 'D' ) `U` (( Out 'U' ) `And` ( Not $ In 'D' )))),
    ( G $ ( Not $ Out 'X' ) `Or` (( G $ Not $ Out 'Y' ))),
    ( Not $ Out 'W' ) `WU` ( In 'B' ),
    ( Not $ In 'E' ) `WU` (( Out 'V' ) `And` ( Not $ In 'E' )),
    (( G $ Not $ In 'E' )) `Or` (( F $ ( In 'E' ) `And` (( F $ Out 'U' )))),
    ( Not $ ( F $ Out 'W' )) `Or` ((( Not $ Out 'X' ) `And` ( Not $ Out 'W' ) ) `U` (( Out 'W' ) `Or` ((( Out 'X' ) `And` ( Not $ Out 'W' ) ) `U` (( Out 'W' ) `Or` ((( Not $ Out 'X' ) `And` ( Not $ Out 'W' ) ) `U` (( Out 'W' ) `Or` ((( Out 'X' ) `And` ( Not $ Out 'W' ) ) `U` (( Out 'W' ) `Or` (( Not $ Out 'X' ) `U` ( Out 'W' )))))))))),
    ( Not $ Out 'Z' ) `WU` ( In 'A' ),
    ( Not $ Out 'Y' ) `WU` ( In 'A' ),
    ( G $ ( Not $ ( In 'C' ) `And` ( Not $ Out 'Z' )) `Or` (( Not $ Out 'Z' ) `U` (( Out 'Y' ) `And` ( Not $ Out 'Z' )))),
    ( G $ ( Not $ ( In 'D' ) `And` ( Not $ Out 'V' )) `Or` (( Not $ Out 'X' ) `WU` ( Out 'V' ))),
    ( F $ Out 'V' ),
    ( G $ ( Not $ In 'E' ) `Or` (( F $ Out 'U' ))),
    ( G $ Not $ Out 'X' ),
    ( Not $ Out 'U' ) `WU` (( Out 'Z' ) `And` ( Not $ Out 'U' )),
    ( G $ ( Not $ ( Out 'W' ) `And` ( Not $ Out 'V' )) `Or` (( Not $ Out 'V' ) `WU` (( Out 'U' ) `And` ( Not $ Out 'V' )))),
    ( Not $ Out 'Z' ) `WU` ( In 'E' ),
    ( Not $ Out 'X' ) `WU` ( Out 'W' ),
    ( G $ ( Not $ (( Out 'Y' ) `And` ( Not $ In 'C' )) `And` (( F $ In 'C' ))) `Or` (( Not $ Out 'W' ) `U` ( In 'C' ))),
    (( G $ Not $ Out 'Z' )) `Or` (( F $ ( Out 'Z' ) `And` (( F $ Out 'Y' )))),
    ( G $ ( Not $ In 'A' ) `Or` (( G $ Not $ Out 'U' ))),
    ( G $ ( Not $ ( In 'B' ) `And` ( Not $ Out 'Y' )) `Or` (( Not $ Out 'Y' ) `WU` (( Out 'W' ) `And` ( Not $ Out 'Y' )))),
    ( G $ ( Not $ (( Out 'W' ) `And` ( Not $ In 'A' )) `And` (( F $ In 'A' ))) `Or` (( Not $ Out 'X' ) `U` ( In 'A' ))),
    ( G $ ( Not $ ( In 'F' ) `And` ( Not $ In 'C' )) `Or` (( Not $ Out 'Z' ) `WU` ( In 'C' ))),
    ( G $ ( Not $ ( In 'D' ) `And` ( Not $ In 'B' )) `Or` (( Not $ In 'B' ) `WU` (( Out 'X' ) `And` ( Not $ In 'B' )))),
    ( G $ ( Not $ ( Out 'X' ) `And` ( Not $ Out 'Z' )) `Or` (( Not $ Out 'Z' ) `WU` (( Out 'Y' ) `And` ( Not $ Out 'Z' )))),
    ( Not $ In 'A' ) `WU` (( Out 'U' ) `And` ( Not $ In 'A' )),
    None]
frequencies = [
  (12, elements ['A']),
  (18, elements ['B']),
  (18, elements ['C']),
  (27, elements ['D']),
  (13, elements ['E']),
  (16, elements ['F']),
  (0, elements ['Z'])]

machine = "./Problem1.exe"

inputsequences = "Problem1.inputs"
