#!/usr/bin/bash
# Run the ROSE Tool through MPI on toss3 (rzgenie).  
# Parameters are passed through.

rel_test_dir=`dirname $0`
test_dir=`(cd ${rel_test_dir}; pwd)`
. ${test_dir}/set_ROSE_HOME

export ACTUAL_ROSE_TOOL_PATH=${ROSE_HOME}/tutorial/identityTranslator

compiler=intel

case ${compiler} in 
  intel)
    export MPICH_CXX=${ACTUAL_ROSE_TOOL_PATH}
    exec /usr/tce/packages/mvapich2/mvapich2-2.2-intel-16.0.3/bin/mpicxx "$@"
    break;;
  gcc)
    export OMPI_CXX=${ACTUAL_ROSE_TOOL_PATH}
    exec /usr/tce/packages/openmpi/openmpi-2.0.0-gcc-4.9.3/bin/mpicxx "$@"
    break;;
  *)
    echo "$0 - unknown compiler \"${compiler}\". Exiting"; 
    exit 1;;
esac

