#!/bin/bash
set -e

# Overall low density with a few high-density blocks

base=x-test

run_test () {
    # Set things up
    echo "====================================================================================================\n";
    local density=$1 nfunctions=$2 nchunks=$3 nparts=$4
    $(rg-src)/31-genpoints $density $nfunctions $nchunks > $base.allpoints
    npoints=$(wc -l <$base.allpoints)
#    echo "plot '$base.allpoints' with dots" |gnuplot -p
    rm -f $base.[12]d.???
    echo

    # The old 1d method: just split the file into equal sized parts
    partsize=$[ (npoints + nparts - 1) / nparts ]
    split --lines=$partsize --suffix-length=3 $base.allpoints $base.1d.
    echo "               O L D   M E T H O D"
    $(rg-src)/31-analyze-split $base.1d.???
    echo

    # The new method does the splitting in 2d space
    ./31-split-2dworklist $nparts <$base.allpoints | $(rg-src)/31-split-into-files --prefix=$base.2d. --suffix-length=3
    echo "               N E W   M E T H O D"
    $(rg-src)/31-analyze-split $base.2d.???
}




#         density  nfunctions  chunked  npartitions
#         -------  ----------  -------  -----------
#run_test    0.01        2000        1           64
#run_test    0.10        2000        1           64
#run_test    0.50        2000        1           64
#run_test    0.90        2000        1           64
#run_test    0.90        2000        1          256
#run_test    0.90        2000        1         1024

run_test    0.01        2000       10           64
run_test    0.10        2000       10           64
run_test    0.50        2000       10           64
run_test    0.90        2000       10           64
run_test    0.90        2000       10          256
run_test    0.90        2000       10         1024

#run_test    0.01        2000       10           64
#run_test    0.10        2000       10           64
#run_test    0.50        2000       10           64
#run_test    0.90        2000       10           64
#run_test    0.90        2000       10          256
#run_test    0.90        2000       10         1024
