#!/usr/bin/perl
# Exits success or failure depending on whether the tests indicated on the command line constitute a "pass" or "failure"
# of a branch. A branch that "passes" can be merged into the master branch if doing so would be a fast-forward.
#
# Arguments are TEST=STATUS where TEST is the name of a test (the tag specified with the --tag switch of the "rgit test"
# command) and STATUS is "1" if the test passed and "0" if the test failed.
#
use strict;
my %test = map {split /=/} @ARGV;
exit 1 if grep {$_ == 0} values %test;  # fail if any test failed
exit 1 unless $test{"rat-nobins"};      # rat-nobins must have passed
exit 1 unless $test{"rat-gentoo"};      # rat-gentoo must have passed
exit 0;
