#!/bin/bash
# Fails if the source tree contains binary EDG tarballs.
# Current working directory should be the top of the ROSE source tree.

mesg=<<EOF
Binary EDG tarballs should not be in the repository:
  1. They are not source-level files; they are genenerated by other commands,
  2. They have unique names for each version and so do not need to be in a revision management system,
  3. They are large binary files that add to the size of the repository,
  4. There were as many EDG tarball revisions as other source code revisions in the old repository.
A better place for these would be a simple directory located on a server somewhere. Perhaps an ftp or http
server, but certainly not somewhere that requires them to all be downloaded every time a developer wants to
work on source code!
EOF

for tarball in src/frontend/CxxFrontend/roseBinaryEDG-*.tar.gz; do
    if [ -f "$tarball" ]; then
	echo $mesg;
	echo
	ls -l src/frontend/CxxFrontend/roseBinaryEDG-*.tar.gz
	exit 1
    fi
done
exit 0
