#include "sage3basic.h"
#include "AbstractValue.h"
#include "StateRepresentations.h"
#include "Analyzer.h"

#include "RERS_Problem8_mod.C"

namespace RERS_Problem {
  void rersGlobalVarsCallInit(CodeThorn::Analyzer* analyzer, CodeThorn::PState& pstate) {
    COPY_PSTATEVAR_TO_GLOBALVAR(a22);
    COPY_PSTATEVAR_TO_GLOBALVAR(a20);
    COPY_PSTATEVAR_TO_GLOBALVAR(a0);
    COPY_PSTATEVAR_TO_GLOBALVAR(a27);
    COPY_PSTATEVAR_TO_GLOBALVAR(a18);
    COPY_PSTATEVAR_TO_GLOBALVAR(a5);
    COPY_PSTATEVAR_TO_GLOBALVAR(a15);
    COPY_PSTATEVAR_TO_GLOBALVAR(a12);
    COPY_PSTATEVAR_TO_GLOBALVAR(a4);
    COPY_PSTATEVAR_TO_GLOBALVAR(a3);
    COPY_PSTATEVAR_TO_GLOBALVAR(a6);
  }
  void rersGlobalVarsCallReturnInit(CodeThorn::Analyzer* analyzer, CodeThorn::PState& pstate) {
    COPY_GLOBALVAR_TO_PSTATEVAR(a22);
    COPY_GLOBALVAR_TO_PSTATEVAR(a20);
    COPY_GLOBALVAR_TO_PSTATEVAR(a0);
    COPY_GLOBALVAR_TO_PSTATEVAR(a27);
    COPY_GLOBALVAR_TO_PSTATEVAR(a18);
    COPY_GLOBALVAR_TO_PSTATEVAR(a5);
    COPY_GLOBALVAR_TO_PSTATEVAR(a15);
    COPY_GLOBALVAR_TO_PSTATEVAR(a12);
    COPY_GLOBALVAR_TO_PSTATEVAR(a4);
    COPY_GLOBALVAR_TO_PSTATEVAR(a3);
    COPY_GLOBALVAR_TO_PSTATEVAR(a6);
  }
}
