#include "sage3basic.h"
#include "AbstractValue.h"
#include "EState.h"
#include "Analyzer.h"

#include "RERS_Problem7_mod.C"

namespace RERS_Problem {
  void rersGlobalVarsCallInit(CodeThorn::Analyzer* analyzer, CodeThorn::PState& pstate) {
    COPY_PSTATEVAR_TO_GLOBALVAR(a14);
    COPY_PSTATEVAR_TO_GLOBALVAR(a0);
    COPY_PSTATEVAR_TO_GLOBALVAR(a11);
    COPY_PSTATEVAR_TO_GLOBALVAR(a28);
    COPY_PSTATEVAR_TO_GLOBALVAR(a20);
    COPY_PSTATEVAR_TO_GLOBALVAR(a7);
    COPY_PSTATEVAR_TO_GLOBALVAR(a22);
    COPY_PSTATEVAR_TO_GLOBALVAR(a24);
    COPY_PSTATEVAR_TO_GLOBALVAR(a25);
    COPY_PSTATEVAR_TO_GLOBALVAR(a29);
    COPY_PSTATEVAR_TO_GLOBALVAR(a19);
  }
  void rersGlobalVarsCallReturnInit(CodeThorn::Analyzer* analyzer, CodeThorn::PState& pstate) {
    COPY_GLOBALVAR_TO_PSTATEVAR(a14);
    COPY_GLOBALVAR_TO_PSTATEVAR(a0);
    COPY_GLOBALVAR_TO_PSTATEVAR(a11);
    COPY_GLOBALVAR_TO_PSTATEVAR(a28);
    COPY_GLOBALVAR_TO_PSTATEVAR(a20);
    COPY_GLOBALVAR_TO_PSTATEVAR(a7);
    COPY_GLOBALVAR_TO_PSTATEVAR(a22);
    COPY_GLOBALVAR_TO_PSTATEVAR(a24);
    COPY_GLOBALVAR_TO_PSTATEVAR(a25);
    COPY_GLOBALVAR_TO_PSTATEVAR(a29);
    COPY_GLOBALVAR_TO_PSTATEVAR(a19);
  }
}
