#include "sage3basic.h"
#include "AbstractValue.h"
#include "StateRepresentations.h"
#include "Analyzer.h"

#include "RERS_Problem9_mod.C"

namespace RERS_Problem {
  void rersGlobalVarsCallInit(CodeThorn::Analyzer* analyzer, CodeThorn::PState& pstate) {
    COPY_PSTATEVAR_TO_GLOBALVAR(a2);
    COPY_PSTATEVAR_TO_GLOBALVAR(a11);
    COPY_PSTATEVAR_TO_GLOBALVAR(a12);
    COPY_PSTATEVAR_TO_GLOBALVAR(a28);
    COPY_PSTATEVAR_TO_GLOBALVAR(a13);
    COPY_PSTATEVAR_TO_GLOBALVAR(a3);
    COPY_PSTATEVAR_TO_GLOBALVAR(a6);
    COPY_PSTATEVAR_TO_GLOBALVAR(a23);
    COPY_PSTATEVAR_TO_GLOBALVAR(a8);
    COPY_PSTATEVAR_TO_GLOBALVAR(a26);
    COPY_PSTATEVAR_TO_GLOBALVAR(a0);
    COPY_PSTATEVAR_TO_GLOBALVAR(a18);
    COPY_PSTATEVAR_TO_GLOBALVAR(a27);
    COPY_PSTATEVAR_TO_GLOBALVAR(a4);
    COPY_PSTATEVAR_TO_GLOBALVAR(a7);
    COPY_PSTATEVAR_TO_GLOBALVAR(a14);
    COPY_PSTATEVAR_TO_GLOBALVAR(a24);
    COPY_PSTATEVAR_TO_GLOBALVAR(a25);
    COPY_PSTATEVAR_TO_GLOBALVAR(a10);
    COPY_PSTATEVAR_TO_GLOBALVAR(a15);
    COPY_PSTATEVAR_TO_GLOBALVAR(a29);
    COPY_PSTATEVAR_TO_GLOBALVAR(a22);
    COPY_PSTATEVAR_TO_GLOBALVAR(a1);
    COPY_PSTATEVAR_TO_GLOBALVAR(a5);
    COPY_PSTATEVAR_TO_GLOBALVAR(a9);
    COPY_PSTATEVAR_TO_GLOBALVAR(a17);
    COPY_PSTATEVAR_TO_GLOBALVAR(a20);
    COPY_PSTATEVAR_TO_GLOBALVAR(a16);
    COPY_PSTATEVAR_TO_GLOBALVAR(a19);
    COPY_PSTATEVAR_TO_GLOBALVAR(a21);
  }
  void rersGlobalVarsCallReturnInit(CodeThorn::Analyzer* analyzer, CodeThorn::PState& pstate) {
    COPY_GLOBALVAR_TO_PSTATEVAR(a2);
    COPY_GLOBALVAR_TO_PSTATEVAR(a11);
    COPY_GLOBALVAR_TO_PSTATEVAR(a12);
    COPY_GLOBALVAR_TO_PSTATEVAR(a28);
    COPY_GLOBALVAR_TO_PSTATEVAR(a13);
    COPY_GLOBALVAR_TO_PSTATEVAR(a3);
    COPY_GLOBALVAR_TO_PSTATEVAR(a6);
    COPY_GLOBALVAR_TO_PSTATEVAR(a23);
    COPY_GLOBALVAR_TO_PSTATEVAR(a8);
    COPY_GLOBALVAR_TO_PSTATEVAR(a26);
    COPY_GLOBALVAR_TO_PSTATEVAR(a0);
    COPY_GLOBALVAR_TO_PSTATEVAR(a18);
    COPY_GLOBALVAR_TO_PSTATEVAR(a27);
    COPY_GLOBALVAR_TO_PSTATEVAR(a4);
    COPY_GLOBALVAR_TO_PSTATEVAR(a7);
    COPY_GLOBALVAR_TO_PSTATEVAR(a14);
    COPY_GLOBALVAR_TO_PSTATEVAR(a24);
    COPY_GLOBALVAR_TO_PSTATEVAR(a25);
    COPY_GLOBALVAR_TO_PSTATEVAR(a10);
    COPY_GLOBALVAR_TO_PSTATEVAR(a15);
    COPY_GLOBALVAR_TO_PSTATEVAR(a29);
    COPY_GLOBALVAR_TO_PSTATEVAR(a22);
    COPY_GLOBALVAR_TO_PSTATEVAR(a1);
    COPY_GLOBALVAR_TO_PSTATEVAR(a5);
    COPY_GLOBALVAR_TO_PSTATEVAR(a9);
    COPY_GLOBALVAR_TO_PSTATEVAR(a17);
    COPY_GLOBALVAR_TO_PSTATEVAR(a20);
    COPY_GLOBALVAR_TO_PSTATEVAR(a16);
    COPY_GLOBALVAR_TO_PSTATEVAR(a19);
    COPY_GLOBALVAR_TO_PSTATEVAR(a21);
  }
}
