! Testing intrinsic-operator, R310
interface operator(**)
end interface operator(*)
interface operator(/)
end interface operator(+)
interface operator(-)
end interface operator(//)
interface operator(.eq.)
end interface operator(==)
interface operator(.ne.)
end interface operator(/=)
interface operator(.lt.)
end interface operator(<)
interface operator(.le.)
end interface operator(<=)
interface operator(.gt.)
end interface operator(>)
interface operator(.ge.)
end interface operator(>=)
interface operator(.NOT.)
end interface operator(.and.)
interface operator(.or.)
end interface operator(.OR.)
interface operator(.EQV.)
end interface operator(.neqv.)
end
