== Compass Static Analysis Tool
[source, makefile]
--------------------------------------------------------------------------------

include $(top_srcdir)/config/Makefile.for.ROSE.includes.and.libs
include $(top_srcdir)/projects/compass/src/compassSupport/compass_dirs.inc

--------------------------------------------------------------------------------

=== Compass Executables
[source, makefile]
--------------------------------------------------------------------------------

bin_PROGRAMS = compassEmptyMain
include_HEADERS = compass.h

compassEmptyMain_SOURCES = compassEmptyMain.C

--------------------------------------------------------------------------------

=== Compass Libtool Library (Archive)
[source, makefile]
--------------------------------------------------------------------------------

lib_LTLIBRARIES = libCompass.la
libCompass_la_SOURCES = compass.C

--------------------------------------------------------------------------------

=== Compile / Link Dependencies
[source, makefile]
--------------------------------------------------------------------------------

BUILT_SOURCES = prerequisites.h instantiate_prerequisites.h 
nodist_include_HEADERS = prerequisites.h instantiate_prerequisites.h

prerequisites.h: $(compass_prereqs_dir)
	find $(compass_prereqs_dir) -name "*.h" | awk -F/ '{print "#include \"" $$NF "\""}' > $@

instantiate_prerequisites.h: $(compass_prereqs_dir)
	cat $(compass_prereqs_dir)/*.h | grep "^extern" | sed -e 's@extern[\t\ ]*@Compass::@g' | awk '{print $$1 " Compass::" $$2}' > $@

#---------------------------------------
#                   Library dependencies
LDADD = \
  libCompass.la \
  $(ROSE_LIBS)

#---------------------------------------
#                        Include headers
INCLUDES = \
  $(ROSE_INCLUDES) \
  -I$(compass_prereqs_dir)

#---------------------------------------
#                            MPI Support
if ROSE_MPI
  INCLUDES += -DROSE_MPI
endif

#---------------------------------------
#                            OMP support
if ROSE_USE_GCC_OMP
  LDADD += -lgomp
  CPPFLAGS += -fopenmp
endif

--------------------------------------------------------------------------------

=== Tests
[source, makefile]
--------------------------------------------------------------------------------

test: compassEmptyMain 
	env COMPASS_PARAMETERS=$(srcdir)/compass_parameters ./compassEmptyMain $(compass_test_dir)/exampleTest_1.C

check-local: test
	@echo "************************************************************************************"
	@echo "*** ROSE/projects/compassSupport: make check rule complete (terminated normally) ***"
	@echo "************************************************************************************"

--------------------------------------------------------------------------------

=== Installation
[source, makefile]
--------------------------------------------------------------------------------

install-exec-hook:
	cp $(compass_prereqs_dir)/*.h $(DESTDIR)$(includedir)

uninstall-local:
	@sh -c 'for file in `ls $(compass_prereqs_dir)/*.h`; do rm -f $(DESTDIR)$(includedir)/`basename $$file`; done'

--------------------------------------------------------------------------------

=== Distribution
[source, makefile]
--------------------------------------------------------------------------------

EXTRA_DIST = \
  compassEmptyMain.C \
  compassMain.C \
  compassTestMain.C \
  compassQRoseMain.C \
\
  compass.C \
  compass.h \
  compass.C.gergo \
  compass.h.gergo \
\
  compass.inc \
  compass_dirs.inc \
  compass_parameters \
\
  compassDocs.tex \
  README

--------------------------------------------------------------------------------

=== Cleanup
[source, makefile]
--------------------------------------------------------------------------------

clean-local:
	rm -f \
		a.out \
		*.sty \
		*.ti \
		$(nodist_include_HEADERS)

--------------------------------------------------------------------------------
