ompAnal_OBJ = -L../ompAnal/lib/ -lompAnal -lboost_regex
ompAnal_H = ../ompAnal/ompUtils.h

.PHONY: ompAnal
ompAnal:
	cd ${ANALYSIS_ROOT}/src/ompAnal; ${MAKE} all; cd ${ANALYSIS_ROOT}/src/${Component}
