# this file was generated during the kdelibs build process
set(KDE_VERSION_MAJOR 4)
set(KDE_VERSION_MINOR 2)
set(KDE_VERSION_RELEASE 2)
set(KDE_VERSION "4.2.2")
set(KDE_VERSION_STRING "4.2.2 (KDE 4.2.2)")
set(KDE_DEFAULT_HOME ".kde")

if (NOT KDE4_INSTALL_DIR)
   set(KDE4_INSTALL_DIR         "/usr")
endif (NOT KDE4_INSTALL_DIR)

set(KDE4_LIB_INSTALL_DIR     "/usr/lib")
set(KDE4_LIBEXEC_INSTALL_DIR "/usr/lib/kde4/libexec")
set(KDE4_INCLUDE_INSTALL_DIR "/usr/include")
set(KDE4_BIN_INSTALL_DIR     "/usr/bin")
set(KDE4_SBIN_INSTALL_DIR    "/usr/sbin")
set(KDE4_DATA_INSTALL_DIR    "/usr/share/kde4/apps")
set(KDE4_HTML_INSTALL_DIR    "/usr/share/doc/kde/HTML")
set(KDE4_CONFIG_INSTALL_DIR  "/usr/share/kde4/config")
set(KDE4_ICON_INSTALL_DIR    "/usr/share/icons")
set(KDE4_KCFG_INSTALL_DIR    "/usr/share/kde4/config.kcfg")
set(KDE4_LOCALE_INSTALL_DIR  "/usr/share/locale")
set(KDE4_MIME_INSTALL_DIR    "/usr/share/mimelnk")
set(KDE4_SOUND_INSTALL_DIR   "/usr/share/sounds")
set(KDE4_TEMPLATES_INSTALL_DIR "/usr/share/templates")
set(KDE4_WALLPAPER_INSTALL_DIR "/usr/share/wallpapers")
set(KDE4_KCONF_UPDATE_INSTALL_DIR "/usr/share/kde4/apps/kconf_update")
set(KDE4_AUTOSTART_INSTALL_DIR "/usr/share/autostart")
set(KDE4_XDG_APPS_INSTALL_DIR        "/usr/share/applications/kde4")
set(KDE4_XDG_DIRECTORY_INSTALL_DIR   "/usr/share/desktop-directories")
set(KDE4_SYSCONF_INSTALL_DIR "/etc")
set(KDE4_MAN_INSTALL_DIR     "/usr/share/man")
set(KDE4_INFO_INSTALL_DIR    "/usr/share/info")
set(KDE4_DBUS_INTERFACES_DIR "/usr/share/dbus-1/interfaces")
set(KDE4_DBUS_SERVICES_DIR   "/usr/share/dbus-1/services")
set(KDE4_SERVICES_INSTALL_DIR "/usr/share/kde4/services")
set(KDE4_SERVICETYPES_INSTALL_DIR "/usr/share/kde4/servicetypes")

set(KDE4_TARGET_PREFIX KDE4__ )


