all:
	$(MAKE) -C pred
	$(MAKE) -C shape
	$(MAKE) -C typeexpr
	$(MAKE) -C shape2
	$(MAKE) -C nielson

check:
	$(MAKE) check -C shape

clean:
	$(MAKE) clean -C pred
	$(MAKE) clean -C shape
	$(MAKE) clean -C typeexpr
	$(MAKE) clean -C shape2
	$(MAKE) clean -C nielson

