# PDFlib bindings Makefile
# $Id: Makefile,v 1.1 2005/10/11 17:18:07 vuduc2 Exp $

include ../../config/mkcommon.inc

SUB_DIRS =  $(BINDINGS)

include ../../config/mksubdirs.inc


clean::
	$(RM) php/smoke_c*.trace php/smoke_c*.pdf
	$(RM) rpg/smoke_c*.trace rpg/smoke_c*.pdf
