set(GENERATED_HEADERS
    ${ROSE_TOP_BINARY_DIR}/src/ROSETTA/src/grammar.h  
    ${ROSE_TOP_BINARY_DIR}/src/ROSETTA/src/grammarString.h  
    ${ROSE_TOP_BINARY_DIR}/src/ROSETTA/src/ROSETTA_macros.h  
    ${ROSE_TOP_BINARY_DIR}/src/ROSETTA/src/terminal.h
    ${ROSE_TOP_BINARY_DIR}/src/ROSETTA/src/AST_FILE_IO.h         
    ${ROSE_TOP_BINARY_DIR}/src/ROSETTA/src/AstSpecificDataManagingClass.h  
    ${ROSE_TOP_BINARY_DIR}/src/ROSETTA/src/Cxx_GrammarMemoryPoolSupport.h
    ${ROSE_TOP_BINARY_DIR}/src/ROSETTA/src/StorageClasses.h
    ${ROSE_TOP_BINARY_DIR}/src/ROSETTA/src/AstQueryMemoryPool.h  
    ${ROSE_TOP_BINARY_DIR}/src/ROSETTA/src/Cxx_Grammar.h
    ${ROSE_TOP_BINARY_DIR}/src/ROSETTA/src/Cxx_GrammarDeclarations.h
    ${ROSE_TOP_BINARY_DIR}/src/ROSETTA/src/Cxx_GrammarDowncast.h
    ${ROSE_TOP_BINARY_DIR}/src/ROSETTA/src/Cxx_GrammarStorageClasses.h
    ${ROSE_TOP_BINARY_DIR}/src/ROSETTA/src/Cxx_GrammarSgNodeDefinitions.h
    ${ROSE_TOP_BINARY_DIR}/src/ROSETTA/src/Cxx_GrammarSgAsmNodeDefinitions.h
    ${ROSE_TOP_BINARY_DIR}/src/ROSETTA/src/Cxx_GrammarSgAsmCilNodeDefinitions.h
    ${ROSE_TOP_BINARY_DIR}/src/ROSETTA/src/Cxx_GrammarSgAsmDwarfNodeDefinitions.h
    ${ROSE_TOP_BINARY_DIR}/src/ROSETTA/src/Cxx_GrammarSgAsmJvmNodeDefinitions.h
    ${ROSE_TOP_BINARY_DIR}/src/ROSETTA/src/Cxx_GrammarVariants.h
    ${ROSE_TOP_BINARY_DIR}/src/ROSETTA/src/Cxx_GrammarVisitorSupport.h
    ${ROSE_TOP_BINARY_DIR}/src/ROSETTA/src/Cxx_GrammarTreeTraversalAccessEnums.h
    ${ROSE_TOP_BINARY_DIR}/src/ROSETTA/src/SgNode.h
    ${ROSE_TOP_BINARY_DIR}/src/ROSETTA/src/SgAsmAarch32Coprocessor.h
    ${ROSE_TOP_BINARY_DIR}/src/ROSETTA/src/SgAsmAarch32Instruction.h
    ${ROSE_TOP_BINARY_DIR}/src/ROSETTA/src/SgAsmAarch64AtOperand.h
    ${ROSE_TOP_BINARY_DIR}/src/ROSETTA/src/SgAsmAarch64BarrierOperand.h
    ${ROSE_TOP_BINARY_DIR}/src/ROSETTA/src/SgAsmAarch64CImmediateOperand.h
    ${ROSE_TOP_BINARY_DIR}/src/ROSETTA/src/SgAsmAarch64Instruction.h
    ${ROSE_TOP_BINARY_DIR}/src/ROSETTA/src/SgAsmAarch64PrefetchOperand.h
    ${ROSE_TOP_BINARY_DIR}/src/ROSETTA/src/SgAsmAarch64PState.h
    ${ROSE_TOP_BINARY_DIR}/src/ROSETTA/src/SgAsmAarch64SysMoveOperand.h
    ${ROSE_TOP_BINARY_DIR}/src/ROSETTA/src/SgAsmBasicString.h
    ${ROSE_TOP_BINARY_DIR}/src/ROSETTA/src/SgAsmBinaryAdd.h
    ${ROSE_TOP_BINARY_DIR}/src/ROSETTA/src/SgAsmBinaryAsr.h
    ${ROSE_TOP_BINARY_DIR}/src/ROSETTA/src/SgAsmBinaryConcat.h
    ${ROSE_TOP_BINARY_DIR}/src/ROSETTA/src/SgAsmBinaryDivide.h
    ${ROSE_TOP_BINARY_DIR}/src/ROSETTA/src/SgAsmBinaryExpression.h
    ${ROSE_TOP_BINARY_DIR}/src/ROSETTA/src/SgAsmBinaryLsl.h
    ${ROSE_TOP_BINARY_DIR}/src/ROSETTA/src/SgAsmBinaryLsr.h
    ${ROSE_TOP_BINARY_DIR}/src/ROSETTA/src/SgAsmBinaryMod.h
    ${ROSE_TOP_BINARY_DIR}/src/ROSETTA/src/SgAsmBinaryMsl.h
    ${ROSE_TOP_BINARY_DIR}/src/ROSETTA/src/SgAsmBinaryMultiply.h
    ${ROSE_TOP_BINARY_DIR}/src/ROSETTA/src/SgAsmBinaryPostupdate.h
    ${ROSE_TOP_BINARY_DIR}/src/ROSETTA/src/SgAsmBinaryPreupdate.h
    ${ROSE_TOP_BINARY_DIR}/src/ROSETTA/src/SgAsmBinaryRor.h
    ${ROSE_TOP_BINARY_DIR}/src/ROSETTA/src/SgAsmBinarySubtract.h
    ${ROSE_TOP_BINARY_DIR}/src/ROSETTA/src/SgAsmBlock.h
    ${ROSE_TOP_BINARY_DIR}/src/ROSETTA/src/SgAsmByteOrder.h
    ${ROSE_TOP_BINARY_DIR}/src/ROSETTA/src/SgAsmCilAssembly.h
    ${ROSE_TOP_BINARY_DIR}/src/ROSETTA/src/SgAsmCilAssemblyOS.h
    ${ROSE_TOP_BINARY_DIR}/src/ROSETTA/src/SgAsmCilAssemblyOSTable.h
    ${ROSE_TOP_BINARY_DIR}/src/ROSETTA/src/SgAsmCilAssemblyProcessor.h
    ${ROSE_TOP_BINARY_DIR}/src/ROSETTA/src/SgAsmCilAssemblyProcessorTable.h
    ${ROSE_TOP_BINARY_DIR}/src/ROSETTA/src/SgAsmCilAssemblyRef.h
    ${ROSE_TOP_BINARY_DIR}/src/ROSETTA/src/SgAsmCilAssemblyRefOS.h
    ${ROSE_TOP_BINARY_DIR}/src/ROSETTA/src/SgAsmCilAssemblyRefOSTable.h
    ${ROSE_TOP_BINARY_DIR}/src/ROSETTA/src/SgAsmCilAssemblyRefProcessor.h
    ${ROSE_TOP_BINARY_DIR}/src/ROSETTA/src/SgAsmCilAssemblyRefProcessorTable.h
    ${ROSE_TOP_BINARY_DIR}/src/ROSETTA/src/SgAsmCilAssemblyRefTable.h
    ${ROSE_TOP_BINARY_DIR}/src/ROSETTA/src/SgAsmCilAssemblyTable.h
    ${ROSE_TOP_BINARY_DIR}/src/ROSETTA/src/SgAsmCilClassLayout.h
    ${ROSE_TOP_BINARY_DIR}/src/ROSETTA/src/SgAsmCilClassLayoutTable.h
    ${ROSE_TOP_BINARY_DIR}/src/ROSETTA/src/SgAsmCilConstant.h
    ${ROSE_TOP_BINARY_DIR}/src/ROSETTA/src/SgAsmCilConstantTable.h
    ${ROSE_TOP_BINARY_DIR}/src/ROSETTA/src/SgAsmCilCustomAttribute.h
    ${ROSE_TOP_BINARY_DIR}/src/ROSETTA/src/SgAsmCilCustomAttributeTable.h
    ${ROSE_TOP_BINARY_DIR}/src/ROSETTA/src/SgAsmCilDataStream.h
    ${ROSE_TOP_BINARY_DIR}/src/ROSETTA/src/SgAsmCilDeclSecurity.h
    ${ROSE_TOP_BINARY_DIR}/src/ROSETTA/src/SgAsmCilDeclSecurityTable.h
    ${ROSE_TOP_BINARY_DIR}/src/ROSETTA/src/SgAsmCilEvent.h
    ${ROSE_TOP_BINARY_DIR}/src/ROSETTA/src/SgAsmCilEventMap.h
    ${ROSE_TOP_BINARY_DIR}/src/ROSETTA/src/SgAsmCilEventMapTable.h
    ${ROSE_TOP_BINARY_DIR}/src/ROSETTA/src/SgAsmCilEventTable.h
    ${ROSE_TOP_BINARY_DIR}/src/ROSETTA/src/SgAsmCilExceptionData.h
    ${ROSE_TOP_BINARY_DIR}/src/ROSETTA/src/SgAsmCilExportedType.h
    ${ROSE_TOP_BINARY_DIR}/src/ROSETTA/src/SgAsmCilExportedTypeTable.h
    ${ROSE_TOP_BINARY_DIR}/src/ROSETTA/src/SgAsmCilField.h
    ${ROSE_TOP_BINARY_DIR}/src/ROSETTA/src/SgAsmCilFieldLayout.h
    ${ROSE_TOP_BINARY_DIR}/src/ROSETTA/src/SgAsmCilFieldLayoutTable.h
    ${ROSE_TOP_BINARY_DIR}/src/ROSETTA/src/SgAsmCilFieldMarshal.h
    ${ROSE_TOP_BINARY_DIR}/src/ROSETTA/src/SgAsmCilFieldMarshalTable.h
    ${ROSE_TOP_BINARY_DIR}/src/ROSETTA/src/SgAsmCilFieldRVA.h
    ${ROSE_TOP_BINARY_DIR}/src/ROSETTA/src/SgAsmCilFieldRVATable.h
    ${ROSE_TOP_BINARY_DIR}/src/ROSETTA/src/SgAsmCilFieldTable.h
    ${ROSE_TOP_BINARY_DIR}/src/ROSETTA/src/SgAsmCilFile.h
    ${ROSE_TOP_BINARY_DIR}/src/ROSETTA/src/SgAsmCilFileTable.h
    ${ROSE_TOP_BINARY_DIR}/src/ROSETTA/src/SgAsmCilGenericParamConstraint.h
    ${ROSE_TOP_BINARY_DIR}/src/ROSETTA/src/SgAsmCilGenericParamConstraintTable.h
    ${ROSE_TOP_BINARY_DIR}/src/ROSETTA/src/SgAsmCilGenericParam.h
    ${ROSE_TOP_BINARY_DIR}/src/ROSETTA/src/SgAsmCilGenericParamTable.h
    ${ROSE_TOP_BINARY_DIR}/src/ROSETTA/src/SgAsmCilImplMap.h
    ${ROSE_TOP_BINARY_DIR}/src/ROSETTA/src/SgAsmCilImplMapTable.h
    ${ROSE_TOP_BINARY_DIR}/src/ROSETTA/src/SgAsmCilInstruction.h
    ${ROSE_TOP_BINARY_DIR}/src/ROSETTA/src/SgAsmCilInterfaceImpl.h
    ${ROSE_TOP_BINARY_DIR}/src/ROSETTA/src/SgAsmCilInterfaceImplTable.h
    ${ROSE_TOP_BINARY_DIR}/src/ROSETTA/src/SgAsmCilManifestResource.h
    ${ROSE_TOP_BINARY_DIR}/src/ROSETTA/src/SgAsmCilManifestResourceTable.h
    ${ROSE_TOP_BINARY_DIR}/src/ROSETTA/src/SgAsmCilMemberRef.h
    ${ROSE_TOP_BINARY_DIR}/src/ROSETTA/src/SgAsmCilMemberRefTable.h
    ${ROSE_TOP_BINARY_DIR}/src/ROSETTA/src/SgAsmCilMetadata.h
    ${ROSE_TOP_BINARY_DIR}/src/ROSETTA/src/SgAsmCilMetadataHeap.h
    ${ROSE_TOP_BINARY_DIR}/src/ROSETTA/src/SgAsmCilMetadataRoot.h
    ${ROSE_TOP_BINARY_DIR}/src/ROSETTA/src/SgAsmCilMethodData.h
    ${ROSE_TOP_BINARY_DIR}/src/ROSETTA/src/SgAsmCilMethodDef.h
    ${ROSE_TOP_BINARY_DIR}/src/ROSETTA/src/SgAsmCilMethodDefTable.h
    ${ROSE_TOP_BINARY_DIR}/src/ROSETTA/src/SgAsmCilMethodImpl.h
    ${ROSE_TOP_BINARY_DIR}/src/ROSETTA/src/SgAsmCilMethodImplTable.h
    ${ROSE_TOP_BINARY_DIR}/src/ROSETTA/src/SgAsmCilMethodSemantics.h
    ${ROSE_TOP_BINARY_DIR}/src/ROSETTA/src/SgAsmCilMethodSemanticsTable.h
    ${ROSE_TOP_BINARY_DIR}/src/ROSETTA/src/SgAsmCilMethodSpec.h
    ${ROSE_TOP_BINARY_DIR}/src/ROSETTA/src/SgAsmCilMethodSpecTable.h
    ${ROSE_TOP_BINARY_DIR}/src/ROSETTA/src/SgAsmCilModule.h
    ${ROSE_TOP_BINARY_DIR}/src/ROSETTA/src/SgAsmCilModuleRef.h
    ${ROSE_TOP_BINARY_DIR}/src/ROSETTA/src/SgAsmCilModuleRefTable.h
    ${ROSE_TOP_BINARY_DIR}/src/ROSETTA/src/SgAsmCilModuleTable.h
    ${ROSE_TOP_BINARY_DIR}/src/ROSETTA/src/SgAsmCilNestedClass.h
    ${ROSE_TOP_BINARY_DIR}/src/ROSETTA/src/SgAsmCilNestedClassTable.h
    ${ROSE_TOP_BINARY_DIR}/src/ROSETTA/src/SgAsmCilNode.h
    ${ROSE_TOP_BINARY_DIR}/src/ROSETTA/src/SgAsmCilParam.h
    ${ROSE_TOP_BINARY_DIR}/src/ROSETTA/src/SgAsmCilParamTable.h
    ${ROSE_TOP_BINARY_DIR}/src/ROSETTA/src/SgAsmCilProperty.h
    ${ROSE_TOP_BINARY_DIR}/src/ROSETTA/src/SgAsmCilPropertyMap.h
    ${ROSE_TOP_BINARY_DIR}/src/ROSETTA/src/SgAsmCilPropertyMapTable.h
    ${ROSE_TOP_BINARY_DIR}/src/ROSETTA/src/SgAsmCilPropertyTable.h
    ${ROSE_TOP_BINARY_DIR}/src/ROSETTA/src/SgAsmCilStandAloneSig.h
    ${ROSE_TOP_BINARY_DIR}/src/ROSETTA/src/SgAsmCilStandAloneSigTable.h
    ${ROSE_TOP_BINARY_DIR}/src/ROSETTA/src/SgAsmCilTypeDef.h
    ${ROSE_TOP_BINARY_DIR}/src/ROSETTA/src/SgAsmCilTypeDefTable.h
    ${ROSE_TOP_BINARY_DIR}/src/ROSETTA/src/SgAsmCilTypeRef.h
    ${ROSE_TOP_BINARY_DIR}/src/ROSETTA/src/SgAsmCilTypeRefTable.h
    ${ROSE_TOP_BINARY_DIR}/src/ROSETTA/src/SgAsmCilTypeSpec.h
    ${ROSE_TOP_BINARY_DIR}/src/ROSETTA/src/SgAsmCilTypeSpecTable.h
    ${ROSE_TOP_BINARY_DIR}/src/ROSETTA/src/SgAsmCilUint32Heap.h
    ${ROSE_TOP_BINARY_DIR}/src/ROSETTA/src/SgAsmCilUint8Heap.h
    ${ROSE_TOP_BINARY_DIR}/src/ROSETTA/src/SgAsmCliHeader.h
    ${ROSE_TOP_BINARY_DIR}/src/ROSETTA/src/SgAsmCoffStrtab.h
    ${ROSE_TOP_BINARY_DIR}/src/ROSETTA/src/SgAsmCoffSymbol.h
    ${ROSE_TOP_BINARY_DIR}/src/ROSETTA/src/SgAsmCoffSymbolList.h
    ${ROSE_TOP_BINARY_DIR}/src/ROSETTA/src/SgAsmCoffSymbolTable.h
    ${ROSE_TOP_BINARY_DIR}/src/ROSETTA/src/SgAsmCommonSubExpression.h
    ${ROSE_TOP_BINARY_DIR}/src/ROSETTA/src/SgAsmConstantExpression.h
    ${ROSE_TOP_BINARY_DIR}/src/ROSETTA/src/SgAsmControlFlagsExpression.h
    ${ROSE_TOP_BINARY_DIR}/src/ROSETTA/src/SgAsmDirectRegisterExpression.h
    ${ROSE_TOP_BINARY_DIR}/src/ROSETTA/src/SgAsmDOSExtendedHeader.h
    ${ROSE_TOP_BINARY_DIR}/src/ROSETTA/src/SgAsmDOSFileHeader.h
    ${ROSE_TOP_BINARY_DIR}/src/ROSETTA/src/SgAsmDwarfAccessDeclaration.h
    ${ROSE_TOP_BINARY_DIR}/src/ROSETTA/src/SgAsmDwarfArrayType.h
    ${ROSE_TOP_BINARY_DIR}/src/ROSETTA/src/SgAsmDwarfBaseType.h
    ${ROSE_TOP_BINARY_DIR}/src/ROSETTA/src/SgAsmDwarfCatchBlock.h
    ${ROSE_TOP_BINARY_DIR}/src/ROSETTA/src/SgAsmDwarfClassTemplate.h
    ${ROSE_TOP_BINARY_DIR}/src/ROSETTA/src/SgAsmDwarfClassType.h
    ${ROSE_TOP_BINARY_DIR}/src/ROSETTA/src/SgAsmDwarfCommonBlock.h
    ${ROSE_TOP_BINARY_DIR}/src/ROSETTA/src/SgAsmDwarfCommonInclusion.h
    ${ROSE_TOP_BINARY_DIR}/src/ROSETTA/src/SgAsmDwarfCompilationUnit.h
    ${ROSE_TOP_BINARY_DIR}/src/ROSETTA/src/SgAsmDwarfCompilationUnitList.h
    ${ROSE_TOP_BINARY_DIR}/src/ROSETTA/src/SgAsmDwarfCondition.h
    ${ROSE_TOP_BINARY_DIR}/src/ROSETTA/src/SgAsmDwarfConstant.h
    ${ROSE_TOP_BINARY_DIR}/src/ROSETTA/src/SgAsmDwarfConstruct.h
    ${ROSE_TOP_BINARY_DIR}/src/ROSETTA/src/SgAsmDwarfConstructList.h
    ${ROSE_TOP_BINARY_DIR}/src/ROSETTA/src/SgAsmDwarfConstType.h
    ${ROSE_TOP_BINARY_DIR}/src/ROSETTA/src/SgAsmDwarfDwarfProcedure.h
    ${ROSE_TOP_BINARY_DIR}/src/ROSETTA/src/SgAsmDwarfEntryPoint.h
    ${ROSE_TOP_BINARY_DIR}/src/ROSETTA/src/SgAsmDwarfEnumerationType.h
    ${ROSE_TOP_BINARY_DIR}/src/ROSETTA/src/SgAsmDwarfEnumerator.h
    ${ROSE_TOP_BINARY_DIR}/src/ROSETTA/src/SgAsmDwarfFileType.h
    ${ROSE_TOP_BINARY_DIR}/src/ROSETTA/src/SgAsmDwarfFormalParameter.h
    ${ROSE_TOP_BINARY_DIR}/src/ROSETTA/src/SgAsmDwarfFormatLabel.h
    ${ROSE_TOP_BINARY_DIR}/src/ROSETTA/src/SgAsmDwarfFriend.h
    ${ROSE_TOP_BINARY_DIR}/src/ROSETTA/src/SgAsmDwarfFunctionTemplate.h
    ${ROSE_TOP_BINARY_DIR}/src/ROSETTA/src/SgAsmDwarfImportedDeclaration.h
    ${ROSE_TOP_BINARY_DIR}/src/ROSETTA/src/SgAsmDwarfImportedModule.h
    ${ROSE_TOP_BINARY_DIR}/src/ROSETTA/src/SgAsmDwarfImportedUnit.h
    ${ROSE_TOP_BINARY_DIR}/src/ROSETTA/src/SgAsmDwarfInformation.h
    ${ROSE_TOP_BINARY_DIR}/src/ROSETTA/src/SgAsmDwarfInheritance.h
    ${ROSE_TOP_BINARY_DIR}/src/ROSETTA/src/SgAsmDwarfInlinedSubroutine.h
    ${ROSE_TOP_BINARY_DIR}/src/ROSETTA/src/SgAsmDwarfInterfaceType.h
    ${ROSE_TOP_BINARY_DIR}/src/ROSETTA/src/SgAsmDwarfLabel.h
    ${ROSE_TOP_BINARY_DIR}/src/ROSETTA/src/SgAsmDwarfLexicalBlock.h
    ${ROSE_TOP_BINARY_DIR}/src/ROSETTA/src/SgAsmDwarfLine.h
    ${ROSE_TOP_BINARY_DIR}/src/ROSETTA/src/SgAsmDwarfLineList.h
    ${ROSE_TOP_BINARY_DIR}/src/ROSETTA/src/SgAsmDwarfMacro.h
    ${ROSE_TOP_BINARY_DIR}/src/ROSETTA/src/SgAsmDwarfMacroList.h
    ${ROSE_TOP_BINARY_DIR}/src/ROSETTA/src/SgAsmDwarfMember.h
    ${ROSE_TOP_BINARY_DIR}/src/ROSETTA/src/SgAsmDwarfModule.h
    ${ROSE_TOP_BINARY_DIR}/src/ROSETTA/src/SgAsmDwarfMutableType.h
    ${ROSE_TOP_BINARY_DIR}/src/ROSETTA/src/SgAsmDwarfNamelist.h
    ${ROSE_TOP_BINARY_DIR}/src/ROSETTA/src/SgAsmDwarfNamelistItem.h
    ${ROSE_TOP_BINARY_DIR}/src/ROSETTA/src/SgAsmDwarfNamespace.h
    ${ROSE_TOP_BINARY_DIR}/src/ROSETTA/src/SgAsmDwarfPackedType.h
    ${ROSE_TOP_BINARY_DIR}/src/ROSETTA/src/SgAsmDwarfPartialUnit.h
    ${ROSE_TOP_BINARY_DIR}/src/ROSETTA/src/SgAsmDwarfPointerType.h
    ${ROSE_TOP_BINARY_DIR}/src/ROSETTA/src/SgAsmDwarfPtrToMemberType.h
    ${ROSE_TOP_BINARY_DIR}/src/ROSETTA/src/SgAsmDwarfReferenceType.h
    ${ROSE_TOP_BINARY_DIR}/src/ROSETTA/src/SgAsmDwarfRestrictType.h
    ${ROSE_TOP_BINARY_DIR}/src/ROSETTA/src/SgAsmDwarfSetType.h
    ${ROSE_TOP_BINARY_DIR}/src/ROSETTA/src/SgAsmDwarfSharedType.h
    ${ROSE_TOP_BINARY_DIR}/src/ROSETTA/src/SgAsmDwarfStringType.h
    ${ROSE_TOP_BINARY_DIR}/src/ROSETTA/src/SgAsmDwarfStructureType.h
    ${ROSE_TOP_BINARY_DIR}/src/ROSETTA/src/SgAsmDwarfSubprogram.h
    ${ROSE_TOP_BINARY_DIR}/src/ROSETTA/src/SgAsmDwarfSubrangeType.h
    ${ROSE_TOP_BINARY_DIR}/src/ROSETTA/src/SgAsmDwarfSubroutineType.h
    ${ROSE_TOP_BINARY_DIR}/src/ROSETTA/src/SgAsmDwarfTemplateTypeParameter.h
    ${ROSE_TOP_BINARY_DIR}/src/ROSETTA/src/SgAsmDwarfTemplateValueParameter.h
    ${ROSE_TOP_BINARY_DIR}/src/ROSETTA/src/SgAsmDwarfThrownType.h
    ${ROSE_TOP_BINARY_DIR}/src/ROSETTA/src/SgAsmDwarfTryBlock.h
    ${ROSE_TOP_BINARY_DIR}/src/ROSETTA/src/SgAsmDwarfTypedef.h
    ${ROSE_TOP_BINARY_DIR}/src/ROSETTA/src/SgAsmDwarfUnionType.h
    ${ROSE_TOP_BINARY_DIR}/src/ROSETTA/src/SgAsmDwarfUnknownConstruct.h
    ${ROSE_TOP_BINARY_DIR}/src/ROSETTA/src/SgAsmDwarfUnspecifiedParameters.h
    ${ROSE_TOP_BINARY_DIR}/src/ROSETTA/src/SgAsmDwarfUnspecifiedType.h
    ${ROSE_TOP_BINARY_DIR}/src/ROSETTA/src/SgAsmDwarfUpcRelaxedType.h
    ${ROSE_TOP_BINARY_DIR}/src/ROSETTA/src/SgAsmDwarfUpcSharedType.h
    ${ROSE_TOP_BINARY_DIR}/src/ROSETTA/src/SgAsmDwarfUpcStrictType.h
    ${ROSE_TOP_BINARY_DIR}/src/ROSETTA/src/SgAsmDwarfVariable.h
    ${ROSE_TOP_BINARY_DIR}/src/ROSETTA/src/SgAsmDwarfVariant.h
    ${ROSE_TOP_BINARY_DIR}/src/ROSETTA/src/SgAsmDwarfVariantPart.h
    ${ROSE_TOP_BINARY_DIR}/src/ROSETTA/src/SgAsmDwarfVolatileType.h
    ${ROSE_TOP_BINARY_DIR}/src/ROSETTA/src/SgAsmDwarfWithStmt.h
    ${ROSE_TOP_BINARY_DIR}/src/ROSETTA/src/SgAsmElfDynamicEntry.h
    ${ROSE_TOP_BINARY_DIR}/src/ROSETTA/src/SgAsmElfDynamicEntryList.h
    ${ROSE_TOP_BINARY_DIR}/src/ROSETTA/src/SgAsmElfDynamicSection.h
    ${ROSE_TOP_BINARY_DIR}/src/ROSETTA/src/SgAsmElfEHFrameEntryCI.h
    ${ROSE_TOP_BINARY_DIR}/src/ROSETTA/src/SgAsmElfEHFrameEntryCIList.h
    ${ROSE_TOP_BINARY_DIR}/src/ROSETTA/src/SgAsmElfEHFrameEntryFD.h
    ${ROSE_TOP_BINARY_DIR}/src/ROSETTA/src/SgAsmElfEHFrameEntryFDList.h
    ${ROSE_TOP_BINARY_DIR}/src/ROSETTA/src/SgAsmElfEHFrameSection.h
    ${ROSE_TOP_BINARY_DIR}/src/ROSETTA/src/SgAsmElfFileHeader.h
    ${ROSE_TOP_BINARY_DIR}/src/ROSETTA/src/SgAsmElfNoteEntry.h
    ${ROSE_TOP_BINARY_DIR}/src/ROSETTA/src/SgAsmElfNoteEntryList.h
    ${ROSE_TOP_BINARY_DIR}/src/ROSETTA/src/SgAsmElfNoteSection.h
    ${ROSE_TOP_BINARY_DIR}/src/ROSETTA/src/SgAsmElfRelocEntry.h
    ${ROSE_TOP_BINARY_DIR}/src/ROSETTA/src/SgAsmElfRelocEntryList.h
    ${ROSE_TOP_BINARY_DIR}/src/ROSETTA/src/SgAsmElfRelocSection.h
    ${ROSE_TOP_BINARY_DIR}/src/ROSETTA/src/SgAsmElfSection.h
    ${ROSE_TOP_BINARY_DIR}/src/ROSETTA/src/SgAsmElfSectionTableEntry.h
    ${ROSE_TOP_BINARY_DIR}/src/ROSETTA/src/SgAsmElfSectionTable.h
    ${ROSE_TOP_BINARY_DIR}/src/ROSETTA/src/SgAsmElfSegmentTableEntry.h
    ${ROSE_TOP_BINARY_DIR}/src/ROSETTA/src/SgAsmElfSegmentTableEntryList.h
    ${ROSE_TOP_BINARY_DIR}/src/ROSETTA/src/SgAsmElfSegmentTable.h
    ${ROSE_TOP_BINARY_DIR}/src/ROSETTA/src/SgAsmElfStringSection.h
    ${ROSE_TOP_BINARY_DIR}/src/ROSETTA/src/SgAsmElfStrtab.h
    ${ROSE_TOP_BINARY_DIR}/src/ROSETTA/src/SgAsmElfSymbol.h
    ${ROSE_TOP_BINARY_DIR}/src/ROSETTA/src/SgAsmElfSymbolList.h
    ${ROSE_TOP_BINARY_DIR}/src/ROSETTA/src/SgAsmElfSymbolSection.h
    ${ROSE_TOP_BINARY_DIR}/src/ROSETTA/src/SgAsmElfSymverDefinedAux.h
    ${ROSE_TOP_BINARY_DIR}/src/ROSETTA/src/SgAsmElfSymverDefinedAuxList.h
    ${ROSE_TOP_BINARY_DIR}/src/ROSETTA/src/SgAsmElfSymverDefinedEntry.h
    ${ROSE_TOP_BINARY_DIR}/src/ROSETTA/src/SgAsmElfSymverDefinedEntryList.h
    ${ROSE_TOP_BINARY_DIR}/src/ROSETTA/src/SgAsmElfSymverDefinedSection.h
    ${ROSE_TOP_BINARY_DIR}/src/ROSETTA/src/SgAsmElfSymverEntry.h
    ${ROSE_TOP_BINARY_DIR}/src/ROSETTA/src/SgAsmElfSymverEntryList.h
    ${ROSE_TOP_BINARY_DIR}/src/ROSETTA/src/SgAsmElfSymverNeededAux.h
    ${ROSE_TOP_BINARY_DIR}/src/ROSETTA/src/SgAsmElfSymverNeededAuxList.h
    ${ROSE_TOP_BINARY_DIR}/src/ROSETTA/src/SgAsmElfSymverNeededEntry.h
    ${ROSE_TOP_BINARY_DIR}/src/ROSETTA/src/SgAsmElfSymverNeededEntryList.h
    ${ROSE_TOP_BINARY_DIR}/src/ROSETTA/src/SgAsmElfSymverNeededSection.h
    ${ROSE_TOP_BINARY_DIR}/src/ROSETTA/src/SgAsmElfSymverSection.h
    ${ROSE_TOP_BINARY_DIR}/src/ROSETTA/src/SgAsmExecutableFileFormat.h
    ${ROSE_TOP_BINARY_DIR}/src/ROSETTA/src/SgAsmExpression.h
    ${ROSE_TOP_BINARY_DIR}/src/ROSETTA/src/SgAsmExprListExp.h
    ${ROSE_TOP_BINARY_DIR}/src/ROSETTA/src/SgAsmFloatType.h
    ${ROSE_TOP_BINARY_DIR}/src/ROSETTA/src/SgAsmFloatValueExpression.h
    ${ROSE_TOP_BINARY_DIR}/src/ROSETTA/src/SgAsmFunction.h
    ${ROSE_TOP_BINARY_DIR}/src/ROSETTA/src/SgAsmGenericDLL.h
    ${ROSE_TOP_BINARY_DIR}/src/ROSETTA/src/SgAsmGenericDLLList.h
    ${ROSE_TOP_BINARY_DIR}/src/ROSETTA/src/SgAsmGenericFile.h
    ${ROSE_TOP_BINARY_DIR}/src/ROSETTA/src/SgAsmGenericFileList.h
    ${ROSE_TOP_BINARY_DIR}/src/ROSETTA/src/SgAsmGenericFormat.h
    ${ROSE_TOP_BINARY_DIR}/src/ROSETTA/src/SgAsmGenericHeader.h
    ${ROSE_TOP_BINARY_DIR}/src/ROSETTA/src/SgAsmGenericHeaderList.h
    ${ROSE_TOP_BINARY_DIR}/src/ROSETTA/src/SgAsmGenericSection.h
    ${ROSE_TOP_BINARY_DIR}/src/ROSETTA/src/SgAsmGenericSectionList.h
    ${ROSE_TOP_BINARY_DIR}/src/ROSETTA/src/SgAsmGenericString.h
    ${ROSE_TOP_BINARY_DIR}/src/ROSETTA/src/SgAsmGenericStrtab.h
    ${ROSE_TOP_BINARY_DIR}/src/ROSETTA/src/SgAsmGenericSymbol.h
    ${ROSE_TOP_BINARY_DIR}/src/ROSETTA/src/SgAsmGenericSymbolList.h
    ${ROSE_TOP_BINARY_DIR}/src/ROSETTA/src/SgAsmIndirectRegisterExpression.h
    ${ROSE_TOP_BINARY_DIR}/src/ROSETTA/src/SgAsmInstruction.h
    ${ROSE_TOP_BINARY_DIR}/src/ROSETTA/src/SgAsmInstructionList.h
    ${ROSE_TOP_BINARY_DIR}/src/ROSETTA/src/SgAsmIntegerType.h
    ${ROSE_TOP_BINARY_DIR}/src/ROSETTA/src/SgAsmIntegerValueExpression.h
    ${ROSE_TOP_BINARY_DIR}/src/ROSETTA/src/SgAsmInterpretation.h
    ${ROSE_TOP_BINARY_DIR}/src/ROSETTA/src/SgAsmInterpretationList.h
    ${ROSE_TOP_BINARY_DIR}/src/ROSETTA/src/SgAsmJvmAnnotationDefault.h
    ${ROSE_TOP_BINARY_DIR}/src/ROSETTA/src/SgAsmJvmAttribute.h
    ${ROSE_TOP_BINARY_DIR}/src/ROSETTA/src/SgAsmJvmAttributeTable.h
    ${ROSE_TOP_BINARY_DIR}/src/ROSETTA/src/SgAsmJvmBootstrapMethod.h
    ${ROSE_TOP_BINARY_DIR}/src/ROSETTA/src/SgAsmJvmBootstrapMethods.h
    ${ROSE_TOP_BINARY_DIR}/src/ROSETTA/src/SgAsmJvmClass.h
    ${ROSE_TOP_BINARY_DIR}/src/ROSETTA/src/SgAsmJvmCodeAttribute.h
    ${ROSE_TOP_BINARY_DIR}/src/ROSETTA/src/SgAsmJvmConstantPoolEntry.h
    ${ROSE_TOP_BINARY_DIR}/src/ROSETTA/src/SgAsmJvmConstantPool.h
    ${ROSE_TOP_BINARY_DIR}/src/ROSETTA/src/SgAsmJvmConstantValue.h
    ${ROSE_TOP_BINARY_DIR}/src/ROSETTA/src/SgAsmJvmEnclosingMethod.h
    ${ROSE_TOP_BINARY_DIR}/src/ROSETTA/src/SgAsmJvmExceptionHandler.h
    ${ROSE_TOP_BINARY_DIR}/src/ROSETTA/src/SgAsmJvmExceptions.h
    ${ROSE_TOP_BINARY_DIR}/src/ROSETTA/src/SgAsmJvmExceptionTable.h
    ${ROSE_TOP_BINARY_DIR}/src/ROSETTA/src/SgAsmJvmField.h
    ${ROSE_TOP_BINARY_DIR}/src/ROSETTA/src/SgAsmJvmFieldTable.h
    ${ROSE_TOP_BINARY_DIR}/src/ROSETTA/src/SgAsmJvmFileHeader.h
    ${ROSE_TOP_BINARY_DIR}/src/ROSETTA/src/SgAsmJvmInnerClassesEntry.h
    ${ROSE_TOP_BINARY_DIR}/src/ROSETTA/src/SgAsmJvmInnerClasses.h
    ${ROSE_TOP_BINARY_DIR}/src/ROSETTA/src/SgAsmJvmInstruction.h
    ${ROSE_TOP_BINARY_DIR}/src/ROSETTA/src/SgAsmJvmLineNumberEntry.h
    ${ROSE_TOP_BINARY_DIR}/src/ROSETTA/src/SgAsmJvmLineNumberTable.h
    ${ROSE_TOP_BINARY_DIR}/src/ROSETTA/src/SgAsmJvmLocalVariableEntry.h
    ${ROSE_TOP_BINARY_DIR}/src/ROSETTA/src/SgAsmJvmLocalVariableTable.h
    ${ROSE_TOP_BINARY_DIR}/src/ROSETTA/src/SgAsmJvmLocalVariableTypeEntry.h
    ${ROSE_TOP_BINARY_DIR}/src/ROSETTA/src/SgAsmJvmLocalVariableTypeTable.h
    ${ROSE_TOP_BINARY_DIR}/src/ROSETTA/src/SgAsmJvmMethod.h
    ${ROSE_TOP_BINARY_DIR}/src/ROSETTA/src/SgAsmJvmMethodParametersEntry.h
    ${ROSE_TOP_BINARY_DIR}/src/ROSETTA/src/SgAsmJvmMethodParameters.h
    ${ROSE_TOP_BINARY_DIR}/src/ROSETTA/src/SgAsmJvmMethodTable.h
    ${ROSE_TOP_BINARY_DIR}/src/ROSETTA/src/SgAsmJvmModuleMainClass.h
    ${ROSE_TOP_BINARY_DIR}/src/ROSETTA/src/SgAsmJvmNestHost.h
    ${ROSE_TOP_BINARY_DIR}/src/ROSETTA/src/SgAsmJvmNestMembers.h
    ${ROSE_TOP_BINARY_DIR}/src/ROSETTA/src/SgAsmJvmNode.h
    ${ROSE_TOP_BINARY_DIR}/src/ROSETTA/src/SgAsmJvmSignature.h
    ${ROSE_TOP_BINARY_DIR}/src/ROSETTA/src/SgAsmJvmSourceFile.h
    ${ROSE_TOP_BINARY_DIR}/src/ROSETTA/src/SgAsmJvmStackMapFrame.h
    ${ROSE_TOP_BINARY_DIR}/src/ROSETTA/src/SgAsmJvmStackMapTable.h
    ${ROSE_TOP_BINARY_DIR}/src/ROSETTA/src/SgAsmJvmStackMapVerificationType.h
    ${ROSE_TOP_BINARY_DIR}/src/ROSETTA/src/SgAsmLEEntryPoint.h
    ${ROSE_TOP_BINARY_DIR}/src/ROSETTA/src/SgAsmLEEntryTable.h
    ${ROSE_TOP_BINARY_DIR}/src/ROSETTA/src/SgAsmLEFileHeader.h
    ${ROSE_TOP_BINARY_DIR}/src/ROSETTA/src/SgAsmLENameTable.h
    ${ROSE_TOP_BINARY_DIR}/src/ROSETTA/src/SgAsmLEPageTableEntry.h
    ${ROSE_TOP_BINARY_DIR}/src/ROSETTA/src/SgAsmLEPageTable.h
    ${ROSE_TOP_BINARY_DIR}/src/ROSETTA/src/SgAsmLERelocTable.h
    ${ROSE_TOP_BINARY_DIR}/src/ROSETTA/src/SgAsmLESection.h
    ${ROSE_TOP_BINARY_DIR}/src/ROSETTA/src/SgAsmLESectionTableEntry.h
    ${ROSE_TOP_BINARY_DIR}/src/ROSETTA/src/SgAsmLESectionTable.h
    ${ROSE_TOP_BINARY_DIR}/src/ROSETTA/src/SgAsmM68kInstruction.h
    ${ROSE_TOP_BINARY_DIR}/src/ROSETTA/src/SgAsmMemoryReferenceExpression.h
    ${ROSE_TOP_BINARY_DIR}/src/ROSETTA/src/SgAsmMipsInstruction.h
    ${ROSE_TOP_BINARY_DIR}/src/ROSETTA/src/SgAsmNEEntryPoint.h
    ${ROSE_TOP_BINARY_DIR}/src/ROSETTA/src/SgAsmNEEntryTable.h
    ${ROSE_TOP_BINARY_DIR}/src/ROSETTA/src/SgAsmNEFileHeader.h
    ${ROSE_TOP_BINARY_DIR}/src/ROSETTA/src/SgAsmNEModuleTable.h
    ${ROSE_TOP_BINARY_DIR}/src/ROSETTA/src/SgAsmNENameTable.h
    ${ROSE_TOP_BINARY_DIR}/src/ROSETTA/src/SgAsmNERelocEntry.h
    ${ROSE_TOP_BINARY_DIR}/src/ROSETTA/src/SgAsmNERelocTable.h
    ${ROSE_TOP_BINARY_DIR}/src/ROSETTA/src/SgAsmNESection.h
    ${ROSE_TOP_BINARY_DIR}/src/ROSETTA/src/SgAsmNESectionTableEntry.h
    ${ROSE_TOP_BINARY_DIR}/src/ROSETTA/src/SgAsmNESectionTable.h
    ${ROSE_TOP_BINARY_DIR}/src/ROSETTA/src/SgAsmNEStringTable.h
    ${ROSE_TOP_BINARY_DIR}/src/ROSETTA/src/SgAsmNode.h
    ${ROSE_TOP_BINARY_DIR}/src/ROSETTA/src/SgAsmNullInstruction.h
    ${ROSE_TOP_BINARY_DIR}/src/ROSETTA/src/SgAsmOperandList.h
    ${ROSE_TOP_BINARY_DIR}/src/ROSETTA/src/SgAsmPEExportDirectory.h
    ${ROSE_TOP_BINARY_DIR}/src/ROSETTA/src/SgAsmPEExportEntry.h
    ${ROSE_TOP_BINARY_DIR}/src/ROSETTA/src/SgAsmPEExportEntryList.h
    ${ROSE_TOP_BINARY_DIR}/src/ROSETTA/src/SgAsmPEExportSection.h
    ${ROSE_TOP_BINARY_DIR}/src/ROSETTA/src/SgAsmPEFileHeader.h
    ${ROSE_TOP_BINARY_DIR}/src/ROSETTA/src/SgAsmPEImportDirectory.h
    ${ROSE_TOP_BINARY_DIR}/src/ROSETTA/src/SgAsmPEImportDirectoryList.h
    ${ROSE_TOP_BINARY_DIR}/src/ROSETTA/src/SgAsmPEImportItem.h
    ${ROSE_TOP_BINARY_DIR}/src/ROSETTA/src/SgAsmPEImportItemList.h
    ${ROSE_TOP_BINARY_DIR}/src/ROSETTA/src/SgAsmPEImportSection.h
    ${ROSE_TOP_BINARY_DIR}/src/ROSETTA/src/SgAsmPERVASizePair.h
    ${ROSE_TOP_BINARY_DIR}/src/ROSETTA/src/SgAsmPERVASizePairList.h
    ${ROSE_TOP_BINARY_DIR}/src/ROSETTA/src/SgAsmPESection.h
    ${ROSE_TOP_BINARY_DIR}/src/ROSETTA/src/SgAsmPESectionTableEntry.h
    ${ROSE_TOP_BINARY_DIR}/src/ROSETTA/src/SgAsmPESectionTable.h
    ${ROSE_TOP_BINARY_DIR}/src/ROSETTA/src/SgAsmPEStringSection.h
    ${ROSE_TOP_BINARY_DIR}/src/ROSETTA/src/SgAsmPointerType.h
    ${ROSE_TOP_BINARY_DIR}/src/ROSETTA/src/SgAsmPowerpcInstruction.h
    ${ROSE_TOP_BINARY_DIR}/src/ROSETTA/src/SgAsmRegisterNames.h
    ${ROSE_TOP_BINARY_DIR}/src/ROSETTA/src/SgAsmRegisterReferenceExpression.h
    ${ROSE_TOP_BINARY_DIR}/src/ROSETTA/src/SgAsmRiscOperation.h
    ${ROSE_TOP_BINARY_DIR}/src/ROSETTA/src/SgAsmScalarType.h
    ${ROSE_TOP_BINARY_DIR}/src/ROSETTA/src/SgAsmStackExpression.h
    ${ROSE_TOP_BINARY_DIR}/src/ROSETTA/src/SgAsmStatement.h
    ${ROSE_TOP_BINARY_DIR}/src/ROSETTA/src/SgAsmStaticData.h
    ${ROSE_TOP_BINARY_DIR}/src/ROSETTA/src/SgAsmStoredString.h
    ${ROSE_TOP_BINARY_DIR}/src/ROSETTA/src/SgAsmStringStorage.h
    ${ROSE_TOP_BINARY_DIR}/src/ROSETTA/src/SgAsmSynthesizedDataStructureDeclaration.h
    ${ROSE_TOP_BINARY_DIR}/src/ROSETTA/src/SgAsmSynthesizedDeclaration.h
    ${ROSE_TOP_BINARY_DIR}/src/ROSETTA/src/SgAsmSynthesizedFieldDeclaration.h
    ${ROSE_TOP_BINARY_DIR}/src/ROSETTA/src/SgAsmType.h
    ${ROSE_TOP_BINARY_DIR}/src/ROSETTA/src/SgAsmUnaryExpression.h
    ${ROSE_TOP_BINARY_DIR}/src/ROSETTA/src/SgAsmUnaryMinus.h
    ${ROSE_TOP_BINARY_DIR}/src/ROSETTA/src/SgAsmUnaryPlus.h
    ${ROSE_TOP_BINARY_DIR}/src/ROSETTA/src/SgAsmUnaryRrx.h
    ${ROSE_TOP_BINARY_DIR}/src/ROSETTA/src/SgAsmUnarySignedExtend.h
    ${ROSE_TOP_BINARY_DIR}/src/ROSETTA/src/SgAsmUnaryTruncate.h
    ${ROSE_TOP_BINARY_DIR}/src/ROSETTA/src/SgAsmUnaryUnsignedExtend.h
    ${ROSE_TOP_BINARY_DIR}/src/ROSETTA/src/SgAsmUserInstruction.h
    ${ROSE_TOP_BINARY_DIR}/src/ROSETTA/src/SgAsmValueExpression.h
    ${ROSE_TOP_BINARY_DIR}/src/ROSETTA/src/SgAsmVectorType.h
    ${ROSE_TOP_BINARY_DIR}/src/ROSETTA/src/SgAsmVoidType.h
    ${ROSE_TOP_BINARY_DIR}/src/ROSETTA/src/SgAsmX86Instruction.h
    ${ROSE_TOP_BINARY_DIR}/src/ROSETTA/src/SgAsmJvmIndexedAttribute.h
    ${ROSE_TOP_BINARY_DIR}/src/ROSETTA/src/SgAsmJvmRuntimeAnnotation.h
    ${ROSE_TOP_BINARY_DIR}/src/ROSETTA/src/SgAsmJvmRuntimeAnnotationPair.h
    ${ROSE_TOP_BINARY_DIR}/src/ROSETTA/src/SgAsmJvmRuntimeAnnotationValue.h
    ${ROSE_TOP_BINARY_DIR}/src/ROSETTA/src/SgAsmJvmRuntimeParameterAnnotation.h
    ${ROSE_TOP_BINARY_DIR}/src/ROSETTA/src/SgAsmJvmRuntimeVisibleAnnotations.h
    ${ROSE_TOP_BINARY_DIR}/src/ROSETTA/src/SgAsmJvmRuntimeVisibilityParamAnnotations.h
    ${ROSE_TOP_BINARY_DIR}/src/ROSETTA/src/SgAsmJvmRuntimeInvisibleAnnotations.h
    )

#temporaries of source files generated by ROSETTA
set(GENERATED_SRC
    ${ROSE_TOP_BINARY_DIR}/src/ROSETTA/src/AST_FILE_IO.C                                   
    ${ROSE_TOP_BINARY_DIR}/src/ROSETTA/src/Cxx_GrammarNewAndDeleteOperators.C                
    ${ROSE_TOP_BINARY_DIR}/src/ROSETTA/src/Cxx_GrammarTraverseMemoryPool.C
    ${ROSE_TOP_BINARY_DIR}/src/ROSETTA/src/Cxx_Grammar.C
    ${ROSE_TOP_BINARY_DIR}/src/ROSETTA/src/Cxx_GrammarNewConstructors.C
    ${ROSE_TOP_BINARY_DIR}/src/ROSETTA/src/Cxx_GrammarTreeTraversalSuccessorContainer.C
    ${ROSE_TOP_BINARY_DIR}/src/ROSETTA/src/Cxx_GrammarCheckingIfDataMembersAreInMemoryPool.C
    ${ROSE_TOP_BINARY_DIR}/src/ROSETTA/src/Cxx_GrammarProcessDataMemberReferenceToPointers.C  
    ${ROSE_TOP_BINARY_DIR}/src/ROSETTA/src/Cxx_GrammarVariantEnumNames.C
    ${ROSE_TOP_BINARY_DIR}/src/ROSETTA/src/Cxx_GrammarCopyMemberFunctions.C
    ${ROSE_TOP_BINARY_DIR}/src/ROSETTA/src/Cxx_GrammarReturnClassHierarchySubTree.C      
    ${ROSE_TOP_BINARY_DIR}/src/ROSETTA/src/SourcesOfIRNodesAstFileIOSupport.C
    ${ROSE_TOP_BINARY_DIR}/src/ROSETTA/src/Cxx_GrammarGetChildIndex.C
    ${ROSE_TOP_BINARY_DIR}/src/ROSETTA/src/Cxx_GrammarReturnDataMemberPointers.C  
    ${ROSE_TOP_BINARY_DIR}/src/ROSETTA/src/StorageClasses.C
    ${ROSE_TOP_BINARY_DIR}/src/ROSETTA/src/Cxx_GrammarMemoryPoolSupport.C  
    ${ROSE_TOP_BINARY_DIR}/src/ROSETTA/src/Cxx_GrammarRTI.C
    ${ROSE_TOP_BINARY_DIR}/src/ROSETTA/src/Cxx_GrammarVisitorSupport.C
    )
#Copy the generated files to ${BUILD_DIR}/src/frontend/SageIII
foreach (src ${GENERATED_HEADERS} ${GENERATED_SRC})
  get_filename_component (FILE_BASE ${src} NAME_WE)

  add_custom_command(
      OUTPUT ${CMAKE_BINARY_DIR}/src/frontend/SageIII/${FILE_BASE} 
      COMMAND
      ${CMAKE_COMMAND}  -E copy  ${FILE_BASE} ${ROSE_TOP_BINARY_DIR}/src/frontend/SageIII/${FILE_BASE}
      DEPENDS ${FILE_BASE} 
      )
endforeach(src)

