if(CPACK_GENERATOR MATCHES "NSIS")
  set(CPACK_NSIS_DISPLAY_NAME "ROSE - open source compiler infrastructure")
  set(CPACK_NSIS_HELP_LINK "http:\\\\rosecompiler.org")
  set(CPACK_NSIS_URL_INFO_ABOUT "http:\\\\rosecompiler.org")
endif()
