#define EOF_Sym	0	/* EOF */
#define SgNameSym	1	/* SgName */
#define SgSymbolTableSym	2	/* SgSymbolTable */
#define SgInitializedNameSym	3	/* SgInitializedName */
#define SgModifierNodesSym	4	/* SgModifierNodes */
#define SgUnderscoreFileUnderscoreInSym	5	/* Sg_File_Info */
#define SgFileSym	6	/* SgFile */
#define SgProjectSym	7	/* SgProject */
#define SgOptionsSym	8	/* SgOptions */
#define SgUnparseUnderscoreInfoSym	9	/* SgUnparse_Info */
#define SgBaseClassSym	10	/* SgBaseClass */
#define SgTypedefSeqSym	11	/* SgTypedefSeq */
#define SgFunctionParameterTypeListSym	12	/* SgFunctionParameterTypeList */
#define SgPragmaSym	13	/* SgPragma */
#define SgFuncDeclUnderscoreattrSym	14	/* SgFuncDecl_attr */
#define SgClassDeclUnderscoreattrSym	15	/* SgClassDecl_attr */
#define SgFunctionTypeTableSym	16	/* SgFunctionTypeTable */
#define SgExprStatementSym	17	/* SgExprStatement */
#define SgLabelStatementSym	18	/* SgLabelStatement */
#define SgCaseOptionStmtSym	19	/* SgCaseOptionStmt */
#define SgTryStmtSym	20	/* SgTryStmt */
#define SgDefaultOptionStmtSym	21	/* SgDefaultOptionStmt */
#define SgBreakStmtSym	22	/* SgBreakStmt */
#define SgContinueStmtSym	23	/* SgContinueStmt */
#define SgReturnStmtSym	24	/* SgReturnStmt */
#define SgGotoStatementSym	25	/* SgGotoStatement */
#define SgSpawnStmtSym	26	/* SgSpawnStmt */
#define SgPragmaStatementSym	27	/* SgPragmaStatement */
#define SgForInitStatementSym	28	/* SgForInitStatement */
#define SgCatchStatementSeqSym	29	/* SgCatchStatementSeq */
#define SgClinkageStartStatementSym	30	/* SgClinkageStartStatement */
#define SgIncludeDirectiveStatementSym	31	/* SgIncludeDirectiveStatement */
#define SgDefineDirectiveStatementSym	32	/* SgDefineDirectiveStatement */
#define SgUndefDirectiveStatementSym	33	/* SgUndefDirectiveStatement */
#define SgIfdefDirectiveStatementSym	34	/* SgIfdefDirectiveStatement */
#define SgIfndefDirectiveStatementSym	35	/* SgIfndefDirectiveStatement */
#define SgIfDirectiveStatementSym	36	/* SgIfDirectiveStatement */
#define SgElseDirectiveStatementSym	37	/* SgElseDirectiveStatement */
#define SgElseifDirectiveStatementSym	38	/* SgElseifDirectiveStatement */
#define SgEndifDirectiveStatementSym	39	/* SgEndifDirectiveStatement */
#define SgLineDirectiveStatementSym	40	/* SgLineDirectiveStatement */
#define SgErrorDirectiveStatementSym	41	/* SgErrorDirectiveStatement */
#define SgCUnderscoreStyleCommentStaSym	42	/* SgC_StyleCommentStatement */
#define SgCxxStyleCommentStatementSym	43	/* SgCxxStyleCommentStatement */
#define SgVariableDeclarationSym	44	/* SgVariableDeclaration */
#define SgVariableDefinitionSym	45	/* SgVariableDefinition */
#define SgEnumDeclarationSym	46	/* SgEnumDeclaration */
#define SgAsmStmtSym	47	/* SgAsmStmt */
#define SgTypedefDeclarationSym	48	/* SgTypedefDeclaration */
#define SgTemplateDeclarationSym	49	/* SgTemplateDeclaration */
#define SgFunctionParameterListSym	50	/* SgFunctionParameterList */
#define SgCtorInitializerListSym	51	/* SgCtorInitializerList */
#define SgTemplateInstantiationDeclSym	52	/* SgTemplateInstantiationDecl */
#define SgMemberFunctionDeclarationSym	53	/* SgMemberFunctionDeclaration */
#define SgFunctionDeclarationSym	54	/* SgFunctionDeclaration */
#define SgGlobalSym	55	/* SgGlobal */
#define SgBasicBlockSym	56	/* SgBasicBlock */
#define SgIfStmtSym	57	/* SgIfStmt */
#define SgForStatementSym	58	/* SgForStatement */
#define SgFunctionDefinitionSym	59	/* SgFunctionDefinition */
#define SgWhileStmtSym	60	/* SgWhileStmt */
#define SgDoWhileStmtSym	61	/* SgDoWhileStmt */
#define SgSwitchStatementSym	62	/* SgSwitchStatement */
#define SgCatchOptionStmtSym	63	/* SgCatchOptionStmt */
#define SgTemplateInstantiationDefnSym	64	/* SgTemplateInstantiationDefn */
#define SgExprListExpSym	65	/* SgExprListExp */
#define SgVarRefExpSym	66	/* SgVarRefExp */
#define SgClassNameRefExpSym	67	/* SgClassNameRefExp */
#define SgFunctionRefExpSym	68	/* SgFunctionRefExp */
#define SgMemberFunctionRefExpSym	69	/* SgMemberFunctionRefExp */
#define SgFunctionCallExpSym	70	/* SgFunctionCallExp */
#define SgSizeOfOpSym	71	/* SgSizeOfOp */
#define SgTypeIdOpSym	72	/* SgTypeIdOp */
#define SgConditionalExpSym	73	/* SgConditionalExp */
#define SgNewExpSym	74	/* SgNewExp */
#define SgDeleteExpSym	75	/* SgDeleteExp */
#define SgThisExpSym	76	/* SgThisExp */
#define SgRefExpSym	77	/* SgRefExp */
#define SgAggregateInitializerSym	78	/* SgAggregateInitializer */
#define SgConstructorInitializerSym	79	/* SgConstructorInitializer */
#define SgAssignInitializerSym	80	/* SgAssignInitializer */
#define SgBoolValExpSym	81	/* SgBoolValExp */
#define SgStringValSym	82	/* SgStringVal */
#define SgShortValSym	83	/* SgShortVal */
#define SgCharValSym	84	/* SgCharVal */
#define SgUnsignedCharValSym	85	/* SgUnsignedCharVal */
#define SgWcharValSym	86	/* SgWcharVal */
#define SgUnsignedShortValSym	87	/* SgUnsignedShortVal */
#define SgIntValSym	88	/* SgIntVal */
#define SgEnumValSym	89	/* SgEnumVal */
#define SgUnsignedIntValSym	90	/* SgUnsignedIntVal */
#define SgLongIntValSym	91	/* SgLongIntVal */
#define SgLongLongIntValSym	92	/* SgLongLongIntVal */
#define SgUnsignedLongLongIntValSym	93	/* SgUnsignedLongLongIntVal */
#define SgUnsignedLongValSym	94	/* SgUnsignedLongVal */
#define SgFloatValSym	95	/* SgFloatVal */
#define SgDoubleValSym	96	/* SgDoubleVal */
#define SgLongDoubleValSym	97	/* SgLongDoubleVal */
#define SgArrowExpSym	98	/* SgArrowExp */
#define SgDotExpSym	99	/* SgDotExp */
#define SgDotStarOpSym	100	/* SgDotStarOp */
#define SgArrowStarOpSym	101	/* SgArrowStarOp */
#define SgEqualityOpSym	102	/* SgEqualityOp */
#define SgLessThanOpSym	103	/* SgLessThanOp */
#define SgGreaterThanOpSym	104	/* SgGreaterThanOp */
#define SgNotEqualOpSym	105	/* SgNotEqualOp */
#define SgLessOrEqualOpSym	106	/* SgLessOrEqualOp */
#define SgGreaterOrEqualOpSym	107	/* SgGreaterOrEqualOp */
#define SgAddOpSym	108	/* SgAddOp */
#define SgSubtractOpSym	109	/* SgSubtractOp */
#define SgMultiplyOpSym	110	/* SgMultiplyOp */
#define SgDivideOpSym	111	/* SgDivideOp */
#define SgIntegerDivideOpSym	112	/* SgIntegerDivideOp */
#define SgModOpSym	113	/* SgModOp */
#define SgAndOpSym	114	/* SgAndOp */
#define SgOrOpSym	115	/* SgOrOp */
#define SgBitXorOpSym	116	/* SgBitXorOp */
#define SgBitAndOpSym	117	/* SgBitAndOp */
#define SgBitOrOpSym	118	/* SgBitOrOp */
#define SgCommaOpExpSym	119	/* SgCommaOpExp */
#define SgLshiftOpSym	120	/* SgLshiftOp */
#define SgRshiftOpSym	121	/* SgRshiftOp */
#define SgPntrArrRefExpSym	122	/* SgPntrArrRefExp */
#define SgScopeOpSym	123	/* SgScopeOp */
#define SgAssignOpSym	124	/* SgAssignOp */
#define SgPlusAssignOpSym	125	/* SgPlusAssignOp */
#define SgMinusAssignOpSym	126	/* SgMinusAssignOp */
#define SgAndAssignOpSym	127	/* SgAndAssignOp */
#define SgIorAssignOpSym	128	/* SgIorAssignOp */
#define SgMultAssignOpSym	129	/* SgMultAssignOp */
#define SgDivAssignOpSym	130	/* SgDivAssignOp */
#define SgModAssignOpSym	131	/* SgModAssignOp */
#define SgXorAssignOpSym	132	/* SgXorAssignOp */
#define SgLshiftAssignOpSym	133	/* SgLshiftAssignOp */
#define SgRshiftAssignOpSym	134	/* SgRshiftAssignOp */
#define SgExpressionRootSym	135	/* SgExpressionRoot */
#define SgMinusOpSym	136	/* SgMinusOp */
#define SgUnaryAddOpSym	137	/* SgUnaryAddOp */
#define SgNotOpSym	138	/* SgNotOp */
#define SgPointerDerefExpSym	139	/* SgPointerDerefExp */
#define SgAddressOfOpSym	140	/* SgAddressOfOp */
#define SgMinusMinusOpSym	141	/* SgMinusMinusOp */
#define SgPlusPlusOpSym	142	/* SgPlusPlusOp */
#define SgBitComplementOpSym	143	/* SgBitComplementOp */
#define SgCastExpSym	144	/* SgCastExp */
#define SgThrowOpSym	145	/* SgThrowOp */
#define SgVariableSymbolSym	146	/* SgVariableSymbol */
#define SgFunctionTypeSymbolSym	147	/* SgFunctionTypeSymbol */
#define SgTemplateSymbolSym	148	/* SgTemplateSymbol */
#define SgEnumSymbolSym	149	/* SgEnumSymbol */
#define SgEnumFieldSymbolSym	150	/* SgEnumFieldSymbol */
#define SgTypedefSymbolSym	151	/* SgTypedefSymbol */
#define SgLabelSymbolSym	152	/* SgLabelSymbol */
#define SgDefaultSymbolSym	153	/* SgDefaultSymbol */
#define SgTemplateInstantiationSymboSym	154	/* SgTemplateInstantiationSymbol */
#define SgMemberFunctionSymbolSym	155	/* SgMemberFunctionSymbol */
#define SgFunctionSymbolSym	156	/* SgFunctionSymbol */
#define SgTypeUnknownSym	157	/* SgTypeUnknown */
#define SgTypeCharSym	158	/* SgTypeChar */
#define SgTypeSignedCharSym	159	/* SgTypeSignedChar */
#define SgTypeUnsignedCharSym	160	/* SgTypeUnsignedChar */
#define SgTypeShortSym	161	/* SgTypeShort */
#define SgTypeSignedShortSym	162	/* SgTypeSignedShort */
#define SgTypeUnsignedShortSym	163	/* SgTypeUnsignedShort */
#define SgTypeIntSym	164	/* SgTypeInt */
#define SgTypeSignedIntSym	165	/* SgTypeSignedInt */
#define SgTypeUnsignedIntSym	166	/* SgTypeUnsignedInt */
#define SgTypeLongSym	167	/* SgTypeLong */
#define SgTypeSignedLongSym	168	/* SgTypeSignedLong */
#define SgTypeUnsignedLongSym	169	/* SgTypeUnsignedLong */
#define SgTypeVoidSym	170	/* SgTypeVoid */
#define SgTypeGlobalVoidSym	171	/* SgTypeGlobalVoid */
#define SgTypeWcharSym	172	/* SgTypeWchar */
#define SgTypeFloatSym	173	/* SgTypeFloat */
#define SgTypeDoubleSym	174	/* SgTypeDouble */
#define SgTypeLongLongSym	175	/* SgTypeLongLong */
#define SgTypeUnsignedLongLongSym	176	/* SgTypeUnsignedLongLong */
#define SgTypeLongDoubleSym	177	/* SgTypeLongDouble */
#define SgTypeStringSym	178	/* SgTypeString */
#define SgTypeBoolSym	179	/* SgTypeBool */
#define SgComplexSym	180	/* SgComplex */
#define SgTypeDefaultSym	181	/* SgTypeDefault */
#define SgReferenceTypeSym	182	/* SgReferenceType */
#define SgModifierTypeSym	183	/* SgModifierType */
#define SgArrayTypeSym	184	/* SgArrayType */
#define SgTypeEllipseSym	185	/* SgTypeEllipse */
#define SgPartialFunctionTypeSym	186	/* SgPartialFunctionType */
#define SgUnknownMemberFunctionTypeSym	187	/* SgUnknownMemberFunctionType */
#define SgEnumTypeSym	188	/* SgEnumType */
#define SgTypedefTypeSym	189	/* SgTypedefType */
#define SgTemplateInstantiationTypeSym	190	/* SgTemplateInstantiationType */
#define SgPointerMemberTypeSym	191	/* SgPointerMemberType */
#define SgClassDeclarationSym	192	/* SgClassDeclaration */
#define SgClassDefinitionSym	193	/* SgClassDefinition */
#define LparenSym	194	/* "(" */
#define RparenSym	195	/* ")" */
#define No_Sym	196	/* not */
#define MAXT	No_Sym	/* Max Terminals */
