#!/bin/bash
set -e

add="$1"
exe="$2"

rpath="$(patchelf --print-rpath "$exe")"
old_rpath="$rpath"

if [ -n "$rpath" ]; then
    if [ -n "$add" ]; then
	rpath="$rpath:$add"
    fi
else
    if [ -n "$add" ]; then
	rpath="$add"
    fi
fi

if [ "$rpath" != "$old_rpath" ]; then
    patchelf --set-rpath "$rpath" "$exe"
fi
