#!/bin/sh

# choice in thesis (best results)
./start-benchmark --pag-memsize-mb=2000 --pag-memsize-grow=30 --callstringlength=3 &
echo "press Enter"; read

./start-benchmark --pag-memsize-mb=2000 --pag-memsize-grow=30 --callstringlength=0 &
echo "press Enter"; read
./start-benchmark --pag-memsize-mb=2000 --pag-memsize-grow=30 --callstringlength=1 &
echo "press Enter"; read
./start-benchmark --pag-memsize-mb=2000 --pag-memsize-grow=30 --callstringlength=2 &
echo "press Enter"; read
./start-benchmark --pag-memsize-mb=2000 --pag-memsize-grow=30 --callstringlength=3 &
echo "press Enter"; read

./start-benchmark --pag-memsize-mb=5 --pag-memsize-grow=30 --callstringlength=0 &
echo "press Enter"; read
./start-benchmark --pag-memsize-mb=5 --pag-memsize-grow=30 --callstringlength=1 &
echo "press Enter"; read
./start-benchmark --pag-memsize-mb=5 --pag-memsize-grow=30 --callstringlength=2 &
echo "press Enter"; read
./start-benchmark --pag-memsize-mb=5 --pag-memsize-grow=30 --callstringlength=3 &

