CC=g++
ROSE_LIBS=-lrose
LLVM_LIBS=-lLLVMSupport -lLLVMSystem -lLLVMCore -lLLVMTarget -lLLVMArchive -lLLVMAnalysis

INCLUDEDIR=./include
SRCDIR=./src
ROSE_INCLUDE=/home/aananthakris1/local/rose/include
LLVM_INCLUDE=/export/sriram/local/llvm/include


INCLUDE_FLAG= -I $(INCLUDEDIR) $(ROSE_INCLUDE) $(LLVM_INCLUDE)
LIBS=$(ROSE_LIBS) $(LLVM_LIBS)

rose-llvm: main.o VisitorTraversal.o
	$(CC) -o $@ $< $(LIBS)

main.o: $(SRCDIR)/main.cpp $(SRCDIR)/VisitorTraversal.cpp
	$(CC) $(INCLUDEFLAG) -c -o $@

VisitorTraversal.o: $(SRCDIR)/VisitorTraversal.cpp
	$(CC) $(INCLUDEFLAG) -c -o $@ 

clean:
	rm -rf *.o
